### ISSUE TITLE
[Bug] [1.18.1] [CEM] Broken CEM with spider eyes

### ISSUE THREAD

**Issue by xProBomb** [sp614x/optifine#6486] opened 2021-12-18 02:30 UTC
the CEM for spider eyes no longer works again.
other glowing eye textures untested

OptiFine 1.18_HD_U_H3 briefly tested OptiFine 1.18.1_HD_U_H5_pre2

**Comment by ewanhowell5195** [comment] 2021-12-19 13:08
screenshots?

**Comment by MinecraftMinun** [comment] 2021-12-21 10:03
Not sure why this is happening, but it's an issue for me in OptiFine 1.18.1_HD_U_H4_pre1 and OptiFine 1.18.1_HD_U_H4_pre1
In game
![2021-12-21_20 00 46](https://user-images.githubusercontent.com/22704209/146910731-32e8ea22-d51d-4995-83a8-1239418bd554.png)



Texture without spider_eyes overlay
![Red-headed Mouse Spider](https://user-images.githubusercontent.com/22704209/146908086-4015e9d7-a5d7-4e52-b266-2c583ee5aef1.png)

cave_spider.properties and spider_eyes.properties (same in both)
```
#Red-headed Mouse Spider
skins.2=2
name.2=iregex:(Red-headed Mouse Spider|Red headed Mouse Spider)
```

**Comment by ewanhowell5195** [comment] 2021-12-21 10:46
duplicate of #6480

**Closed** 2021-12-23 00:01 UTC
Labels: CEM, details needed, 1.18
