### ISSUE TITLE
mob not turning red even without shaders but when internal is on

### ISSUE THREAD

**Issue by Ender1355** [sp614x/optifine#5110] opened 2020-12-17 11:05 UTC
## Description of Issue
normally when internal is off mobs turn red when damaged, but after internal is on they are not red, they are normal

## Steps to Reproduce
1. I recently used Sildurs shaders normally without mob damage overlay, after I enabled to internal this happend, no fast render, 

## OptiFine Version
1.16.4 OptiFine HD U G5

## Installation Method
standalone installer, no mods, 

the pictures:

![bugreport5](https://user-images.githubusercontent.com/70771654/102479964-b14c1400-4070-11eb-88a9-a9143a2b09e8.png)
![bugreport4](https://user-images.githubusercontent.com/70771654/102479981-b6a95e80-4070-11eb-8f0d-d0e4e1668f38.png)

**Comment by Regnander** [comment] 2020-12-17 15:09
Sounds like #4894

**Comment by sp614x** [comment] 2020-12-18 15:40
Duplicate of #4894

**Closed by sp614x** 2020-12-18 15:40 UTC
