### ISSUE TITLE
[Bug] (OptiFine HD U G5 pre2) 1.16.4 the Invisible mobs issue is back. 

### ISSUE THREAD

**Issue by Lythael** [sp614x/optifine#5006] opened 2020-11-06 15:37 UTC
This issue is back in recent release of Optifine : https://github.com/sp614x/optifine/issues/4322

This bug causes occassional Piglins in or near Bastion became invisible and remain in that state untill re-entering world started happening in recent release of Optifine.

Not sure if it affects other mobs as i haven't ran into this problem untill i reached the Bastion.
I'll provide more details if i notice this anywhere else or with other mobs aswell.

EDIT: Some Overworld mobs seem to be affected aswell so far seen a Skeleton appearing completely invisible.
Tempoary fix for this is to exit to title and re-enter your world.

**Comment by SilverDude65536** [comment] 2020-11-06 22:40
Can confirm for OptiFine HD U G5 in 1.16.4

**Comment by Lythael** [comment] 2020-11-08 13:05
This happens occassionally with other entities aswell it seems.
Saw this invisible spider lately near a village :
https://i.imgur.com/3Tvu77N.jpg
The model is completely invisible except the glowing eyes

**Comment by Lythael** [comment] 2020-11-08 18:23
Noticed a Skeleton on Plains shooting another Skeleton that was invisible.
Unless that's a feature i missed this seems to be a part of the problem too.
So its not just with the Piglins. Hmm.

**Comment by danbalam** [comment] 2020-11-19 16:55
I had a zombie villager stashed away in a desert sand dune. I returned and was killed by it.

**Comment by dpill83** [comment] 2020-12-04 18:51
I have a server running the Drehmal: PRIMORDIAL map and Optifine is a requirement to use it. I've gotten complaints that some mobs are invisible. Advised users to close the game and relaunch it and the mobs appear.

**Comment by VirulentSlayer** [comment] 2020-12-06 15:06
In SMP vanilla, with no additional mods, piglin brutes are invisible. I haven't noticed any other mobs being invisible yet. OptiFine HD G5 Ultra for 1.16.4

**Comment by khops94** [comment] 2020-12-07 02:10
Also can confirm with 1.16.4 - named mobs and some piglins can become invisible - seems like they may be visible if rendered when you load the game, but can become invisible if you leave render distance and return.  Mods in my setup include:
Fabric-api-0.25.7+1.16.jar
optifabric-1.8.5.jar
Optifine_1.16.4_HD_U_G5.jar
replaymod-1.16.4-2.5.0.jar
worldedit-fabric-mc1.16.3-7.2.0-dist.jar

**Comment by JBHUTT09** [comment] 2020-12-08 18:30
Encountered invisible piglin brutes this morning.
MC: 1.16.4
Forge: 35.1.10
OptiForge: MC1.16.4-0.4.3

**Comment by Teasy** [comment] 2020-12-11 11:13
Related thread:
https://github.com/sp614x/optifine/issues/5016

**Comment by chasejsutton49** [comment] 2020-12-15 18:01
Rest assured, this is not a vanilla bug.

**Comment by berkkrkc09** [comment] 2020-12-15 18:07
This bug report is a duplicate of #1892. Can you guys move the info you gathered to there. It would be easier for sp614x to keep track of the issue.

**Comment by chasejsutton49** [comment] 2021-01-11 23:50
*Potentially* fixed in 1.16.4 Optifine HD U G6 pre12, but don't quote me on that.
Went into a bastion remnant where I was experiencing this bug, Piglins have spawned inside.

**Comment by sp614x** [comment] 2021-02-13 19:16
Duplicate of #5016

**Closed by sp614x** 2021-02-13 19:16 UTC
