### ISSUE TITLE
[CIT "Renamed Tools & Armor"] 

### ISSUE THREAD

**Issue by 9phials** [sp614x/optifine#3654] opened 2020-04-02 12:57 UTC
## [Description of Issue]
I use 1.13+ conquest textures. 1. When I rename tools in an anvil to get a specific cosmetic appearance, some of the larger textures show up as really small in the hotbar and when held in my hand. For example ("stone sword" renamed through an anvil as "Shortsword" works perfectly.) but a 64x64 texture for example ("stone sword" renamed "Nodachi" comes out REALLY small, when in older optifine versions it came out perfectly to size.)

When I try to rename armor, the icon changes, but the armor on my player character does not change at all. The same goes with shields & crossbows.

Tridents are invisible, and changing the name for a custom texture does not help it show either.

## Steps to Reproduce
1. Download Conquest 1.13 resource pack from [ http://conquest.ravand.org/ ]
2. Apply resource pack in-game.
3. Create a world in creative mode.
4. Refer to [ https://ravand.org//refsheet_tools.html ]
5. Try renaming ANY sword using the anvil using the names of any sword or dagger that has a 64x64 or 128x128 texture.
{for example}
- Nodachi
- Bastardsword
- Heavy Greatsword

You will notice that these large swords appear to be small, which isn't right.
This goes for al of the larger textures.

6. Get a piece of armor and refer to the armor category on the website I linked you, try renaming it to any armor name on that page and apply it thru anvil.

7. Wear armor, and notice that the armor doesnt change from its original state.

8. Get a trident, realize it is invisible.

9. Get a shield and {for example} rename it to "Big Round Woodshield"
You will notice that when you hold the shield, it doesnt change it's texture.

10. Try renaming a crossbow to "Heavy Crossbow", notice that this doesn't change a thing either.

 -  - - OptiFine 1.15.2 HD U G1 pre12 - - -

## Installation Method
I used the standalone Installer.

## F3 Debug Screenshot

This will not help.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

NO it does not, Optifine allows the use of renaming the tools and the textures showing up when using conquest.

## Additional Information

If this issue is not related to optifine, and is purely conquests resources fault, i am deeply sorry for making you read all of that :/.

Hope i helped somehow.

**Comment by sp614x** [comment] 2020-05-19 15:39
Duplicate of #3588.

**Closed by sp614x** 2020-05-19 15:39 UTC
Labels: 1.15, CIT, duplicate
