### ISSUE TITLE
[Issue] Loading Screen tints/brightens logo if it is not grayscale

### ISSUE THREAD

**Issue by Gappysona** [sp614x/optifine#4258] opened 2020-07-05 18:05 UTC
## Description of Issue
Because the original logo is grayscale, trying to convert it to 16-bit colour image will cause it to tint (or brighten) slightly.

## Steps to Reproduce
1. Create a logo which fits the new Mojang Studios logo, that is not grayscale.
2. View the loading screen.

## OptiFine Version
OptiFine 1.16.1_HD_U_G2_pre2

## Installation Method
JAR Standalone Installer

## Log Files/Crash Reports
https://hastebin.com/yewenozipe.md

Expected result:
![Expected result.](https://user-images.githubusercontent.com/51373236/86539157-5ffcfd80-bef2-11ea-8014-aa62b5ba73ed.png)

What actually happens:
![What actually happens.](https://user-images.githubusercontent.com/51373236/86539155-5ecbd080-bef2-11ea-8bc4-8ecc4edba912.png)

**Comment by ewanhowell5195** [comment] 2020-07-08 20:36
same 
![image](https://user-images.githubusercontent.com/48070995/86967831-17984680-c163-11ea-9ecb-6eb93a8c2466.png)

**Comment by Gappysona** [comment] 2020-07-08 21:19
I think what is happening is that it's getting tinted the same colour as the Mojang Studios colour background?

**Comment by sp614x** [comment] 2020-08-28 14:30
Duplicate of #4712
Fixed in 1.16.2 pre7.

**Closed by sp614x** 2020-08-28 14:30 UTC
Labels: 1.16, gui
