### ISSUE TITLE
Crash when enderpearl lands (pre7)

### ISSUE THREAD

**Issue by nerdyshoes** [sp614x/optifine#3423] opened 2020-02-22 07:46 UTC
As soon as enderpearl lands, I crash. When I log back into the world again (using optifine still) I crash for the second time. Log back in, using vanilla and do not crash. Go back into the world with optifine and am fine until I throw another pearl. The three crash reports are as follows

`---- Minecraft Crash Report ----
// My bad.

Time: 22/02/20 5:21 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: bitIndex < 0: -1
	at java.util.BitSet.set(BitSet.java:444)
	at net.optifine.SmartAnimations.spriteRendered(SmartAnimations.java:38)
	at drd.a(OverlayRenderer.java:80)
	at drd.a(OverlayRenderer.java:34)
	at dqn.renderHand(GameRenderer.java:602)
	at dqn.a(GameRenderer.java:543)
	at dqn.a(GameRenderer.java:1002)
	at dqn.a(GameRenderer.java:684)
	at dbn.d(SourceFile:989)
	at dbn.d(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.BitSet.set(BitSet.java:444)
	at net.optifine.SmartAnimations.spriteRendered(SmartAnimations.java:38)
	at drd.a(OverlayRenderer.java:80)
	at drd.a(OverlayRenderer.java:34)
	at dqn.renderHand(GameRenderer.java:602)
	at dqn.a(GameRenderer.java:543)
	at dqn.a(GameRenderer.java:1002)

-- Affected level --
Details:
	All players: 1 total; [dqb['Nerdy_Shoes'/57, l='MpServer', x=1327.53, y=51.44, z=-2351.93]]
	Chunk stats: Client Chunk Cache: 441, 255
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: -2899133510831460738
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (160,72,208), Chunk: (at 0,4,0 in 10,13; contains blocks 160,0,208 to 175,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 9021335 game time, 2572787 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at dno.a(ClientWorld.java:611)
	at dbn.c(SourceFile:1921)
	at dbn.d(SourceFile:639)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 521534896 bytes (497 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.15.2-OptiFine_HD_U_G1_pre7
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) R5 Graphics GL version 4.6.13560 Compatibility Profile Context 26.20.11024.4001, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/VanillaTweaks (incompatible)
	Current Language: English (US)
	CPU: 4x AMD A10-9620P RADEON R5, 10 COMPUTE CORES 4C+6G
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre7
	OptiFine Build: 20200221-181745
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13560 Compatibility Profile Context 26.20.11024.4001
	OpenGlRenderer: AMD Radeon(TM) R5 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4`

`---- Minecraft Crash Report ----
// Why did you do that?

Time: 22/02/20 5:26 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: bitIndex < 0: -1
	at java.util.BitSet.set(BitSet.java:444)
	at net.optifine.SmartAnimations.spriteRendered(SmartAnimations.java:38)
	at drd.a(OverlayRenderer.java:80)
	at drd.a(OverlayRenderer.java:34)
	at dqn.renderHand(GameRenderer.java:602)
	at dqn.a(GameRenderer.java:543)
	at dqn.a(GameRenderer.java:1002)
	at dqn.a(GameRenderer.java:684)
	at dbn.d(SourceFile:989)
	at dbn.d(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.BitSet.set(BitSet.java:444)
	at net.optifine.SmartAnimations.spriteRendered(SmartAnimations.java:38)
	at drd.a(OverlayRenderer.java:80)
	at drd.a(OverlayRenderer.java:34)
	at dqn.renderHand(GameRenderer.java:602)
	at dqn.a(GameRenderer.java:543)
	at dqn.a(GameRenderer.java:1002)

-- Affected level --
Details:
	All players: 1 total; [dqb['Nerdy_Shoes'/45, l='MpServer', x=1327.63, y=51.44, z=-2352.03]]
	Chunk stats: Client Chunk Cache: 441, 1
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: -2899133510831460738
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (160,72,208), Chunk: (at 0,4,0 in 10,13; contains blocks 160,0,208 to 175,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 9021512 game time, 2572964 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at dno.a(ClientWorld.java:611)
	at dbn.c(SourceFile:1921)
	at dbn.d(SourceFile:639)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1450436760 bytes (1383 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.15.2-OptiFine_HD_U_G1_pre7
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) R5 Graphics GL version 4.6.13560 Compatibility Profile Context 26.20.11024.4001, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/VanillaTweaks (incompatible)
	Current Language: English (US)
	CPU: 4x AMD A10-9620P RADEON R5, 10 COMPUTE CORES 4C+6G
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre7
	OptiFine Build: 20200221-181745
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13560 Compatibility Profile Context 26.20.11024.4001
	OpenGlRenderer: AMD Radeon(TM) R5 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4`

`---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 22/02/20 5:32 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: bitIndex < 0: -1
	at java.util.BitSet.set(BitSet.java:444)
	at net.optifine.SmartAnimations.spriteRendered(SmartAnimations.java:38)
	at drd.a(OverlayRenderer.java:80)
	at drd.a(OverlayRenderer.java:34)
	at dqn.renderHand(GameRenderer.java:602)
	at dqn.a(GameRenderer.java:543)
	at dqn.a(GameRenderer.java:1002)
	at dqn.a(GameRenderer.java:684)
	at dbn.d(SourceFile:989)
	at dbn.d(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.BitSet.set(BitSet.java:444)
	at net.optifine.SmartAnimations.spriteRendered(SmartAnimations.java:38)
	at drd.a(OverlayRenderer.java:80)
	at drd.a(OverlayRenderer.java:34)
	at dqn.renderHand(GameRenderer.java:602)
	at dqn.a(GameRenderer.java:543)
	at dqn.a(GameRenderer.java:1002)

-- Affected level --
Details:
	All players: 1 total; [dqb['Nerdy_Shoes'/45, l='MpServer', x=1317.14, y=47.27, z=-2352.31]]
	Chunk stats: Client Chunk Cache: 441, 127
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: -2899133510831460738
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (160,72,208), Chunk: (at 0,4,0 in 10,13; contains blocks 160,0,208 to 175,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 9021967 game time, 2573419 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at dno.a(ClientWorld.java:611)
	at dbn.c(SourceFile:1921)
	at dbn.d(SourceFile:639)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1267265504 bytes (1208 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.15.2-OptiFine_HD_U_G1_pre7
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) R5 Graphics GL version 4.6.13560 Compatibility Profile Context 26.20.11024.4001, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/VanillaTweaks (incompatible)
	Current Language: English (US)
	CPU: 4x AMD A10-9620P RADEON R5, 10 COMPUTE CORES 4C+6G
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre7
	OptiFine Build: 20200221-181745
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13560 Compatibility Profile Context 26.20.11024.4001
	OpenGlRenderer: AMD Radeon(TM) R5 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4`

**Comment by asbyth** [comment] 2020-02-22 07:46
dupe of #3412

**Comment by sp614x** [comment] 2020-02-22 20:57
Fixed, coming in pre8.

**Closed by sp614x** 2020-02-22 20:57 UTC
Labels: 1.15, animation, bug
