### ISSUE TITLE
Particles are visible through blocks

### ISSUE THREAD

**Issue by CentiSalad** [sp614x/optifine#5881] opened 2021-06-26 16:18 UTC
## Description of Issue
in one of my Minecraft worlds I built a large build that had lots of campfire, endrods, candles and torches. when I loaded it with 1.17-OptiFine_HD_U_G9_pre22 everything was fine until I turned on shaders. after I turned them on the particles that torches campfire ect. make start to be seen through walls. It didnt matter what shaders I used the issue stayed the same (all shaders were updated to 1.17). I loaded up a new world and immediately saw glow squid particles float through the grass.

## Steps to Reproduce
1. Start a world
2. turn on any shader
3. place a campfire

## OptiFine Version
1.17-OptiFine_HD_U_G9_pre22

## Installation Method
I went to the official website and downloaded the installer

## F3 Debug Screenshot

![2021-06-26_18 11 50](https://user-images.githubusercontent.com/86528009/123519227-42e4b000-d6aa-11eb-8989-b34573747fac.png)

## Prior Testing
no it does not

## Additional Information
here are the shaders I used:
[BSL_v8.0.01 (1).zip](https://github.com/sp614x/optifine/files/6720365/BSL_v8.0.01.1.zip)

**Comment by DaCoolKitty** [comment] 2021-06-26 16:24
Duplicate of #5861

**Closed** 2021-06-26 16:47 UTC
