### ISSUE TITLE
[Bug] Parrots don't show custom textures when on a player's shoulder

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#6772] opened 2022-04-29 08:03 UTC
## Description of Issue
When a parrot is on a player's shoulder, the random entites texture it has won't show. It reappears when dismounted from the shoulder.

## OptiFine Version
OptiFine 1.18.2_HD_U_H7

![2022-04-29_01 01 10](https://user-images.githubusercontent.com/62183036/165906536-e0b5cc8f-3916-407b-abd8-7ff4213ccce1.png)
![2022-04-29_01 01 15](https://user-images.githubusercontent.com/62183036/165906557-5e2b19e1-07c5-456f-9db4-def7f2f696e1.png)

**Comment by sp614x** [comment] 2022-05-01 21:49
Duplicate of #6223

**Closed by sp614x** 2022-05-01 21:49 UTC
