### ISSUE TITLE
[Bug] Chunks will not load

### ISSUE THREAD

**Issue by Gavins38** [sp614x/optifine#4241] opened 2020-07-04 18:44 UTC
## Description of Issue
Chunks simply will not load heres an image

![](https://cdn.discordapp.com/attachments/729043766891118692/729043974815481936/86513052-110d7600-bdd5-11ea-91fb-5b1e03b74f0b.png)

## OptiFine Version
Optifine 1.16.1 HD U G2 Pre 2

## Installation Method
Double clicked on the jar file.

## Other Installed Mods
None

![](https://cdn.discordapp.com/attachments/729043766891118692/729043974815481936/86513052-110d7600-bdd5-11ea-91fb-5b1e03b74f0b.png)
^ is with optifine
![](https://cdn.discordapp.com/attachments/729043766891118692/729044042242981918/86513134-c2141080-bdd5-11ea-8a7f-905d18ae2539.png)
^ is without optifine

Specs of my pc yep i got the most potato pc ever
4 GB of ram
AMD E1-3500 APU with Radeon(TM) HD Graphics 1.40 GHz
64 bit operating system

**Comment by Exolirating** [comment] 2020-07-05 18:58
Have the same issue. But mine is the non-loaded chunks make you fall into the void.

**Comment by FernandoSerio** [comment] 2020-07-06 03:05
I have only had that problem once, it presented itself to me when I left my world and left it on the main screen of the game for about 10 minutes and re-entered the game, it was solved by entering and exiting the game, have you tried that?

**Comment by Gavins38** [comment] 2020-07-06 10:15
optifine know its a bug they are gona fix it if u look at this
https://github.com/sp614x/optifine/issues/3506
exact same issue

**Comment by Exolirating** [comment] 2020-07-07 21:50
Yes I have, issue proceed. Was the same chunks as well. Still couldn't walk on the unloaded chunks and was on a hardcore world. If that makes any difference. Also was running shaders but tried without shaders as well.

**Comment by sp614x** [comment] 2020-07-10 14:39
Relevant #3506

**Comment by sp614x** [comment] 2020-08-26 16:12
Duplicate of #4261

**Closed by sp614x** 2020-08-26 16:12 UTC
Labels: 1.16, chunks, performance
