### ISSUE TITLE
[Bug] Player Hand and Item do not show as visible

### ISSUE THREAD

**Issue by NateslPlayzzz** [sp614x/optifine#4638] opened 2020-08-18 17:15 UTC
When using a shader, my players hand does not show up visible, nor does the item, it all works fine but the hand and item are just not visible

1.Load 1.16.2 pre1 optifine
2.load shader

1.16.2 pre 1

I used the standalone installer

![2020-08-18_13 14 42](https://user-images.githubusercontent.com/69865617/90544216-d4af9280-e154-11ea-87c8-42f9f2f836f8.png)
![2020-08-18_13 15 16](https://user-images.githubusercontent.com/69865617/90544266-e5f89f00-e154-11ea-8fc0-504e08554004.png)

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

No it does not happen with vanilla

**Comment by sp614x** [comment] 2020-08-20 14:41
Duplicate of #4640

**Closed by sp614x** 2020-08-20 14:41 UTC
