### ISSUE TITLE
[Graphical glitch] Flickering items and entities.

### ISSUE THREAD

**Issue by Sparky2001** [sp614x/optifine#6056] opened 2021-07-18 17:55 UTC
## Description of Issue
I just started to make a map-wall a bit ago, on a Minecraft realm on 1.17.1, using a 1.17.1 preview version of Optifine. However, my entities, item frames, signs, mobs and whatnot begin to randomly flicker and blink black pretty frequently and it gets very irritating and frustrating as it took quite a while for the whole setup. The issue doesn't happen when i don't look in the direction the map-wall is, which would surprise me as i only have a few item frames with maps placed on it. Having THAT be the start of that problem would just be odd as i had made one on another realm, on 1.16.4, and the problem didn't happen at all.
Due to it happening for a split-second, it's pretty much impossible for me to capture it on a screenshot.
## Steps to Reproduce
1. Placed item frames on Jack-o-lanterns for lighting.
2. Placed a few maps in some item-frames.
3.  ... problem happened.

## OptiFine Version
OptiFine HD U G9 pre29

## Installation Method
I downloaded the folder off of the Optifine website. Since my pc downloads them as "Rar" folders, i right-clicked and selected "open with Java" and installed it using the installer that popped up.

## F3 Debug Screenshot
![2021-07-18_19 51 09](https://user-images.githubusercontent.com/80028104/126077304-20919bf5-da76-48dd-88fc-457583b058c7.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine? = No, no it doesn't.

**Comment by Bulcsu-stack** [comment] 2021-07-18 18:05
so I have the same issue in 1.17.1 optifine but it doesn't happen on singleplayer worlds just on multiplayer and things like entities, chests, dropped items and signs turn black and flicker sometimes. If there is a player or I'm in f5 then sometimes the player flickers and their optifine cape of they have one turns black and their shield if they are holding one does too but otherwise the whole player is invisible and in f5 when this happens and you look through the player you cant see water. I was able to take a some screenshots not sure if this is what you mean.
![2021-07-18_13 57 25](https://user-images.githubusercontent.com/87616171/126077713-6ead4c12-cb8a-4d9f-bb68-d2c461d7aec8.png)

![2021-07-18_09 30 33](https://user-images.githubusercontent.com/87616171/126077699-fa988009-dfaa-48e7-a4fc-3082f7b9768c.png)

**Comment by Sparky2001** [comment] 2021-07-18 18:07
> 
> 
> so I have the same issue in 1.17.1 optifine but it doesn't happen on singleplayer worlds just on multiplayer and things like entities, chests, dropped items and signs turn black and flicker sometimes. If there is a player or I'm in f5 then sometimes the player flickers and their optifine cape of they have one turns black and their shield if they are holding one does too but otherwise the whole player is invisible and in f5 when this happens and you look through the player you cant see water. I was able to take a some screenshots not sure if this is what you mean.
> ![2021-07-18_13 57 25](https://user-images.githubusercontent.com/87616171/126077713-6ead4c12-cb8a-4d9f-bb68-d2c461d7aec8.png)
> 
> ![2021-07-18_09 30 33](https://user-images.githubusercontent.com/87616171/126077699-fa988009-dfaa-48e7-a4fc-3082f7b9768c.png)

That's exactly the kind of flickering i mean, however i get it with fully vanilla textures and i haven't checked it on my own player yet.. but it wouldn't surprise me if it happens too.

**Comment by Bulcsu-stack** [comment] 2021-07-18 18:09
I took all my texture packs off but that didn't fix it so I just try to ignore it but its fairly annoying sometimes the water just turns completely transparent and flickers like the entities.

**Comment by Sparky2001** [comment] 2021-07-18 18:11
> 
> 
> I took all my texture packs off but that didn't fix it so I just try to ignore it but sometimes the water just turns completely transparent and flickers like the entities.

That's weird as the water doesn't seem to have issues for me. I just hope it gets resolved in a future Optifine version, but it really makes me wonder, as this issue happened all of a sudden and hasn't gone away since.

**Comment by Whitelisted1** [comment] 2021-07-18 21:16
This is a duplicate of #6013, try looking there for any answers

**Comment by ZenIsBestWolf** [comment] 2021-07-23 17:49
> 
> 
> This is a duplicate of #6013, there currently is no solution yet, but it seems to be related to maps in item frames

basically this, closing

**Closed by ZenIsBestWolf** 2021-07-23 17:49 UTC
