### ISSUE TITLE
[Bug] Menu splashes not visible

### ISSUE THREAD

**Issue by lucscood** [sp614x/optifine#4066] opened 2020-06-09 03:50 UTC
## Description of Issue
Main menu splashes are not rendered.

## Steps to Reproduce
1. Install OptiFine with Forge
2. Start Minecraft

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre23

## Installation Method
Installed for Minecraft Forge, dragged into the "mods" folder.

## Fabric/Forge Version
Forge 31.2.0

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
Only OptiFine and Forge

![1](https://user-images.githubusercontent.com/66658710/84104077-9dd93580-a9c9-11ea-8c6f-b6080902eba4.PNG)

**Comment by asbyth** [comment] 2020-06-09 04:35
dupe of #4004

**Closed** 2020-06-09 21:53 UTC
Labels: duplicate
