### ISSUE TITLE
[Servers] Cannot join through SRV records.

### ISSUE THREAD

**Issue by NotPhantomX** [sp614x/optifine#4005] opened 2020-05-30 21:41 UTC
## Description of Issue
My minecraft network is running using srv records as the ports that are used are not the defualt.
mc.mydomain.com will not resolve however if I use forge or vanilla it will. However I am able to join the server when i put in mydomain.com:port
## Steps to Reproduce
1. join through an known srv record or create a server port forward an port and setup an srv record to point to the port.

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre18

## Installation Method
I downloaded the installer and told it to install the client.

## Prior Testing
Im able to join when using the vanilla client or forge.

## Additional Information
I am able to join when I use it as a forge mod.

**Comment by sp614x** [comment] 2020-06-03 21:18
Duplicate of #2917.

**Closed by sp614x** 2020-06-03 21:18 UTC
