### ISSUE TITLE
When forge is used with optifine glowing effect makes the player appear as a solid color

### ISSUE THREAD

**Issue by axemwa** [sp614x/optifine#1464] opened 2018-06-16 19:07 UTC
When forge is used with optifine the glowing effect makes the player appear as a solid color, tested optifine without forge and the glowing effect seems to work/look like normal

original issue:

https://github.com/MinecraftForge/MinecraftForge/issues/4983#issuecomment-397832647

**Comment by sp614x** [comment] 2018-06-16 19:34
Duplicate of #1377, #1174, #189, #1432, #1427.

The spectral effect (glowing outline) is not compatible with Fast Render and with shaders. When one of them is active an alternative "ghost" effect is used instead.

**Closed by sp614x** 2018-06-16 19:34 UTC

**Comment by axemwa** [comment] 2018-06-16 22:50
thankyou :) was stuck on this for a while
