### ISSUE TITLE
Shaders issue chest. bed, enchanting table, lighting issues as well as sign and grass problems

### ISSUE THREAD

**Issue by Sparkthecat** [sp614x/optifine#5896] opened 2021-06-27 08:21 UTC
## Description of Issue
When I back away from these specified objects some turn pitch black while others are darker than usual. Signs and grass when affected by the rain either cause lighting issues or cause them to change color.

## Steps to Reproduce
1.Back away from the objects and they will turn black.
2.When it rains look at signs or grass and you'll see the effects immediately.

## OptiFine Version
1.17 Pre 23

## Installation Method
 Standalone

![2021-06-26_18 39 24](https://user-images.githubusercontent.com/86541733/123537742-d687a200-d6e5-11eb-939c-84b9ae174bc8.png)
![2021-06-26_18 39 27](https://user-images.githubusercontent.com/86541733/123537748-dbe4ec80-d6e5-11eb-98f1-81bfc7e5c348.png)
![2021-06-26_18 59 57](https://user-images.githubusercontent.com/86541733/123537750-dedfdd00-d6e5-11eb-874b-dd766599b5b9.png)
![2021-06-26_19 01 58](https://user-images.githubusercontent.com/86541733/123537753-e2736400-d6e5-11eb-8e08-eb3016ff5d5f.png)

**Comment by Whitelisted1** [comment] 2021-06-27 13:49
Duplicate of #5895 (released an hour before)

**Closed** 2021-06-27 16:55 UTC
