### ISSUE TITLE
[Crash Report] Won't even load the game :( 

### ISSUE THREAD

**Issue by Nel-27** [sp614x/optifine#6892] opened 2022-07-01 12:16 UTC
## Description of Issue
Hi guys! Firstly thanks for all the hard work! However, both pre1 and pre2 versions are having the same issue for me. When I load the game - no matter what "server" (single player, multi, realms). It crashes immediately upon loading the game - which is upsetting! Haha. (I'm sorry if this is bad, I have no idea what I'm doing!) 

## Steps to Reproduce
1. What do you do... Literally just load the game with either pre1 or pre2 

## OptiFine Version
1.19 pre1 & 2

## Installation Method
standalone installer

## Other Installed Mods

No mods at all - deleted them all and nothing changed. 

## Log Files/Crash Reports

[crash-2022-07-01_13.07.48-client.txt](https://github.com/sp614x/optifine/files/9028686/crash-2022-07-01_13.07.48-client.txt)

## F3 Debug Screenshot

I can't actually be in game long enough to screenshot this, I'm sorry!

## Additional Information
This is the exit code that pops up on the launcher when the game has crashed
 The game crashed whilst accessing legacyrandomsource from multiple threads
Error: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
Exit Code: -1

**Comment by fayer3** [comment] 2022-07-01 12:18
duplicate of #6858
you can disable connected textures in the meantime.

**Comment by Nel-27** [comment] 2022-07-01 12:24
> 

Thank you! I'll give it a try :)

**Closed** 2022-07-01 18:50 UTC
