### ISSUE TITLE
[Category] Screen goes black when breaking blocks with tools.

### ISSUE THREAD

**Issue by Jgards3** [sp614x/optifine#5123] opened 2020-12-21 21:12 UTC
## Description of Issue
Screen either goes black or white (depending on the shader being used) when breaking blocks with a tool. It is a conflict with a COFH mod.

didn't occur back on 1.15 A24. Occurs on all optifine versions after that.

## Steps to Reproduce
1. Have COFH mod and optifine loaded. load a shader.
2. try to break a block with a tool. (e.g. a pickaxe and stone or dirt)

## OptiFine Version
Any version after 1.15 A24.

## Installation Method
dropped the JAR file into my "mods" folder

## Fabric/Forge Version
Forge 35.1.13

## Other Installed Mods
-COFH

**If OptiFine is installed as standalone, remove this section.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
**- No**

**Comment by berkkrkc09** [comment] 2020-12-21 21:29
There is a workaround.

**This line is taken from cofh_core-client.toml:**
#If TRUE, Area Effect Block breaking will be rendered. Disable if you are using buggy mods such as OptiFine which apparently with this. Please also report the issue to OptiFine.

**Comment by sp614x** [comment] 2020-12-22 11:12
Duplicate of #5023

**Closed by sp614x** 2020-12-22 11:12 UTC
Labels: 1.16, mods, shaders
