### ISSUE TITLE
Santa hat showing up even when invisible

### ISSUE THREAD

**Issue by janilowski** [sp614x/optifine#5166] opened 2020-12-31 09:25 UTC
## Description of Issue
When player with a santa hat goes invisible, their hat is still visible to other players and themselves. This ruins some mini-games like Hypixel Bedwars.

## Steps to Reproduce
1. Have optifine santa hat enabled
2. Use a potion of invisibility
3. The santa hat is still visible

I've demonstrated the process in this video: https://youtu.be/r5u9oSkBZ00

## OptiFine Version
I've recorded the video using 1.8.9-OptiFine_HD_U_L6_pre1 but also found the issue on 1.16.4-OptiFine_HD_U_G5 and 1.8.9-OptiFine_HD_U_L5

## Installation Method
I used the installer, downloaded directly from optifine.net

## F3 Debug Screenshot
![2020-12-31_10 23 10](https://user-images.githubusercontent.com/76809077/103403940-414e8b00-4b52-11eb-8f87-d8cef2a3371a.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
 **no**

**Comment by Regnander** [comment] 2021-01-01 13:21
Related #5150

**Comment by sp614x** [comment] 2021-01-01 17:47
Duplicate of #5150

**Closed by sp614x** 2021-01-01 17:47 UTC
