### ISSUE TITLE
Fullscreen issue

### ISSUE THREAD

**Issue by DonaldDoc** [sp614x/optifine#5178] opened 2021-01-03 01:25 UTC
## Description of Issue
If you have macOS Big Sur and you go fullscreen on 1.8.9, the game will show you a white screen.

## Steps to Reproduce
1. Install macOS Big Sur, download Optifine for 1.8.9, go fullscreen

## OptiFine Version
OptiFine HD U L5

## Installation Method
Installed from optifine.net 

## F3 Debug Screenshot
Cant capture.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
- No, it happens only in optifine.

**Comment by Regnander** [comment] 2021-01-03 19:11
Related #5028 and #5034

**Comment by ZenIsBestWolf** [comment] 2021-02-01 18:25
Duplicate of #5028

**Closed by ZenIsBestWolf** 2021-02-01 18:25 UTC
Labels: duplicate
