### ISSUE TITLE
Sides of grass blocks seem strange (1.15.2 HD U G1 pre1)

### ISSUE THREAD

**Issue by devereaux98** [sp614x/optifine#3309] opened 2020-02-14 03:55 UTC
Attached is this screenshot that demonstrates what I mean.  Thank you guys for all you do :)

![image](https://user-images.githubusercontent.com/22154989/74500095-2247fb80-4ea3-11ea-8edf-0e7c3a4dd5f0.png)

**Comment by sp614x** [comment] 2020-02-14 08:18
Caused by Natural Textures

**Comment by sp614x** [comment] 2020-02-14 14:42
Duplicate of #3297.

**Closed by sp614x** 2020-02-14 14:42 UTC
Labels: 1.15, textures

**Comment by devereaux98** [comment] 2020-02-15 02:18
> Caused by Natural Textures

Apologies, thanks for being patient haha
