### ISSUE TITLE
[bug] portal not rendering properly in preview for mc 1.17

### ISSUE THREAD

**Issue by Dorus06** [sp614x/optifine#5697] opened 2021-06-08 17:51 UTC
## Description of Issue

![2021-06-08_19 36 42](https://user-images.githubusercontent.com/85579656/121232646-1b13e080-c892-11eb-9130-ffb1140ff77d.png)
![2021-06-08_19 36 49](https://user-images.githubusercontent.com/85579656/121232664-1e0ed100-c892-11eb-9fd0-be8b48573257.png)
![2021-06-08_19 36 55](https://user-images.githubusercontent.com/85579656/121232673-1fd89480-c892-11eb-95b4-78d4e2f2d372.png)
i dont know wat needs fixing, but i now what is wrong here
the portal frames render about 100 blocks away from the portal and about 80 blocks in de sky
[](url)
## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## OptiFine Version

preview 16 for 1.17

## Installation Method

i just ran the .jar file, and installed it in the installer

**Comment by Dorus06** [comment] 2021-06-08 17:55
i forgot to mention: de portal frames disapere when you get close to them

**Comment by Dorus06** [comment] 2021-06-08 17:58
i discoverd that it also happend with coloured glass

**Comment by KaiAF** [comment] 2021-06-08 18:12
Send an F3 screenshot

**Comment by KaiAF** [comment] 2021-06-08 18:24
Closing this as this bug is caused by render regions, and this https://github.com/sp614x/optifine/issues/5698 issue is the main one.

**Closed by KaiAF** 2021-06-08 18:24 UTC
Labels: 1.17
