### ISSUE TITLE
[Crash]  Game randomly crashes

### ISSUE THREAD

**Issue by Ceelbc** [sp614x/optifine#6863] opened 2022-06-29 16:35 UTC
## Description of Issue

Game just crashes using a flailed cheat.
## Steps to Reproduce
1. What do you do...
2. ...to find this bug?
Start an invallid fill command like
/fill x y z
This is invallid and it chashed shortly after, when I wanted to fly.
The game runned whell for a couple of minutes.

## OptiFine Version

OptiFine HD U H8 pre1 (1.19)
## Installation Method

Using the installer.

## Log Files/Crash Reports

[crash-2022-06-29_18.19.18-client.txt](https://github.com/sp614x/optifine/files/9012401/crash-2022-06-29_18.19.18-client.txt)

## Prior Testing

I have the john smith legacy texture pach installed.

**Comment by UnknownTheLad** [comment] 2022-06-29 16:42
Duplicate of #6858

**Closed** 2022-06-29 19:43 UTC
