### ISSUE TITLE
Bug invisible players

### ISSUE THREAD

**Issue by SrLokiToo** [sp614x/optifine#341] opened 2016-11-21 02:48 UTC
Also you can not see the bar in specter mode
comes out invincible
Incompatibility with mod better pvp?
OptiFine 1.10.2 HD U D3 + better pvp mod
https://www.youtube.com/watch?v=IleSgj3syN8

**Comment by sp614x** [comment] 2016-11-21 09:29
Does it happen with OptiFine only (no BetterPvP?)

**Comment by Celestaux** [comment] 2016-11-21 20:51
I have also experienced this bug but it isn't just players its mobs and drops too. 
All I have is OptiFine and Chocapic13's v6 shader and it happens regardless of the shader.
It happened on a new world generated after 1.11 and it seems to be entire chunks of invisible entities. But not the same chunks after disconnecting and reconnecting. 

It is so prevalent me and my friends have had to stop using OptiFine altogether.

**Comment by sp614x** [comment] 2016-11-21 23:22
Is it only multiplayer or also singleplayer?
Only when using shaders?

**Comment by Celestaux** [comment] 2016-11-21 23:34
Ive only played mp since 1.11 but ill see if I can reproduce it in sp in a minute.
It happens even with shaders off.

**Comment by SrLokiToo** [comment] 2016-11-22 00:29
The problem only happens when I use the 2 mod at the same time

I do not understand much about creating mod

But I found a temporary solution

When I use f3 + a

Reloading all chuncks

You can see the players again
But minutes later returns to players invicible

version 1.10.2

**Comment by sp614x** [comment] 2016-11-22 11:22
I can not reproduce the invisible entities.
Already tried singleplayer, multiplayer, shaders, AA, AF, different resource packs, etc.
Is there a specific option that triggers it?
You can try to reset the video settings and try the options one by one.
Forge or OptiFine standalone? Which Forge version?
Only singleplayer or multiplayer?
Specific steps to reproduce it, for example: create new world, seed XYZ, walk to 120,70,600 see the sheep disappear?
Any errors in the error log?

**Comment by SrLokiToo** [comment] 2016-11-22 23:12
confirmed
The bug is optifine
I'm wearing optifine alone
And players invicible
Evidence on the link
https://www.youtube.com/watch?v=AWqWBRnDsys

**Comment by RViper80** [comment] 2016-11-23 05:37
Can confirm I am getting this as well on my 1.11 server, and that F3 + A to reload the chunks clears it up for a time. (strange that it's affecting two different versions?)  And I wasn't able to duplicate it on a single player instance.

Easiest way to find it is to drag an animal behind you on a lead while you fly around.  I'm doing that here with a pig. http://i513.photobucket.com/albums/t334/RViper80/OptifineBug/2016-11-22_22.59.46_zpseii379hd.png   I cross over into the next chunk, and it disappears.  You can still see the shadow of it from the shaders on the edge of the tree.  http://i513.photobucket.com/albums/t334/RViper80/OptifineBug/2016-11-22_22.59.59_zpslysk60ep.png

As far as reproducing it, unfortunately it seems completely random.  I created a world with a specific seed (MCWorld111 in this case), flew around until the pig went invisible, then took the screenshots.  I then deleted the world folder and remade it, but upon flying back to those coordinates, the pig remained visible this time.

**Comment by sp614x** [comment] 2016-11-23 10:39
Managed to reproduce it, flying in creative multiplayer with a pig on a leash did the trick.
Also found what the cause is, now looking for a workaround.

**Comment by DNx5** [comment] 2016-11-23 11:17
Could you provide the fix for 1.10.2 too? this problem is happen since D1 (I believe).
Many thanks!

**Comment by sp614x** [comment] 2016-11-23 12:14
Fixed in preview A5.
The problem was in the chunk cache and it was only appearing in multiplayer.

**Comment by sp614x** [comment] 2016-11-23 12:47
Updated preview D4 for 1.10.2 with a bugfix.

**Closed** 2016-11-24 13:11 UTC
Labels: bug
