### ISSUE TITLE
Blurred text when used with JourneyMap

### ISSUE THREAD

**Issue by joe1587joe** [sp614x/optifine#6441] opened 2021-12-05 16:50 UTC
All minecraft text (chat, item names etc) become blurred when using Optifine HD U H3 Pre7 and Journeymap

**Comment by KaiAF** [comment] 2021-12-05 17:12
Duplicate of #6281

**Closed** 2021-12-07 18:54 UTC

**Comment by mysticdrew** [comment] 2021-12-07 19:22
@joe1587joe 
I believe I fixed the issue, if you would like to verify it is fixed. Can you please head to the Journeymap discord and I can give you a test version.
