### ISSUE TITLE
Optifine plus tinkers construct armor causes crash

### ISSUE THREAD

**Issue by ArmouredDrood** [sp614x/optifine#6681] opened 2022-03-14 08:45 UTC
## Description of Issue

While playing 1.18.1, forge version 39.1.0, wearing tinkers armor causes player and all other players on the server to crash.
## Steps to Reproduce
1.Load game with tinkers construct and optifine, 
2wear tinkers construct Plate armor. (travelers armor probably works, haven't tested it)
3. crash

1. What do you do...
2. ...to find this bug?

## OptiFine Version

1.18.1_HD_U_H5
## Installation Method
jarfile into GDLauncher mods folder

## Fabric/Forge Version

Forge 1.18.1 39.1.0
## Other Installed Mods

https://pastebin.com/VS36Mpwz
see bottom of crashlog for mod list.

## Log Files/Crash Reports

https://pastebin.com/VS36Mpwz

## Prior Testing

      - 
Happens with Optifine and Tinkers.

**Comment by IvorAmlug** [comment] 2022-03-14 08:51
Neither of the Armors will Work not the slimeskulls the travelers or Plate armor.
This issue has allready been reportet here a while ago.

**Comment by fayer3** [comment] 2022-03-14 11:57
Duplicate of #6607 I think

**Comment by ArmouredDrood** [comment] 2022-03-14 20:28
Didn't realize this issue was already reported, apologies for the double post.
Still really hoping for a fix for optifine so it can support tinkers.

**Comment by ZenithRogue** [comment] 2022-03-22 18:15
closing in favor of #6607, added additional details

**Closed by ZenithRogue** 2022-03-22 18:15 UTC

**Comment by ZenithRogue** [comment] 2022-03-24 21:34
@ArmouredDrood update to the latest version of OptiFine, it shouod resolve your issue
