### ISSUE TITLE
cit question/issue

### ISSUE THREAD

**Issue by patrocinio-ptr** [sp614x/optifine#3520] opened 2020-03-08 16:11 UTC
I’m not sure if this is just a matter of time to cit armor models(not items, those work perfectly) start working or if anything on the programming side is going to change, because on my custom resourcepack when I use the cit for an armor piece, it doesn’t work

**Comment by realjackasterisk** [comment] 2020-03-20 21:18
What version of OptiFine? Link to resource pack?

**Comment by Sammyjoyplayz** [comment] 2020-05-14 07:35
Hey I am working on stacking enchantments on tools and making them all show. How can I create a .Properties text doc that has multiple enchants. As an example, a folder for tools with BOTH silk touch and efficiency.

**Comment by sp614x** [comment] 2020-05-28 19:11
Duplicate of #3276.

**Closed by sp614x** 2020-05-28 19:11 UTC
Labels: CIT, details needed
