### ISSUE TITLE
1.10.2 D7 - Crash with Malisis Doors / Malisis Core Mod

### ISSUE THREAD

**Issue by VideoklipBG** [sp614x/optifine#530] opened 2017-03-16 10:43 UTC
Minecraft Version: 1.10.2

Tested with: From 'Forge 12.18.3.2239' - To '12.18.3.2254'

OptiFine_1.10.2_HD_U_D6.jar - No Problem, No Crashes;

OptiFine_1.10.2_HD_U_D7.jar - Problems, Crash; (*Extracted Version Too*)

[crash-2017-03-16_12.34.04-client.txt](https://github.com/sp614x/optifine/files/847431/crash-2017-03-16_12.34.04-client.txt)

No Crashes, No Problems, Working with Older OptiFine Version Than 'D6' (Included)

**Comment by sp614x** [comment] 2017-03-16 11:07
Duplicate of https://github.com/sp614x/optifine/issues/461

**Closed by sp614x** 2017-03-16 11:07 UTC
