### ISSUE TITLE
[Mob not flashing] Mobs don't flash when they take damage

### ISSUE THREAD

**Issue by TheMaskedGamer06** [sp614x/optifine#3905] opened 2020-05-09 14:46 UTC
## Steps to Reproduce
1. Hit a mob

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre16

## Installation Method
I just clicked on install and it just installed right into Minecraft

## Other Installed Mods
Don't have any mods

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by sp614x** [comment] 2020-05-30 12:39
Duplicate of #3598.

**Closed by sp614x** 2020-05-30 12:39 UTC
Labels: 1.15, duplicate, shaders
