### ISSUE TITLE
[Shaders] Too shiny enchanted items & banners artifacting (on SEUS shaders) and no breaking animation on any block

### ISSUE THREAD

**Issue by denisbl** [sp614x/optifine#3726] opened 2020-04-10 13:28 UTC
## Description of Issue
I've been trying couple shaders (SEUS Renewed 1.0.1 and Sildur's Vibrant Shaders v1.25) in the latest optifine preview on Minecraft 1.15.2 and I've experienced some issues that didnt happen on 1.14.4 with the same shaders.
[EDIT: I also tried Sildur's Vibrant Shaders v1.27 but block breaking animation issue is still there]

The first issue I noticed is related to only one shader pack, which is SEUS Renewed 1.0.1, the issue is related to the banners, for some reason they keep flickering and turning white constantly, this didnt happen on 1.14.4 with the same shaders, however when I use Sildur's Vibrant Shaders v1.25 banners work normally, so its only related to SEUS Renewed.

The second issue that I've went through is related to SEUS shaders aswell, I've seen more users reporting it and apparently its known, basically every enchanted item looks too shiny. This wont happen on Minecraft 1.14.4 or using Sildur's shaders on 1.15.2.

The third issue I found is everytime I break a block on survival, no matter what block it is (wood, dirt, stone, ores, whatever) it doesnt have any breaking or cracking animations, It looks the same until it breaks. This happens with both shaders packs and its the most annoying bug from them all.

Here's link to a folder with an example video of me reproducing the issues and also having a look around my settings:
https://drive.google.com/open?id=12WusJe-JO96eYWfnICJWoa6jTgJdquHZ

## Steps to Reproduce
1. Enable shaders
2. Look at a banner or break a block or enchant an item

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre13

## Installation Method
I used the included standalone installer

## Log Files/Crash Reports
[2020-04-10-1.log](https://github.com/sp614x/optifine/files/4461678/2020-04-10-1.log)

## F3 Debug Screenshot
The screenshot is also included on the link that I wrote earlier, however here it is again:
https://drive.google.com/open?id=12WusJe-JO96eYWfnICJWoa6jTgJdquHZ

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No, the blocks break normally with their animation, banners wont artifact and enchanted items look normal.

## Additional Information
I have used the standalone installer which means that I have a Minecraft 1.15.2 installation just for Optifine, but I also have a forge installation (1.15.2-forge-31.1.0), two snapshots (20w14infinte and 20w15a) and a clean version of minecraft 1.15.2.
I dont know if they can somehow conflict each other but I thought it might be worth mentioning.
[EDIT: I tried a clean install by deleting the .minecraft folder and reinstalling 1.15.2 and then the standalone installer but the issues persist so I guess the other installation dont matter]

Lastly I wanted to say that I've also noticed but Im not sure if its a bug at all. When attacking mobs, they dont really turn red like on vanilla minecraft, I think they actually do it but its almost not noticeable as its a very slight effect. However Im unsure if its a bug or its just how the shaders are supposed to look like, I consider it a minor thing.

I also have couple texture packs (sapixcraft and purebdcraft) both x128 and for 1.15, but issues happen both of them and also with vanilla texture pack.

**Comment by NiemandTV** [comment] 2020-04-10 13:45
Duplicate of https://github.com/sp614x/optifine/issues/3590, https://github.com/sp614x/optifine/issues/3722 and https://github.com/sp614x/optifine/issues/3600. Please just use the search function.

**Comment by Destroyerz117** [comment] 2020-05-03 12:39
Having the exact same issues

**Comment by naeqirelle2020** [comment] 2020-06-07 06:11
First Problem (Banners Artifacting) still occurs on SEUS in pre-22

Second Problem (Enchanted Items too shiny) i can't see this issue in pre-22

Third Issue (Block Breaking animation doesn't show) still occurs in pre-22

**Comment by sp614x** [comment] 2020-06-21 09:54
Most should be fixed in latest preview.
The SEUS banner colors are still problematic #4084.

**Closed by sp614x** 2020-06-21 09:54 UTC
Labels: 1.15, shaders
