### ISSUE TITLE
CEM of Piglin, Piglin brute and zombified Piglin's arms and legs are not replaced with custom one.

### ISSUE THREAD

**Issue by minelist04** [sp614x/optifine#4727] opened 2020-08-29 03:13 UTC
Description of Issue
I created CEM to replace the whole model and I noticed that arms and legs are not replaced with the custom one I made.

image
![dvd](https://user-images.githubusercontent.com/57478204/91627137-6afa7880-e9df-11ea-8c89-d7af0053e31d.png)
![2563-08-29_10 05 12](https://user-images.githubusercontent.com/57478204/91627150-85cced00-e9df-11ea-8b0f-7dc1c0873e3d.png)

OptiFabric Version
OptiFine 1.16.2_HD_U_G3_pre7

file
[test_CEM_1162.zip](https://github.com/sp614x/optifine/files/5144719/test_CEM_1162.zip)

**Comment by ChaosDogG** [comment] 2020-12-08 21:18
yeah, i noticed this too, the arms seem to not want to work, instead they both form in the back right next to each other

**Comment by sp614x** [comment] 2021-03-26 22:33
Duplicate of #4766

**Closed by sp614x** 2021-03-26 22:33 UTC
Labels: 1.16, CEM
