### ISSUE TITLE
Optifine and JustEnoughItems weird issue

### ISSUE THREAD

**Issue by Senophoe** [sp614x/optifine#571] opened 2017-04-01 17:43 UTC
I'll just adress another issue posted at JEI's issue tracker, since it's exactly the same issue I was gonna post here.

https://github.com/mezz/JustEnoughItems/issues/790

Basically, Optifine causes the sky to change colors when hovering a mouse over an item in JEI. This happens on some other interfaces in game, like the one from FTB Utils in the top right corner of the image below. When it appears, the sky change colors. When the tooltip is gone, the color goes back to normal.

https://ibb.co/bYt5MF

**Comment by PapiDimmi** [comment] 2017-04-02 01:46
Duplicate of #534.

Anyway, I have the same issue, and it’s really annoying. In addition to this, OptiFine also changes the contrast of the game whenever you leave or enter a team zone created by FTB Utilities.

**Comment by Aphyxia** [comment] 2017-04-11 10:47
Doesn't happen for me after disabling Fast Rendering.

**Comment by sp614x** [comment] 2017-04-24 15:44
Duplicate of #534.

**Closed by sp614x** 2017-04-24 15:44 UTC

**Comment by PapiDimmi** [comment] 2017-04-25 03:33
@sp614x Your comment is a duplicate of my comment.
