### ISSUE TITLE
Borderless Fullscreen

### ISSUE THREAD

**Issue by WonkeIncorporated** [sp614x/optifine#7593] opened 2023-12-26 18:13 UTC
Adding functionality for minecraft to be played in "Borderless Fullscreen" on all computers. This stops the game minimizing every time the user will change tabs, saving time and making things easier for switching tabs, this helps people who may use multiple monitors, and do not want minecraft to minimize when going onto a second monitor for situations, such as messaging on other platforms, using browsers, using file explorer for resource packs/shaders/mods and other ideas. Just helps with EoA for users of optifine, thanks

**Comment by ZenithRogue** [comment] 2023-12-27 17:40
Closed as duplicate of #2516

**Closed by ZenithRogue** 2023-12-27 17:40 UTC
