### ISSUE TITLE
[Shaders Bug] Weird motion blur glitch on any shader

### ISSUE THREAD

**Issue by RacingWatermelon** [sp614x/optifine#3858] opened 2020-05-04 14:01 UTC
Turning on motion blur for any shader in all of the optifine 1.15.2 releases causes the arm to blur and glitch out. This did not happen on optifine 1.14.4.
![Badlion Client 2020 05 04 - 09 54 24 01_Trim_Moment(2)](https://user-images.githubusercontent.com/47016923/80973995-1f97db00-8dee-11ea-8101-8fae82200bfa.jpg)
![Badlion Client 2020 05 04 - 09 54 24 01_Trim_Moment(3)](https://user-images.githubusercontent.com/47016923/80974006-2292cb80-8dee-11ea-9223-103e52cea309.jpg)
![Badlion Client 2020 05 04 - 09 54 24 01_Trim_Moment](https://user-images.githubusercontent.com/47016923/80974018-258dbc00-8dee-11ea-8820-3d1a921ed47e.jpg)

**Comment by rre36** [comment] 2020-05-05 15:16
This is a (well) known issue affecting shaderpacks that use a specific method to detect the hand due to a bug in OptiFine for 1.15.
Related: #3646

**Comment by JPaalman** [comment] 2020-05-06 15:13
Same for me, I've had the issue since the first shader-compatible release. Walking also messes around with the hands, especially backwards.

**Comment by sp614x** [comment] 2020-06-03 19:04
Duplicate of #3646.
Fixed in pre17.

**Closed by sp614x** 2020-06-03 19:04 UTC
Labels: 1.15, shaders
