### ISSUE TITLE
[1.16.3-Optifine_HD_U_G3 Render Bug] Mobs seems to keep turning invisible at random, have to exit and reenter world to fix.

### ISSUE THREAD

**Issue by elman879** [sp614x/optifine#4922] opened 2020-10-16 01:18 UTC
## Description of Issue
I wrote out a good bit of this [here](https://old.reddit.com/r/MinecraftHelp/comments/jbgicd/java_mobs_keep_turning_invisible_video_example_in/g8yf0fe/) but ever since I downloaded 1.16.3 Optifine I've been getting invisible mobs everywhere. It started with my endermites, then my creepers (which got me killed), and then my piglins in my bartering farm. [Here is the link](https://streamable.com/7nv9xs) to the invisible piglins, and you can see the gold being warped to my position. It didn't matter where I was, it always did that. I also encountered a zombie that was invisible.

## Steps to Reproduce
I just started up the game and checked my creeper farm, endermite cage, and bartering farm, and something is usually invisible. I think it happens on startup.

## OptiFine Version
1.16.3-Optifine_HD_U_G3

## Installation Method
Used the installer.

## Other Installed Mods
I had BSL shaders installed in the streamable vid above but didn't have them turned on, my computer seems to not be good enough to run them at consistent 120fps so I don't really use them.

## F3 Debug Screenshot
https://imgur.com/a/1xgGtGq It's from the video above, I removed Optifine for the time being so sorry for the stuff

## Prior Testing
If you've installed standalone:
Don't think so. Didn't have this issue until I installed Optifine from what I can remember, and doing a fresh install of Minecraft fixed it. Reinstalling 1.16.3-Optifine_HD_U_G3 caused it to happen again.

## Additional Details
Let me know if I need to add anything to help get this fixed. It seems like this was a bug in 1.16.1 but I guess it's back, unless my computer has problems or something.

**Comment by AcmeLogan** [comment] 2020-10-22 00:28
I have this same issue, very frustrating. I was exploring a Piglin Bastion and got slaughtered by invisible brutes...

**Comment by diablo050189** [comment] 2020-10-25 16:03
Seems to happen when loading or reloading mobs. I can login and see mobs in my mob zoo then leave the area and come back and they will sometimes be invisible. If I relog then I can see them again but if I leave the area and come back theres a decent chance they will be invisible again.

**Comment by Lythael** [comment] 2020-11-09 10:55
Happens in Optifine release for 1.16.4 aswell.
So much for "issue already being fixed"

**Comment by dpill83** [comment] 2020-12-04 18:52
I have a server running the Drehmal: PRIMORDIAL map and Optifine is a requirement to use it. I've gotten complaints that some mobs are invisible. Advised users to close the game and relaunch it and the mobs appear.

**Comment by Teasy** [comment] 2020-12-11 11:12
Related thread:
https://github.com/sp614x/optifine/issues/5016

**Comment by elman879** [comment] 2020-12-19 05:02
I really hope this bug gets fixed soon because I would like to try using Optifine again, this bug is a dealbreaker for me though. I've had piglins, zombies, and creepers kill me that were invisible. Don't know what the roadmap is for bugs but this one can be game breaking at times.

**Comment by ZenIsBestWolf** [comment] 2021-02-01 19:05
Duplicate of #5016

**Closed by ZenIsBestWolf** 2021-02-01 19:05 UTC
