### ISSUE TITLE
[Shader] Unloaded chunks are just white

### ISSUE THREAD

**Issue by 1CAMOU** [sp614x/optifine#3778] opened 2020-04-23 22:53 UTC
## Description of Issue
it seems like a lot of chunks which are not loaded yet are just totally white which is super odd..
image is here: https://i.imgur.com/KTxOVQo.png

## Steps to Reproduce
1. Load in a shader in optifine 1.15.2
2. look around I guess...

## OptiFine Version
Latest

## Installation Method
Standalone installer Java

## F3 Debug Screenshot
https://i.imgur.com/OtikPnd.png

## Prior Testing
If you've installed standalone:
- no because i cant install shader in vanilla

- Does this happen without any mods at all?
   - no..
- Does this happen in OptiFine standalone?
   - yes
- Does this happen in Vanilla without OptiFine?
   - no......
- Have you tried using a binary search to find which mods cause this issue?
   - optifine does

## Additional Information
I feel like it mostly happens at certain day times.. there are a few times where it seems to be working

**Comment by sp614x** [comment] 2020-05-29 12:11
Duplicate of #3659.

**Closed by sp614x** 2020-05-29 12:11 UTC
Labels: 1.15, chunks, shaders
