### ISSUE TITLE
[Mac Shaders] Game not working with shaders still with pre-30

### ISSUE THREAD

**Issue by Theamazingrpm** [sp614x/optifine#6064] opened 2021-07-21 21:06 UTC
## Description of Issue

Hello. I just downloaded pre30 of Optifine Update 1-17 on Minecraft, and these pictures are what I got...please help. :(
## Steps to Reproduce
1. What do you do...
2. ...to find this bug?
I just got on the game and loaded it.
## OptiFine Version

pre30 update 1.17
## Installation Method

I used the standalone JAR installer
## Additional Information

![2021-07-21_17 01 11](https://user-images.githubusercontent.com/33363421/126560115-bd6fae8b-a388-4c7d-8559-f49292e399a7.png)
<img width="853" alt="Game not working" src="https://user-images.githubusercontent.com/33363421/126560159-a76ea6b3-7b8d-496e-b12e-b31c5eed793d.png">

**Comment by fayer3** [comment] 2021-07-21 21:24
could you post the latest.log, that should give more information on what the problem could be

**Comment by Theamazingrpm** [comment] 2021-07-21 21:47
Yes of course man! @fayer3 
[latest.log](https://github.com/sp614x/optifine/files/6858986/latest.log)

**Comment by rlefkowitz** [comment] 2021-07-22 18:27
I'm getting the message "No EXT_framebuffer_object". According to [this](https://www.khronos.org/opengl/wiki/Framebuffer_Object#EXT_Framebuffer_object), EXT_framebuffer_object has been completely removed in Core OpenGL 3.1 and above (my 2018 MacBook Pro uses OpenGL 4.1 with the core profile). What I find more interesting here is that with simpler shaders (say, Sildur's Enhanced Default 1.12 with settings maxed out), the error still gets thrown but the shaders still work as intended _SOME_ of the time.

**Comment by EricShi1685** [comment] 2021-07-23 02:56
I'm also getting the same exact issue

**Comment by sp614x** [comment] 2021-08-30 21:41
Should be fixed in pre31.

**Closed by sp614x** 2021-08-30 21:41 UTC
