### ISSUE TITLE
[Optifine 1.15.2 pre17] Items in hud and boats textures

### ISSUE THREAD

**Issue by Roma4kaaa** [sp614x/optifine#3957] opened 2020-05-16 16:54 UTC
## Description of Issue
I have a resource pack, in this renamed items have texture, but he have texture only in hud or inventory or when it drops, in hand he don't have texture. And boats don't have textures with resource pack.

## Steps to Reproduce
1. What do you do... 
2. ...to find this bug?

## OptiFine Version
1.15.2 Pre 1.17 

## Installation Method
With install program

I## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by sp614x** [comment] 2020-05-28 19:09
Duplicate of #3276.

**Closed by sp614x** 2020-05-28 19:09 UTC
Labels: 1.15, CIT
