### ISSUE TITLE
[CIT] Support for 1.20.5 Item Components

### ISSUE THREAD

**Issue by ZenithRogue** [sp614x/optifine#7658] opened 2024-04-23 15:50 UTC
## 1.20.5 Overhauled the Item Format 
MC release 1.20.5 has significantly overhauled the structure of item data.  The existing generic `tag` on items has been split up into a ton of new `component` fields.  Full details can be found on the release article below:
https://www.minecraft.net/en-us/article/minecraft-java-edition-1-20-5#:~:text=has%20been%20changed-,ITEM%20DATA%20FORMAT,-We%20have%20made

### Proposal:
Introduce a new CIT property called `components` that can address the components in much the same way as before
```properties
# Old:
nbt.display.Name=Example
# New:
component.minecraft\:custom_name=Example
# As a shorthand, leaving off the `minecraft:` prefix will assume `minecraft:` namespace
component.custom_name=Example
```
### Considerations:
Existing custom NBT data has been moved from item NBT `tag:{}` to the new `minecraft:custom_data` component, as a result, you might consider making `nbt.*=` as alias of `component.custom_data.*=`, to allow for a smoother transition.

Alternatively, a user could be warned on pack load that nbt selectors on CIT is no longer valid, and they need to update their pack.

**Comment by ZenithRogue** [comment] 2024-04-23 15:52
Leave it to mojang to release major breaking changes in a minor release, lol

**Comment by IMS212** [comment] 2024-04-23 20:22
having `:` in a key value may not be good for property reading code

**Comment by ZenithRogue** [comment] 2024-04-24 00:31
> having `:` in a key value may not be good for property reading code

how would you work around that? split it into multiple properties?
```properties
namespace=minecraft
component.custom_name=Example
```

**Comment by SHsuperCM** [comment] 2024-04-24 06:01
Json is definitely a very harsh transition but it does fit with vanilla resourcepacks formats pretty well. 

Another approach to that issue is using what's being done in the language file format conventions, where the namespace and path are separated by a dot, for example
```properties
component.minecraft.custom_name=Example
# or, alternatively, since minecraft is the defaulted namespace, whenever a namespace is not present
component.custom_name=Example
```

**Comment by SHsuperCM** [comment] 2024-04-24 06:07
Something else to be considered while making major/breaking changes is that components can be of any type and only then are serialized into nbt. There have been reports of item components slowing down the game(specifically talking about [MC-270668](https://bugs.mojang.com/browse/MC-270668)). Might be the time to handle components directly instead of their nbt representation. 

It'd be a shame to serialize a `Text` object to nbt just to check it against the old cit matching.

**Comment by soqb** [comment] 2024-05-05 06:54
note that the `.properties` spec officially supports key escapes like the following:
```properties
component.minecraft\:custom_name=Example
```

also, we should probably be using `components` instead of `component` to fit with the [NBT-ified data format](https://minecraft.wiki/w/Data_component_format#Item_format).

**Comment by PickleOnAString** [comment] 2024-05-29 04:28
any progress?

**Comment by ZenithRogue** [comment] 2024-06-07 15:26
the first preview version of OptiFine for 1.20.6 just came out, so it may be a little while before this gets added

**Comment by STICKzilla21** [comment] 2024-06-20 00:30
Some news? What solution is there to this right now to be able to continue using CIT in 1.20.6?

**Comment by STICKzilla21** [comment] 2024-06-20 00:51
I have also noticed that when using component.custom_name=Example all the items related to it change texture, regardless of the name

**Comment by Mukul1127** [comment] 2024-06-20 12:45
https://github.com/SHsuperCM/CITResewn/issues/406 this is a good idea in the meantime

**Comment by Ethanwu0608** [comment] 2024-07-09 21:46
> the first preview version of OptiFine for 1.20.6 just came out, so it may be a little while before this gets added

Sadly they did nothing.

**Comment by TQNL** [comment] 2024-07-20 14:32
as @soqb said, the new format should fit with vanilla, where you access nbt paths with `components."minecraft:custom_name"`

**Comment by GitsurferQwerty** [comment] 2024-07-20 22:08
It's been 4 months since 1.20.5 released with all the big changes so I was wondering how the progress on porting to item components is going? I've been waiting for the update so that CITResewn can update and I can use some enchantment datapacks that I like, and I'm not sure where the devs are at. Of course, I know that porting this is difficult and takes time, but I was wondering if anyone knew the progress they had so far.

**Comment by GitsurferQwerty** [comment] 2024-07-21 04:07
Looking back at my previous message I probably could've phrased it better, but I want to reiterate that I know doing a port like this takes time and all I'm asking is if anyone knows the status of the CIT, just so that I could extrapolate some sort of loose timeline for this. I was mainly wondering because I heard rumors that CITResewn was being deprecated and I know that's not true but I was just looking for some more insight

**Comment by KaiAF** [comment] 2024-07-21 13:05
No clue about the status for CIT support. Developer has had some IRL issues so the update to 1.21 has been really slow. Once he updates and actually has time to work on it, (not like 1.20.6 where 1.21 was released very soon after) I am sure it will be fixed, or at the very least looked at.

**Comment by Sameer-Expert** [comment] 2024-08-03 17:39
I would love if you could have both of the conditions "nbt" and "components" in a single .properties file and the resource pack shall work on every version of Minecraft.

Just like how minecraft:predicate works. By default, the condition is always true, and the condition is only set to false when no data matches. If any of the single data matches the condition, the condition shall be true. That's what I want for OptiFine CIT. So that we can use both nbt and components in a single resourcepack file and there won't be more clone copies of resourcepack on a resourcepack submission website.

**Comment by ditt0132** [comment] 2024-08-11 13:18
What about, create support for old nbt and mark as deprecated?
I mean, convert old nbt to new components and detect it
i believe there is a library doing same thing or in minecraft's code [(Like this)](https://docs.papermc.io/misc/tools/item-command-converter)

**Comment by Spike-has-no-idea-how-to-code** [comment] 2024-08-13 16:24
Can we get component support before gta 6 (impossible challenge)

**Comment by Spike-has-no-idea-how-to-code** [comment] 2024-08-13 20:27
go ahead, remove my comment, but im done trying to be respectful. its been over 4 months, make a decision so we can get on with our lives.

**Comment by Herobrine-Hunter** [comment] 2024-08-18 18:12
Hello @sp614x can you make a resource pack and exhibit how to do it cuz I don't understand anything.
Please do it fast

**Comment by blryface** [comment] 2024-08-18 18:18
no??? Sp is busy with life and won't do it to a random non paying person

**Comment by delta889x** [comment] 2024-08-27 16:57
@Herobrine-Hunter https://citresewn.shcm.io/ this is what I use to learn how it works. It's not perfect and probably will be out of date when 1.21 CIT comes out but you can use it to learn pre-1.21 CIT

**Comment by ZenithRogue** [comment] 2024-09-04 18:54
Waiting for final doc update, this is how things are been implemented as of `J1_pre9`
```properties
# (Optional) Component-based rule.  Use the replacement texture only when an item component
# has a specific value.  If multiple rules are provided, all of them must match.
# Use a command like "/data get entity @s SelectedItem" to view the item components.
# The component namespace must have a "\" before the ":"
#   components.minecraft\:custom_name=<value>
# If the component name doesn't have a namespace, the default "minecraft:" is automatically used.
#   components.lore -> components.minecraft\:lore
# For further atributes/properties the shortcut "~" can be used instead of the default namespace.
#   components.enchantments.levels.~thorns -> components.minecraft\:enchantments.levels.minecraft\:thorns
# Some common legacy NBT checks are translated as component names:
#   nbt.display.Name -> components.minecraft\:custom_name
#   nbt.display.Lore -> components.minecraft\:lore
# See: https://minecraft.wiki/w/Data_component_format
components.<name>=<value>
```

**Comment by WhoAteMyButter** [comment] 2024-09-04 21:52
Tracking this on OptiDocs at https://gitlab.com/whoatemybutter/optifinedocs/-/issues/28.
Will put pen to paper when this format is confirmed to be stable. Thanks.
Also,
```diff
- For further atributes
+ For further attributes
```

**Comment by GitsurferQwerty** [comment] 2024-09-10 23:06
Wow, this honestly got out earlier than I expected, so great job. On behalf of the community, sorry for all the impatience, but your doing gods work here

**Comment by sp614x** [comment] 2024-09-17 18:27
Finalized.

**Closed by sp614x** 2024-09-17 18:27 UTC
Labels: enhancement, CIT, in progress, 1.20.5, components
