### ISSUE TITLE
[Bug Report] ALL mobs randomly go invisible, not just nether mobs or in the nether.

### ISSUE THREAD

**Issue by WoodWorker54** [sp614x/optifine#4783] opened 2020-09-07 07:25 UTC
## Description of Issue
All mobs will randomly go invisible. It is sometimes fixed when logging off/on, but then other mobs will go invisible.

## Steps to Reproduce
1. Sometimes just waiting a couple minutes will result in mobs going invisible.
2. Sometimes when logging on, mobs will just be invisible from the start.

## OptiFine Version
Latest full release of 1.16.2 v.3. 

## Installation Method
Used the installer.

## Other Installed Mods
No other mods installed. Vanilla textures.

## Prior Testing
If you've installed standalone:
- This does NOT happen with vanilla by itself.

## Additional Information
Mobs are still there, making sounds, but completely invisible. Just wanted to report it again since the last report was claimed as fixed and was only nether mobs.

**Comment by Regnander** [comment] 2020-09-07 08:47
Related #4322

**Comment by Teasy** [comment] 2020-12-11 11:12
Related thread:
https://github.com/sp614x/optifine/issues/5016

**Comment by sp614x** [comment] 2021-02-13 19:17
Duplicate of #5016

**Closed by sp614x** 2021-02-13 19:17 UTC
