### ISSUE TITLE
CustomColor error

### ISSUE THREAD

**Issue by Paenthy** [sp614x/optifine#2183] opened 2019-02-03 12:41 UTC
Optifine was working fine with VoxelMap perfectly until today out of nowhere.
Now i'm getting the following error:

Error: java.lang.NoClassDefFoundError: net/optifine/CustomColors

I've tried multiple Optfine versions, clean installs of everything to no avail.

LOG:

---- Minecraft Crash Report ----
// Don't do that.

Time: 03-02-2019 12:35
Description: Unexpected error

java.lang.NoClassDefFoundError: net/optifine/CustomColors
	at net.optifine.util.TextureUtils.resourcesReloaded(TextureUtils.java:320)
	at net.optifine.util.TextureUtils$1.a(TextureUtils.java:367)
	at vh.a(SourceFile:118)
	at net.optifine.util.TextureUtils.registerResourceListener(TextureUtils.java:371)
	at cty.frameInit(EntityRenderer.java:1995)
	at cty.a(EntityRenderer.java:951)
	at cft.c(SourceFile:850)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.optifine.CustomColors
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 17 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.rift.optifine.json:client.MixinCustomColors] from phase [DEFAULT] in config [mixins.rift.optifine.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
	... 20 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @Inject annotation on handler$fixFluidColours$zcc000 could not find any targets matching 'getFluidColor' in the target class net.optifine.CustomColors. Using refmap mixins.rift.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:172)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:159)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:151)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:44)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:472)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1188)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:954)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:318)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:281)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 20 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 562091656 bytes (536 MB) / 1476395008 bytes (1408 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.13.2-rift-1.0.4-SNAPSHOT
	LWJGL: 3.1.6 build 14
	OpenGL: AMD Radeon R7 200 Series GL version 4.6.13544 Compatibility Profile Context 25.20.15011.1004, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'rift'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Dandelion-With-Mods-1.13.x.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor 
	OptiFine Version: OptiFine_1.13.2_HD_U_E5
	OptiFine Build: 20181221-162116
	Render Distance Chunks: 10
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13544 Compatibility Profile Context 25.20.15011.1004
	OpenGlRenderer: AMD Radeon R7 200 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 6

**Comment by AngrySpaceDorito64** [comment] 2019-02-03 13:01
I have the exact same problem. Everything was fine until this exact day. Hope it gets a fix soon.

**Comment by Fitchinks** [comment] 2019-02-03 13:35
Can back this up. Was wondering since I haven't changed anything. Tried reinstalling etc.
All I found is: The Optinefine Version alone works without problems. I only get ctd when trying to run it with RIFT.

**Comment by Paenthy** [comment] 2019-02-03 13:47
Yeah, this was all of a sudden. If you remove optfine, voxelmap works, but together no. If you try to run Optifine alone, then works. Super weird. Hope they fix it soon

**Comment by errorsallthethings** [comment] 2019-02-03 13:50
Same error as the original poster. Previous days it has been working fine without issue, this morning I am getting the similar error. No updates were made to the client, mods, or other files.

Mods installed:
- Rift 1.13.2
- OptiFine 1.13.2 HD U E5
- VoxelMap 1.8.2 for 1.13.2


---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2/3/19 7:41 AM
Description: Unexpected error

java.lang.NoClassDefFoundError: net/optifine/CustomColors
	at net.optifine.util.TextureUtils.resourcesReloaded(TextureUtils.java:320)
	at net.optifine.util.TextureUtils$1.a(TextureUtils.java:367)
	at vh.a(SourceFile:118)
	at net.optifine.util.TextureUtils.registerResourceListener(TextureUtils.java:371)
	at cty.frameInit(EntityRenderer.java:1995)
	at cty.a(EntityRenderer.java:951)
	at cft.c(SourceFile:850)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.optifine.CustomColors
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 17 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.rift.optifine.json:client.MixinCustomColors] from phase [DEFAULT] in config [mixins.rift.optifine.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
	... 20 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @Inject annotation on handler$fixFluidColours$zcc000 could not find any targets matching 'getFluidColor' in the target class net.optifine.CustomColors. Using refmap mixins.rift.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:172)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:159)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:151)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:44)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:472)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1188)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:954)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:318)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:281)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 20 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 696365336 bytes (664 MB) / 1140850688 bytes (1088 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.13.2-rift-1.0.4-SNAPSHOT
	LWJGL: 3.1.6 build 14
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'rift'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, voxelmap
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7 CPU 950 @ 3.07GHz
	OptiFine Version: OptiFine_1.13.2_HD_U_E5
	OptiFine Build: 20181221-162116
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 388.13
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by sp614x** [comment] 2019-02-03 17:00
OptiFine hasn't been tested with Rift. It may not be compatible with it.
Looks like the Rift mixin is failing to patch CustomColors.
Maybe Rift has been updated automatically.

**Comment by Paenthy** [comment] 2019-02-03 17:04
> 
> 
> OptiFine hasn't been tested with Rift. It may not be compatible with it.
> Looks like the Rift mixin is failing to patch CustomColors.
> Maybe Rift has been updated automatically.

Has been working the past weeks with both running together,... If Rift updated last night/today, then that could be the cause since nothing else changed in my computer/versions :/

Will you test on your end at least just to make sure? Will try to get the previous version of rift, if it updated without me knowing

**Comment by jakey1995abc** [comment] 2019-02-03 17:43
This is very strange, I am getting this exact error as well since last night. So I guess something related to rift/optifine is connecting to a server which has now changed in some way or something?

**Comment by Paenthy** [comment] 2019-02-03 18:03
This issue has been fixed a few minutes ago after my bug report on Rift page ^_^

**Comment by sp614x** [comment] 2019-02-03 18:07
OptiFine has no auto aupdate functionality. Either by itself or via the Mojang launcher.

**Comment by Paenthy** [comment] 2019-02-03 18:08
> 
> 
> OptiFine has no auto aupdate functionality. Either by itself or via the Mojang launcher.

Rift dev fixed the issue, was on their end

**Comment by Fitchinks** [comment] 2019-02-03 18:09
yea, in hindsight it seemed more like a RIFt Error than a Optifine one

**Comment by Chocohead** [comment] 2019-02-03 18:11
This is fixed in Chocohead/Rift@173f0df63a89f63e111401a5ab35fbf9c3582deb

**Closed** 2019-07-25 08:32 UTC
Labels: mods
