### ISSUE TITLE
[Bug 1.7.10] Crash / Compatibility issue when using OptiFine 1.7.10 HD U D7 and newer with morph

### ISSUE THREAD

**Issue by SolDev69** [sp614x/optifine#5106] opened 2020-12-14 22:19 UTC
## Description of Issue
Forge crashes when using versions newer than HD U D6 with the Morph mod by iChun

## Steps to Reproduce
1. Download forge (1614)
2. Install OptiFine (jar or extracted, doesn't matter), iChunUtil and Morph
3. Kill an animal on a superflat with default morph settings, or try morphing into an morph you already have, game crashes.

## OptiFine Version
HD U D7 and newer

## Installation Method
In mods folder. Doesn't matter if extracted or not.

## Fabric/Forge Version
Latest 1614

## Other Installed Mods
Morph and iChunUtil

## Log Files/Crash Reports
Do not currently have a log as I am on mobile. Will try to reproduce and will post the log in comments when I do.

## F3 Debug Screenshot
Not possible to get due to instant crash

## Prior Testing
It doesn't happen on HD U D6 and older, this issue is likely due to the addition of shaders messing with the Morph animation rendering.

## Additional Information
This issue is also present in 1.7.2, and requires the 1.7.2 equivalent of D6 to not crash. I know 1.7.10 isnt being maintained anymore but using an older version of OptiFine to not crash is annoying.

## GPU info
Included this encase it has something to do with my gpu, as I don't think this issue occured on my old PC with integrated graphics. My current gpu is an Nvidia Quadro 4000 with 2GB GDDR5 vram based off the Fermi architecture on GF100. Basically a cut-down GTX 480 that preforms more like a GT 240 according to techpowerup.

**Comment by sp614x** [comment] 2020-12-17 00:13
Crash report?

**Comment by ZenithRogue** [comment] 2020-12-17 13:54
> https://paste.ee/p/qmxOK
> Here is the log. I do not crash with just OptiFine, Morph, and iChunUtil, it just kicks me. I know OptiFine is the cause of the crash. (as removing it or downgrading to D6 solves the issue).

Here is the log the user provided in the discord server

**Comment by sp614x** [comment] 2020-12-17 15:24
Morph crashes in GLAllocation when handling a network packet.
There is not a single class in the stack trace that is changed by OptiFine.
The crash is in deleteDisplayLists(), looks like it is trying to delete a display list that is not allocated:
```
    public static synchronized void deleteDisplayLists(int par0)
    {
        GL11.glDeleteLists(par0, ((Integer)mapDisplayLists.remove(Integer.valueOf(par0))).intValue());
    }
```
```
java.lang.NullPointerException
	at net.minecraft.client.renderer.GLAllocation.func_74523_b(SourceFile:23) ~[ban.class:?]
	at morph.client.model.ModelHelper.getModelCubesCopy(ModelHelper.java:48) ~[ModelHelper.class:?]
	at morph.client.model.ModelMorphAcquisition.<init>(ModelMorphAcquisition.java:36) ~[ModelMorphAcquisition.class:?]
	at morph.client.entity.EntityMorphAcquisition.<init>(EntityMorphAcquisition.java:36) ~[EntityMorphAcquisition.class:?]
	at morph.common.packet.PacketMorphAcquisition.handleClient(PacketMorphAcquisition.java:87) ~[PacketMorphAcquisition.class:?]
	at morph.common.packet.PacketMorphAcquisition.execute(PacketMorphAcquisition.java:49) ~[PacketMorphAcquisition.class:?]
	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:84) ~[ChannelHandler$PacketExecuter.class:?]
	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:66) ~[ChannelHandler$PacketExecuter.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
```

**Comment by Jiingy** [comment] 2023-08-01 02:56
Closing for the following reasons:
1. Issue is very dated by now
2. As sp614x stated in the [previous comment](https://github.com/sp614x/optifine/issues/5106#issuecomment-747506514), this does not seem to be an issue with OptiFine in the first place.

If this issue is still present on 1.20.1 respective to both mods, and it is verifiable that this is caused by OptiFine it can be opened as a new issue.

**Closed by Jiingy** 2023-08-01 02:56 UTC
Labels: forge, mods, crash, 1.7
