### ISSUE TITLE
Change my donation email because my cape has been stolen and the email is temporaly ;-;

### ISSUE THREAD

**Issue by MonroyR** [sp614x/optifine#2596] opened 2019-07-06 08:48 UTC
I have a problem with the donation mail and it's because it doesn't require a password to get in because of what happened to me today and they changed my cover to another user so I require that they change my mail because on the page I don't allow it or indicate that it can be done, to avoid being fighting with the other guy who wants to take advantage without even paying a penny, pardon my English I'm relying ona translator, viva Mexico!

**Comment by Dragon8oy** [comment] 2019-07-10 08:22
I also need an email change, the email it's registered to is my dad's not mine.

**Comment by mindforger** [comment] 2019-07-10 08:32
you need to understand that sp614x requires to identify that you are the original owner of the account, how do ou think you can proof that?! 

the easiest and most common way is to send an email to the registered email account (you are kind of to blame yourself for using an public email for an registration, this is the worst that you could have done in the first place)

for @MonroyR i would say, you are kinda shit out of luck as long as you can not assure you are the original owner, you are out of luck

for @Dragon8oy even if it is your dads email, could you at least get him to hand you out the verification email?! this can not be sooo hard (except family reasons which i won't forget but it's low probability)

**Comment by Dragon8oy** [comment] 2019-07-10 10:24
So I get my Dad to send sp614x and email requesting a change then?

**Comment by mindforger** [comment] 2019-07-10 11:28
Email sender can be faked way too easily, i guess it would require sp614x to send you some sort of verification code to that email and you would have to verify it back to ap614x but isn't there a mechanism in your account settings on the website?!

**Comment by Dragon8oy** [comment] 2019-07-10 12:30
I couldn't find any mechanism to do this, if I'm missing something please show me where it is.

**Comment by mindforger** [comment] 2019-07-10 12:39
@sp614x should be able to help out here

**Comment by sp614x** [comment] 2019-07-10 15:33
Changing the donation email is currently not possible.
Verifying who is the real owner of the donation is not trivial.
Duplicate of #1868.

**Closed by sp614x** 2019-07-10 15:33 UTC
