### ISSUE TITLE
Error: java.lang.NullPointerException: Rendering overlay

### ISSUE THREAD

**Issue by FaranTahir1** [sp614x/optifine#4083] opened 2020-06-12 17:08 UTC
[crash-2020-06-12_21.37.11-client.txt](https://github.com/sp614x/optifine/files/4772204/crash-2020-06-12_21.37.11-client.txt)
[crash-2020-06-12_21.49.06-client.txt](https://github.com/sp614x/optifine/files/4772205/crash-2020-06-12_21.49.06-client.txt)
[crash-2020-06-12_22.00.46-client.txt](https://github.com/sp614x/optifine/files/4772206/crash-2020-06-12_22.00.46-client.txt)
[crash-2020-06-12_20.41.53-client.txt](https://github.com/sp614x/optifine/files/4772207/crash-2020-06-12_20.41.53-client.txt)
[crash-2020-06-12_20.48.14-client.txt](https://github.com/sp614x/optifine/files/4772208/crash-2020-06-12_20.48.14-client.txt)

**Comment by sp614x** [comment] 2020-06-13 16:29
Duplicate of #4082

**Closed by sp614x** 2020-06-13 16:29 UTC
