### ISSUE TITLE
[1.15.2] CIT Items viewable in inv, not when places

### ISSUE THREAD

**Issue by phoennikin** [sp614x/optifine#3992] opened 2020-05-25 15:00 UTC
When holding a renamed item, I can see the custom texture in my inventory. However when I place it in an item frame, the texture doesn't place properly.

I simply did what I usually would when using a CIT pack, and renamed the item for the custom texture. I could see the custom texture within my inventory but when placed it simply looked like an item within an item frame rather than a texture. 

Optifine 1.15.2 pre18 (and all other preview versions) 

Optifine was standalone. 

Forgive me if I've missed anything, I did my best.

**Comment by JermoMetGamesServer** [comment] 2020-05-25 19:46
It also doesn't show the item in hand.

**Comment by sp614x** [comment] 2020-05-28 19:08
Duplicate of #3276.

**Closed by sp614x** 2020-05-28 19:08 UTC
Labels: 1.15, CIT
