### ISSUE TITLE
[Bug] Vanilla ores not spawning with Optifine.

### ISSUE THREAD

**Issue by Grootloops33** [sp614x/optifine#5099] opened 2020-12-10 19:13 UTC
## Description of Issue
Vanilla ores do not spawn in modpacks, while optifine is installed and active on creating a new world.
When optifine is disabled, behaviour returns to normal. This bug was specifically found in ATM6.

## Steps to Reproduce
1. Install optifine
2. Create ATM6 World
3. No ores.
4. Uninstall Optifine
5. Create new world.
6. Ores.

## OptiFine Version
Minecraft 1.16.4
OptiFine HD U G5

## Installation Method
Manually dropped jar into the mods folder.

## Fabric/Forge Version
Forge-35.1.4

## Other Installed Mods
It's the ATM6 pack. No modifactions made.

**If OptiFine is installed as standalone, remove this section.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   Yes.

- Does this happen without any mods at all?
   No.

- Does this happen in OptiFine standalone?
   Yes.

- Does this happen in Vanilla without OptiFine?
   No. 

- Have you tried using a binary search to find which mods cause this issue?
   I have not.

## Additional Information
Regards to the "## F3 Debug Screenshot" I don't see any point of photographic evidence of "No ores".

**Comment by TelepathicGrunt** [comment] 2020-12-16 18:43
this is a duplicate of https://github.com/sp614x/optifine/issues/4880 which basically, using shaders in optifine nukes the features from biomes. even vanilla ones too

**Comment by sp614x** [comment] 2020-12-22 15:37
Duplicate of #4880

**Closed by sp614x** 2020-12-22 15:37 UTC
Labels: 1.16, biomes, forge, mods, shaders
