### ISSUE TITLE
[1.15.2_pre16] Glowing effect not working when Shaders or Fast Render are enabled

### ISSUE THREAD

**Issue by FranJose13** [sp614x/optifine#3914] opened 2020-05-10 21:13 UTC
Glowing effect is simply not worging and its annoying the bug is in OptiFine 1.15.2 HD U G1 pre16

**Comment by Mickael97o** [comment] 2020-05-11 12:29
Same here, but turning off fast render will solve the problem. (at least it worked for me)

**Comment by Aeltumn** [comment] 2020-05-18 12:30
Bump, would really like to see this fixed! Really annoying that some users are completely unable to see the glowing effect.

**Comment by sp614x** [comment] 2020-05-19 14:53
Is the glowing effect missing with shaders or without shaders?

**Comment by Aeltumn** [comment] 2020-05-19 21:51
The glowing effect is missing when using shaders, but this issue is rather about the glowing effect not working when using the Fast Render setting.

**Comment by sp614x** [comment] 2020-05-29 10:57
Duplicate of #3662.

**Closed by sp614x** 2020-05-29 10:57 UTC
Labels: 1.15, details needed
