### ISSUE TITLE
[Bug] 1.17.1 CEM only partially renders

### ISSUE THREAD

**Issue by Bane-7** [sp614x/optifine#6357] opened 2021-11-03 20:59 UTC
## Description of Issue
In OptiFine 1.17.1, CEM models only partially render. The models being used are .jem files using .jpm files containing the model information for each part. From what I can tell, it only renders the last part passed to the "models" list in the .jem file. Removing that model from the list allows the one before it (now the last model in the list) to render. I.e., the order the parts are listed in are:
- Body (part: "body", attach: false)
- Head (part: "body", attach: true)
- Left Arm (part: "body", attach: true)
- Right Arm (part: "body", attach: true)
- Left Leg (part: "body", attach: true)
- Right Leg (part: "body", attach: true)

Only the right leg renders. If the right leg is removed from the .jem, only the left leg renders, and so on.

## Steps to Reproduce
1. Load a resource pack using CEM in OptiFine 1.17.1.
    - .jem, .jpm, and textures (with a few exceptions) should all generally be put in <resource_pack>/assets/minecraft/optifine/cem/
2. Enter a world and spawn a modified mob.
3. Observe.

## OptiFine Version
1.17.1 HD U G9
1.17.1 HD U H1 pre9
1.17.1 HD U H2 pre1
1.18 HD U H3

## Installation Method
OptiFine standalone installer

## F3 Debug Screenshot
1.16.5 HD U G8 (full, correct render)
![2021-11-03_15 52 09](https://user-images.githubusercontent.com/60361427/140187681-47fc01a6-6a12-4591-9705-ee54320babc7.png)

1.17.1 HD U G9 (only right leg renders)
![2021-11-03_15 54 02](https://user-images.githubusercontent.com/60361427/140187904-9600c1a3-6c35-452d-8566-ea5caf6b60da.png)

1.17.1 HD U H1 pre9 (only right leg renders)
![2021-11-03_15 55 28](https://user-images.githubusercontent.com/60361427/140187999-4755f064-19c0-44a9-9cac-78306a8b8066.png)

## Prior Testing
As shown in the screenshots, OptiFine 1.16.5 HD U G8 does not have this issue. The exact same resource pack was used in each version. Reinstalling OptiFine 1.16.5, 1.17.1, and 1.17.1 pre9 all yielded the same results.

I also concluded that it wasn't just the texture mapping acting weird and only rendering transparent pieces. Replacing the mob textures with entirely solid colors still shows that only one part is actually rendering at all.

Also, I know that, according to the CEM documentation, setting "attach": false on any part in the "models" list causes that part to replace the original part from the vanilla model, while "attach": true does not. However, setting "attach": false on the head, arms, or legs does nothing visually in 1.17.1 on my model, and setting "attach": true on the body part allows the original body to render again, but the right leg is still the only CEM part that renders.

## Additional Information
Here are the .jem and .jpm files used in the screenshots:
[cem_models.zip](https://github.com/sp614x/optifine/files/7470426/cem_models.zip)
Because of how relatively complex villager textures are (they are among the "few exceptions" mentioned earlier), I also included the creeper's .jem file. It shows behavior identical to the villager, and all it needs for a texture is a 64x64 creeper.png in the same directory (skin layout is the same as Alyx).

On a tangent, there is a typo in the CEM documentation in the cem_model.txt file at line 144:
`models`
should be
`"models":`
I was leery, but I tried making this change in my .jem files to see if for some reason this was an actual change in the way they were parsed/processed. Neglecting the quotes and colon will still cause an error in the JSON file.

Edit: Updated versions.

**Comment by Bane-7** [comment] 2021-11-09 01:17
Further testing:
Replacing the last model's .jpm reference in the list (right leg) by directly inserting the box coordinates allows the next one in the list (left leg) to render (albeit incorrectly, actually), but also does not render the replaced model.

**Comment by LastMagmarian** [comment] 2021-12-09 16:07
I'm having the same problem. It seems like it isn't checking whether something has attach set to true or not and just replaces anything on the same bone with the lowest item on the list.

**Comment by ewanhowell5195** [comment] 2021-12-14 10:34
duplicate of #5793

**Comment by ZenithRogue** [comment] 2021-12-20 18:09
Fixed as per https://github.com/sp614x/optifine/issues/5793#issuecomment-998140614

**Closed by ZenithRogue** 2021-12-20 18:09 UTC
