### ISSUE TITLE
[Bug] When breaking or place blocks near large areas of water the game lags

### ISSUE THREAD

**Issue by Gaduji** [sp614x/optifine#4073] opened 2020-06-10 15:59 UTC
## Description of Issue
When I am breaking or placing blocks near large areas of water like a river, ocean, or lake my FPS drops significantly. This started to happen when I was draining an ocean monument and needed to break the monument and then place sand afterwards to remove the water. In both cases my FPS dropped from 75 down to 20-30 after simply breaking one or two blocks. I tried to break and mine without Optifine and there were no FPS drops. The FPS drops seem to happen only when using Optifine.

## Steps to Reproduce
1. Find a large area of water like an ocean or river. 
2. Place/Mine blocks in that area
3. Watch FPS decrease

## OptiFine Version
1.15.2_HD_U_G1_pre23

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
In Vanilla this issue is non existent
![2020-06-10_10 54 59](https://user-images.githubusercontent.com/66739747/84290533-65d90c00-ab09-11ea-856c-5697126abff7.png)

**Comment by sp614x** [comment] 2020-06-15 10:27
Duplicate of #3797.

**Closed by sp614x** 2020-06-15 10:27 UTC
Labels: 1.15, chunks, performance
