### ISSUE TITLE
Ghost blocks above frozen ocean

### ISSUE THREAD

**Issue by Masken644** [sp614x/optifine#5703] opened 2021-06-08 18:43 UTC
windows 10 
mc version 1.17 java
![1](https://user-images.githubusercontent.com/85582375/121239910-6d1b2d00-c8b7-11eb-83d0-707dadaec6c7.png)
![2](https://user-images.githubusercontent.com/85582375/121239919-70161d80-c8b7-11eb-981d-8fc2c4c37c90.png)
![image](https://user-images.githubusercontent.com/85582375/121239964-7c9a7600-c8b7-11eb-81c6-d0875ca1291a.png)

**Comment by Scorpion34** [comment] 2021-06-08 18:53
> windows 10
> mc version 1.17 java
> ![1](https://user-images.githubusercontent.com/85582375/121239910-6d1b2d00-c8b7-11eb-83d0-707dadaec6c7.png)
> ![2](https://user-images.githubusercontent.com/85582375/121239919-70161d80-c8b7-11eb-981d-8fc2c4c37c90.png)
> ![image](https://user-images.githubusercontent.com/85582375/121239964-7c9a7600-c8b7-11eb-81c6-d0875ca1291a.png)

turn off render regions the issue is already addressed in #5698

**Comment by Cart3r1234** [comment] 2021-06-08 18:59
Happens anywhere there is ice; I saw it happen in mountain biomes

**Comment by KaiAF** [comment] 2021-06-08 19:17
Closing this issue as it already has been reported.
#5698

**Closed by KaiAF** 2021-06-08 19:17 UTC
