### ISSUE TITLE
1.16.5+ Player hand does not appear when spectating an entity in the Replay mod

### ISSUE THREAD

**Issue by VkPipi** [sp614x/optifine#6364] opened 2021-11-05 16:35 UTC
This bug exists for months now, and has been well explain in the #6139 issue. It seems to be unfortunately forgoten, so im trying to bring some attention to it. Sorry for posting a bug that has been already reported.

**Comment by KaiAF** [comment] 2021-11-06 13:35
Closing this because this is not a bug report

**Closed by KaiAF** 2021-11-06 13:35 UTC
