### ISSUE TITLE
[Feature] Custom armor models

### ISSUE THREAD

**Issue by CalamityGreen** [sp614x/optifine#4059] opened 2020-06-08 12:56 UTC
Honestly lot of us waiting a possibility to create custom armor models for years.

We can make custom helmets via pumpkin models (custom helmets from Conqest is just amazing) but can't do nothing withs our limbs and body.
We are can make custom slots in the our inventory, can add multilayers to armor textures trough lore using optifine features but...

Can you make this feature somehow please?

**Comment by sp614x** [comment] 2020-06-08 13:43
Relevant #823.

**Comment by ewanhowell5195** [comment] 2024-09-13 15:00
duplicate of #561

**Closed by ewanhowell5195** 2024-09-13 15:00 UTC
Labels: enhancement, CEM
