### ISSUE TITLE
[Category] Food Item Texture Problem

### ISSUE THREAD

**Issue by Shark10199** [sp614x/optifine#7571] opened 2023-10-25 18:57 UTC
I made a custom texture for a food in Minecraft when I rename it in a anvil. The food changed to my custom texture and so it worked but when I eat it the food particles look like the original texture.

**Comment by ZenithRogue** [comment] 2023-11-28 16:11
Duplicate of #5326. If you want to use CIT with food for now, use a custom model that has that texture, rather than a texture directly. According to the commenter on the linked issue, this should fix it

**Comment by Jiingy** [comment] 2023-12-07 01:58
Closing as dupe of https://github.com/sp614x/optifine/issues/5326.

**Closed by Jiingy** 2023-12-07 01:58 UTC
