### ISSUE TITLE
Cobblestone Wall rendering issue

### ISSUE THREAD

**Issue by Zefferis** [sp614x/optifine#1972] opened 2018-10-24 22:48 UTC
When a line of cobblestone walls are placed above another set of cobblestone walls, the upper texture of the lower set of walls becomes black - instead of normally rendering like in Vanilla.

Effected blocks that I'm aware of are:

``cobblestone_wall``
``mossy_cobblestone_wall``

![2018-10-24_15 44 47](https://user-images.githubusercontent.com/15270437/47466007-26c73d00-d7a4-11e8-92eb-02632297dda1.png)

**Comment by sp614x** [comment] 2018-10-24 22:50
Duplicate of #1872.

**Closed by sp614x** 2018-10-24 22:50 UTC
