### ISSUE TITLE
[Crash] Game crashed "Accessing LegacyRandomSource from multiple threads"

### ISSUE THREAD

**Issue by slambert-msft** [sp614x/optifine#6913] opened 2022-07-03 04:44 UTC
## Description of Issue
Shortly after launching the game I was gliding toward unloaded chunks when the game crashed.  I have no idea what the triggering event was, as I was still at least a chunk away from the black.

Looking at the log, I see a warning about the inability to play an ambient cod sound, so maybe that's related?

## Steps to Reproduce
1. Sorry, not sure.  Maybe listen to the fishes?

## OptiFine Version
1.19-OptiFine_HD_U_H8_pre2
[crash-2022-07-02_21.29.02-client.txt](https://github.com/sp614x/optifine/files/9034091/crash-2022-07-02_21.29.02-client.txt)

## Installation Method
Clicking the jar doesn't work on my machine for whatever reason, so I used an admin console window to run
"java -jar preview_OptiFine_1.19_HD_U_H8_pre2.jar" in the appropriate directory.

## Log Files/Crash Reports
[crash-2022-07-02_21.29.02-client.txt](https://github.com/sp614x/optifine/files/9034091/crash-2022-07-02_21.29.02-client.txt)
[latest.log](https://github.com/sp614x/optifine/files/9034094/latest.log)

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine? This is the first time the game has ever crashed for me, after many happy hours of both Vanilla and OptiFine 18.1 and 18.2 use.  =]

**Comment by UnknownTheLad** [comment] 2022-07-03 13:12
Duplicate of #6858

**Comment by UnknownTheLad** [comment] 2022-07-03 13:12
Disable connected textures as a temporary workaround.

**Closed** 2022-07-04 07:59 UTC
