### ISSUE TITLE
[1.17 bug]opifine and minihud incompatibility

### ISSUE THREAD

**Issue by ruhzn** [sp614x/optifine#5773] opened 2021-06-11 13:56 UTC
In singleplayer mode, When both opifine and minihud are installed(Including their frontiers)  killing a creature and pick up its droppings then my cilent crash XD

**Comment by KaiAF** [comment] 2021-06-11 17:47
This needs more details, can you send a F3 screenshot? Can you provide a crash log? Are you using fabric or trying to use forge?

**Comment by ruhzn** [comment] 2021-06-12 03:08
[hs_err_pid2892.log](https://github.com/sp614x/optifine/files/6641570/hs_err_pid2892.log)
![2](https://user-images.githubusercontent.com/82208032/121763391-581bf380-cb6e-11eb-9e7c-4cf3d718534a.png)

**Comment by KaiAF** [comment] 2021-06-12 03:18
The crash is caused by Nvidia Drivers, not OptiFine. You could update them and see if that help or you can downgrade them to see if that helps. But since this is not an OptiFine issue, I am closing the report.

**Closed by KaiAF** 2021-06-12 03:18 UTC
Labels: 1.17, details needed

**Comment by ruhzn** [comment] 2021-06-12 03:32
ok, thanks for your help
