### ISSUE TITLE
[name bades model] for tridents...

### ISSUE THREAD

**Issue by maxipetri05** [sp614x/optifine#6742] opened 2022-04-05 19:04 UTC
I know you get requested for the name-based trident models a lot but I just wanted to know if it is somehow possible and if it will be comming soon, it would be pretty grattifying and a lot of people would make use of it. But if it is not possible then we have to live with it :/. Great job on everything tho.

**Comment by Ari-RERA-43** [comment] 2022-04-05 19:06
Duplicate of #2703. Close this issue. If you would like to discuss this issue, do so there.

**Closed** 2022-04-05 19:16 UTC
