### ISSUE TITLE
[Bug] Forests without trees

### ISSUE THREAD

**Issue by Allomere** [sp614x/optifine#5103] opened 2020-12-12 16:52 UTC
## Description of Issue
Today i decided to update my private modpack to 1.16.4 since most mods had a working build for that version, i createad a new world to do some troubleshooting and verify if everything was working as intended, but i noticed that the biomes were a little to "plane" and realised that most of the forests from "Oh the Biomes you'll go"weren't generating with trees.
I unistalled all the mods that affected world generation, leaving only optfine, byg and minimap that shows my current biome.

And when i created a new wolrd i spawned on a Seasonal Forest biome and imeadtly noticed the lack of trees and folliages:
![image](https://user-images.githubusercontent.com/71918599/101989015-3ce23100-3c7c-11eb-99c7-42b313b11310.png)

After i discovered this i posted an issue on BYG's (Oh the Biomes you'll go) github and the dev noticed me that optifine does in fact alter world generation and that it was the problem.
So i unistalled Optifine and generated a world with the same seed and all the folliage generated normally

## Steps to Reproduce
1. install optifine;
2. install [BYG](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go);
3. create a world with this seed 2005637330215208216.
4. get no trees

## OptiFine Version
OptiFine HD U G5 1.16.4

## Installation Method
.jar on the mod's folder

## Fabric/Forge Version
Forge 35.0.1

## Other Installed Mods
1. Oh the biomes you'll go

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
[2020-12-12-1.log](https://github.com/sp614x/optifine/files/5683434/2020-12-12-1.log)

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/71918599/101989638-89c80680-3c80-11eb-8a7a-681978170ace.png)

## Prior Testing
- Does this happen without other mods installed? 
   - No, only happens when i install OptiFine
- Does this happen without any mods at all?
   - No, its an issue with modded biomes (as far as i know this didnt happen with vanilla biomes)
- Does this happen in OptiFine standalone?
  - No
- Does this happen in Vanilla without OptiFine?
  - No
- Have you tried using a binary search to find which mods cause this issue?
   - Yes, i  used this to find wich mods where conflicting
   - Does the issue still happen with only the remaining mods installed?
      - No, only happens when i have BYG and OptiFine installed

## Additional Information
I'm not sure if this actually affects vanilla biomes aswell

**Comment by TelepathicGrunt** [comment] 2020-12-16 18:42
This is a duplicate of this issue: https://github.com/sp614x/optifine/issues/4880

basically, using shaders in optifine will nuke the features of biome mods.

**Comment by Cr4fTJuNkiE** [comment] 2020-12-17 22:38
Not just biome mods though. Using OF for 1.16.4 with the latest version of Mekanism for 1.16.4 causes vanilla ores to NOT spawn as well.

**Comment by sp614x** [comment] 2020-12-18 15:51
Duplicate of #4880

**Closed by sp614x** 2020-12-18 15:51 UTC
