### ISSUE TITLE
Hitboxes don't show with shaders

### ISSUE THREAD

**Issue by Julnz** [sp614x/optifine#6103] opened 2021-07-29 05:55 UTC
Hitboxes are nonexistent

**Comment by KaiAF** [comment] 2021-07-30 20:41
Can you provide a f3 screenshot? What shaders you are using? Any resource packs? You have to provide more details.

**Comment by sp614x** [comment] 2021-08-20 20:30
This is caused by the Minecraft 1.17 change to OpenGL 3.2 core profile.
For shader packs that use standard transformations OptiFine adds a compatibility patch and fixes the block outline.
Shader packs that use custom transformations can't be fixed by OptiFine and would have to be updated to 1.17.

**Closed by sp614x** 2021-08-20 20:30 UTC
Labels: shaders, details needed, 1.17

**Comment by DriesMagnus** [comment] 2021-11-29 15:55
I encountered this issue this very week.
I used OptiFine version 1.17.1 HD U H1 (this also occurred with HD U G9 and HD U H2 pre1) and Sildur's Vibrant Shaders.
Because you said it should be the shader packs' fault, I decided to download a couple of different shader packs from different creators, BSL, SEUS Renewed, and some others.
All had this same issue.

Then I decided to try Iris instead of OptiFine and low and behold, it just works as intended.

To be clear and for more details: the issue itself is the hitboxes not showing after enabling them using F3 + B.
It will show them if shaders are disabled, but the moment you use any shader (not the internal one), it will stop showing shaders as seen here (screenshots are shown with HD U H1 and Sildur's Vibrant Shaders High-MotionBlur v1.30):
![2021-11-29_16 40 51](https://user-images.githubusercontent.com/61743943/143898057-d5cd9a44-64cd-4f83-b999-98f16b682926.png)

Strangely, when viewing your inventory, it does show your player's hitbox:
![2021-11-29_16 41 11](https://user-images.githubusercontent.com/61743943/143898168-fd1b9c42-b252-4fce-b0a3-5c80bf42144c.png)

This is how it looks like when I turn off shaders:
![2021-11-29_16 42 20](https://user-images.githubusercontent.com/61743943/143898269-dc1ac007-b51d-4777-aa0a-28f57f56ed51.png)

As it does work perfectly fine when using Iris, it seems as if it is an OptiFine issue, but I am not a developer so I can't say for sure.

To eliminate my desktop being a factor in this, I tested this as well on my (powerful) laptop, with the same results.
I also tested this on Hypixel and a private survival server and had the same results.

If I can provide any other details to help investigate this issue, I am glad to do so!
