### ISSUE TITLE
Tinkers' Construct Items....Invisible

### ISSUE THREAD

**Issue by DishyCorn23** [sp614x/optifine#814] opened 2017-08-04 20:26 UTC
I did post an issue on SlimeKnight (Tinker Dev) and his members said it's something to do with Optifine, please fix it (or be compatible with Tinker Construct, to fix the texture)
![2017-08-03_09 10 18](https://user-images.githubusercontent.com/30673360/28985660-f5288940-79a6-11e7-981b-a488041e4ae0.png)

**Comment by Builderb0y** [comment] 2017-08-04 22:37
#785?

**Comment by sp614x** [comment] 2017-08-08 14:19
Duplicate of #775 and #785.
Fixed in C5 for 1.12.

**Closed by sp614x** 2017-08-08 14:19 UTC
