### ISSUE TITLE
[Issue] Mobs not flashing red when hitting

### ISSUE THREAD

**Issue by DJaq02** [sp614x/optifine#3640] opened 2020-04-01 13:07 UTC
When hitting hostile mobs they are not flashing red as they should.
Optifine version is 1.15.2 HD U G1 pre12

**Comment by seeruk** [comment] 2020-04-02 14:03
Issue also present in pre13

**Comment by NiemandTV** [comment] 2020-04-02 14:09
Duplicate of https://github.com/sp614x/optifine/issues/3598
(This is because the uniform `entityColor` is currently not working.)

**Comment by sp614x** [comment] 2020-06-07 16:39
Duplicate of #3598.

**Closed by sp614x** 2020-06-07 16:39 UTC
Labels: 1.15, shaders
