### ISSUE TITLE
Game Crashed

### ISSUE THREAD

**Issue by MissEnaB** [sp614x/optifine#6902] opened 2022-07-02 01:47 UTC
## Description of Issue
 Game Crashed almost immediately after starting.

## Steps to Reproduce
1. What do you do... Opened Game
2. ...to find this bug? Regular Game Play

## OptiFine Version
 1.19 Preview 2

## Installation Method
 Installed Standalone

## Log Files/Crash Reports
 
[crash-2022-07-01_18.35.13-client.txt](https://github.com/sp614x/optifine/files/9032213/crash-2022-07-01_18.35.13-client.txt)

## Additional Information

![image](https://user-images.githubusercontent.com/108559251/176982175-038c2300-f61c-487f-b02f-b7716a7d42da.png)

**Comment by UnknownTheLad** [comment] 2022-07-02 14:17
Duplicate of #6858

**Comment by KaiAF** [comment] 2022-07-03 02:42
Reported #6858

**Closed by KaiAF** 2022-07-03 02:42 UTC
