### ISSUE TITLE
[1.16.1-pre2] Some textures not rendering

### ISSUE THREAD

**Issue by clin444** [sp614x/optifine#4257] opened 2020-07-05 17:42 UTC
## Description of Issue
Beds, Chests, Mobs, Dropped Items, and Block Breaking textures don't render.
## Steps to Reproduce
1. Start up the game.
2. Set "Fast Render" to "On".
3. Set "Graphics" to "Fabulous"
## OptiFine Version
1.16.1 HD U G2 pre2
## Installation Method
Used included standalone installer
## Log Files/Crash Reports
N/A
## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/33680274/86538591-69806880-bee6-11ea-8f99-db8642417265.png)
## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No
## Additional Information
Works on both servers and singleplayer worlds.

Problem only occurs during the first life after loading up the game. (start up the game, load up any world/server, the problem occurs immediately.)

After dying, the objects mentioned above render correctly.

Sometimes, facing a certain direction will allow the objects to render correctly (unable to reliable reproduce this).

Switching worlds/servers does not fix this.

**Comment by MtKrRa** [comment] 2020-07-05 19:19
Disable "Fast render" option in "Other" seems to fix this.
(I'm sorry if the names are wrong, I'm using Optifine in another language)

**Comment by sp614x** [comment] 2020-07-09 13:40
Duplicate of #4289

**Closed by sp614x** 2020-07-09 13:40 UTC
