### ISSUE TITLE
[Issue] Crashes at undefined intervals

### ISSUE THREAD

**Issue by ElementOfSmash** [sp614x/optifine#6877] opened 2022-06-30 05:09 UTC
## Description of Issue
When playing the game in any gamemode, and on any save file, the game will crash. It usually returns a -1 exit code. 

## Steps to Reproduce
There are no discernable action which reliably produce a crash. Reloading the same save several times may produce a crash at different points, even if the same actions are taken. 

## OptiFine Version
1.19 HD U pre

## Installation Method
Used the standalone JAVA installer

## Other Installed Mods
I am testing 4 different Shaders*:
-BSL v8.1.02.3
-Complementary Shaders v4.5
-MakeUp UltraFast v8.5b
-projectLUMA v1.32

*Shaders are being used in an installation of OF 1.18.2 HD, and are not being used on 1.19pre. However, they are present in the shaders folder and able to be selected in the Shader menu. 

Some saves use the full suite of VanillaTweaks datapacks, but not all files that have experienced crashed use datapacks

Resource Packs are sometimes used:
SimonKraft 128x
Clarity 1.19
Creator Pack 1.19 v1.2.3
Vis Mundis 1.19 v1.0

## Log Files/Crash Reports
See Below

## F3 Debug Screenshot
Attached

## Prior Testing

- Does this happen in Vanilla without OptiFine?
-No

## Additional Information
The game crashed whilst accessing legacyrandomsource from multiple threads
Error: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
Exit Code: -1

I've only started using shaders. I've used previous OF versions for performance purposes. Crashes happen even with no shaders or resource packs loaded. 

[2022-06-29-7.log.gz](https://github.com/sp614x/optifine/files/9016478/2022-06-29-7.log.gz)
[crash-2022-06-29_21.02.27-client.txt](https://github.com/sp614x/optifine/files/9016480/crash-2022-06-29_21.02.27-client.txt)
[crash-2022-06-29_23.40.54-client.txt](https://github.com/sp614x/optifine/files/9016481/crash-2022-06-29_23.40.54-client.txt)
[2022-06-29-5.log.gz](https://github.com/sp614x/optifine/files/9016483/2022-06-29-5.log.gz)
![2022-06-30_00 06 30](https://user-images.githubusercontent.com/108447969/176597166-80b359ef-2df0-4bf3-b493-2cb8abc318d6.png)

**Comment by UnknownTheLad** [comment] 2022-06-30 09:58
Duplicate of #6858

**Closed** 2022-06-30 13:28 UTC
