### ISSUE TITLE
A bit more open

### ISSUE THREAD

**Issue by ZoruaBit** [sp614x/optifine#5128] opened 2020-12-23 20:01 UTC
Most mod creators whos mods crash with optifine says that due to its closed sorce its hard to add compatibilty. i do wish for you (while maby not going full open sorce) help mod creators add compatibilty for shaders and other stuff. aswell as make it more transparent if you do. the only few mod creators that have full shader compbatibility are the ones who also make mods. thank you

**Comment by ZenIsBestWolf** [comment] 2021-02-01 19:03
Duplicate of #3270

**Closed by ZenIsBestWolf** 2021-02-01 19:03 UTC
Labels: duplicate, wontfix
