### ISSUE TITLE
[BUG] Optifine 1.8.9 crashes minecraft and turns screen white 

### ISSUE THREAD

**Issue by Chezburger4lyfe** [sp614x/optifine#5066] opened 2020-11-27 08:06 UTC
## Description of Issue
When I open Minecraft with forge and Optifine it crashes and shows a white screen. I am still able to interact with it

## Steps to Reproduce
1. Launch Minecraft with Optifine
2. Crash

## OptiFine Version
OptiFine_1.8.9_HD_U_L5

## Installation Method
JAR file was dropped into mods folder

## Fabric/Forge Version
Forge 1.8.9 - 11.15.1.2318

## Other Installed Mods
*Every* single mod you have installed, besides OptiFine. Please don't leave anything out, even if you think it has nothing to do with the issue at hand. For long lists of mods, use Pastebin. https://pastebin.com/
[1.8.9] ArmorStatusHUD
[1.8.9] BspkrsCore
[1.8.9] StatusEffectHUD
AutoGG-4.0.3 (1.8.9)
AutoSprint-1.2.0
Levelhead-7.2 (1.8.9)
Orange's+1.7+Animations-6.7

## Log Files/Crash Reports
[Crash.txt](https://github.com/sp614x/optifine/files/5606655/Crash.txt)

## F3 Debug Screenshot
None

## Prior Testing
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
No, it just crashes with exit code 0, but when I add Optifine to my mod folder it becomes a white screen

## Additional Information
It only started when I updated my mac to Big Sur

**Comment by ZenIsBestWolf** [comment] 2021-02-01 18:24
Duplicate of #5028

**Closed by ZenIsBestWolf** 2021-02-01 18:24 UTC
Labels: duplicate
