### ISSUE TITLE
Enchantment glint glitch and sky fix

### ISSUE THREAD

**Issue by StrongerFish309** [sp614x/optifine#7636] opened 2024-03-19 23:34 UTC
If you reload a texture pack, or change the language in your settings, or do anything that makes the Mojang logo come up while you are in a world. The enchant glint on the item you are holding looks dodgy. Only way to fix this right now is to quit out of the game entirely and log back into a world.

Day/Night cycle: When it is getting darker or brighter during a Minecraft day, the brightness of the sky does about 4 tiny time change updates, and does not go darker or brighter smoothly, but in regular Vanilla Minecraft, it is very smooth.

**Comment by GeForceLegend** [comment] 2024-03-20 07:39
Duplicate of #7482

**Comment by Jiingy** [comment] 2024-03-20 22:14
Considering this issue contains two seperate bugs, I am closing this as a duplicate of https://github.com/sp614x/optifine/issues/7482 as mentioned prior.

**Closed by Jiingy** 2024-03-20 22:14 UTC
