### ISSUE TITLE
Some Lead things (Visual)

### ISSUE THREAD

**Issue by TheSnowyChickens** [sp614x/optifine#1181] opened 2018-01-25 19:15 UTC
Hello,

in a world I "tried to swim in lava" with blindness and nausea effect, then I respawned and see this (Look at the screenshot) :
![2018-01-25_20 08 17](https://user-images.githubusercontent.com/29357962/35407244-97ae11a2-020b-11e8-98c6-132e5edd0130.png)
The Leads from the horses are flickering (difficult to make it visible in screenshots) and they are visible from the fence (or horse) to my death point (Look screenshot 2)
![2018-01-25_20 12 24](https://user-images.githubusercontent.com/29357962/35407387-15dfe4ec-020c-11e8-820f-86985a23f581.png)
In this Lava I "tried to swim in lava".

MC 1.12.2
Newest optifine preview (22.01.2018, C9)
No Forge and no other mods

**Comment by Regnander** [comment] 2018-02-05 20:53
Can you reproduce this glitch without Optifine?

**Comment by TheSnowyChickens** [comment] 2018-02-06 15:18
Nope

**Comment by Regnander** [comment] 2018-02-07 20:01
I just tried to reproduce your glitch using your instructions and your screenshots for reference, but to no avail. Although I used 1.12.2 HD U C9 pre from 02.02.2018, which is currently the most recent preview. Does the glitch still occur in this version for you?

**Comment by TheSnowyChickens** [comment] 2018-02-08 14:08
Yes, maybe I forgot to say, that I was in Adventure mode. (and probably I sneaked)

![bug](https://user-images.githubusercontent.com/29357962/35976938-f34229a0-0ce1-11e8-8a93-39acd4ffe5e2.PNG)

**Comment by TheSnowyChickens** [comment] 2018-02-08 14:34
Nvm. I tried it in Vanilla now, without opti, and now it happens there too. We can close it here now and report this issue at mojangs bug tracker. (In my first Vanilla test I forgot the Adventure mode presumably, sry. :) )

**Comment by sp614x** [comment] 2018-02-08 15:10
Looks like a vanilla bug. 
It can't be easily fixed in OptiFine.

**Closed by sp614x** 2018-02-08 15:10 UTC
