### ISSUE TITLE
Mipmap changes texture of reeds

### ISSUE THREAD

**Issue by Godlander** [sp614x/optifine#880] opened 2017-09-04 22:10 UTC
http://imgur.com/a/9hz8O

First picture is without optifine, second is with. I found out that turning mipmapping on anything but off results in this change in texture. Antialiasing and Anistropic Filtering does not affect textures.

**Comment by sp614x** [comment] 2017-09-05 02:33
The reeds texture is 26x26. Mipmaps needs power of 2 textures (16, 32, 64, etc) to work properly.
Vanilla decreases the mipmap level or effectively disables mipmaps, OptiFine scales the textures so the mipmaps can work.
Duplicate of #618.

**Closed by sp614x** 2017-09-05 02:33 UTC
