### ISSUE TITLE
Shadow Issue (OptiFine HD U G9 pre22)

### ISSUE THREAD

**Issue by Zekerupp** [sp614x/optifine#5870] opened 2021-06-26 06:59 UTC
![2021-06-26_01 49 17](https://user-images.githubusercontent.com/86511140/123504973-17b67e00-d622-11eb-9ad8-915e49182878.png)
![2021-06-26_01 51 47](https://user-images.githubusercontent.com/86511140/123504978-1ab16e80-d622-11eb-90c5-947b921cc6e8.png)
Not sure what else to say... But the shadows are broken as seen in the first shot.
In the second shot, we see a torch I placed down at night, as you may see there is no light.

**Comment by MisterNoNameLP** [comment] 2021-06-26 08:30
Same issue here with "Sildurs Vibrant Shaders v1.29"

[Logfile](https://pastebin.com/2WKb7D35)

**Comment by KaiAF** [comment] 2021-06-26 15:59
Closing in favor for #5872. This bug is caused by shaders.

**Closed by KaiAF** 2021-06-26 15:59 UTC
