### ISSUE TITLE
[Suggestion] Cloud  layers

### ISSUE THREAD

**Issue by TreeHorse** [sp614x/optifine#2681] opened 2019-07-26 13:49 UTC
I'm not sure if this is the right place for these kinds of suggestions, here goes...

I had the idea from the cloud height setting that you guys have in optifine, and i thought that "I wonder if it would be difficult to add the ability to control more than just one cloud layer." Like have two or even three layers and control the height, maybe speed and texture. Change textures the same way as you do with resource packs (just so that the other layers wouldn't be identical, might look funny at times if they were).

**Comment by realjackasterisk** [comment] 2019-07-26 13:56
#1441

**Comment by TreeHorse** [comment] 2019-07-26 14:13
I meant more like layers of the 3D clouds. but yeah, I didn't see that there was a suggestion for this already, sorry D:

**Comment by sp614x** [comment] 2019-08-29 10:05
Duplicate of #1441

**Closed by sp614x** 2019-08-29 10:05 UTC
Labels: duplicate
