### ISSUE TITLE
0 fps with optifine 1.15.2 pre 13

### ISSUE THREAD

**Issue by Es-mea** [sp614x/optifine#3841] opened 2020-05-03 14:55 UTC
## Description of Issue
I open a world in Minecraft (superflat, peacefull, a few pigs around, some water and some buildings with some armorstands and itemframes) and I have 0 fps. Just now when I opened it I had 18/3 fps but it immediately changed to 0/0. I have 4 installed ram.

## Steps to Reproduce
1. Open world
2. nothing
3. more nothing

## OptiFine Version
1.15.2-Optifine_HD_U_G1_pre13/vanilla. I also tried the pre 9

## Installation Method
I downloaded it from the official optine website and clicked: open when ready. I also downloaded one on another website and did the same

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/4570796/latest.log)

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/64739570/80917252-0fd0b600-8d5e-11ea-9db3-dc4ba1da279d.png)

## Prior Testing
This doesn't happen in normal vanilla. In the same place in the same world I have 5-48 fps, around 30 most of the time(without moving).

## Additional Information
My processor is Intel(R) Core(TM) i5-3210M CPU @ 2.50 GHz 2.50 GHz
I have 4 installed ram.
I also turned all the options optifine gives to as fast as possible.

**Comment by Regnander** [comment] 2020-05-03 15:50
Try upgrading to pre15 and see if the problem still is there.

**Comment by sp614x** [comment] 2020-06-07 13:10
Duplicate of #3543.

**Closed by sp614x** 2020-06-07 13:10 UTC
Labels: 1.15, performance
