### ISSUE TITLE
Christmas hat??

### ISSUE THREAD

**Issue by Blueeyestar** [sp614x/optifine#5163] opened 2020-12-30 20:52 UTC
With us NPC generated all have Christmas hats on. Should that be so ?

how can i deactivate it in optifine?

![2020-12-30_20 21 03](https://user-images.githubusercontent.com/35557302/103380371-fcdad500-4ae8-11eb-8cf3-0c39c576d50d.png)

**Comment by KaiAF** [comment] 2020-12-30 20:54
This is mainly for bug reports. But you can deactivate it by going to the cape editor

**Comment by Blueeyestar** [comment] 2020-12-30 20:58
that has nothing to do with cape editor. If I create an NPC with Citizens and this skin that I create has a cape on, this NPC automatically has a Santa hat on. so i can't remove it. So every NPC I create and their namesake has a cape automatically has a hat on.

**Comment by Regnander** [comment] 2021-01-01 13:20
Related #5150

**Comment by sp614x** [comment] 2021-01-01 18:40
Duplicate of #5150

**Closed by sp614x** 2021-01-01 18:40 UTC
