### ISSUE TITLE
[Shaders][1.15.2 pre13] Red Damage Flash not showing up when shaders are on.

### ISSUE THREAD

**Issue by Violainbow** [sp614x/optifine#3683] opened 2020-04-05 05:41 UTC
Pretty much exactly as described. I tried this with multiple different shaders (could only test shaders that work on Intel graphics), making sure that the damage flash option is set to "on" when applicable.

![2020-04-04_22 32 00](https://user-images.githubusercontent.com/61405813/78467794-2d5e2180-76c5-11ea-9250-06f235c2fc88.png)

It was kind of hard to really get a screenshot, but here it is.

**Comment by RedCarlos26** [comment] 2020-04-07 02:52
I have the same bug in preview 13 with BSL shader

**Comment by seeruk** [comment] 2020-04-07 10:14
Duped by https://github.com/sp614x/optifine/issues/3598

**Comment by Scorpion34** [comment] 2020-04-13 14:50
Yeah from my understanding it has something to do with the optifine client setup, and the version sided client the uniform exists and the game doesn't recognize the bug which not an expert by any means but I think it has something to do with org.lwjgl.opengl.ARBShaderObjects because using just plain optifine the mob flash works just fine but as soon as any type of shaders is added including internal it seems to turn it off for some odd reason and not quite sure but the VALUE_UNKNOWN = -3.4028235E38F could plausibly be messing with it too it's hard to pinpoint an exact reason but either way the main cause is from the Uniform hopefully gets patched soon in pre_14 or the new release of 1.15.2

**Comment by YoussefSaleh2004** [comment] 2020-04-29 16:48
> Yeah from my understanding it has something to do with the optifine client setup, and the version sided client the uniform exists and the game doesn't recognize the bug which not an expert by any means but I think it has something to do with org.lwjgl.opengl.ARBShaderObjects because using just plain optifine the mob flash works just fine but as soon as any type of shaders is added including internal it seems to turn it off for some odd reason and not quite sure but the VALUE_UNKNOWN = -3.4028235E38F could plausibly be messing with it too it's hard to pinpoint an exact reason but either way the main cause is from the Uniform hopefully gets patched soon in pre_14 or the new release of 1.15.2

where can i find org.lwjgl.opengl.ARBShaderObjects?

**Comment by Scorpion34** [comment] 2020-04-30 04:11
> > Yeah from my understanding it has something to do with the optifine client setup, and the version sided client the uniform exists and the game doesn't recognize the bug which not an expert by any means but I think it has something to do with org.lwjgl.opengl.ARBShaderObjects because using just plain optifine the mob flash works just fine but as soon as any type of shaders is added including internal it seems to turn it off for some odd reason and not quite sure but the VALUE_UNKNOWN = -3.4028235E38F could plausibly be messing with it too it's hard to pinpoint an exact reason but either way the main cause is from the Uniform hopefully gets patched soon in pre_14 or the new release of 1.15.2
> 
> where can i find org.lwjgl.opengl.ARBShaderObjects?

I used 7zip to access archives i don't know the exact file in where it lies but I know that is what it is called the thing is though is it cannot be fixed unless you have some coding knowledge even then some of the data inside optifine is very all over the place making a fix very difficult the uniform is to blame something is causing an issue without the debugger realizing it so it could be a shader problem a debugging problem a shadow rendering problem basically it could be anything and unfortunately all we can do is wait to see if it'll get fixed by spx which as of currently optifine 1.15 is still not out most likely due to forge and fixing this uniform bug until then we either deal with the issue or just play in no shaders which BTW tested to see if downloading 1.14 and replacing the uniforms it doesn't work nor do I think any version will fix it its really just a client bug unfortunately :/

**Comment by sp614x** [comment] 2020-05-30 12:39
Duplicate of #3598

**Closed by sp614x** 2020-05-30 12:39 UTC
Labels: 1.15, duplicate, shaders
