### ISSUE TITLE
[1.15.2] White void with Shaders

### ISSUE THREAD

**Issue by Master5157** [sp614x/optifine#3659] opened 2020-04-02 18:31 UTC
Apparently this goes back and has happened before with other optifine versions. While using shaders the void when uncovered appears as a white square.

**Comment by HiItsDevin** [comment] 2020-04-02 18:34
Are you using fabric or forge? Are you using standalone? Visuals of this happening? What version? Please... use the template.

**Comment by Master5157** [comment] 2020-04-02 18:51
I apologize for the lack of information. Here is all the information needed.

Steps to reproduce: 
The white plot/square seems to be replacing the void when you view it from above. I'm using the BSL 1.15.2 shader and nothing else.
Optifine version:
OptiFine 1.15.2 HD U G1 pre13
Installation Method: 
Standalone Installer
-----------------
Not using anything else than optifine and the shader itself.
----------------- 
As soon as the shaders are off, the problem doesn't appear.
![problem](https://user-images.githubusercontent.com/38780844/78290167-97d75c00-7523-11ea-9851-ca1d92f85d8b.png)

**Comment by TheJSHuA** [comment] 2020-04-04 13:00
This is an already known bug, caused by the sky renderer not rendering over the entire sky in shaders. This won't happen in every shader, just in shaders that use the vanilla sky renderer instead of just rendering their own sky.

**Comment by sp614x** [comment] 2020-06-06 18:18
Duplicate of  #3673.

**Closed by sp614x** 2020-06-06 18:18 UTC
Labels: 1.15, shaders
