### ISSUE TITLE
Texture error

### ISSUE THREAD

**Issue by github226268** [sp614x/optifine#6665] opened 2022-03-09 10:57 UTC
I found a texture error in Optifine 1.18.2 H6 pre1.
![2022-03-09_17 38 31](https://user-images.githubusercontent.com/61681976/157428284-71fa56f5-ea48-4869-9db3-463607373435.png)

**Comment by Ari-RERA-43** [comment] 2022-03-09 11:07
Duplicate of #6646. Close this issue.

**Closed** 2022-03-09 18:18 UTC
