### ISSUE TITLE
[1.12.2] Crash if using forge and entity.properties

### ISSUE THREAD

**Issue by Sildurs-shaders** [sp614x/optifine#3116] opened 2019-12-01 19:12 UTC
If you use optifine with forge minecraft crashes on 1.12.2 if a shaderpack makes use of entity.properties. It doesn't crash if the file is empty or deleted.
[latest.log](https://github.com/sp614x/optifine/files/3908615/latest.log)

**Comment by sp614x** [comment] 2019-12-06 21:58
Fixed in F6_pre1 for 1.12.2
Duplicate of #3044.

**Closed by sp614x** 2019-12-06 21:58 UTC
Labels: crash, shaders
