### ISSUE TITLE
Chunks not loading in 15.2 pre 16 

### ISSUE THREAD

**Issue by ThatsNutty** [sp614x/optifine#3927] opened 2020-05-12 19:13 UTC
Anytime i try to load into a world, its limited to about 16 chunks by 16 chunks and if i go over the edge in survival i get stuck and cant move but when i go in creative all of the chunks disappear and only entities are visable. Is this a glitch with optifine or something on my end?

**Comment by gtstorm99** [comment] 2020-05-12 19:31
I am experiencing the same issues. Started out of nowhere seemingly. Doesn't happen when I boot the game without optifine.

![2020-05-12_15 22 25](https://user-images.githubusercontent.com/53832971/81737058-8314af00-9465-11ea-9692-f18f72a596bd.png)
![2020-05-12_15 22 31](https://user-images.githubusercontent.com/53832971/81737062-8445dc00-9465-11ea-8ca1-adeeea9e7596.png)

**Comment by sp614x** [comment] 2020-05-29 12:21
Duplicate of #3873.

**Closed by sp614x** 2020-05-29 12:21 UTC
Labels: 1.15, chunks
