### ISSUE TITLE
[1.14.2] java.lang.NoSuchFieldError: clearEnabled

### ISSUE THREAD

**Issue by MagentaRuby** [sp614x/optifine#2498] opened 2019-06-15 19:24 UTC
OptiFine 1.14.2 HD U F1 pre13 crashes shortly after the window opens. This happens with or without other mods enabled.

OS: Kubuntu 18.04
Minecraft Version: 1.14.2
Launcher: MultiMC 5 v0.6.5-1217

### Crash Report
```
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 6/15/19 2:09 PM
Description: Unexpected error

java.lang.NoSuchFieldError: clearEnabled
	at agd.a(DebugProfiler.java:96)
	at cvk.e(SourceFile:942)
	at cvk.b(SourceFile:411)
	at net.minecraft.client.main.Main.main(SourceFile:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.2
	Operating System: Linux (amd64) version 4.15.0-51-generic
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 505222448 bytes (481 MB) / 816316416 bytes (778 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	Launched Version: MultiMC5
	LWJGL: 3.2.1 build 12
	OpenGL: GeForce GT 745M/PCIe/SSE2 GL version 4.6.0 NVIDIA 418.56, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/VanillaTweaks_r786884.zip
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
```

### patches/optifine.OptiFine.json
```
{
    "formatVersion": 1,
    "+libraries": [
        {
            "name": "net.minecraft:launchwrapper:1.12"
        },
        {
            "name": "optifine:OptiFine:1.14.2_HD_U_F1_pre13",
            "MMC-hint": "local",
            "MMC-filename": "preview_OptiFine_1.14.2_HD_U_F1_pre13.jar"
        }
    ],
    "+tweakers": [ "optifine.OptiFineTweaker" ],
    "fileId": "optifine.OptiFine",
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "requires": [
        {
            "uid": "net.minecraft",
            "equals": "1.14.2"
        }
    ],
    "name": "OptiFine",
    "version": "1.14.2_HD_U_F1_pre13"
}
```

**Comment by sp614x** [comment] 2019-06-15 21:19
Duplicate of #2411.
The crash is different, but it is caused by the same problem.

**Closed by sp614x** 2019-06-15 21:19 UTC
