### ISSUE TITLE
[Shaders] at_tangent attribute is missing for entities.

### ISSUE THREAD

**Issue by rayferric** [sp614x/optifine#4097] opened 2020-06-15 15:08 UTC
## Description of Issue
`vec4 at_tangent` attribute is not provided for living entities, signs, chests, etc.

## Steps to Reproduce
1. Write a shaderpack that utilizes normal mapping technique.
2. Modify it to display the `at_tangent.xyz` value.

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre26

## Installation Method
Installed using the standalone installer.

## Log Files/Crash Reports
No warnings nor error reports displayed.

## F3 Debug Screenshot
![missing-at_tangent](https://user-images.githubusercontent.com/63957587/84673581-315eb900-af2a-11ea-927d-3c925f0df031.png)

## Additional Information
- This problem doesn't appear in OptiFine 1.12.2 HD U E1 installed via Minecraft Forge.
- I'm using `gbuffers_textured_lit` program to display the debug view.

**Comment by sp614x** [comment] 2020-06-15 15:53
In 1.15 the entities use a separate vertex format which doesn't have the extended attributes yet.

**Comment by naeqirelle2020** [comment] 2020-06-19 05:55
duplicate of #3808

**Closed** 2020-06-19 10:48 UTC
Labels: 1.15, bug, shaders, todo
