### ISSUE TITLE
optifine.net is recognized as malicious by google

### ISSUE THREAD

**Issue by liach** [sp614x/optifine#1206] opened 2018-02-09 06:13 UTC
![image](https://user-images.githubusercontent.com/7806504/36014145-2c19ed2c-0d1d-11e8-8936-57367594a09d.png)

This is very disturbing to users trying to download optifine. I wish you can contact google to fix this silly thing.

**Comment by sp614x** [comment] 2018-02-09 11:56
The google transparency report shows as reason "Try to trick visitors into sharing personal info or downloading software".

![image](https://user-images.githubusercontent.com/16635441/36026690-7d5a1b64-0d98-11e8-8b41-c23ebfce17b6.png)

**Comment by sp614x** [comment] 2018-02-09 11:59
You can report a false positive here: https://safebrowsing.google.com/safebrowsing/report_error/?hl=en

No idea how Google comes to this conclusion. All authentication pages are secured with SSL (https).

**Comment by sp614x** [comment] 2018-02-09 13:29
The VirusTotal report shows Fortinet and Google Safe Browsing as problematic.
https://www.virustotal.com/en/url/18bf8c18f49875d4a41a5170f7748f9bef6056c2d582a2b282c8b469147cc887/analysis/1518182601/

To report a false positive:

1. Fortinet
https://fortiguard.com/webfilter?q=optifine.net
https://fortiguard.com/faq/wfratingsubmit?url=optifine.net

2. Google Safe Browsing
https://safebrowsing.google.com/safebrowsing/report_error/?hl=en

**Comment by vpontin** [comment] 2018-02-09 14:58
Can be something related to bad ads? Forge forums had similar issues in the past

**Comment by liach** [comment] 2018-02-09 14:58
already reported for false positives.

**Comment by WesCook** [comment] 2018-02-09 15:02
Are you set up in Google Search Console?  You may be able to review the claim through that interface.

**Comment by sp614x** [comment] 2018-02-09 15:16
The google search console reports:

```
Deceptive Inclusions
These pages embed content such as images or ads that attempts to trick users into doing something dangerous such as installing unwanted software or revealing personal information.
```
Looks like it may be related to ads.

**Comment by sp614x** [comment] 2018-02-09 15:35
Removed all ads and submitted a review request to Google.

**Comment by liach** [comment] 2018-02-09 16:26
I thought https://optifine.net/capeChange may be considered as phishing minecraft account details

**Comment by yer-mtd** [comment] 2018-02-09 18:00
I wonder if it's related to adfly ads? Adfly's ads being deceptive is a common thing.

**Comment by yer-mtd** [comment] 2018-02-09 18:13
Adfly ads are "deceptive" at best. I've had them pretend to be the actual site they point to! 

If you want to be clear from things like this, avoid those redirect ad things. None of them are safe. Use in-site ads instead.

**Comment by Puremin0rez** [comment] 2018-02-10 05:08
Optifines website has some nasty ads to be fair - my friend was tricked into downloading something else because of it. Too many download buttons and people get confused as to what one is real.

**Comment by pie-flavor** [comment] 2018-02-10 07:54
I might have actually prompted this. A couple of weeks ago, I noticed that if you googled 'optifine', the topminecraftmods.com Optifine link was displayed as the 'ad' link (it still does at the time of this posting). I reported it, as one would, because the TMM link was not only an Optifine rehost with potentially malicious content, but one that tried to look like the actual site.
Has Google gotten it flipped around? Did they flag the wrong site? It seems like too much of a coincidence.

**Comment by jcm2606** [comment] 2018-02-10 09:10
Puremin0rez, you can't really blame that on Optifine. Sites using third-party advertising services like Adsense don't have a say in what ads are shown to the user, and address shortening services like AdFly even more so. Potentially any website using third-party services can deliver malicious ads to the user, its just up to the service.

Not saying it's acceptable, but you can't fault Optifine or sp for something that's out of his control.

**Comment by WesCook** [comment] 2018-02-10 09:33
AdSense gives you [decent control](https://support.google.com/adsense/answer/180609?hl=en) over permitted ads.  Of course, you also have the option of choosing a reputable ad network.  AdFly is certainly not considered reputable, and are more likely to serve ads that violate Google's guidelines.

**Comment by Puremin0rez** [comment] 2018-02-10 10:20
@jcm2606 It most certainly is under his control for displaying malicious ads - he chose to use Adfly. Adfly is the worst offender of them all. Adfly is garbage. Nobody is forcing him to use this.

If Google Adsense was used, there would be a ton of control and much better, safer ads. So yes, he has no control over the SPECIFIC Ads shown - but has control over what advertisement services he uses.

I'm not here to be negative but I honestly think Google was right in it's decision to mark the website as deceptive. There were so many fake "download" buttons on the page from malicious ads, or terrible ad.fly redirect based ads.

Every time I tell someone to get Optifine, I give them the site, and they start getting bombed with ads and it's hard to even get to the legitimate download. It's easier to just download the jar and send it to them directly using an ad blocker.

Love Optifine, but I hope this is a lesson learned.

**Comment by hanakocz** [comment] 2018-02-10 11:35
Why you cannot use Curse as everyone else. It rewards uploaders by the amount of downloads from ad revenue and such a well downloaded mod would manage to make a lot of credit on that. 
Personally I hate adfly links and when I can, I avoid them. Because adfly is nasty and I won't support such a practic. But I would be totally okay in supporting *you* by adding to the number of downloads, thus to your revenue on Curse.

**Comment by mchorse** [comment] 2018-02-10 11:49
@hanakocz Curse doesn't pay as much Adfly or other URL shorteners, and you'll need to wait a long time before you get paid.

**Comment by vpontin** [comment] 2018-02-10 12:22
But Curse also would be good because it automates a lot modpack things - good for newbie players

**Comment by Puremin0rez** [comment] 2018-02-10 13:34
@mchorse You're entirely correct - Adfly does have good payout in comparison to some others, but the reason it does is because of how malicious it is. They will show anything they can with no remorse for the content shown. Malicious, pornographic in some cases - as long as it earns money, they show it. I've had adfly open popups, new tabs with other ads, and more. It's an nasty ad service that earns money by treating the user like garbage and forcing their hand to view an advertisement.

Google blocking Optifine.net is a good example of what kind of terror adfly (or any other non reputable ad service) can cause your completely legitimate website and product. It's not worth it.

**Comment by bballboy2002** [comment] 2018-02-10 15:56
I agree, adfly is the worst. Google should just block that instead.

**Comment by mchorse** [comment] 2018-02-10 19:02
@Puremin0rez I know, but isn't there other services like Adf.ly? All I was stating is that Curse doesn't give as much as those kind of services would.

**Comment by yer-mtd** [comment] 2018-02-11 16:21
I've noticed that many people mention Curse. You shouldn't forget that Optifine not only works in a modpack, but is also a standalone mod that requires no loader, while most Curse mods are purely Forge mods. Optifine.net is also used for handling donations and donor features - not sure if moving to Curse would allow for any of that

**Comment by liach** [comment] 2018-02-12 01:08
Optifine should have its right to host anywhere. It can choose not host on curse, although not all curse mods are forge mods (there are bukkit plugins and litemods, too).

**Comment by spannerman79** [comment] 2018-02-12 06:49
> Optifine should have its right to host anywhere. It can choose not host on curse, although not all curse mods are forge mods (there are bukkit plugins and litemods, too).

True, but these days with Malvertising on the rise the legal ramification involved for willingly participating in infecting third party systems does raise some concerns.  I am no legal expert but I'm sure that there will be some law, be it a law against participating in the willful damage of computer program and/or data. 

Just because you have a choice doesn't mean that there aren't consequences of that choice (example to reflect/reinforce - the postings of hate based messages. Many governments have taken measures against said behavior via laws etc.)

Throwing your hands up into the air and saying "Oh but I didn't place that ad on there, I am only just displaying it" is a very poor excuse and I suspect a poor legal defense.

And because there will be some level of revenue obtained by distributing said malvertising/payload it changes the legal stance on what can and cannot be done against the one that ran the website.

There are plenty of references and links that can be gathered if you spend some time with a search engine on this topic to understand that 9 out of 10 times websites that use advertising aren't immune to possible legal actions in various different countries if said ads contain an unwanted payload.

Laws are complicated to say the least - that is why when I have a legal concern about something on my website I consult a solicitor of my legal stance, only then do I take action.

**Comment by dshadowwolf** [comment] 2018-02-12 09:49
AdFly and AdFocus both require (these days) turning off adblockers and things like NoScript and do not police the ads provided - nor are the ad providers required to meet any form of standards against deceptive practices.

Google's adsense has an issue with some of the ads they carry having a platform-specific malicious payload. I cannot count the number of times an AdSense ad has carried a hidden payload designed to only trigger on Android devices...

Truthfully... no platform is safe from a determined criminal, but AdFly and AdFocus both seem to carry nothing but criminal advertisements.

**Comment by hanakocz** [comment] 2018-02-12 12:59
I think you can look at http://journeymap.info/ , as they have similar structure as this. They also have not only Forge version and so on, also have donation system on the webpage, but they handle download files through Curse (even Bukkit versions for non-forge server!). That way it is Curse's job to show ads, and the revenue from those ads (and numbers of downloads) is also credited by Curse. So ad-problems won't ever land on their webpage, while maintaing to get credited for ALL downloads. The Curse is also good spot for direct linking of modpacks to - so the client is fetching mods for modpack also from the Curse, raising more downloads (but the rightful ones, getting one download for every client that installed it, even though it came via pre-packed modpack).

For example if you use Technic's Solder system, you can include direct address to the mod file on Curse into your pack, thus client downloads not from modpack's server, but from the location chosen by mod authors -> see this page: https://journeymap.info/Modpack_FAQ - most of clients actually do this already. I am not saying to incorporate such a strict terms of use, but hiding your files after adfly links quite blocks this practice and thus eliminates additional download numbers, because everyone sane nowadays will download it ONCE and redistribute it to his players with, or additionally to, his modpack. Not gonna send children on your webpage, and guess why.

**Comment by Makattack1213** [comment] 2018-02-12 21:05
I need to ask, as of now (when comment was posted) Is anyone 'allowed' on optifine.net/donate  optifine.net/home, and optifine.net/login (All marked as secure), but it won't let you on cape. This happened to me, and it's getting on my nerves, because i want to change my cape REALLY bad, and that's the only part of the website blocked... It is the only part of the site with this pop-up, but it says "Cannot access site, connection was interrupted". It's not my wifi because everything else in the moment is working, even on the optifine website, except the cape part... Even when i log in, it won't let me access the cape change part of the site. Please help :(

**Comment by spannerman79** [comment] 2018-02-12 21:09
> I need to ask, as of now (when comment was posted) Is anyone 'allowed' on optifine.net/donate optifine.net/home, and optifine.net/login (All marked as secure), but it won't let you on cape. This happened to me, and it's getting on my nerves, because i want to change my cape REALLY bad, and that's the only part of the website blocked... It is the only part of the site with this pop-up, but it says "Cannot access site, connection was interrupted". It's not my wifi because everything else in the moment is working, even on the optifine website, except the cape part... Even when i log in, it won't let me access the cape change part of the site. Please help :(

What does that have to do with this issue being discussed @Makattack1213 ? Create a new issue when it has **nothing** to do with your actual problem.

**Comment by Makattack1213** [comment] 2018-02-12 22:00
@spannerman79   Uhh, the fact that it is giving me the exact warning photo does not relate to this? You don't need to get butthurt because i asked a question relating to this topic.

**Comment by sp614x** [comment] 2018-02-12 22:32
![image](https://user-images.githubusercontent.com/16635441/36123461-faad8054-104c-11e8-8ea2-d0224c9af0bf.png)

**Comment by sp614x** [comment] 2018-02-12 22:32
Google has removed the warning for optifine.net

**Closed by sp614x** 2018-02-12 22:32 UTC

**Comment by ConnorFranta** [comment] 2018-02-12 22:35
@sp614x Damage control needs to be done on this. A lot of people are questioning the legitimacy of your site and downloads now. The site says nothing about the incident. I think a header should be added to the homepage and downloads section explaining what happened and restore the faith.
Two people from our server community heard from other people about it being 'hacked' and are no longer using OptiFine. It turned into a he said she said from a simple Google warning. We had to personly do research to find out what was going on. Most people won't do that and just say the above.

**Comment by liach** [comment] 2018-02-13 02:44
people misunderstood this issue. sad.

**Comment by Puremin0rez** [comment] 2018-02-13 04:10
@liach what is there to misunderstand?

Optifine.net was blocked due to using a malicious ad provider. It was not a false positive - it was fully legitimate. Optifine.net was a distributor of malware indirectly due to the ad provider used.

Malicious ad provider was removed. Optifine.net is no longer blocked. The product is safe. The distribution is now safe. Going forward, if he chose to use a reputable ad service, it will remain safe. The issue is that how the hell is anyone supposed to know what happened? I see no alert, news article, nothing. So now you have people wondering "Is Optifine a virus?" because unless they happen to follow GitHub (most people don't), they don't know what happened.

This could have been avoided originally. We're all here giving constructive criticism on how to fix this going forward, and to prevent it from happening again.

Nobody misunderstood anything. We love Optifine and want to see the developer and website make the right decisions and prevent its great product from being stifled with a bad reputation and a malware ridden website. I love Optifine. 

I would also love to see @sp614x provide a reasonable (official) statement on what went wrong, what he plans to do going forward, and ensuring the general public that Optifine itself is safe. Those are the kinds of things you do when you have something you distribute to the general public in any greater meaning.

**Comment by liach** [comment] 2018-02-13 04:42
I originally opened this issue stating that google marked optifine.net incorrectly; however, now people incorrectly believe that optifine.net is a malware site.

**Comment by Puremin0rez** [comment] 2018-02-13 04:47
It was not marked incorrectly - Optifine.net was most certainly a malware distributor - but not on purpose.

How are people supposed to believe otherwise when zero communication from the developer is anywhere to be found on the website? No statement, nothing.

**Comment by sp614x** [comment] 2018-02-13 09:22
Only 2 of 67 antivurus/malware detection engines were reporting optifine.net as not safe. One was Google Safebrowsing and the other one was Fortinet: https://www.virustotal.com/en/url/18bf8c18f49875d4a41a5170f7748f9bef6056c2d582a2b282c8b469147cc887/analysis/1518182601/

Fortinet switched back to "safe" after it was reported as false positive. Looks like they have just mirrored the google report without verification.

To me this looks like a glitch with google safebrowsing. Either they have made a wrong decision or they had a problem with a specific ad. 

If adfly was problematic they would have flagged adfly itself as not safe. Currently google marks adf.ly as safe: https://transparencyreport.google.com/safe-browsing/search?url=adf.ly

Another strange thing is that the google report did not include any specific URLs in the URL section. If there was a problem on the download page its URL should have been listed there. Instead the whole domain "optifine.net" was marked as unsafe.

Adf.ly will remain disabled for now, the other ads will be verified and enabled later.

**Comment by sp614x** [comment] 2018-02-13 10:42
Added a note to the website explaining what has happened.

**Comment by dshadowwolf** [comment] 2018-02-13 18:52
The only mistake @sp614x made was trusting an ad-provider. That the mass of internet users will twist facts into strange shapes to fit what they want to believe is part of the truth of all humanity - that it was forgotten about in the immediate is understandable and the best bet is to report the truth of the incident, as has, apparently, been done

**Comment by w-o-a-h** [comment] 2018-02-19 23:11
maybe you should use google adsense.

**Comment by TheRealIceBear1** [comment] 2019-09-14 18:37
Optifine is still using adfly, this is the redirect page from the 1.14.4 download:
![Screen Shot 2019-09-14 at 11 36 16 AM](https://user-images.githubusercontent.com/47952092/64912428-08cc3900-d6e4-11e9-90e0-efbbbac56ea0.png)

**Comment by spannerman79** [comment] 2019-09-14 18:48
@TheRealIceBear1 going off https://github.com/sp614x/optifine/issues/1206#issuecomment-365201560 I'm going to assume that adfly will still be used regardless.

**Comment by TheRealIceBear1** [comment] 2019-09-14 21:04
I'm assuming the website only redirects to safe adfly ads now(?)
