### ISSUE TITLE
[1.16.2] [BSL Shader] Player model disappears when changing perspective 

### ISSUE THREAD

**Issue by elewho** [sp614x/optifine#4614] opened 2020-08-16 08:16 UTC
My friend is using BSL Shaders when this bug occurs. When he  changes perspective, the model flashes white before disappearing completely in all POVs. 

## Steps to Reproduce
https://youtu.be/8sJJDtKzZGA
1. Change perspectives with BSL enabled

## OptiFine Version
OptiFine 1.16.2 HD U G3 pre1

## Installation Method
He used the standalone installer.

## Prior Testing
No

**Comment by NateslPlayzzz** [comment] 2020-08-18 17:20
I am having the same issue

**Comment by sp614x** [comment] 2020-08-20 14:44
Duplicate of #4640.

**Closed by sp614x** 2020-08-20 14:44 UTC
