### ISSUE TITLE
[Texture animation] _n.png, _s.png and diffuse animations sometimes gets temporally misaligned.

### ISSUE THREAD

**Issue by BentoGambin** [sp614x/optifine#4967] opened 2020-10-28 22:33 UTC
## Description of Issue
Please provide as much detail as possible.
![2020-10-28_18 55 09](https://user-images.githubusercontent.com/41645690/97502932-de265980-1952-11eb-80c0-35c9d05e6349.png)
^This is when the bug does not occur, changing camera angle, opening menus, taking screenshots and probably a bunch of other actions trigger the bug, if not triggered it plays all the animations frames just fine over and over.
if triggered the bug looks like this:
![2020-10-28_18 55 11](https://user-images.githubusercontent.com/41645690/97503040-0dd56180-1953-11eb-9107-c5ff4258e84a.png)
Once triggered the frames will play offset from each other for a good while (several loops), then return to what it should look like.
## Steps to Reproduce
Used the following textures and files:
[textures.zip](https://github.com/sp614x/optifine/files/5455115/textures.zip)

## OptiFine Version
preview_OptiFine_1.16.3_HD_U_G4_pre2

## Installation Method
dropped the Jar

## Fabric/Forge Version
i'm using forge-1.16.3-34.1.25

## Other Installed Mods
https://pastebin.com/BV7f5Seq

## F3 Debug Screenshot
![2020-10-28_19 28 35](https://user-images.githubusercontent.com/41645690/97503465-d6b38000-1953-11eb-9a83-584fe7428843.png)

## Prior Testing
Happens with both Chocapic's V9.1, BSL and Complementary (two which are very different shaders)
(Screenshots on complementary) 

I'm not 100% but I'm pretty sure it would happen with standalone Optifine.

**Comment by sp614x** [comment] 2021-02-04 18:33
Duplicate of #5279

**Closed by sp614x** 2021-02-04 18:33 UTC
