### ISSUE TITLE
[1.15.2 Pre17] Chunks not rendering

### ISSUE THREAD

**Issue by AlternateTheory** [sp614x/optifine#3962] opened 2020-05-17 07:34 UTC
## Description of Issue
Only a little way away from the start location chunks do not render. And in fact flicker in and out as shown in the video I link

## Steps to Reproduce
1. Create a brand new creative world
2. travel a shortish distance in any direction
3. look around to see the world stop loading after a point

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre17

## Installation Method
stand alone installer method

## F3 Debug Screenshot
![2020-05-17_19 29 05](https://user-images.githubusercontent.com/64950502/82138475-d5463d80-9874-11ea-9d35-7556e3389aec.png)
![2020-05-17_19 09 29](https://user-images.githubusercontent.com/64950502/82138481-e1ca9600-9874-11ea-8490-47cdc8949d76.png)
![2020-05-17_19 09 35](https://user-images.githubusercontent.com/64950502/82138485-eabb6780-9874-11ea-9729-6a0bbfbfa2ab.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? Vanilla without Optifine does not have this issue

## Additional Information
https://youtu.be/Kt86mmpeQiU

I did a video to show how quick and easy it is to cause the issue by starting a new creative world.
At the end of the vid I flick through the video settings to show what they are.
In case it is important:
2070 RTX
3700x Ryzen

**Comment by DADaddy** [comment] 2020-05-18 14:46
i have the same issue.
i tryed whit the same seed, whitout optifine and there are no probloms

**Comment by Schinchipanda** [comment] 2020-05-19 05:40
I also have this issue, in survival. This issue happened in multiplayer and singleplayer.
Without Optifine, I do not have problems.

**Comment by DADaddy** [comment] 2020-05-19 06:16
> I also have this issue, in survival. This issue happened in multiplayer and singleplayer.
> Without Optifine, I do not have problems.

I had forged installed. Now i removed it and the issued disappeared. So try that if you have forged...

**Comment by dznygal** [comment] 2020-05-19 06:43
Same issue here. Doesn't happen in Vanilla. 

I was running Prev17 with Forge 31.2.0 (recommended ver.) and experienced this. Prev17 says it's compatible with Forge 31.1.63 in the changelog so I made sure I was running that and the issue persists.

**Comment by Schinchipanda** [comment] 2020-05-19 06:44
> 
> 
> > I also have this issue, in survival. This issue happened in multiplayer and singleplayer.
> > Without Optifine, I do not have problems.
> 
> I had forged installed. Now i removed it and the issued disappeared. So try that if you have forged...

And How do I suppose play with mods without Forge ? This issue happened with and without Forge.

**Comment by Schinchipanda** [comment] 2020-05-19 06:52
> 
> 
> > I also have this issue, in survival. This issue happened in multiplayer and singleplayer.
> > Without Optifine, I do not have problems.
> 
> I had forged installed. Now i removed it and the issued disappeared. So try that if you have forged...

This issue happened with and without Forge. And I forgot to notice that I am on a modded Forge server. ^^

**Comment by dznygal** [comment] 2020-05-19 17:41
I'm unable to render additional chunks on some edges because I fly beyond the boundary shown in the video and get stuck, but I can render 1 additional chunk at a time in other directions by updating one of the invisible blocks. It does not seem to continue indefinitely since it failed to work again after loading a few chunks manually this way.

**Comment by AlternateTheory** [comment] 2020-05-19 22:11
I know a lot of people are mentioning Forge:

In my case I am not running Forge - nor has any version of Forge been on this PC.

This is a very pure install of just Minecraft - and just optifine.
The only other minecraft version on the system was Minecraft 1.14.4 with Optifine_HD_U_F4

Also I am only playing solo so it is locally created and played worlds.

**Comment by mturley** [comment] 2020-05-20 16:47
I have had this issue both with and without Forge, on both Vanilla and Paper servers.

**Comment by realjackasterisk** [comment] 2020-05-22 08:18
Duplicate of #3365.

**Closed by realjackasterisk** 2020-05-22 08:18 UTC
Labels: chunks, forge
