### ISSUE TITLE
[Bug] Emissive Textures are not working

### ISSUE THREAD

**Issue by Pumpking0108** [sp614x/optifine#3949] opened 2020-05-15 21:24 UTC
Emissive Textures don't light up

## OptiFine Version
1.15.2 pre-17

## Installation Method
jar file

**Comment by Ratchet97** [comment] 2020-05-15 22:29
This is a duplicate of #3500  . Next time please search for the bug you want to report so you do not make a duplicate like this. Also you can just comment on existing bug reports that a bug is still present in new version.

**Closed** 2020-05-19 15:35 UTC
Labels: 1.15, duplicate, emissive
