### ISSUE TITLE
[Bug] Java crashes every time I try to load into a world on Mac.

### ISSUE THREAD

**Issue by howdee-folks** [sp614x/optifine#5974] opened 2021-07-05 23:49 UTC
## Description of Issue
Whenever I try to load up a world or join a server on my Mac using 

## Steps to Reproduce
This bug occurs whenever I load up Minecraft and try to join a multiplayer or singleplayer world using the 1.17 preview versions of OptiFine. It loads the world normally, and then when it gets to "loading terrain", Java crashes. But Minecraft still thinks that the game is running.

## OptiFine Version
all 1.17 Preview versions

## Installation Method
I used the standalone installer

## Log
[Here's the log](https://pastebin.com/Jdp2qqzy)

## Crash reports
There are no crash reports because Minecraft still thinks that the game is running and I have to force quit the launcher.

## Prior Testing
This only happens with OptiFine

**Comment by Whitelisted1** [comment] 2021-07-05 23:52
Try disabling all shaders, including internal shaders

**Comment by ZenIsBestWolf** [comment] 2021-07-06 02:13
Dupe of #5900. Shaders are not supported on macOS yet.

**Closed by ZenIsBestWolf** 2021-07-06 02:13 UTC
