### ISSUE TITLE
Preview_1.14.4_HD_U_F4_pre4 isnt compatible with Forge 28.1.0

### ISSUE THREAD

**Issue by RyanCR03** [sp614x/optifine#2885] opened 2019-09-15 18:04 UTC
optifine version: **Preview_1.14.4_HD_U_F4_pre4** isnt compatible with **Forge 28.1.0**

**Comment by sylvermist** [comment] 2019-09-17 21:26
i'm using pre4 with forge 28.1.1 and was only seeing a overflow issue that may have been caused by one of the mods that i'm using

**Comment by bscout9956** [comment] 2019-09-27 22:30
I recommend against using versions not recommended by sp614x. I tried 28.1.5 on F4 pre4 and noticed terrible bugs with map loading/saving. Don't do it.

**Comment by sp614x** [comment] 2019-10-08 12:19
Fixed in latest preview.

**Closed by sp614x** 2019-10-08 12:19 UTC
Labels: forge, mods
