### ISSUE TITLE
[Texture] Kelp water block with air block above turns greyish

### ISSUE THREAD

**Issue by Damekennn** [sp614x/optifine#6651] opened 2022-03-05 13:41 UTC
## Description of Issue

![image](https://user-images.githubusercontent.com/69418212/156885680-b10a2c5b-8cc6-4269-8ef6-b70b31d8c468.png)

## Steps to Reproduce
<!- no user input, just texture issue -->

**Comment by fayer3** [comment] 2022-03-05 15:03
Duplicate of #6646

**Closed** 2022-03-05 18:04 UTC
