### ISSUE TITLE
1.17 Wrong block selection position

### ISSUE THREAD

**Issue by KoT3isGood** [sp614x/optifine#5915] opened 2021-06-28 08:40 UTC
wrong block selection position in optifine 1.17 pre 22-24
![2021-06-28_11 33 11](https://user-images.githubusercontent.com/86564118/123606232-5c4e3f00-d805-11eb-9a0e-6e164f8105c5.png)

**Comment by Whitelisted1** [comment] 2021-06-28 14:39
Duplicate of #5892

**Closed** 2021-06-28 14:42 UTC
