### ISSUE TITLE
[Shaders] Shadow Clipping Issues

### ISSUE THREAD

**Issue by RageYT** [sp614x/optifine#3686] opened 2020-04-05 18:42 UTC
## Description of Issue
So there is this very annoying and unusual issue that is causing shadows to clip through to places where it shouldn't be and screws with the lighting. When I teleport to a location, everything is bright but when I look around the shadows fix themselves however they start to clip again. Usually I notice this underground in like a cave or something.

Also this occurs with any Shaderpack installed.

![2020-04-05_14 30 58](https://user-images.githubusercontent.com/17907584/78506991-82dd1180-774b-11ea-8d18-4b1829b3a36b.png)
![2020-04-02_19 45 40](https://user-images.githubusercontent.com/17907584/78506997-8b354c80-774b-11ea-94c0-1cad907a4473.png)

## Steps to Reproduce
1. Install a Shader pack, preferably Sildurs Vibrant Shaders v 1.27,
2. Activate the shader pack in-game
3. Go underground or somewhere where shadows or godrays from the sun should not be visibile
4. Observe that the godrays/shadows appear through the blocks

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre13

## Installation Method
Used the installer and installed it directly into my .minecraft folder

## Log Files/Crash Reports
- https://pastebin.com/yyGWrUCM

## F3 Debug Screenshot
![2020-04-05_14 37 02](https://user-images.githubusercontent.com/17907584/78506905-f5012680-774a-11ea-8587-da9cf595d7db.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
  - No

**Comment by sp614x** [comment] 2020-06-05 20:51
Duplicate of #3634

**Closed by sp614x** 2020-06-05 20:51 UTC
Labels: 1.15, shaders
