### ISSUE TITLE
[Bug] Sky turns black when using shaders

### ISSUE THREAD

**Issue by MRcharisma101** [sp614x/optifine#5950] opened 2021-07-01 13:03 UTC
## Description of Issue

im playing minecraft 1.17 and have optifine version HD U G9 pre24 and sildur's vibrant high shaders. when it gets nighttime and moon starts rising. if i look at a certain vertical line between the sun and the moon the sky goes black, and if i stop looking at that line the sky is back to normal. the line seems to be moving from sun towards the moon. forgot to add im on tlauncher, and i installed "optifine 1.17" which automatically came with optifine installed, i dont have any other mod installed

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## Additional Information

https://user-images.githubusercontent.com/74053823/124128859-3ab3b880-da8e-11eb-89ac-dcf72f8c7a4a.mp4

![2021-07-01_16 32 31](https://user-images.githubusercontent.com/74053823/124128884-41423000-da8e-11eb-95c9-ea458a5abec9.png)

**Comment by fayer3** [comment] 2021-07-01 13:38
Duplicate of #5925

**Comment by Whitelisted1** [comment] 2021-07-01 14:07
Just for future reference, please don't put the "Description of issue" in the title

**Comment by KaiAF** [comment] 2021-07-01 14:13
Already addressed here: #5925

**Closed** 2021-07-01 14:13 UTC
