### ISSUE TITLE
Bug, Optifine 1.16 g2 Minecolonies gui not working with optifine

### ISSUE THREAD

**Issue by drakosoldier298** [sp614x/optifine#4582] opened 2020-08-08 16:36 UTC
Minecolonies, cannot show the gui, i went to them and they said come complain to you guys.

1.use shaders.
2.use minecolonies.
3.try to right click a citizen

**Comment by gunmaker** [comment] 2020-08-09 11:39
agreed

**Comment by pgkrol** [comment] 2020-08-09 16:15
Same problem.
Playing without shaders, and can't see GUI on a citizen by right click.  Other interfaces are working, for example, on town hall or builder's hut and structurize interface is working too.


OptiFine Version: OptiFine 1.16.1 HD U G2
Forge Version: 1.16.1 - 32.0.107
Minecolonies: 
minecolonies-0.13.96-ALPHA-universal
structurize-0.13.37-ALPHA

About other mods: I'm sure that is a problem between minecolonies and Optifine. I was checking 4 times with reinstalling Opti and colonies. But I can try to check it on clear Mine.

F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/61147081/89736786-b5d63f80-da74-11ea-9ec2-a3d3541864f3.png)

**Comment by Raycoms** [comment] 2020-08-10 21:59
I believe there is a problem with the container open handling. I believe optifine suppresses that somewhat.

**Comment by Raycoms** [comment] 2020-08-10 22:02
It used to work fine with early 1.16 optifine versions. It only broke recently.

**Comment by Emilis23** [comment] 2020-08-11 17:05
I can confirm, I'm getting the same thing. Uninstalled every mod besides optifine, minecolonies, and structurize. Got newest versions available of all 3 of those, and have the issue. If I remove just optifine, but put back all 70+ other mods I usually run with, the issue goes away.

**Comment by Aokiral** [comment] 2020-08-13 01:47
I can also say this doesn't work and it is ONLY optifine, tested for hours and was like i doubt its just optifine, nope y'all done broke something and not sure what? not sure if its a setting i can turn off or on didn't wanna fiddle but... not sure why no one has responded. granted i haven't seen a response much so y'all are prob viewing and just working on it.

**Comment by angeerey** [comment] 2020-08-15 18:48
;(

**Comment by nord-kitten** [comment] 2020-08-24 00:17
the same issue, not much to add but I thought I should add my voice to say that this bug is still a thing, and has not gone away, hopefully it can get fixed soon.

**Comment by Lonedrahon25** [comment] 2020-08-24 01:43
plox fix. tks

**Comment by angeerey** [comment] 2020-08-29 14:44
Just test the new optifine 1.16.2 release with only minecolonies and Structurize on forge 1.16.2 33.0.22 and the exact problem is still there...

**Comment by oliandcharis** [comment] 2020-09-03 17:35
please fix this issue, it's rendering the 1.16.1 modpack our friends are playing unplayable,

**Comment by flumignano** [comment] 2020-09-09 08:32
Help us, Obi-sp614x-kenobi! You're our only hope!

**Comment by flumignano** [comment] 2020-09-09 08:46
Still a problem in OptiFine 1.16.2 HD U G3 as well!

**Comment by TrelLyX** [comment] 2020-09-09 22:07
I also hope that this will be fixed as soon as possible, we are playing Valhelsia 3 and optifine now makes it impossible to work with minecolonies.
But we don't want to give up our great shader either.

**Comment by katykat5099** [comment] 2020-09-14 04:41
I also want to add to this. Very annoying bug, hope it gets fixed soon. Otherwise everything else is fantastic!

**Comment by TrelLyX** [comment] 2020-09-15 22:48
:C This ticket is so long open... and now? nobody has new infos of them...

Pls Fix it :(
I want to build with minecolonies on 1.16.1

**Comment by katykat5099** [comment] 2020-09-15 23:39
> :C This ticket is so long open... and now? nobody has new infos of them...
> 
> Pls Fix it :(
> I want to build with minecolonies on 1.16.1

You can still play Minecolonies, you just cant use it with Optifine. If you want to use Minecolonies with the GUI just remove Optifine.

**Comment by angeerey** [comment] 2020-09-20 17:46
This isn't about optifine, but I just wanted to put this out there. If you're playing on 1.16.1, i'd suggest you give this a try:

https://www.curseforge.com/minecraft/mc-mods/sodium-forge-unoffcial

It's a forge port of a fabric optimization mod. I use it and I gained around 125+ fps. Here is the fabric mod if you're interested:

https://www.curseforge.com/minecraft/mc-mods/sodium

also keep in mind you cannot use optifine with this (obviously).

**Comment by sp614x** [comment] 2020-09-23 14:27
The problem is the access transformer for `MobEntity.func_233661_c_`.

MineColonies changes `MobEntity.func_233661_c_` to public with an access transformer and then overrides it in a subclass.
`public net.minecraft.entity.MobEntity func_233661_c_(Lnet/minecraft/entity/player/PlayerEntity;Lnet/minecraft/util/Hand;)Lnet/minecraft/util/ActionResultType; # processInteract`

The OF patcher correctly recognizes that the method is public and fixes the access flags when patching:
`[main/INFO] [op.AccessFixer/]: Fix method access: net/minecraft/entity/MobEntity.func_233661_c_ -> public`
However the overriding method is not called, which means that there is something wrong in ModLauncher when computing the class hierarchy.

When the method is changed to public at compile time then the overriding method is called correctly.

**Comment by ZekerZhayard** [comment] 2020-09-23 14:38
@sp614x 
OptiFine AccessFixer doesn't change the opcode of method insn node from `invokespecial` to `invokevirtual`. However `invokespecial` a public method means invoke the super method in the class.

See https://github.com/MinecraftForge/AccessTransformers/blob/16c1bdbaf5abdde424a9cc31675beed5b9167e36/src/main/java/net/minecraftforge/accesstransformer/AccessTransformerEngine.java#L44-L49

**Comment by sp614x** [comment] 2020-09-23 17:04
Added fix for `invokespecial/virtual` similar to the one Forge AT uses.
The `MobEntity.func_233661_c_` is called correctly now and the MineColonies GUI is working.
Coming in next preview.

**Closed by sp614x** 2020-09-23 17:04 UTC
Labels: 1.16, forge, mods

**Comment by gunmaker** [comment] 2020-12-13 01:10
fixed in latest optifine
