### ISSUE TITLE
[Crash] Minecraft launcher crashes when installed via Forge 

### ISSUE THREAD

**Issue by SBsteveyHops** [sp614x/optifine#6126] opened 2021-08-04 04:33 UTC
## Description of Issue
When using forge (37.0.22 to 37.0.0) to install optifine (OptiFine HD U G9 pre25 to OptiFine HD U G9 pre32) 

## Steps to Reproduce
1. Use forge 37.0.22 to 37.0.0
2. Drag optifine .jar into mods folder (with mods that you have tested already that works or no mods)
3. Click play in the launcher

## OptiFine Version
OptiFine HD U G9 pre25 to OptiFine HD U G9 pre32

## Installation Method
Install though forge (latest version 37.0.22)

## Fabric/Forge Version
37.0.22 to 37.0.0

## Other Installed Mods
With or without other mods this happens  

## Log Files/Crash Reports
[log.txt](https://github.com/sp614x/optifine/files/6928620/log.txt)
![Screenshot 2021-08-03 212840](https://user-images.githubusercontent.com/88417599/128122255-534b6eb9-b9f6-407f-8a71-346c90de76eb.png)

Tried changing java versions still did not work, this person also had this problem https://forums.minecraftforge.net/topic/102616-mc-1171-exit-code-0-crash-when-trying-to-launch-with-optifine-mod/

**Comment by Lentern** [comment] 2021-08-04 19:55
OptiFine for 1.17.1 currently isn't compatible with Forge, it's being worked on.

**Comment by KaiAF** [comment] 2021-08-25 00:26
Closing this as 1.17 isn't compatible with optifine, it's not a bug.

**Closed by KaiAF** 2021-08-25 00:26 UTC
