### ISSUE TITLE
[Crash] Crash when using texturepack with CIT Models

### ISSUE THREAD

**Issue by DarkChromaMC** [sp614x/optifine#7726] opened 2024-09-01 22:25 UTC
## Description of Issue

Using pre5 Optifine 1.21 causes launcher to crash upon loading texturepack using CIT Models.

## Steps to Reproduce

1. Load Optifine launcher on 1.21 using pre5
2. Join a minecraft server
3. Load the texturepack
4. Observe crash report

## OptiFine Version

OptiFine HD U J1 pre5

## Installation Method

Double-clicked the optifine jar on MAC.

## Log Files/Crash Reports

https://pastebin.com/F2DyJFsu

## Prior Testing
- Does this happen in Vanilla without OptiFine? No

## Additional Information
No

[CatCraft_v8.4.1.zip](https://github.com/user-attachments/files/16830688/CatCraft_v8.4.1.zip)

Attached texturepack for reference.

**Comment by SeaOfPixels** [comment] 2024-09-01 22:46
This is specifically caused by https://github.com/sp614x/optifine/issues/7709, not CIT in general.

**Comment by sp614x** [comment] 2024-09-17 18:16
Fixed in some of the previews.

**Closed by sp614x** 2024-09-17 18:16 UTC
Labels: CIT, crash, 1.21
