### ISSUE TITLE
Chest that are being updated flicker with all Optifine 1.14 previews

### ISSUE THREAD

**Issue by christofin** [sp614x/optifine#2467] opened 2019-06-11 22:01 UTC
I have a glitch with my chest room that affects everybody who on my server who is running Optifine. A whole row of my chests are flashing repeatedly. It seems to be the same chests every time I come back. Quitting the game, reloading texture packs, restarting server doesn't help. A friend can verify the same thing. Here's the video: https://youtu.be/RWCFdJ_4WC0

Here's another video that showcases the issue in further detail, as well as the associated item sorter:
https://youtu.be/eFBCZAodbJw

To replicate: Put an item through an item sorter (put a large stack of items that would go through to the end of the item sorter, such as any type of dyed terracotta). After a certain amount of time, all of the chests on the left side will flicker. 

In the second video, updating my gamemode to spectator, then back to survival seems to have made the flickering have gone away. The flickering always comes back. For everyone on the server who uses Optifine, the chests will start flickering at the same time. The issue is somewhat intermittent, as this doesn't happen every time the item sorter is used. 

World download:
https://drive.google.com/drive/folders/1qPIrhm0xi7bqBHwUCMCKrYydO0V9M8W8?usp=sharing
The coordinates of the chest room are: -271, 84, 63 (x, y, z). 

This is still happening as of OptiFine 1.14.2_HD_U_F1_pre10

I will update this ticket with any further information I find. Thank you, sp614x!

**Comment by sp614x** [comment] 2019-06-12 11:54
The world download doesn't work. It hangs forever on "Zipping 1 file".

**Comment by christofin** [comment] 2019-06-12 13:15
Try this: 

https://drive.google.com/drive/folders/1Ir4NgxNW9eRUk938RaX9uSr_cxkJ_ARQ?usp=sharing 

I cropped out all of the non-relevant chunks so this download is only 44 megabytes. I just tested that link in an incognito window and was able to download and open the world in an single player world. It took forever to unzip but didn't fail this time.

**Comment by sp614x** [comment] 2019-06-12 20:53
I click on "Download all" and it gets stuck forever at "Zipping 1 file".

**Comment by christofin** [comment] 2019-06-12 21:11
That's strange, try downloading the ZIP from this comment. 


[chest-glitch-optifine.zip](https://github.com/sp614x/optifine/files/3283159/chest-glitch-optifine.zip)

**Comment by sp614x** [comment] 2019-06-13 21:23
The download is OK, cool world.
I put a lot of items in the chest, they get moved by the item sorter, but nothing is flickering.

![image](https://user-images.githubusercontent.com/16635441/59468399-37f7b380-8e32-11e9-8daf-a47e59979cf8.png)

**Comment by christofin** [comment] 2019-06-13 21:31
Thanks! There would be a lot more to see if I didn't have to drastically crop the areas. 

I'm not sure how to reproduce it yet -- did you see the flickering in the videos I linked in the description? From what I have tested, sometimes it starts flickering when I'm using the item sorter. But it doesn't flicker **every** time. When the chests flicker, it's all on the left side, and everyone on the server using Optifine sees the same flickering. So far, two other people have confirmed this with me. 

I'm not sure if you have to start the item sorter, leave the chunks, then come back? It's really hard to pinpoint when the flickering starts, exactly. I've noticed the flickering throughout all 10 (now 12, I see) 1.14.x Optifine previews. 

If you have any ideas of how I could help troubleshoot exactly when it starts, I'll see what I can find. I know it's an intermittent issue and that makes it really hard to troubleshoot. 

I also don't think it's an issue with my 3440x1440 resolution (I know ultrawide can have strange effects on culling and the sort). My friend runs 2560x1440 and sees the same flickering. 

Sorry I can't be of more help -- I'll let you know what I find. I can say that this happens every single play session if I'm online long enough. I am the server admin so that helps. If you're on Discord, I can show you when it's happening when it starts -- it flickers the same time for everyone, so if you want to hop on my server when I notice it, I can whitelist you  ¯\_(ツ)_/¯

**Comment by christofin** [comment] 2019-06-13 21:32
Also I should mention -- happens with or without shaders. Appears to just be an issue with Optifine in general. Unfortunately, I don't have a world backup of this prior to 1.14, as this is a new 1.14 world. I did have the exact same item sorter on our 1.13 server (it's the TangoTek item sorter) and never noticed flickering.

**Comment by sp614x** [comment] 2019-06-13 22:08
I can see the flickering in the videos, but I can't reproduce it in the game.
Does it also happen in single-player with the downloaded world?

**Comment by christofin** [comment] 2019-06-13 22:10
I haven't tested for that, I will test for that tonight. What else should I be looking for (such as settings to toggle, etc) when I'm testing or if I notice the flickering?

**Comment by christofin** [comment] 2019-06-14 01:46
Update: I was able to replicate this in my world in single player, from the exact ZIP file I attached here. Here is exactly what I did:

- Logged in
- Dumped my inventory into the chest on the left which starts the sorting system. The chests do not flicker here. 
- Attached an elytra and held rockets so I could easily fly away. I flew about 600 blocks away to unload the chunks, then came back. The item sorter is going off the entire time. 
- When I get back to the chest room, the chests are flickering. 

For good measure, I quit out of the world, then loaded back in and the chests are still flickering. I updated my gamemode to creative, and the chests still flicker. So for you to replicate, I would do exactly as I did. Go into creative, give yourself an elytra and firework rockets, go into survival, load the entire chest up with random unstackable items (pickaxes, shields, boats, minecarts (there's a ton in the barrels right next to the chest), fly away, come back, chests flicker.

**Comment by sp614x** [comment] 2019-06-14 11:16
Managed to reproduce the flickering by dumping a large number of items in the chest, flying away and then returning back.

The flickering is a side effect of optimizing excessive local updates. 
With the optimization OFF the chests don't flicker and the FPS drops to 2.

![image](https://user-images.githubusercontent.com/16635441/59505471-cd805b00-8ea5-11e9-8228-aba1d09a2df8.png)

With the optimization ON the chests flicker, but the FPS is 23.

![image](https://user-images.githubusercontent.com/16635441/59505564-0c161580-8ea6-11e9-8502-5a489b833ee8.png)

The rest of the entities don't flicker, so this should be something specific to chests.

**Comment by sp614x** [comment] 2019-06-14 11:49
The real cause is a bugfix copeid from Forge for this vanilla bug:
https://github.com/MinecraftForge/MinecraftForge/pull/5512

The bug is marked as fixed in 1.13, but some users in the comments suggest that the fix is not complete.
In 1.14 the fix seems to be complete with proper checking for the tile entity block state.

It looks like the Forge bugfix is not needed in 1.14 and it can be removed.

**Comment by sp614x** [comment] 2019-06-14 12:11
Fixed, coming in next preview.

**Closed by sp614x** 2019-06-14 12:11 UTC
