### ISSUE TITLE
doesn't work with buildcraft

### ISSUE THREAD

**Issue by pertoodle** [sp614x/optifine#1317] opened 2018-03-25 05:57 UTC
was causing the engines in buildcraft not to pump items properly

**Comment by sp614x** [comment] 2018-03-25 10:26
More details needed:
- forge version
- buildcraft version
- how to reproduce
- other mods installed
- F3 screenshot

**Comment by pertoodle** [comment] 2018-03-25 23:20
-Forge version: 1.12.2-14.23.2.2611
-buildcraft version: 7.99.15
-how to reproduce: place down an engine and try to power it (any engine) idk what how to reproduce means this is the first time i reported a glitch.
-mods: buildcraft, optifine and others but they don't affect it, i tried it without them
-screenshots: first what happens hand dissapears when close to a wall (only when engine is placed),
engine doesnt work (doesnt pump items) tool bar is not completely darkened when in inventory.
![base profile screenshot 2018 03 25 - 16 13 46 22](https://user-images.githubusercontent.com/37764937/37881136-306eacd4-3048-11e8-8cf0-854bb3bdf6a0.png)
![base profile screenshot 2018 03 25 - 16 14 07 44](https://user-images.githubusercontent.com/37764937/37881143-40e93bd8-3048-11e8-94af-d031ca0c2d9c.png)
![base profile screenshot 2018 03 25 - 16 14 38 40](https://user-images.githubusercontent.com/37764937/37881146-475fc11c-3048-11e8-8c9c-49dadfd43e74.png)
![base profile screenshot 2018 03 25 - 16 15 06 71](https://user-images.githubusercontent.com/37764937/37881147-50d01742-3048-11e8-82e0-2b3c405dc221.png)
thank you for being understanding i know you probably get many glitches and you could be working your butt off.

**Comment by KaiAF** [comment] 2021-05-31 01:42
I know this has been a couple years, but is this still an issue?

**Comment by pertoodle** [comment] 2021-05-31 01:46
Damn I would have never thought you would respond still. That’s very suprising. I stopped playing Minecraft so I don’t know. Sorry bout dat. I do know that I fiddled around too much with mods to know whether it was your mod or not. So you should just call it settled.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by KaiAF** [comment] 2021-05-31 01:55
I am sure the reason why sp614x never responded was because he was *and still is* working through all the bug reports. I am going to close this now

**Comment by pertoodle** [comment] 2021-05-31 01:55
Alright thanks for the response though.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Closed by KaiAF** 2021-05-31 01:55 UTC
Labels: details needed, forge, mods
