### ISSUE TITLE
[1.15.2] Visual glitch with CTM around the chunk borders

### ISSUE THREAD

**Issue by JelCraft** [sp614x/optifine#3285] opened 2020-02-13 18:43 UTC
![2020-02-13_19 36 06](https://user-images.githubusercontent.com/61025393/74467125-c9736580-4e98-11ea-95b9-1b6fe97ccaa2.png)

I placed an empty shulkerbox, this visual glitch appeared (no Z-fighting or other rapid movements it was frozen but I could just walk around) and a few seconds later (without breaking the box) it disappeared.

**Comment by cryoten** [comment] 2020-02-13 18:54
I didn't even place a shulker box, I was just mining sandstone and this entire chunk is messed up.

![image](https://user-images.githubusercontent.com/41876297/74468165-464f1100-4e92-11ea-9a5c-17983856441d.png)

**Comment by JelCraft** [comment] 2020-02-13 19:11
![2020-02-13_20 09 27](https://user-images.githubusercontent.com/61025393/74469403-e1e57f00-4e9c-11ea-9392-5ea069e3a207.png)

K
![2020-02-13_20 09 34](https://user-images.githubusercontent.com/61025393/74469407-e447d900-4e9c-11ea-94f4-b7f8b9e61797.png)
![2020-02-13_20 09 49](https://user-images.githubusercontent.com/61025393/74469410-e5790600-4e9c-11ea-8748-af8761c69560.png)

It seems to be based on the location of the block, here are some more screenshots

**Comment by PSILONCRAFT** [comment] 2020-02-13 19:18
looks like a ctm error tied up to chunk borders. only trigger when a texture goes from 1 chunk to the next one


![2020-02-13_20 11 18](https://user-images.githubusercontent.com/26674039/74469974-ee1e0c00-4e9d-11ea-90ca-f3b803aa9a43.png)
![2020-02-13_20 15 47](https://user-images.githubusercontent.com/26674039/74469989-f24a2980-4e9d-11ea-8337-11954aea9b1a.png)
![2020-02-13_20 15 53](https://user-images.githubusercontent.com/26674039/74469992-f37b5680-4e9d-11ea-81fa-53a0bdf7024d.png)
![2020-02-13_20 16 05](https://user-images.githubusercontent.com/26674039/74469995-f413ed00-4e9d-11ea-9940-27d628da4a76.png)
![2020-02-13_20 16 15](https://user-images.githubusercontent.com/26674039/74469996-f413ed00-4e9d-11ea-8e56-eb0b4c748df9.png)

**Comment by sp614x** [comment] 2020-02-14 14:46
Really seems to be linked to CTM textures around the chunk borders.

**Comment by AJMFactsheets** [comment] 2020-02-15 20:05
Here is a reproducible method:

(Door from a village naturally causes bug)
Seed: -7365127999688755791
X: 159
Y: 74
Z: -143

1. Have a shield in the offhand
2. Click on the door
3. Taste the rainbow? (If you walk inside the house that is)

Here is a striped down version:
![Placement](https://user-images.githubusercontent.com/34605013/74594429-0310b180-4ffc-11ea-864b-742696ecc129.png)
![Rainbow](https://user-images.githubusercontent.com/34605013/74594447-1b80cc00-4ffc-11ea-871d-1b16cb41d713.png)

**Comment by LectroImpuls** [comment] 2020-02-17 07:14
For me, this happens when you open a door with a sign on it. Fixes itself if you open a door without a sign on it or relog. but opening a normal door in-game removes x-ray bug but you can still rainbow artifacts. if you break the sign the bug gets worse. if you break the door and the sign then open a different door the bug is invisible. if you place anything near the spot where the door and sign were the bug reappears. if you relog and place something where the bug occurred after breaking the door and sign the bug reappears.
![2020-02-15_23 25 56](https://user-images.githubusercontent.com/61136579/74631561-79a3d100-511a-11ea-95a8-a6348c3ab604.png)
![2020-02-15_23 26 01](https://user-images.githubusercontent.com/61136579/74631564-7a3c6780-511a-11ea-9225-7316e3645d0e.png)
![2020-02-15_23 26 07](https://user-images.githubusercontent.com/61136579/74631565-7ad4fe00-511a-11ea-9526-09b92a9ea3b0.png)
![2020-02-15_23 26 14](https://user-images.githubusercontent.com/61136579/74631567-7ad4fe00-511a-11ea-99cd-31d74965b44e.png)
![2020-02-15_23 27 12](https://user-images.githubusercontent.com/61136579/74631568-7b6d9480-511a-11ea-85e8-6061db2dbb7a.png)

**Comment by AJMFactsheets** [comment] 2020-02-19 03:46
My issue with the door has been completely resolved as of OptiFine 1.15.2 HD U G1 pre4

**Comment by sp614x** [comment] 2020-02-19 11:47
Should be fixed in pre4.

**Closed by sp614x** 2020-02-19 11:47 UTC
Labels: 1.15, CTM, bug
