### ISSUE TITLE
[Category] Anim Shows up when Reloading Packs

### ISSUE THREAD

**Issue by RavenVLemonRaven** [sp614x/optifine#5619] opened 2021-05-05 02:53 UTC
## Steps to Reproduce
1. Make entity anim file
2. Reload Pack Ingame

## OptiFine Version
OptiFine HD U G8 pre12

## Installation Method
Self Installer

## Prior Testing
- Does this happen in Vanilla without OptiFine?
no

## Additional Information
Only shows up when reloading resource packs. It wont show up on the opening title because the game doesn't need to load in entity/block textures

![hrelp](https://user-images.githubusercontent.com/72989698/117092163-53178900-ad12-11eb-9962-85573d92eb57.png)

**Comment by Cart3r1234** [comment] 2021-05-05 03:02
Duplicate of #4883

**Comment by KaiAF** [comment] 2021-05-05 13:41
closing as this is a duplicate

**Closed by KaiAF** 2021-05-05 13:41 UTC
