### ISSUE TITLE
[Launcher] Crash when starting Optifine 1.13 alpha 8

### ISSUE THREAD

**Issue by DancheZi** [sp614x/optifine#1687] opened 2018-08-19 18:57 UTC
So i  am cracked user , and i have premium account from my friend. When i try to launch 1.13 optifine alpha 8 on official Mojang Minecraft launcher everything works just fine , but when i use cracked launchers like tlauncher , skaialauncher etc. MY GAME JUST CRASHES. and than this window and dev console shows up:

![shit](https://user-images.githubusercontent.com/42520964/44312021-17b5be80-a3f2-11e8-8eae-f93dcd1b3e5d.PNG)
 
I have installed java ver 45 but it still doesnt work. My graphic card is intergrated and it does not have any update !

and this is pastebin of dev console:

https://pastebin.com/RuM1hqEv

PLZ HELP

**Comment by DancheZi** [comment] 2018-08-19 19:00
and yeah , when i add json files from #1645 it doesnt work even libraries in fix 2 so pls dont spam duplicate or something like that

**Comment by skmedix** [comment] 2018-08-19 20:36
Duplicate of #1635

**Comment by SetantaLP** [comment] 2018-08-19 20:38
Does that issue happens when you try to launch the vanilla version (or maybe some older vanilla-version that requires the launchwrapper, since this error seems to be connected to the launchwrapper)? If yes, it's definitely a problem with your launcher, and even if not, it's most likely also a problem with your launcher since it works fine with the official one.
Besides that as far as I know Optifine only supports the official launcher so any data optifine generates during the installation is formatted to comply the data-formatting of the official launcher. So if you have problems on third party launchers, it's most likely because their parser doesn't match the one in the official launcher.

**Comment by DancheZi** [comment] 2018-08-20 18:04
SKMEDIX IT IS NOT DUPLICATE OF #1635 BECAUSE IT DOESNT FIX PROBLEM !

And yeah its possible that its is problem with third party launcher but other optifine fully released version Work Just Fine !

**Comment by DancheZi** [comment] 2018-08-20 18:07
Same windows after crash pop ups even with both of fixed json files are replaced with old ones !

**Comment by Syncter** [comment] 2018-08-24 13:05
i have issue, when i run optifine on world, my screen minecraft is reversed. 
screenshout: ![image](https://user-images.githubusercontent.com/42674453/44586204-1103be80-a7d9-11e8-8aa9-96583d5c2de0.png)

**Comment by Regnander** [comment] 2018-08-24 17:29
@Syncter [Look here.](1654#issuecomment-412890748)

**Comment by Syncter** [comment] 2018-08-25 23:58
@Regnander Where the place of disable anti aliasing

**Comment by sp614x** [comment] 2018-08-27 10:15
The inverted FXAA view is fixed in latest preview.

**Comment by sp614x** [comment] 2018-08-29 20:53
Fixed in beta4.

**Closed by sp614x** 2018-08-29 20:53 UTC
Labels: 1.13

**Comment by damnblah** [comment] 2018-09-15 06:15
@DancheZi same problem with me u got the fix or something because I can't fix this problem. I use Tlanucher too
