### ISSUE TITLE
Entity Status Color bug with shaders

### ISSUE THREAD

**Issue by Scorpion34** [sp614x/optifine#3729] opened 2020-04-10 19:59 UTC
## Description of Issue
The indicator of you damaging an entity normally shows a red texture to indicate damage but this does not occur with internal or external shaders I dove into the code of optifine to possibly figure out a solution but to no avail the entity status color just does not work with shaders.

## Steps to Reproduce
1. Use OptiFine G1 pre-13 and turn on shaders using internal or external shaders
2. Punch or damage an entity 

## OptiFine Version
Optifine G1 pre-13

## Installation Method
I used both methods with fabric and installed the actual client both have the same issues 

## Fabric/Forge Version
Fabric - 1.15.2 - latest version

## OptiFabric Version
OptiFabric - 1.15.2 - latest version

## Other Installed Mods
No mods

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
Yes

- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
Yes
- Does this happen in OptiFine standalone?
Yes
- Does this happen in Vanilla without OptiFine?
No
- Have you tried using a binary search to find which mods cause this issue?
No
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
Yes
      - Forge/Fabric and remaining mods, without OptiFine
Works just fine 
## Additional Information
My guess is its probably just a tiny bug easy to fix maybe just an error in the launcher is my guess

**Comment by SypherRS** [comment] 2020-04-11 14:30
This and also block breaking animation isn't showing up for me.
Using Sildurs Vibrant Shaders. 
Must be some small conflict that isn't loading these textures or something.

**Comment by NiemandTV** [comment] 2020-04-11 14:57
Duplicate of https://github.com/sp614x/optifine/issues/3598.
The uniform called "entityColor" is currently not working, that's why mobs don't turn red when you hit them creepers don't flash white when they're about to explode.
@SypherRS all of that is known.
PLEASE use the search function.

**Comment by Scorpion34** [comment] 2020-04-13 14:22
> Duplicate of #3598.
> The uniform called `entityColor` is currently not working, that's why mobs don't turn red when you hit them and creepers don't flash white when they're about to explode.
> @SypherRS all of that is known.
> PLEASE use the search function.

Is there any possible way to fix it?

**Comment by NiemandTV** [comment] 2020-04-13 14:58
> Is there any possible way to fix it?
No, it's an OptiFine bug. All we can do is wait until Optilad fixes it. Creating thousands of duplicate issues won't help.

**Comment by Scorpion34** [comment] 2020-04-13 17:15
> > Is there any possible way to fix it?
> 
> No, it's an OptiFine bug. All we can do is wait until Optilad fixes it. Creating thousands of duplicate issues won't help.

Well that sucks hopefully gets patched soon and I only made the issue because I didn't see any other reports of it the name of it differs a lot "Mob Flash Bug, Entity Status Color, Damage Indicator" it's all very jumbled together only posted something because I couldn't figure out a solution because I like to play on internal shaders and couldn't figure out this bug again hopefully it gets fixed soon

**Closed** 2020-04-13 17:15 UTC
