### ISSUE TITLE
Optifine black entity textures

### ISSUE THREAD

**Issue by sxl4r** [sp614x/optifine#6066] opened 2021-07-22 06:40 UTC
## Description of Issue
When i use the "Internal" shaders, all the mobs, chest and more have no texture and its black, i check if it was my resource pack but it still happen with the default textures

## Steps to Reproduce
I only use the Internal shaders

## OptiFine Version
1.17.1 G9 pre30 it happens too on pre29

## Installation Method
I install it with the .jar version as normal mode

## Other Installed Mods
No other mods installed

## Log Files/Crash Reports
No crash just black textures

## Additional Information
![2021-07-22_01 29 47](https://user-images.githubusercontent.com/87799377/126598924-6231b88e-afdf-4835-a286-61e4054e17dc.png)
![2021-07-22_01 30 06](https://user-images.githubusercontent.com/87799377/126598927-c1089b0f-ac54-474d-a276-460800e668b9.png)

**Comment by ZenIsBestWolf** [comment] 2021-07-23 17:46
Dupe of #5891

**Closed by ZenIsBestWolf** 2021-07-23 17:46 UTC
Labels: 1.17, bug, duplicate, shaders
