### ISSUE TITLE
Outer part of Slime CEM is not replaced with custom one.

### ISSUE THREAD

**Issue by Stardust178** [sp614x/optifine#5490] opened 2021-03-25 23:08 UTC
## Description of Issue
I created CEM to replace the model of Slime and noticed there's no way to change the outer layer.

![image](https://i.imgur.com/saFRGyE.png)

## Minecraft Version
1.16.5

## OptiFine Version
HD U G7

**Comment by Regnander** [comment] 2021-03-26 12:49
> HD U G7

This is 1.16.5, right?

**Comment by Stardust178** [comment] 2021-03-26 13:23
> > HD U G7
> 
> This is 1.16.5, right?

Yes

**Comment by sp614x** [comment] 2021-03-26 23:16
Duplicate of #5481

**Closed by sp614x** 2021-03-26 23:16 UTC
