### ISSUE TITLE
[1.15.2] Mouseover highlight not showing or being weird with shaders

### ISSUE THREAD

**Issue by LukasAppleFan** [sp614x/optifine#3676] opened 2020-04-04 08:57 UTC
## Description of Issue
In survival : when moving my cursor blocks won't highlight like they usually do, it's a bit like in adventure mode.
In creative, it sometimes shows after breaking a block, and sometimes it just will not show up.
When using Shaders

## Steps to Reproduce
1. Enabling shaders
2. Just moving around with the cursor
3. Not seeing any blocks highlighting 

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre13

## Installation Method
I've tried standalone and with Forge (using OptiForge).

## Fabric/Forge Version
Forge 31.1.35

## ~~OptiFabric Version~~ OptiForge Version
OptiForge-MC1.15.2-0.1.7

## Other Installed Mods
damage_indicator-0.1.0.jar
jei-1.15.2-6.0.0.2.jar
KleeSlabs_1.15.2-8.0.0.jar
MineMenu-1.15.2-1.8.4.jar
MixinLoader-1.1-SNAPSHOT.jar
music_player-1.15.2-2.0.13.64.jar
OptiForge-MC1.15.2-0.1.7.jar
Placebo-1.15.2-3.0.2.jar
preview_OptiFine_1.15.2_HD_U_G1_pre13.jar
shuffle-1.14.4-1.15.2-20w07a-1.1.1.jar
ToastControl-1.15.2-3.0.1.jar
u_team_core-1.15.2-2.11.0.156.jar
worldedit-forge-mc1.15.2-7.1.0.jar

**Obviously those are only using Forge**

## Log Files/Crash Reports
[2020-04-04-1.log](https://pastebin.com/V4b3G5Xf)
[2020-04-04-2.log](https://pastebin.com/mf6E7v6m)

## F3 Debug Screenshot
![2020-04-04_10 27 03](https://user-images.githubusercontent.com/41242166/78422697-7aa8a780-7661-11ea-9a43-f447ed2dbd45.png)
![2020-04-04_10 27 57](https://user-images.githubusercontent.com/41242166/78422704-8300e280-7661-11ea-8ccc-4fd55aa0a848.png)

Both are creative actually, and in survival, it's like in the first one.

## Prior Testing
- It does not happen in Vanilla.

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
Yes, even without mods (just with OptiForge for 1.15 + OptiFine + Forge).
   - Only OptiFine, OptiFabric, and Fabric
Did not tried with Fabric.
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
I just had to have OptiForge.
- Does this happen in OptiFine standalone?
Yes (only with shaders).
- Does this happen in Vanilla without OptiFine?
No

## Additional Information
Here are the shaders I used : 
- Sildurs Vibrant Shaders (even on older versions and with different quality, like low and high)
- BSL (same as before)
- Chocapic13
- And so on...

**Comment by clintmay** [comment] 2020-05-06 05:16
Would love this as well

**Comment by soloHolo** [comment] 2020-05-18 12:45
Same problem here. Gotta wait until this is fixed

**Comment by Gamax42** [comment] 2020-05-20 11:04
Same issue for me

**Comment by takerukoushirou** [comment] 2020-05-20 11:58
I have the same issue on 1.15.2 survival with OptiFine standalone (no Forge) and shaders enabled (Sildurs Vibrant Shaders). At first I thought the block highlight won't show up at all, but it seems that it's at least reproducible visible under a certain small angle from a certain direction.

**Comment by sp614x** [comment] 2020-05-29 10:47
Duplicate of #3708.

**Closed by sp614x** 2020-05-29 10:47 UTC
Labels: 1.15, shaders
