### ISSUE TITLE
[1.8] Christmas hats reveals invis players

### ISSUE THREAD

**Issue by KonstantinTolstoy** [sp614x/optifine#5154] opened 2020-12-28 11:58 UTC
## Description of Issue
Optifine christmas hats are visible on invisible players

## Steps to Reproduce
1. Look at invisible players

## OptiFine Version
1.8.9 L6 pre 1

## Installation Method
Forge

## Fabric/Forge Version
11.15.1.2318

## Log Files/Crash Reports
-

## F3 Debug Screenshot
-

## Prior Testing
-

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? - Yes
- Does this happen without any mods at all? - No
- Does this happen in OptiFine standalone? - I think, yes
- Does this happen in Vanilla without OptiFine? - No, it is an optifine feature...
- Have you tried using a binary search to find which mods cause this issue? - No

## Additional Information
-

**Comment by sp614x** [comment] 2020-12-28 13:06
Duplicate of #5150

**Closed by sp614x** 2020-12-28 13:06 UTC
