### ISSUE TITLE
Black screen with last update

### ISSUE THREAD

**Issue by HireSLH** [sp614x/optifine#4150] opened 2020-06-22 06:31 UTC
## Description of Issue
This morning i update Optifine for 1.15.2 from pre29 to pre 30 and also Forge from 31.2 to 31.2.21 with SEUS PTGI E12 shaders. I only see something in spectador mode. Survival and creative only displays 4 black and purple squares screen. I test it on 31.2 and its the same.

## OptiFine Version
Pre30 with hotfix
## Installation Method
drop the JAR file into your "mods" folder

## Fabric/Forge Version
forge 31.2.21 and 31.2

**Comment by sp614x** [comment] 2020-06-22 06:42
Duplicate of #4144

**Closed by sp614x** 2020-06-22 06:42 UTC
