### ISSUE TITLE
[OptiFine 1.13.1 HD U E3 pre5] Mobs with "Glowing" status effect (from Spectral Arrows) appear solid white while using internal shaders

### ISSUE THREAD

**Issue by Wonkatoad** [sp614x/optifine#1900] opened 2018-10-14 00:02 UTC
With internal shaders turned on, mobs with the "Glowing" status effect from Spectral Arrows incorrectly appear solid white. Here are some screenshots showing this effect with shaders turned on and off:

Internal shaders turned ON:
https://i.imgur.com/cKWQH1g.png

Internal Shaders turned OFF:
https://i.imgur.com/jOrFzL4.png

I'm took these screenshots in OptiFine 1.13.1 HD U E3 pre5, but this is an older issue dating back to at least 1.12

Thank you for reading!

**Comment by sp614x** [comment] 2018-10-14 12:33
Duplicate of #189, #1174, #1377, #1427, #1432 and #1464.

The spectral effect is not compatible with Fast Render, Antialiasing and Shaders. OptiFine uses a simplified version when the full spectral effect is not possible.

**Closed by sp614x** 2018-10-14 12:33 UTC

**Comment by MrTheFunColas974** [comment] 2021-10-10 07:40
i have same probleme with secon image but i don't can remove or disable it ! Help me plz this glowing effect make me crazy

**Comment by MrTheFunColas974** [comment] 2021-10-10 07:47
i have same probleme with secon image but i don't can remove or disable it ! Help me plz this glowing effect make me crazy on optifine 1.17.1 HD_U_G9
