### ISSUE TITLE
Minecraft optifine 1.15.2 loading issue

### ISSUE THREAD

**Issue by mclarke1750** [sp614x/optifine#3572] opened 2020-03-25 14:32 UTC
I have found with optifine 1.15.2 that the entire world does not load, only a small area loads. If I go to far into "the void", my caracter gets stuck. (Note: this only happens with optifine).

**Comment by realjackasterisk** [comment] 2020-05-22 08:12
Duplicate of #3365.

**Closed by realjackasterisk** 2020-05-22 08:12 UTC
Labels: 1.15, bug, chunks
