### ISSUE TITLE
[1.15.2 G1 preview3] Graphics settings dimensions bugs

### ISSUE THREAD

**Issue by 6ix7even** [sp614x/optifine#3362] opened 2020-02-17 20:38 UTC
I noticed a rather strange bug with the settings Graphics 

when going from one dimension to another dimension, the Graphics options automatically go to Fast while it is still in Fancy

![optifine bug](https://user-images.githubusercontent.com/44172841/74685075-c694af80-51cd-11ea-83a0-efcb35b9d729.jpg)

**Comment by sp614x** [comment] 2020-02-17 20:51
Can't reproduce it.

**Comment by sp614x** [comment] 2020-02-17 21:11
Duplicate of #3333.
Fixed, coming in next preview.

**Closed by sp614x** 2020-02-17 21:11 UTC
Labels: 1.15
