### ISSUE TITLE
[Bug Report] Absent block breaking animation with shaders on 1.15.2

### ISSUE THREAD

**Issue by reC0D3D** [sp614x/optifine#3884] opened 2020-05-06 20:45 UTC
## Description of Issue
I've seen a few posts similar to this one, but not in the way that I've experienced it. When breaking a block using shaders, it doesn't display the breaking animation at all nor the selection box. I've experienced this on _Sildurs Vibrant Medium, Chocopic13 V7-8, BSL, SEUS Renewed, and Vanilla Plus._ A friend of mine tested _Sildurs Vibrant Extreme_ with the same result. This doesn't happen using the internal shaders option.

## Specifications
I have an _AMD RX 580_ in my build. My friend was able to confirm this bug with a _GTX 1660 TI_.

## Steps to Reproduce
1. Apply any shader that's not the internal option.
2. Break a block in survival mode.

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre16

## Installation Method
I used the jar installation method. I launched the file from my downloads folder and followed the steps on-screen.

## Screenshots
This screenshot was taken with _OptiFine 1.14.4 HD U F5_

![2020-05-06_13 24 17](https://user-images.githubusercontent.com/29968331/81226076-1f8b0d00-8f9f-11ea-85f7-4aadb145ea19.png)

This screenshot was taken with _OptiFine 1.15.2 HD U G1 pre16_

![2020-05-06_13 25 20](https://user-images.githubusercontent.com/29968331/81226153-3cbfdb80-8f9f-11ea-8863-9e9708687a21.png)

These screenshots are from the same world, using the same resource pack, and the same shader. The only difference is the Optifine and Minecraft version. I was well into breaking the block in 1.15. Notice the absence of the block border and breaking animation.

**Comment by CallumlousTV** [comment] 2020-05-07 15:40
This also happened to xQc on-stream: [https://youtu.be/8u3hhZtVdg4?t=1349](url)

**Comment by seeruk** [comment] 2020-05-19 15:56
Dupe of #3600 - it is exactly the same behaviour you've described here (no outline, no break animation, with Sildur's).

**Closed** 2020-06-05 20:48 UTC
Labels: 1.15, shaders
