### ISSUE TITLE
Minecraft 1.13.2 error optifine

### ISSUE THREAD

**Issue by DragonFlame3201** [sp614x/optifine#2139] opened 2018-12-29 22:14 UTC
I downloaded OptiFine on Minecraft 1.13.2 and I messed around with the settings a bit, closed the game and then reopened and played a bit more. Then I closed it again and 2 hours later I rejoined and this error message came up:

[21:45:24] [main/INFO]: Loading tweak class name net.minecraft.launchwrapper.VanillaTweaker[21:45:24] [main/INFO]: Loading tweak class name net.minecraft.launchwrapper.VanillaTweaker[21:45:24] [main/INFO]: Using primary tweak class name net.minecraft.launchwrapper.VanillaTweaker[21:45:24] [main/INFO]: Calling tweak class net.minecraft.launchwrapper.VanillaTweakerException in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor at java.lang.Class.getDeclaredConstructors0(Native Method) at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) at java.lang.Class.getConstructor0(Unknown Source) at java.lang.Class.newInstance(Unknown Source) at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) at net.minecraft.launchwrapper.VanillaTweaker.injectIntoClassLoader(VanillaTweaker.java:16) at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) at net.minecraft.launchwrapper.Launch.main(Launch.java:28)Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor at java.net.URLClassLoader.findClass(Unknown Source) at java.lang.ClassLoader.loadClass(Unknown Source) at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) at java.lang.ClassLoader.loadClass(Unknown Source) ... 8 moreJava HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release.

Whenever I try to click play the same message reappears. I tried redownloading it (I use shiginima launcher V4.100) but the same thing happened.My computer is a  64 bit Windows 7. Thanks.

**Comment by sp614x** [comment] 2019-01-10 22:47
This is typically caused by custom launchers and can't be fixed by OptiFine: #1956, #1951, #1825, #1804, ...

**Closed by sp614x** 2019-01-10 22:47 UTC
