### ISSUE TITLE
[OF 1.15.2pre10 Glitch] Rendering problems using shaders.

### ISSUE THREAD

**Issue by C0RONAVIRU5** [sp614x/optifine#3614] opened 2020-03-29 04:37 UTC
## Description of Issue
When using any shaderpack, I am having certain rendering problems. While loading the chunks (which is very slow for some reason), I am experiencing certain distortions on the screen, which may be, depending on the distance at which the chunks are loaded, larger or smaller. These distortions only happen in one part of the world, it is like a circle that appears more or less at the bottom of the middle of the screen, I suspect it is the fog. Here are some photos of the glitch, although it will not be fully appreciated, because when making camera movements in the game, the glitch can be more or less annoying.

## Steps to Reproduce
1. Enter a world, preferably a server.
2. While the chunks are still charging, look at the ground, which should be invisible (not yet loaded), and make camera movements.

## OptiFine Version
OptiFine 1.15.2pre10. 

## Installation Method
I used the standalone installer.

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/62824667/77840419-47dc4c00-7155-11ea-964a-7626e630fb49.png)
![image](https://user-images.githubusercontent.com/62824667/77840416-41e66b00-7155-11ea-87f0-a1acd9321e4b.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? No.

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by Alternus** [comment] 2020-03-29 06:55
Hmm I'm experiencing a similar issue but only with projectLUMA Shaders, out of curiosity does this bug still occur when you are below y 61

**Comment by sp614x** [comment] 2020-06-06 18:16
Duplicate of #3673

**Closed by sp614x** 2020-06-06 18:16 UTC
Labels: 1.15, shaders
