### ISSUE TITLE
[Options] Blue Fire Animations Problems

### ISSUE THREAD

**Issue by AxeGt2802** [sp614x/optifine#4260] opened 2020-07-05 19:56 UTC
Hello OF !

I have seen that the Blue Fire Animation when "Terrain Animated" are stop but not the basic Fire and I propose that the Blue Fire Animation can be stop like the Basic Fire with the option "Fire Animated" , its logic .

Thx OF .

**Comment by sp614x** [comment] 2020-07-11 15:10
Duplicate of #4328

**Closed by sp614x** 2020-07-11 15:10 UTC
Labels: 1.16, animation
