### ISSUE TITLE
[SHADERS] No player shadow

### ISSUE THREAD

**Issue by tenshiaka** [sp614x/optifine#4087] opened 2020-06-13 20:38 UTC
## Description of Issue
with Sildur's shaders, the player will have no shadow but the cape

## Steps to Reproduce
1. Shaders on (i used sildur's vibrant VL ext)
2. /time set day

## OptiFine Version
PRE24 1.15.2

## Installation Method
 included standalone installer

## F3 Debug Screenshot

![image](https://user-images.githubusercontent.com/64901373/84578537-74078080-adc6-11ea-8453-b39a7bc55518.png)

## Prior Testing
If you've installed standalone:
- Cannot happen in vanilla due to no shader support

**Comment by naeqirelle2020** [comment] 2020-06-15 01:16
![2020-06-15_02 15 10](https://user-images.githubusercontent.com/63185833/84609245-1b131780-aeae-11ea-9ea5-8bcdd02d75cc.png)

Can't Reproduce, what settings do you have?

**Comment by naeqirelle2020** [comment] 2020-06-15 01:23
Tested on latest preview and cannot reproduce

![2020-06-15_02 22 39](https://user-images.githubusercontent.com/63185833/84609502-27e43b00-aeaf-11ea-873c-fe83a07fde98.png)

**Comment by tenshiaka** [comment] 2020-06-15 09:18
Probably only happens on PRE24 and with Extreme VL shaders, not sure though

**Comment by naeqirelle2020** [comment] 2020-06-15 18:01
@tenshiaka could you test on the latest preview? it doesn't appear for me, even on extreme, may be fixed

**Comment by naeqirelle2020** [comment] 2020-06-19 05:46
![2020-06-19_06 45 43](https://user-images.githubusercontent.com/63185833/85100649-8e8f8e80-b1f8-11ea-9ee6-599577ae56b5.png)

still works in pre-27 most likely fixed

**Comment by sp614x** [comment] 2020-06-19 10:49
Should be fixed by now.

**Closed by sp614x** 2020-06-19 10:49 UTC
Labels: 1.15, shaders
