### ISSUE TITLE
Latest 1.7.10 build crashes with variety of mods

### ISSUE THREAD

**Issue by border999** [sp614x/optifine#647] opened 2017-05-17 01:11 UTC
In Minecraft 1.7.10, on Optifine build 'OptiFine_1.7.10_HD_U_D8'
The game reports several failed construction events for various popular mods during startup and
proceeds to crash. The forge version is 1614.
[crash-2017-05-16_17.57.02-client.zip](https://github.com/sp614x/optifine/files/1006240/crash-2017-05-16_17.57.02-client.zip)

**Comment by sp614x** [comment] 2017-05-17 10:59
`FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) `

Duplicate of #588.

FastCraft 1.25 should work:
https://forum.industrial-craft.net/thread/10820-wip-1-7-10-fastcraft-1-23-note-all-posts-of-new-members-need-to-be-approved-firs/?postID=207199#post207199

**Closed by sp614x** 2017-05-17 10:59 UTC
Labels: mods
