### ISSUE TITLE
Glowing effect on player causes issue

### ISSUE THREAD

**Issue by zantetzou** [sp614x/optifine#3121] opened 2019-12-02 15:27 UTC
https://i.imgur.com/0W71QgR.jpg
https://i.imgur.com/Tf05tvA.jpg

**Comment by sp614x** [comment] 2019-12-02 15:57
Duplicate of #1377, #1174, #189.

The spectral effect (glowing outline) is not compatible with Fast Render and with shaders. When one of them is active an alternative "ghost" effect is used instead.

**Closed by sp614x** 2019-12-02 15:57 UTC
