### ISSUE TITLE
Magma cubes and dropped items gets invisible sometimes

### ISSUE THREAD

**Issue by Spisen** [sp614x/optifine#4411] opened 2020-07-22 20:09 UTC
## Description of Issue
Magma cubes gets invisible sometimes and you can only see the particles. Dropped items also gets invisible when you break blocks and when you drop from inventory. The problem started when i got pre.6. A short while later I saw that pre.7 was out so I tested it but the problem remained

## Steps to Reproduce
1. Find natural generated Magma cubes
2. Drop items from inventory or break block in survival

## OptiFine Version
Pre.7

## Installation Method
The Jar-file from Optifine.net

## F3 Debug Screenshot
invisible dropped items: https://gyazo.com/311c07d25a25d30cb8732ed177145264
invisible magma cubes: https://gyazo.com/9e0a0653adf3b9f7980e0ebb074348b1

**Comment by sp614x** [comment] 2020-07-23 10:10
Duplicate of #4414

**Closed by sp614x** 2020-07-23 10:10 UTC
Labels: 1.16, chunks, duplicate, entities
