### ISSUE TITLE
optifine bug - 1.18.2

### ISSUE THREAD

**Issue by anarchyarcheval** [sp614x/optifine#6653] opened 2022-03-05 18:02 UTC
Hello! i was playing on the recently released optifine version and have found a bug! when waterlogged, water looses its colour![https://cdn.discordapp.com/attachments/812182701276790845/949728222592004177/2022-03-05_18.00.26.png](url)

**Comment by KaiAF** [comment] 2022-03-05 18:04
Duplicate of #6646

**Closed** 2022-03-05 18:04 UTC
