### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by FrostedFlakz** [sp614x/optifine#5905] opened 2021-06-27 20:26 UTC
## Description of Issue

I love optifine I use it all the time, and I was really excited about shaders being available but the recent 1.17 preview 23, no matter which shaders I’ve used my game always crashes and I’ve tried every solution one could think of I’m hoping it gets fixed soon :(
## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## OptiFine Version

1.17 pre 23
## Installation Method

Used Java to install

**Comment by Whitelisted1** [comment] 2021-06-27 20:27
Are you using a mac? If so does it have an M1 chip, since based on other articles this is causing problems as well.

If you are using a mac this is a duplicate of #5864

**Comment by FrostedFlakz** [comment] 2021-06-27 21:18
Yes i am using a iMac, I’m not too sure how to figure out what chip I got.
I dont really know much about computers I’m sorry

**Comment by Whitelisted1** [comment] 2021-06-27 21:38
> Yes i am using a iMac, I’m not too sure how to figure out what chip I got. I dont really know much about computers I’m sorry

If you got this computer past late 2020 then it likely is an M1 mac. Otherwise check #5864 and see if it has a solution that may help

**Comment by FrostedFlakz** [comment] 2021-06-27 23:04
I read thru their issues and someone had commented its not compatible with Mac at the moment :/

**Comment by KaiAF** [comment] 2021-06-29 02:48
Already addressed here: #5900.

**Closed by KaiAF** 2021-06-29 02:48 UTC
