### ISSUE TITLE
Emissive Textures not working

### ISSUE THREAD

**Issue by Pumpking0108** [sp614x/optifine#3886] opened 2020-05-06 22:30 UTC
emissive textures will not work in the version currently

1.Make an emissive  texture
2.Load up minecraft
3. attempt to use the emissive texture

1.15.2 pre-16

Launcher Version for installation
![Annotation 222020-05-06 1821206](https://user-images.githubusercontent.com/64932087/81234882-af44b180-8fc7-11ea-940a-2bc55209e079.png)
![Annotation 20220-05-06 182937](https://user-images.githubusercontent.com/64932087/81234885-b10e7500-8fc7-11ea-991e-d6aa2d135f93.png)
![Annotation 202220-05-06 182937](https://user-images.githubusercontent.com/64932087/81234890-b370cf00-8fc7-11ea-869f-8d980aee0a3c.png)

**Comment by sp614x** [comment] 2020-05-29 12:18
Duplicate of #3437.

**Closed by sp614x** 2020-05-29 12:18 UTC
Labels: 1.15, emissive
