### ISSUE TITLE
frames getting stuck? not sure how to describe it

### ISSUE THREAD

**Issue by joyanna123** [sp614x/optifine#3680] opened 2020-04-04 17:06 UTC
When flying in the air and looking around, frames seem to get stuck and drag around the screen. It doesn't happen when shaders are turned off, or when playing the vanilla game.
preview 10: ![2020-04-04_11 08 47](https://user-images.githubusercontent.com/63157738/78456510-1fcb7c00-7672-11ea-9d19-1ebbeda929a1.png)
preview 13: ![2020-04-04_11 29 13](https://user-images.githubusercontent.com/63157738/78456512-23f79980-7672-11ea-8e33-efa26fd5feee.png)

## Steps to Reproduce
1. fly about 120 blocks into the air
2. look around slowly while moving forward

## OptiFine Version
1.15.2 preview 10 and 1.15.2 preview 13.

## Installation Method
Installed both previews using the standalone installer.

## Other Installed Mods
Not sure if shaders are considered mods, but this problem appeared while using shaders. I have two installed, Chocapic13 V7.1.1 Lite and Sildurs Vibrant Shaders v1.27 Medium, and it happened for both.

## F3 Debug Screenshot
preview 13 debug: ![2020-04-04_12 34 43](https://user-images.githubusercontent.com/63157738/78456446-b3507d00-7671-11ea-9e18-318d5bf9edc4.png)
preview 10 debug: ![2020-04-04_11 18 04](https://user-images.githubusercontent.com/63157738/78456450-ba778b00-7671-11ea-8164-e09ef2880afb.png)

## Additional Information
I play on a windows laptop, so the fps is usually low when using shaders (20-50). The game is still smooth when it happens, but if the low fps is what's causing the problem and not optifine, I sincerely apologize for taking your time away from other posts.

**Comment by sp614x** [comment] 2020-06-06 18:18
Duplicate of  #3673.

**Closed by sp614x** 2020-06-06 18:18 UTC
Labels: 1.15, performance, shaders
