### ISSUE TITLE
[cem, jem, jpm] When a body part is added to the head part of the .jem model (.jpm), the .jem head models are not displayed

### ISSUE THREAD

**Issue by iNkoR-the-2nd** [sp614x/optifine#5981] opened 2021-07-07 01:15 UTC
## Description of Issue
So far I've only seen this with pig and spider models, but when I add a .jpm body part model to the head part of the .jem model, the head doesn't work. The part .jpm does, however. See the attached screenshot.

## Steps to Reproduce
Create any .jem model, then make a .jpm model and attach that part to the head of the .jem model. Will work on pigs or spiders definitely.

## OptiFine Version
1.17 pre-23
## Installation Method
Preview versions on optifine.net/downloads

## Log Files/Crash Reports
No errors in the log or related messages. This message seems unrelated but might be?
_**[OptiFine] Model part not found: hair, model: egi@5d5790ea**_

## F3 Debug Screenshot
Not a debug screenshot but the one you need
![2021-07-06_19 51 40](https://user-images.githubusercontent.com/64202096/124684755-79ce7900-de95-11eb-83ac-0fd10acdc1e5.png)

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No, as cem models don't work in vanilla.

- Does this happen in OptiFine standalone?
Yes

**Comment by ewanhowell5195** [comment] 2021-07-28 15:38
This is how it is meant to work. you need to set `"attach": true` if you want it to attach instead.

**Comment by iNkoR-the-2nd** [comment] 2021-07-30 00:30
> This is how it is meant to work. you need to set `"attach": true` if you want it to attach instead.

it's set to "attach": "true"

**Comment by ewanhowell5195** [comment] 2021-07-30 00:31
Can you send the model so I can test it

**Comment by iNkoR-the-2nd** [comment] 2021-07-30 00:36
> Can you send the model so I can test it

are you on Discord?
it won't send here and I don't wanna make a .zip file
iNkoR_the_2nd#8230

**Comment by ewanhowell5195** [comment] 2021-07-30 00:38
Open the file in notepad, copy it, and paste it here

**Comment by iNkoR-the-2nd** [comment] 2021-07-30 00:40
> Open the file in notepad, copy it, and paste it here

fair enough, but they're hella big files

> {
	"textureSize": [64, 32],
	"models": [
		{
			"part": "head",
			"id": "head",
			"invertAxis": "xy",
			"translate": [0, -9, 3],
			"mirrorTexture": "u",
			"boxes": [
				{
					"coordinates": [-4, 5, -11, 8, 8, 8],
					"uvNorth": [48, 12, 40, 20],
					"uvEast": [56, 12, 48, 20],
					"uvSouth": [64, 12, 56, 20],
					"uvWest": [40, 12, 32, 20],
					"uvUp": [40, 12, 48, 4],
					"uvDown": [48, 4, 56, 12]
				}
			]
		},
		{
			"part": "neck",
			"id": "neck",
			"invertAxis": "xy",
			"translate": [0, -9, 0],
			"mirrorTexture": "u",
			"boxes": [
				{
					"coordinates": [-3, 6, -3, 6, 6, 6],
					"uvNorth": [12, 6, 6, 12],
					"uvEast": [18, 6, 12, 12],
					"uvSouth": [24, 6, 18, 12],
					"uvWest": [6, 6, 0, 12],
					"uvUp": [6, 6, 12, 0],
					"uvDown": [12, 0, 18, 6]
				}
			]
		},
		{
			"part": "body",
			"id": "body",
			"invertAxis": "xy",
			"translate": [0, -9, -9],
			"mirrorTexture": "u",
			"boxes": [
				{
					"coordinates": [-5, 5, 3, 10, 8, 12],
					"uvNorth": [22, 24, 12, 32],
					"uvEast": [34, 24, 22, 32],
					"uvSouth": [44, 24, 34, 32],
					"uvWest": [12, 24, 0, 32],
					"uvUp": [12, 24, 22, 12],
					"uvDown": [22, 12, 32, 24]
				}
			]
		},
		{
			"part": "leg1",
			"id": "leg1",
			"invertAxis": "xy",
			"translate": [-4, -9, -4],
			"mirrorTexture": "u",
			"boxes": [
				{
					"coordinates": [3, 8, 3, 16, 2, 2],
					"uvNorth": [36, 2, 20, 4],
					"uvEast": [2, 0, 0, 2],
					"uvSouth": [54, 2, 38, 4],
					"uvWest": [20, 2, 18, 4],
					"uvUp": [20, 2, 36, 0],
					"uvDown": [36, 0, 52, 2]
				}
			],
			"submodels": [
				{
					"id": "bone",
					"invertAxis": "xy",
					"translate": [0, 0, 0],
					"boxes": [
						{
							"coordinates": [5, 7, 1, 14, 0, 6],
							"uvNorth": [0, 0, 1, 1],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [0, 0, 1, 1],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [46, 20, 64, 26]
						},
						{
							"coordinates": [3, 6, 6, 16, 6, 0],
							"uvNorth": [0, 0, 1, 1],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [46, 20, 64, 26],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [46, 20, 62, 26]
						},
						{
							"coordinates": [3, 6, 2, 16, 6, 0],
							"uvNorth": [46, 20, 64, 26],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [0, 0, 3, 3],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [48, 20, 64, 26]
						}
					],
					"submodels": [
						{
							"id": "leg1_sub_1",
							"invertAxis": "xy",
							"translate": [0, 0, 0],
							"mirrorTexture": "u",
							"boxes": [
								{
									"coordinates": [3, 7, 2, 16, 4, 4],
									"uvNorth": [64, 30, 62, 32],
									"uvEast": [4, 12, 0, 16],
									"uvSouth": [3, 0, 0, 3],
									"uvWest": [12, 12, 8, 16],
									"uvUp": [62, 32, 64, 30],
									"uvDown": [62, 30, 64, 32]
								},
								{
									"coordinates": [3, 11, 1, 16, 0, 6],
									"uvNorth": [0, 0, 1, 1],
									"uvEast": [0, 0, 1, 1],
									"uvSouth": [0, 0, 1, 1],
									"uvWest": [0, 0, 1, 1],
									"uvUp": [46, 20, 64, 26],
									"uvDown": [0, 0, 3, 3]
								}
							]
						}
					]
				}
			]
		},
		{
			"part": "leg2",
			"id": "leg2",
			"invertAxis": "xy",
			"translate": [4, -9, -4],
			"mirrorTexture": "u",
			"boxes": [
				{
					"coordinates": [-19, 8, 3, 16, 2, 2],
					"uvNorth": [36, 2, 20, 4],
					"uvEast": [38, 2, 36, 4],
					"uvSouth": [54, 2, 38, 4],
					"uvWest": [20, 2, 18, 4],
					"uvUp": [20, 2, 36, 0],
					"uvDown": [36, 0, 52, 2]
				}
			],
			"submodels": [
				{
					"id": "bone2",
					"invertAxis": "xy",
					"translate": [0, 0, 0],
					"boxes": [
						{
							"coordinates": [-19, 7, 1, 14, 0, 6],
							"uvNorth": [0, 0, 1, 1],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [0, 0, 1, 1],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [46, 20, 64, 26]
						},
						{
							"coordinates": [-19, 6, 6, 16, 6, 0],
							"uvNorth": [0, 0, 1, 1],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [46, 20, 64, 26],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [46, 20, 62, 26]
						},
						{
							"coordinates": [-19, 6, 2, 16, 6, 0],
							"uvNorth": [46, 20, 64, 26],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [0, 0, 3, 3],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [48, 20, 64, 26]
						}
					],
					"submodels": [
						{
							"id": "leg2_sub_1",
							"invertAxis": "xy",
							"translate": [0, 0, 0],
							"mirrorTexture": "u",
							"boxes": [
								{
									"coordinates": [-19, 7, 2, 16, 4, 4],
									"uvNorth": [64, 30, 62, 32],
									"uvEast": [4, 12, 0, 16],
									"uvSouth": [3, 0, 0, 2],
									"uvWest": [12, 12, 8, 16],
									"uvUp": [62, 32, 64, 30],
									"uvDown": [62, 30, 64, 32]
								},
								{
									"coordinates": [-19, 11, 1, 16, 0, 6],
									"uvNorth": [0, 0, 1, 1],
									"uvEast": [0, 0, 1, 1],
									"uvSouth": [0, 0, 1, 1],
									"uvWest": [0, 0, 1, 1],
									"uvUp": [46, 20, 64, 26],
									"uvDown": [0, 0, 3, 3]
								}
							]
						}
					]
				}
			]
		},
		{
			"part": "leg3",
			"id": "leg3",
			"invertAxis": "xy",
			"translate": [-4, -9, -1],
			"mirrorTexture": "u",
			"boxes": [
				{
					"coordinates": [3, 8, 0, 16, 2, 2],
					"uvNorth": [36, 2, 20, 4],
					"uvEast": [38, 2, 36, 4],
					"uvSouth": [54, 2, 38, 4],
					"uvWest": [20, 2, 18, 4],
					"uvUp": [20, 2, 36, 0],
					"uvDown": [36, 0, 52, 2]
				}
			],
			"submodels": [
				{
					"id": "bone3",
					"invertAxis": "xy",
					"translate": [0, 0, 0],
					"boxes": [
						{
							"coordinates": [5, 7, -2, 14, 0, 6],
							"uvNorth": [0, 0, 1, 1],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [0, 0, 1, 1],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [46, 20, 64, 26]
						},
						{
							"coordinates": [3, 6, 3, 16, 6, 0],
							"uvNorth": [0, 0, 1, 1],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [46, 20, 64, 26],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [46, 20, 62, 26]
						},
						{
							"coordinates": [3, 6, -1, 16, 6, 0],
							"uvNorth": [46, 20, 64, 26],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [0, 0, 3, 3],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [48, 20, 64, 26]
						}
					],
					"submodels": [
						{
							"id": "leg3_sub_1",
							"invertAxis": "xy",
							"translate": [0, 0, 0],
							"mirrorTexture": "u",
							"boxes": [
								{
									"coordinates": [3, 7, -1, 16, 4, 4],
									"uvNorth": [64, 30, 62, 32],
									"uvEast": [4, 12, 0, 16],
									"uvSouth": [3, 0, 0, 3],
									"uvWest": [12, 12, 8, 16],
									"uvUp": [62, 32, 64, 30],
									"uvDown": [62, 30, 64, 32]
								},
								{
									"coordinates": [3, 11, -2, 16, 0, 6],
									"uvNorth": [0, 0, 1, 1],
									"uvEast": [0, 0, 1, 1],
									"uvSouth": [0, 0, 1, 1],
									"uvWest": [0, 0, 1, 1],
									"uvUp": [46, 20, 64, 26],
									"uvDown": [0, 0, 3, 3]
								}
							]
						}
					]
				}
			]
		},
		{
			"part": "leg4",
			"id": "leg4",
			"invertAxis": "xy",
			"translate": [4, -9, -1],
			"mirrorTexture": "u",
			"boxes": [
				{
					"coordinates": [-19, 8, 0, 16, 2, 2],
					"uvNorth": [36, 2, 20, 4],
					"uvEast": [38, 2, 36, 4],
					"uvSouth": [54, 2, 38, 4],
					"uvWest": [20, 2, 18, 4],
					"uvUp": [20, 2, 36, 0],
					"uvDown": [36, 0, 52, 2]
				}
			],
			"submodels": [
				{
					"id": "bone4",
					"invertAxis": "xy",
					"translate": [0, 0, 0],
					"boxes": [
						{
							"coordinates": [-19, 7, -2, 14, 0, 6],
							"uvNorth": [0, 0, 1, 1],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [0, 0, 1, 1],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [46, 20, 64, 26]
						},
						{
							"coordinates": [-19, 6, 3, 16, 6, 0],
							"uvNorth": [0, 0, 1, 1],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [46, 20, 64, 26],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [46, 20, 62, 26]
						},
						{
							"coordinates": [-19, 6, -1, 16, 6, 0],
							"uvNorth": [46, 20, 64, 26],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [0, 0, 3, 3],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [48, 20, 64, 26]
						}
					],
					"submodels": [
						{
							"id": "leg4_sub_1",
							"invertAxis": "xy",
							"translate": [0, 0, 0],
							"mirrorTexture": "u",
							"boxes": [
								{
									"coordinates": [-19, 7, -1, 16, 4, 4],
									"uvNorth": [64, 30, 62, 32],
									"uvEast": [4, 12, 0, 16],
									"uvSouth": [4, 0, 1, 2],
									"uvWest": [12, 12, 8, 16],
									"uvUp": [62, 32, 64, 30],
									"uvDown": [62, 30, 64, 32]
								},
								{
									"coordinates": [-19, 11, -2, 16, 0, 6],
									"uvNorth": [0, 0, 1, 1],
									"uvEast": [0, 0, 1, 1],
									"uvSouth": [0, 0, 1, 1],
									"uvWest": [0, 0, 1, 1],
									"uvUp": [46, 20, 64, 26],
									"uvDown": [0, 0, 3, 3]
								}
							]
						}
					]
				}
			]
		},
		{
			"part": "leg5",
			"id": "leg5",
			"invertAxis": "xy",
			"translate": [-4, -9, 2],
			"mirrorTexture": "u",
			"boxes": [
				{
					"coordinates": [3, 8, -3, 16, 2, 2],
					"uvNorth": [36, 2, 20, 4],
					"uvEast": [38, 2, 36, 4],
					"uvSouth": [54, 2, 38, 4],
					"uvWest": [20, 2, 18, 4],
					"uvUp": [20, 2, 36, 0],
					"uvDown": [36, 0, 52, 2]
				}
			],
			"submodels": [
				{
					"id": "bone5",
					"invertAxis": "xy",
					"translate": [0, 0, 0],
					"boxes": [
						{
							"coordinates": [5, 7, -5, 14, 0, 6],
							"uvNorth": [0, 0, 1, 1],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [0, 0, 1, 1],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [46, 20, 64, 26]
						},
						{
							"coordinates": [3, 6, 0, 16, 6, 0],
							"uvNorth": [0, 0, 1, 1],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [46, 20, 64, 26],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [46, 20, 62, 26]
						},
						{
							"coordinates": [3, 6, -4, 16, 6, 0],
							"uvNorth": [46, 20, 64, 26],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [0, 0, 3, 3],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [48, 20, 64, 26]
						}
					],
					"submodels": [
						{
							"id": "leg5_sub_1",
							"invertAxis": "xy",
							"translate": [0, 0, 0],
							"mirrorTexture": "u",
							"boxes": [
								{
									"coordinates": [3, 7, -4, 16, 4, 4],
									"uvNorth": [64, 30, 62, 32],
									"uvEast": [4, 12, 0, 16],
									"uvSouth": [3, 0, 0, 3],
									"uvWest": [12, 12, 8, 16],
									"uvUp": [62, 32, 64, 30],
									"uvDown": [62, 30, 64, 32]
								},
								{
									"coordinates": [3, 11, -5, 16, 0, 6],
									"uvNorth": [0, 0, 1, 1],
									"uvEast": [0, 0, 1, 1],
									"uvSouth": [0, 0, 1, 1],
									"uvWest": [0, 0, 1, 1],
									"uvUp": [46, 20, 64, 26],
									"uvDown": [0, 0, 3, 3]
								}
							]
						}
					]
				}
			]
		},
		{
			"part": "leg6",
			"id": "leg6",
			"invertAxis": "xy",
			"translate": [4, -9, 2],
			"mirrorTexture": "u",
			"boxes": [
				{
					"coordinates": [-19, 8, -3, 16, 2, 2],
					"uvNorth": [36, 2, 20, 4],
					"uvEast": [38, 2, 36, 4],
					"uvSouth": [54, 2, 38, 4],
					"uvWest": [20, 2, 18, 4],
					"uvUp": [20, 2, 36, 0],
					"uvDown": [36, 0, 52, 2]
				}
			],
			"submodels": [
				{
					"id": "bone6",
					"invertAxis": "xy",
					"translate": [0, 0, 0],
					"boxes": [
						{
							"coordinates": [-19, 7, -5, 14, 0, 6],
							"uvNorth": [0, 0, 1, 1],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [0, 0, 1, 1],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [46, 20, 64, 26]
						},
						{
							"coordinates": [-19, 6, 0, 16, 6, 0],
							"uvNorth": [0, 0, 1, 1],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [46, 20, 64, 26],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [46, 20, 62, 26]
						},
						{
							"coordinates": [-19, 6, -4, 16, 6, 0],
							"uvNorth": [46, 20, 64, 26],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [0, 0, 3, 3],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [48, 20, 64, 26]
						}
					],
					"submodels": [
						{
							"id": "leg6_sub_1",
							"invertAxis": "xy",
							"translate": [0, 0, 0],
							"mirrorTexture": "u",
							"boxes": [
								{
									"coordinates": [-19, 7, -4, 16, 4, 4],
									"uvNorth": [64, 30, 62, 32],
									"uvEast": [4, 12, 0, 16],
									"uvSouth": [3, 0, 0, 2],
									"uvWest": [12, 12, 8, 16],
									"uvUp": [62, 32, 64, 30],
									"uvDown": [62, 30, 64, 32]
								},
								{
									"coordinates": [-19, 11, -5, 16, 0, 6],
									"uvNorth": [0, 0, 1, 1],
									"uvEast": [0, 0, 1, 1],
									"uvSouth": [0, 0, 1, 1],
									"uvWest": [0, 0, 1, 1],
									"uvUp": [46, 20, 64, 26],
									"uvDown": [0, 0, 3, 3]
								}
							]
						}
					]
				}
			]
		},
		{
			"part": "leg7",
			"id": "leg7",
			"invertAxis": "xy",
			"translate": [-4, -9, 5],
			"mirrorTexture": "u",
			"boxes": [
				{
					"coordinates": [3, 8, -6, 16, 2, 2],
					"uvNorth": [36, 2, 20, 4],
					"uvEast": [38, 2, 36, 4],
					"uvSouth": [54, 2, 38, 4],
					"uvWest": [20, 2, 18, 4],
					"uvUp": [20, 2, 36, 0],
					"uvDown": [36, 0, 52, 2]
				}
			],
			"submodels": [
				{
					"id": "bone7",
					"invertAxis": "xy",
					"translate": [0, 0, 0],
					"boxes": [
						{
							"coordinates": [5, 7, -8, 14, 0, 6],
							"uvNorth": [0, 0, 1, 1],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [0, 0, 1, 1],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [46, 20, 64, 26]
						},
						{
							"coordinates": [3, 6, -3, 16, 6, 0],
							"uvNorth": [0, 0, 1, 1],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [46, 20, 64, 26],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [46, 20, 62, 26]
						},
						{
							"coordinates": [3, 6, -7, 16, 6, 0],
							"uvNorth": [46, 20, 64, 26],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [0, 0, 3, 3],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [48, 20, 64, 26]
						}
					],
					"submodels": [
						{
							"id": "leg7_sub_1",
							"invertAxis": "xy",
							"translate": [0, 0, 0],
							"mirrorTexture": "u",
							"boxes": [
								{
									"coordinates": [3, 7, -7, 16, 4, 4],
									"uvNorth": [64, 30, 62, 32],
									"uvEast": [4, 12, 0, 16],
									"uvSouth": [3, 0, 0, 3],
									"uvWest": [12, 12, 8, 16],
									"uvUp": [62, 32, 64, 30],
									"uvDown": [62, 30, 64, 32]
								},
								{
									"coordinates": [3, 11, -8, 16, 0, 6],
									"uvNorth": [0, 0, 1, 1],
									"uvEast": [0, 0, 1, 1],
									"uvSouth": [0, 0, 1, 1],
									"uvWest": [0, 0, 1, 1],
									"uvUp": [46, 20, 64, 26],
									"uvDown": [0, 0, 3, 3]
								}
							]
						}
					]
				}
			]
		},
		{
			"part": "leg8",
			"id": "leg8",
			"invertAxis": "xy",
			"translate": [4, -9, 5],
			"mirrorTexture": "u",
			"boxes": [
				{
					"coordinates": [-19, 8, -6, 16, 2, 2],
					"uvNorth": [36, 2, 20, 4],
					"uvEast": [38, 2, 36, 4],
					"uvSouth": [54, 2, 38, 4],
					"uvWest": [20, 2, 18, 4],
					"uvUp": [20, 2, 36, 0],
					"uvDown": [36, 0, 52, 2]
				}
			],
			"submodels": [
				{
					"id": "bone8",
					"invertAxis": "xy",
					"translate": [0, 0, 0],
					"boxes": [
						{
							"coordinates": [-19, 7, -8, 14, 0, 6],
							"uvNorth": [0, 0, 1, 1],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [0, 0, 1, 1],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [46, 20, 64, 26]
						},
						{
							"coordinates": [-19, 6, -3, 16, 6, 0],
							"uvNorth": [0, 0, 1, 1],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [46, 20, 64, 26],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [46, 20, 62, 26]
						},
						{
							"coordinates": [-19, 6, -7, 16, 6, 0],
							"uvNorth": [46, 20, 64, 26],
							"uvEast": [0, 0, 1, 1],
							"uvSouth": [0, 0, 3, 3],
							"uvWest": [0, 0, 1, 1],
							"uvUp": [0, 0, 1, 1],
							"uvDown": [48, 20, 64, 26]
						}
					],
					"submodels": [
						{
							"id": "leg8_sub_1",
							"invertAxis": "xy",
							"translate": [0, 0, 0],
							"mirrorTexture": "u",
							"boxes": [
								{
									"coordinates": [-19, 7, -7, 16, 4, 4],
									"uvNorth": [2, 0, 0, 2],
									"uvEast": [4, 12, 0, 16],
									"uvSouth": [3, 0, 0, 2],
									"uvWest": [12, 12, 8, 16],
									"uvUp": [62, 32, 64, 30],
									"uvDown": [62, 30, 64, 32]
								},
								{
									"coordinates": [-19, 11, -8, 16, 0, 6],
									"uvNorth": [0, 0, 1, 1],
									"uvEast": [0, 0, 1, 1],
									"uvSouth": [0, 0, 1, 1],
									"uvWest": [0, 0, 1, 1],
									"uvUp": [46, 20, 64, 26],
									"uvDown": [0, 0, 3, 3]
								}
							]
						}
					]
				}
			]
		},
		{
			"model": "flaming_tarantula_head.jpm",
			"id": "flaming_tarantula_head",
			"attach": "true",
			"part": "head",
			"attachTo": "head",
			"translate": [0, 0, 0]
		}
	]
}

**Comment by ewanhowell5195** [comment] 2021-07-30 00:45
This is a bug, but not for the reason you think.

see comments of https://github.com/sp614x/optifine/issues/5793 for explanation.

This issue can also be closed as it is a duplicate.

**Comment by iNkoR-the-2nd** [comment] 2021-07-30 00:52
> This is a bug, but not for the reason you think.
> 
> see comments of #5793 for explanation.
> 
> This issue can also be closed as it is a duplicate.

oh well, I used the example from the comment and it fixed the spider model
but now the head and legs of the custom entity don't work anymore...
![2021-07-29_19 51 17](https://user-images.githubusercontent.com/64202096/127583542-21a48ccf-9c79-480c-b78a-87e87c3ead10.png)

**Comment by iNkoR-the-2nd** [comment] 2021-07-30 00:58
My bad, that was a syntax error. Now it looks like what it did before, still no head, even when using the example in the comment to the other issue that you provided.

**Comment by sp614x** [comment] 2021-12-20 18:40
Duplicate of #5793

**Closed by sp614x** 2021-12-20 18:40 UTC
Labels: bug, CEM, 1.17
