### ISSUE TITLE
[1.15.2 pre16] Block outline and break animation disappear when using shaders

### ISSUE THREAD

**Issue by LunaticKing** [sp614x/optifine#3926] opened 2020-05-12 17:34 UTC
## Description of Issue
Whenever I aim at a block, either its outline disappears entirely, or it get really "thin" to the point where it's hard to see, I've tested if it happens in 1.14.4 and it doesen't so I'm pretty sure it's a 1.15.2 issue.

![2020-05-12_14 18 41](https://user-images.githubusercontent.com/49865890/81726387-ac314180-945d-11ea-9349-5aacad22998d.png)
![2020-05-12_14 18 33](https://user-images.githubusercontent.com/49865890/81726399-af2c3200-945d-11ea-9fd2-641d59123d21.png)

## Steps to Reproduce
1. Just aim at a block

## OptiFine Version
1.15.2 HD U G1 pre16

## Installation Method
Standalone Installer

## Log Files/Crash Reports
https://pastebin.com/zQbsGvXw

## F3 Debug Screenshot
![2020-05-12_14 31 04](https://user-images.githubusercontent.com/49865890/81726171-552b6c80-945d-11ea-8ed1-c7a0d2db23aa.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine?
No.

## Additional Information
I'm using BSL Shaders

**Comment by Neamow** [comment] 2020-05-13 20:10
Getting the same issue as well, same OF version, any shaders I try.

**Comment by seeruk** [comment] 2020-05-19 15:55
Dupe of #3600

**Comment by TheoCGaming** [comment] 2020-05-24 23:10
Using VanillaPlus, the outline is also invisible. This is a 1.15.2 HD Ultra Pre-17 problem as well.

**Comment by sp614x** [comment] 2020-05-30 12:32
Duplicate of #3600.

**Closed by sp614x** 2020-05-30 12:32 UTC
Labels: 1.15, shaders
