### ISSUE TITLE
Emissive Textures still broken in 1.15 pre10

### ISSUE THREAD

**Issue by SkaliberWasTaken** [sp614x/optifine#3596] opened 2020-03-27 23:05 UTC
## Description of Issue

As the title states, emissive textures are still broken in 1.15. It seems to be a common trend that they get missed until very late into the process of updating.

## Steps to Reproduce

1. Have pack with large amount of emissive features
2. Emissive textures aren't working in 1.15
3. Backdate to 1.14 to see if I'm doing something wrong
4. It's working fine in 1.14

## OptiFine Version

OptiFine 1.15.2 HD U G1 pre10

## Installation Method

Used the installer.

## Additional Information
I've removed a lot of the suggested information as it was irrelevant.

**Comment by Ratchet97** [comment] 2020-04-02 14:37
Still a bug in pre13.

**Comment by realjackasterisk** [comment] 2020-04-24 23:19
Duplicate of #3500.

**Closed by realjackasterisk** 2020-04-24 23:19 UTC
Labels: 1.15, bug, emissive
