### ISSUE TITLE
Leaf, grass and flower disappered when using chocapic13 shader

### ISSUE THREAD

**Issue by EdgyPotato** [sp614x/optifine#4048] opened 2020-06-07 10:42 UTC
The leaf, grass and flower seems disappered but the shadows are still there.

## OptiFine Version
Optifine 1.15.2 pre 22

## Installation Method
Standalone

## Additional Information
shaders : Chocapic13_V8.1_Ultra_Beta

It kinda fix the leaves when changing the trees settings to "Fast" but the grass and the flower still gone, here are some screenshot from optifine 1.14.4 & optifine 1.15.2 :
![2020-06-07_18 17 39](https://user-images.githubusercontent.com/64056626/83966647-ea4f4300-a8ed-11ea-92db-2bf06ccc666f.png)
![2020-06-07_18 20 06](https://user-images.githubusercontent.com/64056626/83966651-ecb19d00-a8ed-11ea-8772-c1edc9114f89.png)
![2020-06-07_18 31 37](https://user-images.githubusercontent.com/64056626/83966654-ed4a3380-a8ed-11ea-87f3-eb3db3f955bd.png)
![2020-06-07_18 33 43](https://user-images.githubusercontent.com/64056626/83966656-ede2ca00-a8ed-11ea-8160-f68e396e3aa6.png)

I also told someone to test it but it seems fine to him
![image](https://user-images.githubusercontent.com/64056626/83966710-62b60400-a8ee-11ea-8660-079a70edd9ef.png)

and this is mine
![image](https://user-images.githubusercontent.com/64056626/83966717-7bbeb500-a8ee-11ea-80c1-a1b61a4cb227.png)

**Comment by sp614x** [comment] 2020-06-07 11:03
Works for me, can't reproduce it.

![image](https://user-images.githubusercontent.com/16635441/83967149-333bd300-a8bf-11ea-8bab-92baa7efff4b.png)

**Comment by naeqirelle2020** [comment] 2020-06-07 11:29
turning mipmaps off triggers this bug

![2020-06-07_12 29 12](https://user-images.githubusercontent.com/63185833/83967548-83fcfd00-a8ba-11ea-907e-88efa537238b.png)

**Comment by EdgyPotato** [comment] 2020-06-07 12:18
yea, putting mipmap level at 1 to max fix it

**Comment by sp614x** [comment] 2020-06-20 21:07
Duplicate of #4120

**Closed by sp614x** 2020-06-20 21:07 UTC
Labels: 1.15, not reproducible, shaders
