### ISSUE TITLE
Entites flicker black when looked at

### ISSUE THREAD

**Issue by PoompkinPlayer** [sp614x/optifine#6017] opened 2021-07-12 03:18 UTC
## Description of Issue
 Wehn ever i look at mobs or chests they turn black for a second or two

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## OptiFine Version
 Optifine_1.17.1_G9_pre27

## Installation Method
 Standalone

## Prior Testing
 Does not happen in vanilla

**Comment by Whitelisted1** [comment] 2021-07-12 03:20
You already opened a different issue (#6016), so if you are continuing here, please close that one

This is a duplicate of #6013, which describes the same issue, please continue the thread there

**Comment by Wormcake** [comment] 2021-07-12 19:30
> This is a duplicate of #6013, which describes the same issue, please continue the thread there

While this issue (#6017) is written with not much detail. I think it could be a lightly different issue. Instead of "flickering" like in my issue, it sounds like the textures just change once for a longer period of time ("a second or two" instead of a frame or few, multiple times).

Also this issue is in Optifine_1.17.1_G9_pre**27** instead of OptiFine_1.17.1_G9_pre**26**

**Comment by Whitelisted1** [comment] 2021-07-12 19:37
According to the video they sent, the entities flicker black for about a frame, which some may describe as "A second or two". The other thread gives much more information about this issue, so I think it would be best to continue the thread there

**Comment by KaiAF** [comment] 2021-07-17 18:52
Already addressed here: #6013

**Closed by KaiAF** 2021-07-17 18:52 UTC
