### ISSUE TITLE
[Crash] Game crashed during gameplay

### ISSUE THREAD

**Issue by SGTxGiggleFairy** [sp614x/optifine#6885] opened 2022-06-30 21:34 UTC
## Description of Issue

I was placing end portal blocks in lava and the game crashed about halfway through making the shape of the portal. 
## Steps to Reproduce
1. What do you do...
2. ...to find this bug?
Place end portal blocks facing outward as if to make an end portal but inside of a block deep pool of lava
## OptiFine Version

1.19 pre 
## Installation Method
installer 

The game crashed whilst accessing legacyrandomsource from multiple threads
Error: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
Exit Code: -1
[crash-2022-06-30_17.26.53-client.txt](https://github.com/sp614x/optifine/files/9023545/crash-2022-06-30_17.26.53-client.txt)

[crash-2022-06-30_17.26.53-client.txt](https://github.com/sp614x/optifine/files/9023542/crash-2022-06-30_17.26.53-client.txt)

**Comment by UnknownTheLad** [comment] 2022-06-30 21:46
Duplicate of #6858

Feel free to close.

**Closed** 2022-06-30 22:54 UTC
