### ISSUE TITLE
[bug] game crashes while feeding cookies to parrots

### ISSUE THREAD

**Issue by MagneticChief54** [sp614x/optifine#4292] opened 2020-07-08 02:10 UTC
## Description of Issue
When I feed a cookie to a parrot, (untamed, but I haven't tried tamed) the beginning of the death animation shows and then the game crashes. When I go back in, the animation finishes and returns to normal. This happens consistently and is not a one-time bug. Other things to note: I am on a server 

## Steps to Reproduce
feed a parrot a cookie
## OptiFine Version
OptiFine 1.16.1 HD U G2 pre2

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?
I installed it through https://optifine.net/downloads

## Other Installed Mods
No other mods

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
[crash-2020-07-07_20.48.56-client.txt](https://github.com/sp614x/optifine/files/4888022/crash-2020-07-07_20.48.56-client.txt)
## Prior Testing
I have not tested anything outside of the 2 instances I did on the server

**Comment by yezhiyi9670** [comment] 2020-07-08 04:36
Duplicate of #4214

**Comment by sp614x** [comment] 2020-07-08 12:42
Duplicate of #4214

**Closed by sp614x** 2020-07-08 12:42 UTC
