### ISSUE TITLE
[CEM] Elytra support for custom entity models

### ISSUE THREAD

**Issue by Shizzins** [sp614x/optifine#6492] opened 2021-12-19 01:49 UTC
## Description of the new feature

I would really love it if elytra CEM would be supported soon. It would allow for many creative and amazing possibilities

**Comment by ewanhowell5195** [comment] 2021-12-19 13:06
cem elytra falls under the same category as cem armor, so i don't think it will happen.

**Comment by ewanhowell5195** [comment] 2021-12-20 12:36
also duplicate of #788

**Comment by ZenithRogue** [comment] 2021-12-21 19:07
closed as duplicate

**Closed by ZenithRogue** 2021-12-21 19:07 UTC
