### ISSUE TITLE
Server connection issue on Linux

### ISSUE THREAD

**Issue by P1G4ME** [sp614x/optifine#3821] opened 2020-05-02 22:03 UTC
I'm running a dual boot Ubuntu 19.10/Windows 10. I originally had installed Minecraft on Ubuntu, and I encountered an issue with the pre 13 version of Optifine 1.15.2. The game wouldn't be able to connect to several servers because of a Time out, like if I was missing internet connection (which wasn't the case). Also these servers would work just fine with the standar 1.15.2 version of the game.
I installed Minecraft on my Windows to try out, and it appears that the problem is not a thing on Windows.
So I assume there is something wrong with the Linux version of Minecraft/Optifine which leads Optifine to not be able to connect to specific servers.

**Comment by masterX244** [comment] 2020-05-03 15:22
Looks like another case of this bug https://github.com/sp614x/optifine/issues/3773

If you don't know how to extract the SRV records manually just tell me the affected server IPs here if they are public servers or otherwise protected against unintended user joins so i can quickly do the lookup

**Comment by sp614x** [comment] 2020-05-28 20:31
Duplicate of #3773.

**Closed by sp614x** 2020-05-28 20:31 UTC
Labels: 1.15, java 9+, launcher, linux
