### ISSUE TITLE
[1.15.2] While mining a block with shaders on the screen disappears

### ISSUE THREAD

**Issue by GoTaco** [sp614x/optifine#4139] opened 2020-06-21 19:22 UTC
## Description of Issue
The whole world disappears when trying to break a block with a tool except a sword when using shaders
heres a video of it in action https://streamable.com/basl2v

## Steps to Reproduce
1. im using SEUS shaders along with pbr textures and when breaking a block with a pickaxe shovel or axe the screen disappears

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre29

## Installation Method
Dropped the jar into the mods folder

## Fabric/Forge Version
Forge

## Other Installed Mods
Heres a screenshot of all the installed mods
https://imgur.com/a/1v9gYhz

## Log Files/Crash Reports
There is no crash files but heres the log
[2020-06-21-1.log](https://github.com/sp614x/optifine/files/4810114/2020-06-21-1.log)

## F3 Debug Screenshot
a screenshot of the debug punching and not punching a block
https://imgur.com/a/vmaPvSi

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

If you've installed using Forge/Fabric:
- Does this happen without other mods installed?  Yes
- Does this happen in OptiFine standalone? Yes
- Does this happen in Vanilla without OptiFine? No
- Have you tried using a binary search to find which mods cause this issue? No

**Comment by sp614x** [comment] 2020-06-21 19:25
Most probably a conflict with one of the installed mods.
Please find the mod conflicting with OptiFine so this can be fixed.

   - To find conflicting mods, split your mods into 2 groups (not including OptiFine). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.

**Comment by sp614x** [comment] 2020-06-21 19:46
Duplicate of #4088

**Closed by sp614x** 2020-06-21 19:46 UTC
Labels: 1.15, forge, mods
