### ISSUE TITLE
[Visual] Boats dissappear occasionally and briefly

### ISSUE THREAD

**Issue by elShailee** [sp614x/optifine#4423] opened 2020-07-23 14:33 UTC
## Description of Issue
i have notice that a boat in my world (survival) briefly dissappears (it is still there, but invisible) while i sail in it.
i can continue sailing normally, exit and enter it again (although spam clicking to find to invisible boat).
it doesnt disappear nor reappear while standing still, but only while moving.

## Steps to Reproduce
not so sure, it comes and goes, not every time a play or sail a boat, but some times.
so i guess - try sailing a boat it survival?

## OptiFine Version
both pre 7 and 8 for 1.16.1, didnt happen in 5 nor 6.

## Installation Method
downloaded the jar file from the official site, opened and clicked install, while launcher closed.

## Other Installed Mods
datapacks counts? if so - no endermen griefing from vanilla tweaks.

## F3 Debug Screenshot
@ the end

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? no

## Additional Information
adding screenshots for the same boat while invisible and right after, while inside it, with hitboxes shown, and debug, looking down at the boat.
as you can see, the hitbox is also invisible.
![2020-07-23_17 30 07](https://user-images.githubusercontent.com/67635802/88298952-797fb100-cd0a-11ea-8847-f9c836766476.png)
![2020-07-23_17 30 23](https://user-images.githubusercontent.com/67635802/88298964-7c7aa180-cd0a-11ea-880f-fcbef0a84d2a.png)

**Comment by elShailee** [comment] 2020-07-23 14:36
[latest.log](https://github.com/sp614x/optifine/files/4966664/latest.log)
adding the log for those screenshots, the relevant times are the last 4 minutes, with all the screenshots and hitbox toggles...

**Comment by sp614x** [comment] 2020-07-23 15:02
Duplicate of #4414

**Closed by sp614x** 2020-07-23 15:02 UTC
