### ISSUE TITLE
[Bug][optfinie_1.17_HD_U_G9_pre22] Bubbles seen through walls

### ISSUE THREAD

**Issue by FezzaOrFez** [sp614x/optifine#5875] opened 2021-06-26 10:26 UTC
## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

**Comment by Ari-RERA-43** [comment] 2021-06-26 10:27
This is a duplicate of #5861 so you should close this issue. Check for similar issues before creating your own.

**Closed** 2021-06-26 10:30 UTC
