### ISSUE TITLE
[1.16.~CTM] CTM method "h+v" does not work correct

### ISSUE THREAD

**Issue by Norzeteus** [sp614x/optifine#5525] opened 2021-04-04 09:04 UTC
I´m using CTM for a long time in my resoucepacks and I wonder, if this "graphic error" could be patched some times....Method horizontal+vertical... it would look better I think.... the comparison between optifine and mcpatcher(long times ago...)

[https://www.curseforge.com/minecraft/texture-packs/norzeteus-space-1-13-128x128-ctm-3d-optifine/files](url)

 OptiFine Version 1.16.5
since version 1.12 it doesn't work properly anymore as it should....

installed with standalone installer, no other mods

I've posted this issue before as suggestion #1675

![CTM h+v issue](https://user-images.githubusercontent.com/24456750/113503806-77761f00-9534-11eb-9259-e98ba7a6d6f0.png)

**Comment by ewanhowell5195** [comment] 2024-09-13 20:24
closing as this is a duplicate of #1675

**Closed by ewanhowell5195** 2024-09-13 20:24 UTC
Labels: bug, CTM, 1.16
