### ISSUE TITLE
Why does my OptiFine download do this?

### ISSUE THREAD

**Issue by BlueShaddow432** [sp614x/optifine#943] opened 2017-10-09 03:57 UTC
When I download OptiFine and go to open it it opens an internet explorer page. 
I've downloaded the latest version of java.
Instead of the icon being the java logo it shows the icon for internet explorer.
I've tried downloading different versions of optifine but it does the same thing. 
If anyone knows how to fix this issue please help.
Thanks.

**Comment by xCuri0** [comment] 2017-10-09 04:28
Try this http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/mods-discussion/2467749-optifine-turns-to-internet-explorer-file

**Comment by BlueShaddow432** [comment] 2017-10-09 08:05
I've encountered another problem.
When i do what it says on the posts from the link that xCuri0 left OptiFine still doesn't work.
It come up with:
"Unable to install Java 
There are errors in the following switches 
C:\Users\ellie\Downloads\OptiFine_1.12.2_HD_U_C6.jar
Check that the commands are valid and try again."
I don't know what any of that means. 
I've already installed Java.

**Comment by sp614x** [comment] 2017-10-09 10:45
Duplicate of #763
Possible fix: http://www.softpedia.com/get/Others/Miscellaneous/Jarfix.shtml

**Closed by sp614x** 2017-10-09 10:45 UTC

**Comment by xCuri0** [comment] 2017-10-09 10:47
@sp614x I think the OptiFine installer should not use Java to avoid problems like this and not require Java to be installed.

**Comment by BlueShaddow432** [comment] 2017-10-10 03:37
@sp614x it still pops up with the same message as before.

**Comment by BlueShaddow432** [comment] 2017-10-10 03:46
Thank you @sp614x managed to install it.
