### ISSUE TITLE
Texture packs does not work on enchanted items

### ISSUE THREAD

**Issue by Runimoes** [sp614x/optifine#3523] opened 2020-03-08 22:55 UTC
I was messing around with texture packs while using OptiFine 1.15.2 pre9 and I noticed that all of the enchanted items had the vanilla textures.
This is rather anoying since I can not see my creations.

**Comment by sp614x** [comment] 2020-05-29 09:42
Duplicate of #3420.

**Closed by sp614x** 2020-05-29 09:42 UTC
Labels: 1.15, CIT
