### ISSUE TITLE
Replay Mod Incompatibility [1.11]

### ISSUE THREAD

**Issue by Rapolis** [sp614x/optifine#396] opened 2016-12-20 17:27 UTC
This is weird, I don't know why you use a method around forge, last issue was with Weather2 Mod and now with Replay mod. I can't render videos with shaders anymore! No more cinematics. Can you fix it? I don't know if Replay mod is causing fluctuations with your mod or you are doing it to the mod. Thank you.

Issue proof: When clicking render the video the screen flashes white and when you try to exit the whole screen goes white then crashes violently without a log.

**Comment by SuicSoft** [comment] 2017-01-14 14:25
@Rapolis This didn't happen to me

**Comment by CrushedPixel** [comment] 2017-01-19 16:04
ReplayMod Dev here: The issue can only be reproduced on some Nvidia Graphics Cards (however, it doesn't happen on all graphics cards of the same model, but if it happens, it can be reproduced reliably), and indeed only occurs when Optifine is installed.

The issue with the render settings GUI seems to be that we're rendering an asterisk (*) in said GUI - that's literally all that's wrong. Replacing the asterisk between the two input fields for video resolution with an "x" for example fixes the issue.

Note that we're using our own [jGui library](https://github.com/ReplayMod/jGui) to render our GUI screens, which only calls Minecraft's `FontRenderer#drawString` and `FontRenderer#drawStringWithShadow` methods. The issue occurs regardless of rendering with or without font shadows.

I hope this can help resolving the issue. I have two testers at my disposal which could help test versions of Optifine that attempt to fix the issue.

**Comment by sp614x** [comment] 2017-01-20 01:24
This looks like a driver bug, especially if it crashes hard in the driver.

**Comment by CrushedPixel** [comment] 2017-01-20 06:24
I concur, however all of the testers which experienced the crash stated they were on the latest version of their Nvidia drivers. Also, this only happens with Optifine - could you give any insight what you change in the rendering process?

Oddly enough, the combination ReplayMod + Optifine + ConquestForge also lead to the GuiLabel with the "x" failing to render - ReplayMod + Optifine and ReplayMod + ConquestForge work fine though, so there is something really weird going on. Removing the Label altogether "fixed" it.

**Comment by sp614x** [comment] 2017-01-20 09:50
How does it crash exactly?
Wrong rendering, OpenGL errors in game output (error log), crash report, exception or native crash log (hs_err_pidXXX.log)?

**Comment by CrushedPixel** [comment] 2017-01-21 17:15
It doesn't crash per se, our gui rendering method just stops rendering any further gui elements without exception. We're not messing with the FontRenderer at all.

I wrapped our render loop in an exception handler to possibly get exceptions, but for the only available tester the released version suddenly started working again without him making any changes to his OS/Graphics Card/Drivers. Waiting for the other tester to test my dev build.

**Closed** 2017-02-01 12:30 UTC
Labels: mods

**Comment by cjburkey01** [comment] 2017-07-11 23:37
Is there a version of the mod available with an 'x' instead of the '*'? I'm experiencing this crash, and it's driving me nuts.

**Comment by CrushedPixel** [comment] 2017-07-12 07:12
Removing the HD fonts from the Resource pack being used has always fixed the issue for us - please try without said HD fonts.

**Comment by cjburkey01** [comment] 2017-07-14 15:47
I'll try the vanilla resource pack, I actually hadn't tried that lol.

**Comment by boivsamuel** [comment] 2017-08-06 17:16
Thanks CrushedPixel Turning Custom HD Fonts OFF solved it for me! (Settings > Video > Quality > Use Custom Fonts OFF)

**Comment by sp614x** [comment] 2017-10-02 13:16
The string width calculation for HD fonts was fixed for https://github.com/sp614x/optifine/issues/845, it could also fix this issue.
