### ISSUE TITLE
[Bug] Skybox not rendering properly with shaders

### ISSUE THREAD

**Issue by dbrighthd** [sp614x/optifine#5960] opened 2021-07-03 02:05 UTC
I dont think this is a duplicate because I cant find an issue like this one, but my apologies if I missed one.

When loading Complementary shaders, half of the skybox is not rendered correctly
![image](https://user-images.githubusercontent.com/68525639/124340172-15937880-db68-11eb-8171-b641b500670a.png)

1. Install optifine
2. apply Complementary shaders

OptiFine 1.17_HD_U_G9_pre24

Installation method was using the universal jar

Bug is the same when using standalone optifine, or OptiFabric 1.11.9, or OptiFabric 1.11.6.

There are no openGL errors.
F3 screenshot:
![image](https://user-images.githubusercontent.com/68525639/124340158-07ddf300-db68-11eb-856b-6afcff1ce1ee.png)

Im pretty sure this isn't Complementary shader's fault, because it works just fine in Iris/Starline (pictured below)
![image](https://user-images.githubusercontent.com/68525639/124340204-61462200-db68-11eb-9971-8ba8324bec88.png)

**Comment by Killercat103** [comment] 2021-07-03 09:26
I have the same issue, the end sky is completely white too.
I checked previous versions and this was not an issue in optifine 1.16

**Comment by EminGT** [comment] 2021-07-04 17:20
For sp614x:

The issue is entirely caused by the "skyColor" uniform not working correctly in the gbuffers_skybasic program. It works fine in other programs like deferred or composite.

**Comment by dbrighthd** [comment] 2021-07-09 19:21
update: this bug is still broken with pre26

**Comment by sp614x** [comment] 2021-07-11 23:00
Fixed in pre27.

**Closed by sp614x** 2021-07-11 23:00 UTC
Labels: 1.17, bug, shaders

**Comment by Morabert** [comment] 2022-01-02 02:54
This is an issue in 1.16.5 for months as well & it's not been fixed.
