### ISSUE TITLE
Forge + Optifine + JEI = Crash 1.14.4

### ISSUE THREAD

**Issue by Maxime51** [sp614x/optifine#2798] opened 2019-08-20 22:37 UTC
Forge = 1.14.4-forge-28.0.51
Optine = preview_OptiFine_1.14.4_HD_U_F4_pre2
Just Enough Item = jei-1.14.4-6.0.0.10

"Optifine" make "Just Enough Item" crash when i press E in game the game crash saying this msg :

The game crashed whilst rendering ingredient
Error: java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.ItemRenderer.func_191961_a(Lnet/minecraft/client/renderer/model/IBakedModel;Lnet/minecraft/item/ItemStack;)V from class mezz.jei.render.ItemStackFastRenderer

[crash-2019-08-21_00.31.14-client.txt](https://github.com/sp614x/optifine/files/3522866/crash-2019-08-21_00.31.14-client.txt)

I tryed everything i could and my final conclusion is "Optifine" who make the game crash because without him everything work (even with +16 Mods)
I tryed older version of "Forge" (1.14.4-forge-28.0.45) supported by "Optifine" (preview_OptiFine_1.14.4_HD_U_F4_pre2) but still crash
also tryed the older version of Just Enough Item who is the  jei-1.14.4-6.0.0.9 but still crash

Thanks for your awesome job ! i was gonna give 10$ to get the Cape but i think i need this stuff to be done before 👍

_Originally posted by @Maxime51 in https://github.com/sp614x/optifine/issues/2748#issuecomment-523221353_

**Comment by PseudoResonance** [comment] 2019-08-20 22:44
This is a duplicate of #2748, there is no need to make a new issue about it.

**Comment by sp614x** [comment] 2019-08-29 20:42
OptiFine 1.14.4_HD_U_F4_pre3
 - fixed Forge access transformers (#2737)

**Closed by sp614x** 2019-08-29 20:42 UTC
