### ISSUE TITLE
{Bug] VSync switches to unlimited if tabbed out

### ISSUE THREAD

**Issue by SpencerCKB** [sp614x/optifine#5230] opened 2021-01-19 05:02 UTC
## Description of Issue
I have Vsync(60fps) on. If I alt+tab out of the Minecraft fullscreen window my GPU usages shoots up from 50-60% to 100%. When I click back into Minecraft I can see the fps counter in the top left say 300+ fps then it immediately drops back down to 60fps. So when I'm not in the Minecraft application it seems to unlock the fps from the 60 for VSync and goes to unlimited.

## Steps to Reproduce
1. Have VSync on
2. tab out of fullscreen Minecraft

## OptiFine Version
1.16.5 OptiFine HD U G6

## Installation Method
standalone installer

## F3 Debug Screenshot
https://imgur.com/a/9lcNZuz
also included are images showing the fps counter before and after alt+tab

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No

**Comment by KaiAF** [comment] 2021-03-28 20:58
This is weird, Are you still having this issue? I am not able to reproduce this.

**Comment by SpencerCKB** [comment] 2021-03-28 23:54
> This is weird, Are you still having this issue? I am not able to reproduce this.

It was happening up to when I had stopped playing in February. But as of testing it today it it appears fixed. Even went back and tried the last few optifine versions and could not repeat it. Could have been on my end with drivers, java, or something,

**Comment by KaiAF** [comment] 2021-03-29 00:27
Closing the issue as it's fixed now.

**Closed by KaiAF** 2021-03-29 00:27 UTC
Labels: details needed

**Comment by MrGcGamer** [comment] 2021-04-01 16:02
I got the same issue... I am on 1.8.9 using the M6 pre1 version though

**Comment by KaiAF** [comment] 2021-04-01 19:04
@MrGcGamer I tried in 1.8.9 M6 Pre1, still cannot reproduce this. Unless if it's a macOS issue only?

**Comment by MrGcGamer** [comment] 2021-04-02 00:29
> @MrGcGamer I tried in 1.8.9 M6 Pre1, still cannot reproduce this. Unless if it's a macOS issue only?

I think it's the difference mentioned in my second edit... what does it say for you?
