### ISSUE TITLE
There is water in boat

### ISSUE THREAD

**Issue by DANEXIO** [sp614x/optifine#5980] opened 2021-07-07 00:32 UTC
When Im in a boat there is water half way through the boat. It almost looks like it is sinking.

**Comment by KaiAF** [comment] 2021-07-07 00:36
Can you provide more details? Does this happen on vanilla? Any resource packs, shader packs. Send a f3 debug menu screenshot?

**Comment by DANEXIO** [comment] 2021-07-07 00:41
I use the pre 24 shader pack. Im just playing on a normal singleplayer world. I dont use any resource packs, I use the normal deafault one.

**Comment by dbrighthd** [comment] 2021-07-07 01:36
pre 24 is the optifine version, not the shader pack

**Comment by Lyky35** [comment] 2021-07-08 04:49
pre 25 (as reference)
![image](https://user-images.githubusercontent.com/36609323/124864079-ede44c00-df7d-11eb-8406-9eb60128b851.png)

**Comment by Larueh** [comment] 2021-07-08 08:48
I have the same issue. It only happens with shaders. The intern shader works fine. Using BSL or SEUS "floods" the boat ^^
Using the Pre 25 too.

![2021-07-08_10 43 31](https://user-images.githubusercontent.com/86955151/124891570-64fafe00-dfd9-11eb-83e9-6326b666b76e.png)

![2021-07-08_10 46 59](https://user-images.githubusercontent.com/86955151/124892155-ea7eae00-dfd9-11eb-9759-3db97c374913.png)

![2021-07-08_10 41 14](https://user-images.githubusercontent.com/86955151/124892213-f66a7000-dfd9-11eb-90f0-1a505320bc5b.png)

**Comment by KaiAF** [comment] 2021-07-09 19:09
See if this was fixed in the latest preview version. (pre 26)

**Comment by dbrighthd** [comment] 2021-07-09 19:12
not OP but the issue is still here for me in pre 26
![image](https://user-images.githubusercontent.com/68525639/125125733-e07aaf00-e0ae-11eb-8e73-83f50657cac2.png)

**Comment by Larueh** [comment] 2021-07-10 21:08
For me too :/
![2021-07-10_23 04 15](https://user-images.githubusercontent.com/86955151/125176451-b8d13700-e1d3-11eb-902f-ea6591ab0aba.png)

**Comment by Larueh** [comment] 2021-07-24 08:15
Just wanted to let you know that the issue is gone for me! :)
It was still there in Pre29 but now after loading Pre31 everything is fine! Hope that goes for the others too!
Thank you for putting so much work into this!

**Comment by KaiAF** [comment] 2021-11-06 13:30
I assume this is fixed

**Closed by KaiAF** 2021-11-06 13:30 UTC
Labels: bug, shaders, 1.17
