### ISSUE TITLE
[Crash] Vanilla works fine but not Optifine

### ISSUE THREAD

**Issue by BoyfriendFNF** [sp614x/optifine#5838] opened 2021-06-20 15:30 UTC
## Description of Issue
Vanilla 1.17 [and 1.17.1-pre1] work just fine. but when i try to run Optifine, i get this error: 
![image](https://user-images.githubusercontent.com/80904546/122679769-6ad89d00-d1ec-11eb-95db-dc649c59a80b.png)

## Steps to Reproduce
1. Open MC Launcher
2. Select Optifine [1.17] and press Play
3. The error occurs, when in Vanilla, it doesn't

## OptiFine Version
OptiFine HD U G9 pre21

## Installation Method
I run the .jar and install the version.

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/6682603/latest.log)

## Prior Testing
- Does this happen in Vanilla without OptiFine?
No.

## Additional Information
Even if it isn't a bug for Optifine itself and just my graphic cards. i still posted the bug here juuuust in case.

**Comment by Bobbyperson12** [comment] 2021-06-23 06:32
I can confirm that this happens on the latest version of Ubuntu using the same exact method to reproduce, and does not happen on Vanilla.

**Comment by DarkSlayer3202** [comment] 2021-06-26 15:15
This bug has retained in version `G9_pre22`, tested using `Linux Mint 20.1 Ulyssa / Ubuntu 20.04 LTS` .

**Comment by DarkSlayer3202** [comment] 2021-06-27 15:44
The bug still retains in `G9_pre23`. Tested on `Linux Mint 20.1 / Ubuntu 20.04 LTS`.

**Comment by claude0001** [comment] 2021-06-30 14:49
Linux users, please look at your `glxinfo | grep OpenGL` and check if this is a duplicate of [#5739](https://github.com/sp614x/optifine/issues/5739).

**Comment by KaiAF** [comment] 2021-06-30 18:00
Already addressed here: #5739.

**Closed by KaiAF** 2021-06-30 18:00 UTC
