### ISSUE TITLE
F1 overlay texture issue

### ISSUE THREAD

**Issue by PlumLord** [sp614x/optifine#4623] opened 2020-08-17 01:52 UTC
When using shaders (1.16.2 pre) optifine is getting an incorrect texture when using the F1 overlay to disable the ui. It is likely to do with the slight colour change that occurs when F1 is activated. It results in all everything getting washed an eerie white. the issue is tied to the resource pack being used (default included). This only happens with F1.

**Comment by sp614x** [comment] 2020-08-20 14:40
Duplicate of #4640

**Closed by sp614x** 2020-08-20 14:40 UTC
Labels: 1.16, shaders
