### ISSUE TITLE
CTM Overlays

### ISSUE THREAD

**Issue by M4tt205** [sp614x/optifine#2536] opened 2019-06-25 12:17 UTC
CTM overlay textures aren't connecting to the blocks properly when using the `tintBlock=grass` tag.
I used a glass block so you could see the issue easier.

`matchBlocks=glass
method=overlay
tiles=0-16
connectTiles=grass_block_top
tintIndex=1
tintBlock=grass`

![2019-06-25_21 39 32](https://user-images.githubusercontent.com/49079228/60097185-07007280-9792-11e9-8327-110fabc273b3.png)

`matchBlocks=glass
method=overlay
tiles=0-16
connectTiles=grass_block_top
tintIndex=-1
tintBlock=grass`

![2019-06-25_21 41 46](https://user-images.githubusercontent.com/49079228/60097246-24cdd780-9792-11e9-80e9-73cd1090eafb.png)

`matchBlocks=glass
method=overlay
tiles=0-16
connectTiles=grass_block_top`

![2019-06-25_21 39 06](https://user-images.githubusercontent.com/49079228/60097255-28f9f500-9792-11e9-846b-379a769596e2.png)

`matchBlocks=glass
method=overlay
tiles=0-16
connectTiles=grass_block_top
tintIndex=1
tintBlock=foliage`

![2019-06-25_21 43 05](https://user-images.githubusercontent.com/49079228/60097321-4dee6800-9792-11e9-9c4d-8775746e54e5.png)

Sorry about poor formatting, I don't use GitHub very often.

**Comment by sp614x** [comment] 2019-06-26 14:03
Duplicate of #2514.

**Closed by sp614x** 2019-06-26 14:03 UTC
Labels: CTM, bug
