### ISSUE TITLE
[1.15.2 HD U G1 pre1] Honey Blocks + water glitches

### ISSUE THREAD

**Issue by Legoman99573** [sp614x/optifine#3273] opened 2020-02-13 17:36 UTC
Honey Block on certain angles have a visual problem:

Side i placed it on:
![image](https://user-images.githubusercontent.com/7460704/74461876-d2424800-4e54-11ea-953e-e238c5a53f48.png)

other side where i didnt place the block (will reverse when i place another honey block down on this side):
![image](https://user-images.githubusercontent.com/7460704/74461926-e6864500-4e54-11ea-9085-9e41c9139467.png)

When near a water source:
![image](https://user-images.githubusercontent.com/7460704/74461996-04ec4080-4e55-11ea-89c7-99a440db84db.png)

Placing a block under water and break it:
![image](https://user-images.githubusercontent.com/7460704/74461718-a1621300-4e54-11ea-9a19-6367c7b13fa9.png)

**Comment by sp614x** [comment] 2020-02-14 14:14
Can't reproduce it, works for me.
The breaking of block under water shows a general problem with the chunk updates.

**Comment by naeqirelle2020** [comment] 2020-06-06 17:23
the visual glitches are most likely to do with vanilla bugs
![2020-06-06_18 21 30](https://user-images.githubusercontent.com/63185833/83950445-c410a100-a822-11ea-889d-75b6932671cd.png)

![2020-06-06_18 22 10](https://user-images.githubusercontent.com/63185833/83950446-c5da6480-a822-11ea-9fae-ead0a59c2c9f.png)

**Comment by sp614x** [comment] 2020-06-06 19:43
Should be fixed in latest preview.

**Closed by sp614x** 2020-06-06 19:43 UTC
Labels: 1.15
