### ISSUE TITLE
[Shader Bug] Enchanted tools and armor have no enchantment animation when on hand and armor stands

### ISSUE THREAD

**Issue by EnzoFanAccount** [sp614x/optifine#5930] opened 2021-06-29 14:20 UTC
## Description of Issue
With BSL Shaders v8.0.01 for 1.17. Instead of the enchantment glow moving in a wave pattern like it usually does, it is just stuck in a purple glow that doesn't move.

## Steps to Reproduce
1. Hold an enchanted tool in your hand
2. Place enchanted armor on armor stand

## OptiFine Version
OptiFine HD U G9 pre24/1.17

## Installation Method
standalone

## Other Installed Mods
Only BSL shaders outside of OF.

## F3 Debug Screenshot
![2021-06-29_11 10 36](https://user-images.githubusercontent.com/86670127/123812877-d4326d00-d8ca-11eb-995a-14150b2de414.png)

## Additional Information
Regarding the screenshot above, the enchantment waves were not moving in the armor or the axe, they are stuck like that. (Also ignore the server stuff on the right of the screen)

**Comment by Whitelisted1** [comment] 2021-06-29 14:25
Duplicate of #5846

**Closed** 2021-06-29 23:08 UTC
