### ISSUE TITLE
Pre23 Black texture with shaders bug

### ISSUE THREAD

**Issue by sk0181** [sp614x/optifine#5894] opened 2021-06-27 08:03 UTC
![2021-06-27_09 00 59](https://user-images.githubusercontent.com/82708303/123537227-4027a080-d726-11eb-9f71-3b0a40f1bb26.png)

**Comment by KaiAF** [comment] 2021-06-27 16:54
Duplicate of: #5891

**Closed by KaiAF** 2021-06-27 16:54 UTC

**Comment by 5678Caleb** [comment] 2021-06-28 03:29
I have the same problem. Any solutions yet?
