### ISSUE TITLE
Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by bpalmz** [sp614x/optifine#6924] opened 2022-07-04 22:24 UTC
Hi I keep getting crashes on the v3 version that came out today. I'm pretty much java illiterate so I dont really know what's happening, but I figured I would attach a crash report in case useful.
[crash-2022-07-04_18.19.52-client.txt](https://github.com/sp614x/optifine/files/9042195/crash-2022-07-04_18.19.52-client.txt)

**Comment by UnknownTheLad** [comment] 2022-07-04 22:25
Duplicate of #6858

**Closed** 2022-07-04 23:18 UTC
