### ISSUE TITLE
CEM Armor support and how to combat cheaters.

### ISSUE THREAD

**Issue by MelloJelloGames** [sp614x/optifine#7227] opened 2023-01-19 02:35 UTC
Custom Entity Model support for armor has been a highly anticipated and expected addition to optifine, however it has been repeatedly stated that the primary reasons behind not implementing CEM armor is due to the ability to cheat using CEM, I.E make tall models that reach high in the sky to expose players positions, I have read through #561 and #823 <-- similar idea except utilizing Minecraft's player models as opposed to armor, either way this idea will combat the ability for cheaters to abuse custom armor models indefinitely for non supported servers.

The idea is simple: Enforce Custom NBT lore data for all armor types, and enforce that resource pack creators can only use a specific string for the NBT lore data, I.E: nbt.display.Lore.*=optifine-1 >>> nbt.display.Lore.*=optifine-99999, this way optifine does not have to worry about certain players attempt to abuse this feature to a pvp benefit as servers will most likely not have this exact string of NBT text, and if by some off chance they do they can easily be changed by server owners/administrators that don't wish to utilize this feature, as for protection against this issue by servers that do want to run custom model armor and do not wish for players to have the ability to abuse the armor by making very large/high armor to spot enemies.
A max size limit can be put in-place, let's say height wise the model cannot go higher than 2 blocks tall, and for width 2 blocks wide
if that is too difficult to implement, do not throw away the ability to use the NBT idea, as server owners can then make the executive decision whether to run the risk of players abusing it or just simply not use it at all, I am sure some server owners (including myself) would not mind this trade off as at least I can provide an unbelievable custom experience within vanilla Minecraft for my players while also occasionally having cheaters that my staff will inevitably catch.

Thank you for reading
~Mellow

**Comment by heinrich26** [comment] 2023-05-31 15:40
+1, as one could simply add their opponents names to the `CustomPlayerModels` config within seconds and it'd be reloaded after another >5 secs 🤷‍♂️

HOWEVER, limiting the model size for entities isn't that easy, considering the animation framework CEM offers. Suppose we limited the model size to 1block beyond the hitbox; by using an animation you could stil translate/scale those parts beyond the limit. Limiting that would be much more challenging. I could imagine a shader that clips the rendered model to the hitbox + some threshold...

**Comment by SeaOfPixels** [comment] 2023-06-13 02:49
Hey so this is a super late respone but I stumbled across this post. You can expose players similarly with large CIT models, this shouldn't be a valid reason against armor CEM. In fact, you can size up item models *without* OptiFine already to expose player positions.

**Comment by ewanhowell5195** [comment] 2024-09-13 15:05
closing as duplicate of #561. if you want to add any futher comments on this, feel free to do it over there

**Closed by ewanhowell5195** 2024-09-13 15:05 UTC
Labels: enhancement, CEM, interesting
