### ISSUE TITLE
[Bug] Custom item Models not working

### ISSUE THREAD

**Issue by Goncorer** [sp614x/optifine#3788] opened 2020-04-25 16:16 UTC
## Description of Issue
In the latest 1.15 preview version custom item models don't show up in item frames or players hands, and show with missing textures in hotbar/inventory slots.
As far as I can tell all the other CIT features are working

## Steps to Reproduce
1. Run the preview with or without shaders
2. make/find a CIT with a specified model

## OptiFine Version
Optifine_1.15.2_HD_U_G1_pre13

## Installation Method
Downloaded from optifine.net, ran using java

## Log Files/Crash Reports
No crash

## F3 Debug Screenshot
![2020-04-25_10 09 41](https://user-images.githubusercontent.com/17153074/80284645-fd5ed880-86dc-11ea-8fe0-4182fb2b0126.png)
(broken Tophat model included for scale)

## Prior Testing
Not applicable to vanilla, but vanilla custom block models work fine

## Additional Information
Everything was working as intended in 1.14.4 and the issues only appeared when trying to upgrade my resource pack to 1.15.2.
Also emissive textures are still broken but you probably know that.
Thanks!

**Comment by Kyutatsuki** [comment] 2020-05-01 01:35
The same problem is happening to me, I wanted to upgrade my server that I share with my friends to 1.15.2; hope it isn't a format change and it gets fixed.

**Comment by sp614x** [comment] 2020-05-29 09:52
Duplicate of #3420.

**Closed by sp614x** 2020-05-29 09:52 UTC
Labels: 1.15, CIT, models
