### ISSUE TITLE
[1.15/1.16 Multiplayer] On some servers, blocks are not rendering unless a block update happens

### ISSUE THREAD

**Issue by cs127** [sp614x/optifine#4760] opened 2020-09-02 13:12 UTC
# EDIT: This issue is probably the same as #4976. I'll close it if turns out to be the same issue. #

## Description of Issue
This issue existed in 1.15.2 G1 pre1 in both singleplayer and multiplayer, and was fixed in a later preview, however, this issue still happens in **multiplayer** in 1.16.2/1.16.3 G3, for me at least.

This issue has been reported on here before (#4307), but it has been closed due to the "37 render distance" bug being fixed. However, I still have this problem with my render distance set to 16. So I'm making this issue, and I'll try my best to explain everything as detailed as I can.

Here's the "detailed" explanation:
When I join some servers, either no blocks are rendered, or only the chunk I'm standing on is rendered. Player skins are also not loaded. If I cause a block update on a chunk, that chunk will be rendered.
As time goes on, some more chunks begin to be rendered, however, F3+A will "unrender" the chunks that have already been rendered.
Every time I want to play on those specific servers I either have to not use optifine, or just wait for a few minutes for the chunks to render, while this delay does not happen in vanilla.
To make sure I don't have any options enabled that might be causing the problem, I have tried this on a test instance I created in the minecraft launcher, running on a separate directory with most options set to default. And this problem still occured.

Edit: Something else I found out is that if I exit a server while having this issue, and then switch to a singleplayer world, instead of showing the world loading animation, it just gets stuck on an empty screen with the dirt background.

Here are the list of server IPs that I have tested and have had this issue with:
- hypixel.net
- eu.mineplex.com
- hivemc.eu
- play.cubecraft.net (the issue doesn't happen as much as it does on the other ones though.)

The rest of the servers I have tested don't seem to have this issue. But I will add more to the list if I find one that does.

## Steps to Reproduce
Join a server listed above.

## OptiFine Version
1.16.2/1.16.3 G3

## Installation Method
Standalone. Installed using the jar file.

## Log Files/Crash Reports
Vanilla log
[2020-09-02-1.log](https://github.com/sp614x/optifine/files/5162404/2020-09-02-1.log)

OptiFine log
[latest.log](https://github.com/sp614x/optifine/files/5162406/latest.log)

## F3 Debug Screenshot
![2020-09-02_17 02 39](https://user-images.githubusercontent.com/56088587/91984422-6fa59080-ed41-11ea-9543-8e99e7552e3b.png)

## Prior Testing
If you've installed standalone:
- Does this happen in OptiFine standalone? **Yes**
- Does this happen in Vanilla without OptiFine? **No**

**Comment by NickWilde263** [comment] 2020-09-21 02:09
No this not your connection issue. i'm also have same problem even i run Paper LAN server. LAN servers suppose not cause problem because it literally in same network as my computer

**Comment by NickWilde263** [comment] 2020-09-21 02:29
![2020-09-21_01 26 13](https://user-images.githubusercontent.com/67861857/93729042-e6210a00-fbec-11ea-92c7-019c43c5903e.png)
this more proof if you not trusting

**Comment by cs127** [comment] 2020-11-07 14:22
This issue is probably the same as #4976. I'll close it for now, and will reopen it if it turned out to not be the same issue, or that issue gets closed but my problem still persists.

**Comment by NickWilde263** [comment] 2020-11-09 05:50
no that not the same issue players in my server have no capes at all and it not related to poor network

**Comment by NickWilde263** [comment] 2020-11-09 05:52
also i dont know is this related
1. It happen when i push the RAM too much (i tested by run the minecraft first then the paper server then nothing happen then i restart minecraft and that happening(already push RAM too much because of the paper server) it but im not sure if it the cause or not)

**Comment by cs127** [comment] 2020-11-09 09:22
> no that not the same issue players in my server have no capes at all and it not related to poor network

as far as I know, it doesn't matter if the players have capes or not. the issue is caused if there are too many players, causing the client to send too many requests to the optifine website to check whether they have capes or not, and if they do, what does it look like.

also, how many people are in your server when the problem happens?

**Comment by NickWilde263** [comment] 2020-11-12 03:49
only 2-5 players it was a private server that uses numbered ip instead domain name that open to the internet

**Comment by NickWilde263** [comment] 2020-11-12 03:49
and other players dont have same issue

**Comment by NickWilde263** [comment] 2020-11-12 03:55
only me when reconnect or restart when the server running on same laptop

**Comment by NickWilde263** [comment] 2020-11-12 04:28
1-5 players it private server

**Comment by NickWilde263** [comment] 2020-11-12 04:28
but it visible to the internet

**Comment by NickWilde263** [comment] 2020-11-13 05:10
by restart i mean restarting my client

**Comment by cs127** [comment] 2020-11-15 09:07
> only 2-5 players it was a private server that uses numbered ip instead domain name that open to the internet

The problem only happens to me when there are about 20 players or more, so I don't know if we have the same problem, but I will open this issue just in case this issue isn't related to capes.

**Comment by NickWilde263** [comment] 2020-11-19 07:10
this also happen on other server i connect but it happen for few seconds then render properly

**Comment by NickWilde263** [comment] 2020-11-19 07:13
plus player skin render properly in my case

**Comment by ZenIsBestWolf** [comment] 2021-02-01 19:01
This should be fixed with #4976.

**Closed by ZenIsBestWolf** 2021-02-01 19:01 UTC
