### ISSUE TITLE
Inventory Bar. The inventory bar that holds your hand items is just white.

### ISSUE THREAD

**Issue by Titananik** [sp614x/optifine#4197] opened 2020-07-03 17:21 UTC
## Description of Issue
The inventory bars background is plain white. You can see the item icons  but the background is a solid plain white. It is very distracting and pretty annoying.

## Steps to Reproduce
1. What do you do... 
2. ...to find this bug?
I just opened up the game after installing Optifine 1.16.1 G2 pre1 was installed and the bar was white. I took my texture pack off and it still was white.

## OptiFine Version
Optifine 1.16.1 G2 pre1

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?
I installed the file and opened it with Java SE Binary Platform or whatever. 

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

![2020-07-03_11 20 32](https://user-images.githubusercontent.com/67800396/86488745-40fa4200-bd1f-11ea-97a1-70f6c04a6850.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

No

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

Its plain Minecraft vanilla, it doesn't happen in any other version.

**Comment by OfficialAlexM** [comment] 2020-07-03 17:30
This is caused by FXAA in my case. Turned off FXAA in Video Settings --> Shaders by setting "Antialiasing" to OFF and this bug is gone.

Seems like it's conflicting with the default shaders. Pressing F4 fixes this issue, so that's what it might be.

**Comment by sp614x** [comment] 2020-07-03 19:53
Fixed in pre2.

**Closed by sp614x** 2020-07-03 19:53 UTC
Labels: 1.16, shaders
