### ISSUE TITLE
Drowned Zombies invisible 

### ISSUE THREAD

**Issue by MyNameIsActuallyNotBob** [sp614x/optifine#5183] opened 2021-01-05 14:41 UTC
## Description of Issue
So the bug here is that some drowned spawn invisible, actually most of them. I know they are there, because when I restart Minecraft without Optifine they are visible. I've tried with Optifine on without any shaders but they were still invisible. Baby drowned should still be visible. I've realized this bug when I got hit by a invisible trident drowned and he was nowhere to be seen. I'm not sure if you can hit them, but when I met an invisible with a  trident I could see the trident fly from the invisible downed position.

## Steps to Reproduce
1. Visit underwater monument
2. get hit without anything around you

## OptiFine Version
1.16.4, I don't think they were invisible before this version of Optifine

## Installation Method
I just downloaded it like normal , by the installation mode

## Other Installed Mods
I've only used the BSL shader, but without it on the drowned are still invisible

## Additional Information
I've tried in creative to spawn drowned where it worked, so I guess its something with natural spawning drowned in ruins and water cities that s the problem.

**Comment by MyNameIsActuallyNotBob** [comment] 2021-01-05 19:05
After more playing I realized its the exact same thing on natural spawning witches in witch huts

**Comment by sp614x** [comment] 2021-01-05 19:29
Are the drowned still invisible if you open the world again with OptiFine?

**Comment by MyNameIsActuallyNotBob** [comment] 2021-01-05 20:19
If I chose to take O

ptifine off and on again they will appear visible. So if i meet them the first time they are invisible then i close game and change to normal and then switch to Optifine is will work, but that seems like a long process every time you get attacked.

I've attached a video of the invisible drowned with trident I just took. 
https://drive.google.com/file/d/1KWvNeOCd5VnFZgO3knCjeoq0jol0wm08/view?usp=sharing

**Comment by sp614x** [comment] 2021-01-05 20:58
Can you post a F3 screenshot?

**Comment by MyNameIsActuallyNotBob** [comment] 2021-01-05 21:12
![image](https://user-images.githubusercontent.com/77010244/103699324-0f4e8600-4fa3-11eb-9f11-5c1dea1d997a.png)

**Comment by sp614x** [comment] 2021-01-05 21:40
![image](https://user-images.githubusercontent.com/16635441/103702270-e9c37b80-4fa6-11eb-8033-bfbf3913341a.png)

**Comment by sp614x** [comment] 2021-01-05 21:53
Relevant #5016

**Comment by MyNameIsActuallyNotBob** [comment] 2021-01-05 22:20
Yeah that's the same bug I'm pretty sure, seems like you already are working on it. Thanks for the help, and have a great day/night :) and hopefully you will find a fix for it :)

**Comment by sp614x** [comment] 2021-01-06 01:34
Can't reproduce it so far. 
Tested with identical settings, same version, same shaders, new world - no luck, all mobs visible.
Made the drowned spawn particles in a wide radius to see them even if unvisible, wandered in the ocean for half an hour - all drowned still visible.
This may be hardware related, multi-core CPUs, cache synchronization or something similar.

**Comment by sp614x** [comment] 2021-01-06 01:37
Duplicate of #5016

**Closed by sp614x** 2021-01-06 01:37 UTC
