### ISSUE TITLE
Optifine Spams Output Log with errors

### ISSUE THREAD

**Issue by Enderbyte09** [sp614x/optifine#6162] opened 2021-08-14 15:29 UTC
## Description of Issue
When I start Optifine, it begins spamming the output log with thousands of the same error:
```
[OptiFine] 
java.lang.IllegalAccessException: Can not set static final java.lang.String field eav.n to java.lang.String
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
	at java.base/jdk.internal.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(UnsafeQualifiedStaticObjectFieldAccessorImpl.java:77)
	at java.base/java.lang.reflect.Field.set(Field.java:793)
	at net.optifine.reflect.Reflector.setFieldValue(Reflector.java:1277)
	at enb.updateMainMenu(GameRenderer.java:1792)
	at enb.frameInit(GameRenderer.java:1728)
	at enb.a(GameRenderer.java:1128)
	at dvp.f(SourceFile:1112)
	at dvp.e(SourceFile:728)
	at net.minecraft.client.main.Main.main(SourceFile:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
```
It keeps going even After I close minecraft because of all the errors. As I speak, it is approaching 20,000 errors.
UPDATE: This only occurs on the title screen. Going to something like the multiplayer menu will cause it to stop. Returning to the homescreen will cause it to resumethe spam. 

## Steps to Reproduce
Start the Client with Output Log enabled

## OptiFine Version
1.17.1 pre33
1.17.1 pre32

## Installation Method
I used the standalone installer

## Other Installed Mods
No other mods except this one

## Log Files/Crash Reports
 The file is too large to upload

## Prior Testing
This does not occur on vanilla versions

## Additional Information
The log file is 33 Megabytes and counting.
Update: It stopped at 22000 errors.
I know # 6160 is quite similar, but it is not the same message.

**Comment by HiItsDevin** [comment] 2021-08-14 17:39
Duplicate of #6160, eav.n is the same as the field_32272 issue there.

**Closed** 2021-08-14 17:41 UTC
