### ISSUE TITLE
[Suggestion] Presets for settings

### ISSUE THREAD

**Issue by superpowers04** [sp614x/optifine#1583] opened 2018-07-28 00:48 UTC
I think it would be nice if there was a button or an option you could mess with or a settings file you could download that has preset settings so say like low= Everything Off, Medium= Decent Graphics, And High Everything Maxed out Because people might not understand what certain settings do like "VBO's" if we had presets then people could quickly just change to the preset and BOOM. if you have a reason this shouldent be added/can be added please comment, Thank you for reading :D

**Comment by Regnander** [comment] 2018-07-28 08:32
#205

**Comment by KaiAF** [comment] 2021-03-25 22:54
This is an old ticket, going to close this as it's a duplicate of #205.

**Closed by KaiAF** 2021-03-25 22:54 UTC
