### ISSUE TITLE
Fancy Rain glitch

### ISSUE THREAD

**Issue by DeGameFinisher** [sp614x/optifine#3576] opened 2020-03-26 15:02 UTC
When your turn on the Rain and Snow to Fancy and then destroy a block while it is raining the rain will show through the blocks. Any other settings are fine to what I've seen.

**Comment by EminGT** [comment] 2020-03-26 18:40
Not an Optifine bug. This is a vanilla bug.

**Comment by realjackasterisk** [comment] 2020-03-26 22:01
Please give us more details as stated in the pinned issue #3564

**Comment by DeGameFinisher** [comment] 2020-03-27 17:35
It's NOT a vanilla glitch because when I installed the 1.15.2 optifine it
made the rain glitch.

**Comment by DeGameFinisher** [comment] 2020-03-27 17:38
So explain to me how that's a vanilla glitch.

**Comment by realjackasterisk** [comment] 2020-03-27 19:29
instead of starting an argument, can you please just give us all the details?

**Comment by sp614x** [comment] 2020-05-29 10:29
Duplicate of #3424.
Should be fixed in one of the latest previews.

**Closed by sp614x** 2020-05-29 10:29 UTC
Labels: 1.15, bug, details needed
