### ISSUE TITLE
[Crash] Optifine crashes with texture pack.

### ISSUE THREAD

**Issue by funqii** [sp614x/optifine#6230] opened 2021-09-07 16:54 UTC
When I load into Optifine 1.17.1 HD U G9 while using the PureBDCraft 1.17.1 texture pack the game loads fine, but when I load into a world the game crashes. I get an error code of 0. Everything is on minimal, fast, or off. Graphics are on fancy, and smooth lighting level is on 50%. This issue has never been a problem on vanilla versions of this game. I never got this issue on 1.16 with the same settings and everything.

The latest.log copy: 
[latest_-_Copy (1).log](https://github.com/sp614x/optifine/files/7123174/latest_-_Copy.1.log)

I hope this was enough information to help you help me fix this problem.

**Comment by fayer3** [comment] 2021-09-07 17:10
duplicate of #5918
don't set mipmaps to max or disable Terrain Animated until this is fixed.

**Closed** 2021-09-15 23:16 UTC
