### ISSUE TITLE
Is it possible to add random painting textures in 1.14?

### ISSUE THREAD

**Issue by OktayYeniTR** [sp614x/optifine#2471] opened 2019-06-12 11:49 UTC
in 1.14 the painting textures are seperated and i want to update my [More Paintings Pack](https://www.planetminecraft.com/texture_pack/vanilla-amp-optifine-tweaks/)

**Comment by sp614x** [comment] 2019-06-12 20:33
Duplicate of  #2413.

**Closed by sp614x** 2019-06-12 20:33 UTC
