### ISSUE TITLE
Optifine and Railcraft seem to conflict

### ISSUE THREAD

**Issue by karikusa** [sp614x/optifine#309] opened 2016-11-01 18:50 UTC
How can 1.10.02 edition of Railcraft has been released, or disappears in some of the texture of Railcraft conflict with Optifine, will actually when you install the Main cart became a strange state, such like a ghost you.
We can solve it exits the Optifine, so important MOD are essential to better Minecraft, the would disconnect is difficult ...
So, you very helpful if you are able to support!
By the way, I am a Japanese, since the posting by using the translation site, is worried about whether properly transmitted ...

**Comment by Viteksnake** [comment] 2016-11-02 11:23
I am from Russia and perfectly understand you. I, too, are important optifine and railcraft. Hopefully this will fix the problem.

**Comment by sp614x** [comment] 2016-11-07 17:10
Duplicate of #308.

**Closed by sp614x** 2016-11-07 17:10 UTC
Labels: mods
