### ISSUE TITLE
[BUG] Enchanted items and Shader SEUS

### ISSUE THREAD

**Issue by Demyx64** [sp614x/optifine#4509] opened 2020-07-31 13:06 UTC
## Description of Issue
Hello guys with the shader SEUS the enchanting items shine enormously , it's really very annoying.

## OptiFine Version
OptiFine 1.16.1 HD U G2 pre13

## F3 Debug Screenshot

![2020-07-31_15 05 45](https://user-images.githubusercontent.com/68199466/89037714-53c45e80-d33f-11ea-9705-8e5a57573136.png)

**Comment by sp614x** [comment] 2020-07-31 15:40
Does it happen with other shaders?

**Comment by Demyx64** [comment] 2020-07-31 15:52
i think yeah

**Comment by sp614x** [comment] 2020-07-31 22:43
Duplicate of #4512

**Closed by sp614x** 2020-07-31 22:43 UTC
Labels: 1.16, details needed, shaders
