### ISSUE TITLE
Minecraft sound doesnt work with optifine.

### ISSUE THREAD

**Issue by NBAKing0** [sp614x/optifine#755] opened 2017-07-08 13:08 UTC
Whenever I open Minecraft the sound doesn't work when I use optifine when I switch to a normal account with no ptifine it works!! please I need a fix I love optifine it helps my FPS a ton please help!!

**Comment by sp614x** [comment] 2017-07-12 16:33
Duplicate of #758

**Closed by sp614x** 2017-07-12 16:33 UTC
