### ISSUE TITLE
With new forge version, Optifine crash

### ISSUE THREAD

**Issue by xMrVizzy** [sp614x/optifine#646] opened 2017-05-16 15:48 UTC

**Comment by Kylebartaous** [comment] 2017-05-16 16:00
Be helpful if you gave a bit of info with that mine craft version, forge version, opti fine with the crash log and latest log ( witch may need to be in a zip folder.

**Comment by sp614x** [comment] 2017-05-17 10:53
Most probably duplicate of #634.
Latest preview B9 should fix it.

**Closed by sp614x** 2017-05-17 10:53 UTC
