### ISSUE TITLE
[1.17] Leveling up a cartographer causes the internal server to block for a long time

### ISSUE THREAD

**Issue by 7larson** [sp614x/optifine#6044] opened 2021-07-16 23:26 UTC
## Description of Issue
Starting with the 1.17.1 preview of Optifine (specifically Pre26, which is the first 1.17 version I've used), I have been running into an issue where after a few minutes of playing, specifically any play that involves trading heavily with Villagers, I will become unable to interact with Villagers, chests, etc. Villagers will stop moving and making sound, they won't trade with me, I become unable to open chests or pickup experience, mobs stop moving, etc. - I can still break and place blocks, but that's about it. It's not always immediate, sometimes if I right-click a villager and wait for a long period of time the menu will eventually pop, but inevitably it stops working entirely. Also noted, if I try to save and quit once this happens, it takes a _very_ long time, but it does eventually successfully save and quit with no progress lost. I was primarily playing in Creative at this time, but switching between Survival as well.

## Steps to Reproduce
1. Load into the latest release of Minecraft 1.17.1 with Optifine 1.17.1 pre26 or newer
2. Trade with Villagers & level them up

## OptiFine Version
I've tried 1.17.1 pre26 & 1.17.1 pre29

## Installation Method
Standalone installer

## Other Installed Mods
I tried both with and without shaders on, the shaders I initially used were the latest preview of BSL shaders (v8.1) but the issue persisted after removing the BSL shaders using only Optifine as well and only went away after launching Minecraft without Optifine. No mods though outside of the shaderpack.

## Log Files/Crash Reports
Didn't crash, but here's the log file, not sure if there's anything relevant in it, I couldn't really parse anything important from it
https://pastebin.com/LKYRpzvi

## F3 Debug Screenshot
I didn't think to get this before I saved & quit last time but have reproduced this about 7 times now and can do this if it would be helpful, I'll upload it as soon as I have it.

## Prior Testing
- Does this happen in Vanilla without OptiFine?
No

**Comment by Scorpion34** [comment] 2021-07-17 07:52
Yes this is a major issue for me as well I don't think this happens on servers but certainly client-side pretty frustrating to deal with,

**Comment by KaiAF** [comment] 2021-07-17 18:37
I can't reproduce this. Probably best to send a f3 debug menu screenshot.

**Comment by Scorpion34** [comment] 2021-07-18 10:30
> I can't reproduce this. Probably best to send a f3 debug menu screenshot.

Well I never really got an official crash report it never gives a not responding it just keeps playing breaking blocks and interacting with villagers isn't possible and the only way to end the game is by hard closing it with task manager in MultiMC it says it's 3000 ms behind I can try reproducing it today my world crashed around 5 times before I was forced to use vanilla.

**Comment by eggaroonie** [comment] 2021-07-19 18:31
I am experiencing this as well. It seems to occur when leveling up a cartographer from 2-3. The vanilla game was having the same issue, it was being caused by the game trying to locate a new woodland mansion to generate a map to. This seems to have been patched in vanilla, so moderators on Mojang's forums are now saying that it's an issue with optifine.

**Comment by eggaroonie** [comment] 2021-07-19 18:37
You may also need to level up several villagers in order for the bug to occur, it doesn't seem to happen when leveling up the first one.

**Comment by fishy850** [comment] 2021-08-20 16:47
Hey so i have the exact same problem on my singleplayer world 
![2021-08-20_18 42 13](https://user-images.githubusercontent.com/89258529/130266804-4a0dc4d8-5ff0-4a80-852a-ac75066cc32d.png)
i don't know if this helps but ye i try

**Comment by sp614x** [comment] 2021-08-20 22:00
The internal server tick is 1600ms, somethings is slowing it down.

**Comment by sp614x** [comment] 2021-08-21 09:23
Leveling up a cartographer causes the game to search for a woodland mansion. This needs to load (and save?) about 130k chunks. 
The chunk saving is the one blocking the server thread.

**Comment by fishy850** [comment] 2021-08-21 18:03
just a question does this transport over to a server or is this not possible?

**Comment by sp614x** [comment] 2021-08-22 13:28
Vanilla has the same problem, but the delay is smaller, around 1 sec.

**Comment by eggaroonie** [comment] 2021-08-23 01:59
> Vanilla has the same problem, but the delay is smaller, around 1 sec.

Vanilla was having this issue to a similar extent in [1.14.4](https://bugs.mojang.com/browse/MC-126244). Not sure what they did to fix it.

**Comment by sp614x** [comment] 2021-08-23 21:14
The `"/locate mansion"` command blocks for 2s, while leveling a cartographer blocks for several minutes. The cartographer is doing the wooden mansion search differently.

**Comment by sp614x** [comment] 2021-08-24 20:05
Fixed, coming in next preview

**Closed by sp614x** 2021-08-24 20:05 UTC
Labels: details needed, performance, 1.17
