### ISSUE TITLE
Water texture. The water is white when kelp or other things are on it

### ISSUE THREAD

**Issue by MegaterioPampeano** [sp614x/optifine#6671] opened 2022-03-11 17:22 UTC
## Description of Issue
The top layer of water is texture white when kelp, sea grass of half slabs are in it

## Steps to Reproduce
1. Place bottom half slabs under the top layer of water
2. Or kelp or seagrass

## OptiFine Version
HD U H6 pre1

## Installation Method

standalone installer

## Other Installed Mods
none
![2022-03-11_14 19 07](https://user-images.githubusercontent.com/101420332/157916270-289ac4bf-e3e0-40de-87f8-48f47f5f1b0d.png)
![2022-03-11_14 18 46](https://user-images.githubusercontent.com/101420332/157916302-916884f0-e8f7-4910-9193-b966fc4bd640.png)

**Comment by Ari-RERA-43** [comment] 2022-03-11 18:06
Duplicate of #6646. Close this issue.

**Closed** 2022-03-11 18:15 UTC
