### ISSUE TITLE
Optifine and Minecolonies

### ISSUE THREAD

**Issue by Kocytos** [sp614x/optifine#1388] opened 2018-05-03 17:33 UTC
minecolonies-universal-1.12.2-0.8.8147
OptiFine_1.12.2_HD_U_D2

Minecolonies uses shemantics to build houses. You can see the house before you place it and before the builder actually starts to build it. But if I use Optifine it looks like this:

![2018-05-03_17 38 35](https://user-images.githubusercontent.com/28514610/39592987-d5bd7a88-4f08-11e8-9120-cd8616db82fa.png)

it should normally look like this:

![2018-05-03_19 32 25](https://user-images.githubusercontent.com/28514610/39593006-dfffb574-4f08-11e8-916b-b60e732e05c5.png)

**Comment by Kocytos** [comment] 2018-05-03 17:55
i found the problem. when i use a shader i dont see it...

**Comment by sp614x** [comment] 2018-05-18 10:12
Duplicate of #1368.

**Closed by sp614x** 2018-05-18 10:12 UTC
