### ISSUE TITLE
Lodestone Compass enchanment glint is bugged 

### ISSUE THREAD

**Issue by AgaBe2** [sp614x/optifine#6202] opened 2021-08-31 15:52 UTC
## Description of Issue
When a compass is locked into a lodestone, the enchantment glint becomes super small and it kinda shows the copies of itself.

## Steps to Reproduce
1. Get a compass
2. Right click a lodestone

## OptiFine Version
OptiFine HD U G9 and possibly prior versions

## Installation Method
I double clicked on the JAR file

## Other Installed Mods
No other mods

## Prior Testing
This is not an issue without OptiFine. Default minecraft doesn't have this problem.

## Additional Information
![2021-08-31_18 45 23](https://user-images.githubusercontent.com/89860135/131535164-c920470d-00c9-4032-8632-b464df067658.png)

**Comment by fayer3** [comment] 2021-08-31 17:31
duplicate of #6097

**Closed** 2021-09-03 17:32 UTC
