### ISSUE TITLE
[Optifine with Shaders] Diagonal glitched textures when activated shaders

### ISSUE THREAD

**Issue by xicromok** [sp614x/optifine#7059] opened 2022-08-08 23:33 UTC
## Description of Issue
I have always played minecraft with shaders normally on my computer. Yesterday, for some reason when reinstalling the game because after so long I was able to buy it, when starting from the official launcher and doing the usual installation of Optifine and any shader, my game looks like this:

![screenshot1](https://user-images.githubusercontent.com/110861624/183531827-99290e34-6c08-4f1c-9011-43b96c19d0ad.jpg)
![screenshot2](https://user-images.githubusercontent.com/110861624/183531835-01ab2aac-3948-492f-800e-d5560d37d25f.jpg)

I have ruled out that it was a shaderpack error, because I even get the error by activating the internal shaders. I have also ruled out that it is a launcher error, because I have tried uninstalling the game and then installing it with Tlauncher; unsuccessfully.

I remember that I had to update the software of my video card (AMD Software: Adrenalin Edition) that same day, but I cannot remember specifically if it was after that that my game changed.
I'm only posting to find out if it's possible that the same thing has happened to someone, since I haven't found anything similar on Google.

## Steps to Reproduce
1. Open graphics options
2. Enable shaders

## OptiFine Version
Any version.

## Installation Method
I droped the JAR file into my "mods" folder.

## Fabric/Forge Version
Any Forge version.

## Other Installed Mods
No other mod installed.

## Log Files/Crash Reports
No crash reports. The error is graphical while playing. 

## F3 Debug Screenshot

![image](https://user-images.githubusercontent.com/110861624/183535375-ccc6c559-e656-489d-8358-dfd83be25973.png)

**Comment by fayer3** [comment] 2022-08-09 00:03
don't see the photos, but sounds like a duplicate of #7043

**Comment by xicromok** [comment] 2022-08-09 00:08
> don't see the photos, but sounds like a duplicate of #7043

unfortunately I have posted the post without finishing it by mistake and I was editing to complete it. But it's true, it's the same mistake. Should I delete the post?

**Comment by fayer3** [comment] 2022-08-09 00:13
just close the issue

**Closed** 2022-08-09 00:14 UTC
