### ISSUE TITLE
[Bug] 1.15.2 Pre-12 a bug on glowing effect

### ISSUE THREAD

**Issue by youwen233** [sp614x/optifine#3652] opened 2020-04-02 05:48 UTC
## Description of Issue
**This bug may caused by shaders because when I turn off the shaders, this bug can't be recurrent.**
(my shader pack is SEUS renewed 1.0.1)
I can't see the glowing entities or blocks, if they have glowing effect, the game screen will be crazy.
This is the screen that i saw the glowing blocks
![Screenshot](https://dl.alidingtalk.fun/Temp/Optibug2.png)
And this is the screen that I moved my mouse
![Screenshotttttt](https://dl.alidingtalk.fun/Temp/Optibug1.png)

I switched to the internal shader, and if I see the glowing blocks or entities, the game screen will like this, all the chests, entities and other blocks will be crazy too.This is the screenshot
![bug3](https://dl.alidingtalk.fun/Temp/Optibug4.png)
Next screenshot is the screen that I turned off the shaders
![bug5](https://dl.alidingtalk.fun/Temp/Optibug5.png)
## Steps to Reproduce
1. Loaded a shader
2. Make a entity or block have glowing effect

## OptiFine Version
Optifine 1.15.2 G1 Pre-12

## Installation Method
I installed Optifine by the installer, I didn't install forge or fabric loader.

## Log Files/Crash Reports
I loaded the shader at 13:34:03
[Latest.log](https://pastebin.com/sMLAXJH7)

## F3 Debug Screenshot
![Screenshotf3](https://dl.alidingtalk.fun/Temp/Optibug3.png)

**Comment by sp614x** [comment] 2020-05-29 10:59
Duplicate of #3662.

**Closed by sp614x** 2020-05-29 10:59 UTC
Labels: 1.15, glowing, shaders
