### ISSUE TITLE
Broken Pipe Error while using Optifine [1.8.9]

### ISSUE THREAD

**Issue by xiphiasxiphian** [sp614x/optifine#4620] opened 2020-08-16 20:16 UTC
Description of Issue
Whenever i am in a server (e.g. Hypixel) as soon as i try go from one world to another (e.g. bedwars game to bedwars game), i will eventually get the error after doing it another (5 mins) Error while Write(): Broken Pipe

Steps to Reproduce
1 - Play game normally
2 - Get error randomly without warning while changing server

OptiFine Version
1.8.9 I7 (Tried with L5, I3, H7: error the same on all)

Installation Method
put the .jar into mods folder, also tried extracting into mods folder, error the same either way

Fabric/Forge Version
1.8.9 - 11.15.1.2318

Other Installed Mods
https://pastebin.com/hfWAysVf

 Log Files/Crash Reports
Entire Log: https://pastebin.com/rBDG0fKZ
Error Thread: https://pastebin.com/n42RVMK5
[Nothing in crash-reports]

F3 Debug Screenshot
https://user-images.githubusercontent.com/67584549/90343099-66a88580-e005-11ea-9940-2ea52e3ae7b2.png

Testing
Happens with Optifine, however as soon as it is removed doesnt happen, even with all the other mods
Doesnt happen in vanilla
Already tried individually introducing mods back and nothing went wrong until optifine was there. with no other mods and optifine still happens

ive already isolated the issue to optifine, however the error message tells me nothing about what is wrong. I do use linux (pop_os! from ubuntu 20.04 lts) which could be something

.

**Comment by DitDitGitHub** [comment] 2021-01-24 14:15
Same error here, on Ubuntu too. @sp614x please look into this, it causes us to not be able to play. After my testing it seems to only happen on Hypixel, so I'm gonna post a bug report there too.

**Comment by SealsRock12** [comment] 2021-06-07 18:49
This happens for me too.

**Comment by KaiAF** [comment] 2021-06-07 20:39
I was looking at the log and I looked up the error. It seems like this is caused by the Minecraft server? Are you able to play Singleplayer (If this is an issue still). @xiphiasxiphian

**Comment by xiphiasxiphian** [comment] 2021-06-07 20:52
Single player works perfectly fine, it's just on certain servers switching world's crashes the game accordingly

**Comment by KaiAF** [comment] 2021-06-07 20:59
Odd. Looking up the error, it really looks to be caused by servers. Because of this I am going to close the issue

**Closed by KaiAF** 2021-06-07 20:59 UTC

**Comment by TheKodeToad** [comment] 2021-11-16 12:00
I have opened an issue that is more likely to fixed, as it explains the cause of this problem.
