### ISSUE TITLE
[1.15] Stairs lighting

### ISSUE THREAD

**Issue by funbear** [sp614x/optifine#3990] opened 2020-05-24 08:24 UTC
#3377  OptiFine Version
Optifine HDG1_pre18 Ultra

## Installation Method
with installer jar

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
https://prnt.sc/smqgr1

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? no

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by TheoCGaming** [comment] 2020-05-24 23:17
What shaders do you use if any?

**Comment by naeqirelle2020** [comment] 2020-06-07 06:18
cannot reproduce in pre-22 most likely fixed? 

![2020-06-07_07 17 52](https://user-images.githubusercontent.com/63185833/83961835-11c2f300-a88f-11ea-903f-14c893abb381.png)

**Comment by sp614x** [comment] 2020-06-07 09:28
Should be fixed in latest preview.

**Closed by sp614x** 2020-06-07 09:28 UTC
Labels: 1.15, lighting
