### ISSUE TITLE
[Suggestion] change the site for banner capes from miners need cool shoes

### ISSUE THREAD

**Issue by Eilux** [sp614x/optifine#2672] opened 2019-07-24 21:20 UTC
I think that changing sites is a good idea because miners need cool shoes has not said or done anything since 2014. As a result capes are unable to use the 1.12 banner colors or the 1.14 globe banner pattern.

**Comment by Eilux** [comment] 2019-07-24 21:24
The only other banner creators I know of are [planet minecraft](https://www.planetminecraft.com/banner/) and[ minecraft tools](https://minecraft.tools/en/banner.php).

**Comment by realjackasterisk** [comment] 2019-07-24 21:50
dupe of both #2146 and #2476

**Closed** 2021-04-02 19:12 UTC
Labels: website
