### ISSUE TITLE
Optifine not installing

### ISSUE THREAD

**Issue by Tsutome** [sp614x/optifine#906] opened 2017-09-22 23:54 UTC
I apologize if this is a more common error than I realize, but I've been looking for a few days now and have decided to come seeking help. 

Usually I never have any issues with downloading Optifine on Minecraft on my Desktop that runs on Windows 7. A simple installation of the .jar, opening it with Java, and I was pretty much set.

Recently, I got a new laptop which runs on Windows 10. I've appropriately installed the latest Java update, downloaded the Minecraft client/launcher along with version 1.12.2, and was ready to install Optifine. Unfortunately, whenever I try to install Optifine via opening the OptiFine_1.12.2_HD_U_C5.jar, all I get is a Command Prompt that remains open for less than half a second which says 

"Error: Could not find or load main class C:\User\Tsutome\Downloads\New folder\OptiFine_1.12.2_HD_U_C5.jar"

Any help and/or guidance is very much appreciated. Again, sorry if this is just a silly issue with an easier fix than I anticipated!

**Comment by sp614x** [comment] 2017-09-23 09:45
Duplicate of https://github.com/sp614x/optifine/issues/763

**Comment by sp614x** [comment] 2017-09-23 09:46
Possible fix: http://www.softpedia.com/get/Others/Miscellaneous/Jarfix.shtml

**Closed by sp614x** 2017-09-23 09:46 UTC
