### ISSUE TITLE
[Bug] Optifine not compatible with Forge in 1.20.1

### ISSUE THREAD

**Issue by BobSinclair** [sp614x/optifine#7455] opened 2023-07-01 12:35 UTC
## Description of Issue
I am running Java Minecraft and have Forge 1.20.1-47.0.35 with Controllable and Framework (both up to date and working perfectly fine). I am trying to install Optifine 1.20.1 pre7 from the mods loader screen with the intent to install BSL shaders, but comes up with an error. Removing Optifine resolves the issue.

## Steps to Reproduce
1. Launch MC Java from the MC launcher with the Forge 1.20.1 installation. Go to the mods loader screen on the main menu and drag Optifine's Java to the folder.
2. Close and reopen the MC launcher.
3. Orange MC screen briefly shows before showing the MC launcher screen and an error message "Error, Game crashed, An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience. Exit code: 1"

## OptiFine Version
preview_OptiFine_1.20.1_HD_U_I5_pre7

## Installation Method
Both dropped the JAR file into my mods folder and also opened the JAR file separately. Both ways produce the error (although the second method, running it instead of dragging and dropping, produces a Optifine installation on the main MC launcher menu but does not work with Forge ie, there is no mod option on the MC main menu).

## Fabric/Forge Version
1.20.1-forge-47.0.35

## Other Installed Mods
Controllable 1.20.1 with Framework 0.6.5
BSL shaders 1.20.1 (currently just sitting in the shader folder waiting to for Optifine to work)

## Log Files/Crash Reports
"Error, Game crashed, An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience. Exit code: 1"

## Prior Testing
Yes, MC works fine with Forge, Vanilla, Controllable, etc. As soon as Optifine is introduced, it errors.

## Additional Information
Please fix this! I just wanna play some pretty MC.

**Comment by SilentWhisperer** [comment] 2023-07-01 16:28
iirc Controllable isn't compatible with Optifine rn

**Comment by Lolothepro** [comment] 2023-07-01 23:08
Duplicate of #7451

**Comment by BobSinclair** [comment] 2023-07-02 15:24
> 

Is it an issue on Optifine's or Controllable's end?

**Comment by Jiingy** [comment] 2023-07-16 21:37
Closing this issue as it is a duplicate of #7451 . Thank you @Lolothepro

**Closed by Jiingy** 2023-07-16 21:37 UTC

**Comment by EternalCoder454** [comment] 2026-04-03 20:30
Dont use optifine, use embeddium and oculus
