### ISSUE TITLE
JEI and Optifine

### ISSUE THREAD

**Issue by MeinKraft** [sp614x/optifine#2748] opened 2019-08-10 04:43 UTC
preview_OptiFine_1.14.4_HD_U_F4_pre2
Forge 28.0.45
JEI 1.14.4.6.0.010

With JEI and Optifine installed. When press E for inventory the game crashes. Remove Optifine and all is OK.  I reported to JEI, he said to report here also

Crash Report https://pastebin.com/H5HmtrJf

**Comment by pentyum** [comment] 2019-08-10 05:09
Same problem, and my optifine is preview_OptiFine_1.14.4_HD_U_F4_pre2.jar, jei is 1.14.4.6.0.0.10, forge is 28.0.45.

**Comment by Studio528-real** [comment] 2019-08-10 05:10
quick random question, have you tested without JEI instead?

**Comment by MeinKraft** [comment] 2019-08-10 05:12
The preview of optifine works fine without JEI for me. Been using it for a while with shaders and forge with other mods like biomes o'plenty and hywla etc

**Comment by PseudoResonance** [comment] 2019-08-10 05:18
This seems to be a bug directly related to rendering changes made by OptiFine conflicting with the way JEI is rendering it's screen, as the crash report indicates. Looks like a simple fix from the crash report, but I haven't seen OptiFine's source, so I have no idea. Both mods work great alone, but opening the inventory crashes the game immediately.

**Comment by Exopandora** [comment] 2019-08-10 10:26
This issue is most likely a duplicate of #2737

**Comment by jrpryer** [comment] 2019-08-11 21:35
Just want to add my comment that the crash occurred for me as well with both JEI and Optifine. Seems like we are awaiting an update from either parties, but hopefully Optifine will have an answer first. 
Reference: 
JEI Optifine Crash #1668 - https://github.com/mezz/JustEnoughItems/issues/1668

**Comment by FN343** [comment] 2019-08-12 00:12
Yeah, same crash happened with the newest JEI version, Optifine F4 pre2, and Forge 28.0.45.
I'm going to try them again but with the full release of Optifine which is F3 (currently)…

Ok, um, now it's saying that the file is unsupported during the startup, no crash, but once I got to the main menu, Optifine isn't even on the mod list as if it was never installed...
They showed me to check the latest log, here it is...
[https://pastebin.com/5hjvY2bp](url)

Shall I report this as a whole new standalone issue?

**Comment by PseudoResonance** [comment] 2019-08-12 04:20
OptiFine F4 pre2 is the pre-release of a Forge compatible version of OptiFine. OptiFine F3 cannot be loaded with Forge, and was never intended to be, as the changelog states `internally compatible with Forge 28.0.23 (can't be installed yet)` Unfortunately, it looks like we might have to wait for OptiFine F4 or later to fully release before this issue will be fixed.

**Comment by FN343** [comment] 2019-08-12 05:18
Oh, that sucks that Optifine can't work with Forge right now. I guess I'll have resort to older versions of Minecraft, but at least there's much more mods out there anyways...

**Comment by PseudoResonance** [comment] 2019-08-12 21:25
If you're desperate to have modded 1.14.4 with Forge, you can always try out Fabric with OptiFabric. It's buggy and unsupported, but that's what I've been dealing with until OptiFine can finish updating. In my case, I'm just using vanilla enhancing mods though and still playing on a vanilla server, so it works well enough. Fabric doesn't have the greatest selection of gameplay changing mods.

**Comment by FN343** [comment] 2019-08-12 21:38
Well, I'm not that desperate and knowing that there's barely any mods for 1.14.4, I'm just looking to make a very light client-sided modpack so I can play on a friend's realm. Basically, it's just only a few performing enhancing mods and other convenient client mods like you said (JEI, Optifine, FastFurnace/Workbench, Hwyla, etc.). I'll wait for a while until they fix the errors, I'm also waiting for Inventory Tweaks and JourneyMap to get up to that version as well, but I'm sure it'll take a while, though, I can wait, hahaha

**Comment by Maxime51** [comment] 2019-08-20 22:35
Forge = 1.14.4-forge-28.0.51
Optine = preview_OptiFine_1.14.4_HD_U_F4_pre2
Just Enough Item = jei-1.14.4-6.0.0.10

"Optifine" make "Just Enough Item" crash when i press E in game the game crash saying this msg :

The game crashed whilst rendering ingredient
Error: java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.ItemRenderer.func_191961_a(Lnet/minecraft/client/renderer/model/IBakedModel;Lnet/minecraft/item/ItemStack;)V from class mezz.jei.render.ItemStackFastRenderer

[crash-2019-08-21_00.31.14-client.txt](https://github.com/sp614x/optifine/files/3522866/crash-2019-08-21_00.31.14-client.txt)

i tryed everything i could and my final conclusion is "Optifine" who make the game crash because without him everywork (even with +16 Mods)
i tryed older version of forge until they don't support "Optifine" for 1.14.4 but still crash
also tryed the older version of Just Enough Item who is the  jei-1.14.4-6.0.0.9 but still crash

Ty for your awesome job ! i was gonna give 10$ to get the Cape but i think i need this stuff to be done before 👍

**Comment by Bvioto** [comment] 2019-08-26 05:23
I have experimented the same issue: 

[crash-2019-08-26_00.15.35-client.txt](https://github.com/sp614x/optifine/files/3539506/crash-2019-08-26_00.15.35-client.txt)

JEI (jei-1.14.4-6.0.0.10)
Optifine (preview_OptiFine_1.14.4_HD_U_F4_pre2)
Forge (forge-1.14.4-28.0.55-installer)

The game crashes when opening inventory.

**Comment by sp614x** [comment] 2019-08-28 00:05
OptiFine 1.14.4_HD_U_F4_pre3
 - fixed Forge access transformers (#2737)

**Closed by sp614x** 2019-08-28 00:05 UTC

**Comment by MeinKraft** [comment] 2019-08-28 00:23
Thank you also

**Comment by Cr4fTJuNkiE** [comment] 2019-08-29 03:32
Aaaay... Look at that! Thank You!!!

**Comment by FN343** [comment] 2019-08-31 07:01
Ok, you are sofa-king-awesome. 😍😍

**Comment by johnnyboii95** [comment] 2019-09-03 02:28
Does optifine work with JEI now .? If not what's the latest version of Minecraft that can run both optifine and JEI

**Comment by Studio528-real** [comment] 2019-09-03 02:55
they work together in 1.14.4

**Comment by MeinKraft** [comment] 2019-09-03 03:03
use the 1.14.4 preview version OptiFine 1.14.4 HD U F4 pre3

**Comment by jakey1995abc** [comment] 2020-12-12 04:58
Can you fix this for 1.12.2? You released an update a few days ago for it but managed to ignore this widespread issue...
