### ISSUE TITLE
How to make 3D models support nbt judgment

### ISSUE THREAD

**Issue by Wei-Boss** [sp614x/optifine#632] opened 2017-05-10 10:03 UTC
Hello!sp614x.
Can 3D models use nbt to judge?
such as:
Nbt.display.name: abc
My English is not good, sorry XD

**Comment by sp614x** [comment] 2017-05-10 11:27
Item 3D models are currently not supported.
Duplicate of https://github.com/sp614x/optifine/issues/146

**Closed by sp614x** 2017-05-10 11:27 UTC
