### ISSUE TITLE
Rendering doesn't work unless I update the chunks?

### ISSUE THREAD

**Issue by BinarryCode** [sp614x/optifine#4307] opened 2020-07-09 18:27 UTC
..I have no idea why this is happening. Basically: everything in a chunk is invisible until I update the edge of it, or where part of it is (as in, delete the blocks, place blocks, etc). I'm not sure if it's my fault or the server's fault, but this screenshot was taken in a Minehut server.
![2020-07-09_13 41 56](https://user-images.githubusercontent.com/53833277/87076350-a05cc400-c1ef-11ea-9bde-a4f0586507a7.png)

My PC specs:
Windows 10
Intel Core Duo CPU E8600 @ 3.33 GHz
64-bit OS, x64-based processor

**Comment by BinarryCode** [comment] 2020-07-09 18:33
Since I can't update the name of this:

This is a bug with the 2nd preview of 1.16.1 Optifine

**Comment by Exolirating** [comment] 2020-07-09 20:44
Have the same issue except mine I cant even update the chunks. have to force load each one of them.

**Comment by sdhsako** [comment] 2020-07-10 11:15
This happens to me too, I have to restart the game to fix it.

**Comment by sp614x** [comment] 2020-07-10 12:34
Can you post a debug screenshot (F3)?

**Comment by sdhsako** [comment] 2020-07-10 12:37
it will take awhile for me to get that again since its quite rare to get but when i get it i will

**Comment by Exolirating** [comment] 2020-07-10 13:58
This also happens in single player worlds

**Comment by sp614x** [comment] 2020-07-10 14:24
Running with or without shaders?

**Comment by sp614x** [comment] 2020-07-10 15:03
Relevant #3506, #4241

**Comment by cs127** [comment] 2020-08-03 17:07
Still happening in the G2 release

**Comment by Gavins38** [comment] 2020-08-07 01:35
yep i confirm its still happening on the G2 release
Even in older versions of optifine skins take a while to load OR dont load at all so most of the server is just steve and alex on hypixel

**Comment by sp614x** [comment] 2020-08-26 16:11
Duplicate of #4261

**Closed by sp614x** 2020-08-26 16:11 UTC
Labels: 1.16, chunks, multiplayer
