### ISSUE TITLE
Mobs with glowing parts (enderman, spider, cave spider, etc.) have their whole body glow in the dark.

### ISSUE THREAD

**Issue by chasejsutton49** [sp614x/optifine#3712] opened 2020-04-08 18:45 UTC
Any mobs that have a small part of their body glow (Endermen's eyes, spiders' eyes, cave spiders' eyes, etc.) have their entire bodies glow, besides their eyes.
![2020-04-02_11 48 46](https://user-images.githubusercontent.com/19761194/78820825-13ab2b80-799e-11ea-95bc-fda49b7492a4.png)
![2020-04-02_11 53 23](https://user-images.githubusercontent.com/19761194/78820908-32112700-799e-11ea-8209-8dc77de54b21.png)
![2020-04-02_11 54 19](https://user-images.githubusercontent.com/19761194/78820950-40f7d980-799e-11ea-941b-c8ef4dade762.png)
I don't have any screenshots of entire Endermen glowing, but it's a thing. And Phantoms more than likely.
This applies when using many unique shader packs, so it's hard to tell if it's an issue with the shaders or Optifine, or most likely it's due to vanilla changes. No resource packs other than the Programmer Art.

Optifine 1.15.2 HD U G1 pre13

Installed via .jar from optifine.net

**Comment by naeqirelle2020** [comment] 2020-06-08 08:45
Not able to reproduce this behaviour in the latest preview

Packs i tested with:

Oceano Shaders
SEUS Renewed
Sildurs Vibrant 1.27
Chocapic 8.1
Chocapic 7.1.1
BSL 7.1.05

Most likely fixed in a later preview

**Comment by chasejsutton49** [comment] 2020-06-08 12:36
I can't reproduce either, and I think it is fixed. The shaders used in these screenshots were KUDA shaders, but it also applied to continued shaders too. But I think it's fixed.

**Comment by sp614x** [comment] 2020-06-09 08:31
Should be fixed in latest preview.

**Closed by sp614x** 2020-06-09 08:31 UTC
Labels: 1.15, CEM
