### ISSUE TITLE
[1.15.2] Selected block borders do not show with shaders

### ISSUE THREAD

**Issue by michaelpinnoo** [sp614x/optifine#3708] opened 2020-04-08 14:55 UTC
**Problem**
When using any sildurs shaders (not tested any other ones), the black outline on blocks when looking at them does not render or is very faint and glitchy.

**Optifine version**
OptiFine 1.15.2 HD U G1 pre13

**Comment by TwoySenpai** [comment] 2020-04-13 22:57
Same for me, SEUS shaders and Sildurs Vibrant

**Comment by meagle01** [comment] 2020-04-18 16:13
same

**Comment by MrDangless** [comment] 2020-05-01 05:41
I have the same issue, I have noticed that if you use a different version of the game it fixes, might also be the optifine version but they both change at the same time so I have know way of knowing until a new optifine version comes out.

**Comment by seeruk** [comment] 2020-05-03 11:46
@MrDangless It's a bug in the 1.15.x versions of OptiFine.

Still experiencing this in pre15, but I've noticed it's only when facing roughly south east, I can see block outlines in all other directions.

**Comment by Aidowl** [comment] 2020-05-09 03:08
Can confirm this is still an issue in 1.15.2 pre16
I've had this problem in Sildurs, BSL, Chocapic and SEUS

**Comment by Aidowl** [comment] 2020-05-16 03:09
Still an issue in 1.15.2 HD U G1 pre17.

**Comment by Aidowl** [comment] 2020-05-23 10:58
Still an issue in 1.15.2 HD U G1 pre18.

**Comment by sp614x** [comment] 2020-05-30 12:33
Duplicate of #3600.

**Closed by sp614x** 2020-05-30 12:33 UTC
Labels: 1.15, shaders, todo
