### ISSUE TITLE
1.14.3 Startup crash due to custom path

### ISSUE THREAD

**Issue by Ketoyu** [sp614x/optifine#2554] opened 2019-06-28 08:38 UTC
Log: https://paste.ee/p/gA4bo

I've redirected my .minecraft appdata folder (via symbolic link) to a directory containing [ and ], which seem to be considered illegal characters whilst the OptiFine profile fetches class_cache.zip. Redirecting it instead to a directory conforming to those rules does work around the issue.

I've posted it anyway because the vanilla profile doesn't have an issue with it and keeping my installation in the conflicting directory helps me keep all my stuff in one tidy place when I have to do OS reloads, if it's possible to resolve the issue.

**Comment by sp614x** [comment] 2019-06-28 08:43
Duplicate of #2544

**Closed by sp614x** 2019-06-28 08:43 UTC

**Comment by sp614x** [comment] 2019-06-28 10:09
Ninja updated 1.14.3_HD_U_F1 with a bugfix.
Please redownload it and test again.
