### ISSUE TITLE
[Bug] Chunks only load around world spawn

### ISSUE THREAD

**Issue by blueberryperson5** [sp614x/optifine#4568] opened 2020-08-06 18:27 UTC
When loading into a world, chunks only start loading around the world spawn. If the player isn't near the world spawn, everything will freeze, and you'll have to do /setworldspawn or /kill to load chunks around the player again. Sometimes it gives an OpenGL error. 

To reproduce:
1. Set the render distance to 37 or higher

Optifine Version:
Optifine_1.16.1_HD_U_G2

Installation Method:
The bug occurs with fabric, forge, and standalone. 

Fabric Version:
fabric-loader-0.9.0+build.204-1.16.1
Forge Version:
1.16.1-forge-32.0.106

Optifabric Version:
optifabric 1.1.0-beta2

Installed Mods:
fabric-api-0.16.2+build.385-1.16.1

A log file of entering a world with this bug and settings spawnpoints:
[latest.log](https://github.com/sp614x/optifine/files/5037061/latest.log)

F3 Menu:
![image](https://user-images.githubusercontent.com/38706990/89567564-bf427c00-d7d6-11ea-8741-0d4434cb324f.png)

Prior Testing:
When I set the render distance to 37 in options.txt in vanilla minecraft, the bug does not occur. 

Forge/Fabric:
This bug occurs without any other mods installed using every other installation method. 
This bug occurs standalone. 
This bug does not occur in vanilla.

**Comment by sp614x** [comment] 2020-08-24 16:17
Currently Render Distance above 37 may cause the world to be loaded only partially.

**Comment by sp614x** [comment] 2020-08-26 16:11
Duplicate of #4261

**Closed by sp614x** 2020-08-26 16:11 UTC
Labels: 1.16, bug, chunks, interesting, rendering
