### ISSUE TITLE
[1.15.2 pre-30] Unable to join multiplayer servers or singleplayer worlds.

### ISSUE THREAD

**Issue by Whooshy** [sp614x/optifine#4142] opened 2020-06-21 21:57 UTC
## Description of Issue
Game crashes when loading singleplayer worlds or joining servers.

## Steps to Reproduce
Upon loading a singleplayer world, the progress screen indicates a successful load but then the game displays "saving world" before crashing. Something similar happens when trying to connect a multiplayer world, with every step of the process (connecting to server, joining world, encrypting, etc.) being successful, but then the game briefly shows "saving world" before crashing.

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre30

## Installation Method
Extracted it and added the .jar to minecraft.jar using MultiMC.

## Log Files/Crash Reports
https://paste.ee/p/1HtGQ

## F3 Debug Screenshot
N/A

## Prior Testing
I can confirm this didn't happen on a standard build of the game, and also didn't happen on my previous OptiFine 1.15.2 installation (pre18).

## Additional Information
Used default OptiFine settings, no shaders or resource packs were currently enabled.

**Comment by Deviouslrd** [comment] 2020-06-21 21:59
Try it with the updated pre30. that may have been fixed with the ninja update.

**Comment by sp614x** [comment] 2020-06-21 22:03
Fixed with a ninja-update, please download pre30 again.
Duplicate of #4141.

**Closed by sp614x** 2020-06-21 22:03 UTC
Labels: 1.15, crash

**Comment by Whooshy** [comment] 2020-06-21 22:04
Can confirm, the crash no longer exists.
