### ISSUE TITLE
Chunk loading bug - optifine 1.15.2

### ISSUE THREAD

**Issue by tyleramma75** [sp614x/optifine#4034] opened 2020-06-05 18:11 UTC
When using Optifine chunks wont load beyond a small area.

**Comment by realjackasterisk** [comment] 2020-06-05 22:08
this is a very, very well known issue.

duplicate of way too many open issues at the moment (use this to search: `is:issue is:open label:chunks label:1.15 `)

**Closed by realjackasterisk** 2020-06-05 22:08 UTC
