### ISSUE TITLE
[1.15.2 Bug] No block breaking animation (with Sildur's Shaders)

### ISSUE THREAD

**Issue by LukasAppleFan** [sp614x/optifine#3857] opened 2020-05-04 13:28 UTC
## Description of Issue
When breaking blocks in survival mode, I do not see the block-breaking animation. Only with Sildur's Shaders from what I can see.

![2020-05-04_15 13 02](https://user-images.githubusercontent.com/41242166/80970348-49b3c200-8e1b-11ea-936c-fc9d36261c93.png)

## Steps to Reproduce
1. Enable Sildur's Shaders
2. Break some blocks

## OptiFine Version
preview_OptiFine_1.15.2_HD_U_G1_pre15

## Installation Method
Standalone

## F3 Debug Screenshot

![2020-05-04_15 13 08](https://user-images.githubusercontent.com/41242166/80970520-95666b80-8e1b-11ea-8099-be4a19f641f1.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No

## Additional Information
It seems to only happen with Sildur's Shaders.

**Comment by EdgyPotato** [comment] 2020-05-04 13:36
Duplicate of #3600

**Comment by LukasAppleFan** [comment] 2020-05-04 13:42
I did not see it, it's from 28 Mar.

**Comment by HiItsDevin** [comment] 2020-05-05 06:53
> I did not see it, it's from 28 Mar.

I'd suggest you start utilizing the search function.

**Comment by sp614x** [comment] 2020-06-07 15:57
Duplicate of #3600

**Closed by sp614x** 2020-06-07 15:57 UTC
Labels: 1.15, shaders
