### ISSUE TITLE
Crashing.

### ISSUE THREAD

**Issue by Ta-hg** [sp614x/optifine#643] opened 2017-05-15 19:05 UTC
I'm going to start this off with what i did before just so you can get the just of it. I was using optifine and the MinecraftCapes Mod created by james090500 and everything was working fine and dandy. So about two days ago my computer was really slow so i shut it down and turned it on again, but when it turned on it said it was trying to figure what the problem was. This had happened before and i knew that this meant that no matter what, i would have to reset my computer. So i reset my computer and i downloaded java, forge, minecraft, optifine, and minecraftcapes mod. I started up minecraft and played the version of the game that i had to play before installing forge(which was 1.11.2). Then i play the forge version before putting the mods into the mods folder. So once i insert the mods into the mods folder in .minecraft it still allows me to start minecraft and go to settings and stuff like that. But when i go to multiplayer or single player and try to join/create a world it automatically crashes the game. Now i actually currently work for the  MinecraftCapes mod and i gave the crash report to james090500 and he said that the crashing wasn't because of the capes mod, but because of optifine. I tried deleting optifine and downloading it again but the same effect happened. But what i'm confused about is that when only one of the mods is in the mods folder the game runs it and i can go on servers. And both of the mods have always been compatible with each other because James knows that a lot of people use optifine and also use the capes mod.
Here is the crash report i receive. Also here is the website to the capes mod, just in case it could be of use to you. [MinecraftCapes](https://www.MinecraftCapes.co.uk)

The game crashed whilst ticking block entity
The game crashed whilst ticking block entity
Error: java.lang.NoSuchMethodError: net.minecraft.profiler.Profiler.startSection(Ljava/lang/Class;)V

**Comment by skmedix** [comment] 2017-05-15 19:14
[Download preview B9 for 1.11.2](http://optifine.net/downloads.php).
Duplicate of https://github.com/sp614x/optifine/issues/634

**Comment by Ta-hg** [comment] 2017-05-15 19:18
@skmedix Ok, ill see if it works and let you know what happens :)

**Comment by Ta-hg** [comment] 2017-05-15 19:21
@skmedix It worked! Thanks for the help.

**Closed** 2017-05-15 19:22 UTC
