### ISSUE TITLE
Custom Armor Textures not appearing 

### ISSUE THREAD

**Issue by BunColo** [sp614x/optifine#3473] opened 2020-02-27 19:43 UTC
Texture packs that allow armor to have a certain texture when the item has a specific name do not give the armor that texture. Custom item textures depending on their name are working, but not armor textures on the player model

**Comment by CrazyCookieBuddy** [comment] 2020-03-24 14:43
I have the same issue, armor does not work - although elytras work. See attached files.
Do they have to be in specific folders? The elytra textures I made are under cit/elytra, and the armor under cit/armor. In earlier versions it worked, but since 1.15 (i believe?) it stopped working. 

![image](https://user-images.githubusercontent.com/25452923/77438309-f004b480-6de5-11ea-921e-2015b93253ba.png)
![image](https://user-images.githubusercontent.com/25452923/77438358-feeb6700-6de5-11ea-9072-d66d4d5775d6.png)
![image](https://user-images.githubusercontent.com/25452923/77438482-2a6e5180-6de6-11ea-8098-955e58d54d4e.png)

**Comment by Katalijst** [comment] 2020-04-23 02:49
I confirm I have the exact same problem, only armor models are affected

**Comment by sp614x** [comment] 2020-05-29 09:38
Duplicate of #3318.

**Closed by sp614x** 2020-05-29 09:38 UTC
Labels: 1.15, CIT
