### ISSUE TITLE
[Crash] 1.18.2 OptiFine crashes game while world is loading on Forge client version 40.1.59 and above.

### ISSUE THREAD

**Issue by nirzh** [sp614x/optifine#7032] opened 2022-07-27 01:05 UTC
## Description of Issue
While trying to play any world, game crashes because of "Exception in server tick loop".

## Steps to Reproduce
1. Install any available version of OptiFine as a mod on Forge client version 40.1.59 or above
2. Create any world or select an existing one.
3. Try to play this world.

## OptiFine Version
OptiFine 1.18.2 HD U H7 or OptiFine 1.18.2 HD U H6 (Only available for 1.18.2)

## Installation Method
Installed as a mod on Forge client.

## Fabric/Forge Version
Forge 40.1.59 and above.

## Log Files/Crash Reports
OptiFine 1.18.2 HD U H6 & Forge 40.1.59:
https://pastebin.com/uFZJwYRZ
OptiFine 1.18.2 HD U H7 & Forge 40.1.59:
https://pastebin.com/L9hhKjMM
OptiFine 1.18.2 HD U H6 & Forge 40.1.68 (latest for now):
https://pastebin.com/xJXQPced
OptiFine 1.18.2 HD U H7 & Forge 40.1.68 (latest for now):
https://pastebin.com/kPbq4vgk

## Additional Information
Most likely, this happens because of **ForgeChunkManager ticking ticket fixes** in **Forge 40.1.58** version (cannot be downloaded, but this fix still actual to any later version of Forge (40.1.59 - 40.1.68 for now)).

**Comment by earlyshooter** [comment] 2022-07-28 04:20
This is correct. Forge version 40.1.57 works perfectly with Optifine. For anybody that is having trouble getting Optifine to work with your curse forge profiles.

**Comment by HellishINC** [comment] 2022-07-28 23:35
Duplicate of #7009

**Comment by ZenIsBestWolf** [comment] 2022-10-12 15:41
dupe

**Closed by ZenIsBestWolf** 2022-10-12 15:41 UTC
Labels: duplicate
