### ISSUE TITLE
Door/Trapdoor interaction lag (with/out shaders)

### ISSUE THREAD

**Issue by Jamzs3** [sp614x/optifine#3912] opened 2020-05-10 10:13 UTC
## Steps to Reproduce
1. Build near big bodies of water.
> Create a 3x3+ home with torches
> Place doors/trapdoors that enclose the structure (outside light-gaps limit this issue.)
2. Stand near any moderate/large body (within render distance) of water or have you FOV towards a door/trapdoor and spam click.
> Redstone doesn't affect it
> player interaction only
> Results seem to hit 7fps. 
## OptiFine Version
HD-U-G1-Pre16 (any PRE-1.15 versions)

## Installation Method
standalone installer

## Prior Testing
- Does this happen in Vanilla without OptiFine?
No. Render issues happen on optifine only (shaders packs do not matter)  

[https://youtu.be/SgWA_If6fyc](url) <- video

> This issue also happens when instant mining sand/stone near water with shader pack.

> Settings: 
> Smart animations: on
> Fast math: on
> VBOs: on
> Dynam Lights Fancy
> Still cause issues if switched off

**Comment by naeqirelle2020** [comment] 2020-06-05 06:10
Tested this extensively according to the steps to reproduce it and couldn't reproduce, must be fixed

**Comment by Jamzs3** [comment] 2020-06-05 07:37
Tested again, fixes have helped with fps.
Still some noticeable lag. However, it's far more limited in its effect.
Create an ocean world.
Larger building 5x5
Place doors/trapdoors that enclose the structure (outside light-gaps limit this issue.)
Add some torches.

(Same as before)
Stand near any moderate/large body (within render distance) of water or have you FOV towards a door/trapdoor and spam click.
Redstone doesn't affect it
player interaction only
Results seem to hit the lowest 20/30fps. Much better improvement.

OptiFine Version
HD-U-G1-Pre18

Normal worlds have near to no effect on this bug now.
Video >> [https://youtu.be/yySoCwjhbSc](url)

**Comment by naeqirelle2020** [comment] 2020-06-05 08:08
okay tested again and yeah this still occurs in pre-19 not as bad as before like you mentioned, maybe it's related to #3797 ?

**Comment by Jamzs3** [comment] 2020-06-05 08:22
Similar yes. However, I don't get those _issues_ in my world(s). Feel free to close this if necessary.

**Comment by naeqirelle2020** [comment] 2020-06-05 08:25
yeah, it's not a duplicate but i'm just saying it may be related to, no need to close this since it's a valid bug

**Comment by darty11** [comment] 2020-06-17 17:18
Can confirm, also applies to gates and doors. I can get down to 5 fps from an average of 80 by just holding right click on one of them. My base is surrounded by water and has thousands of trapdoors. Redstone activating them doesn't trigger the lag.

**Comment by sp614x** [comment] 2020-06-18 21:52
Should be fixed in pre27.
Same with #3797.

**Closed by sp614x** 2020-06-18 21:52 UTC
Labels: 1.15, performance
