### ISSUE TITLE
[CEM] Custom parrot model doesn't apply to shoulder parrots

### ISSUE THREAD

**Issue by DragendGhast** [sp614x/optifine#2295] opened 2019-04-08 16:57 UTC
Parrot CEM reverts to original model when on a player's shoulder.

**Comment by realjackasterisk** [comment] 2019-04-08 18:04
duplicate of #2179 but at least this ones in plain english.

**Comment by sp614x** [comment] 2019-04-09 10:06
It was fixed for 1.12.2 in #967.
Still open for 1.13.2.

**Comment by sp614x** [comment] 2019-10-21 15:36
Still not working in 1.14.4.

**Comment by BlevinsTyler** [comment] 2020-09-14 23:24
not working in 1.16.2

**Comment by ColonelOverspel** [comment] 2020-12-31 15:22
Not working in 1.16.4!

**Comment by ZenithRogue** [comment] 2021-09-06 21:15
Issue still present in 1.17.1

**Comment by sp614x** [comment] 2022-05-01 21:53
Fixed, coming in next preview.

**Closed by sp614x** 2022-05-01 21:53 UTC
Labels: bug, CEM
