### ISSUE TITLE
[Bug] openGL error on Linux

### ISSUE THREAD

**Issue by Dorus06** [sp614x/optifine#5932] opened 2021-06-29 17:34 UTC
## Description of Issue

i keep getting this error when i start minecraft with optifine:
GLFW error 65543: GLX: Failed to create context: GLXBadFBConfig.

Please make sure you have up-to-date drivers (see aka.ms/mcdriver for instructions).

i only have this problem with optifine and on amd and intel GPU's
if i start minecraft normal then i dont get this error
almost no one has this issue beacause i use linux instead of windows
## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## OptiFine Version

all the 1.17 preview versions
## Installation Method

the normal installer

## Log Files/Crash Reports

GLFW error 65543: GLX: Failed to create context: GLXBadFBConfig.

Please make sure you have up-to-date drivers (see aka.ms/mcdriver for instructions).

[latest.log](https://github.com/sp614x/optifine/files/6735266/latest.log)

## F3 Debug Screenshot

mc doesn't even start

## Additional Information

my specs and OS name:
Ubuntu 21.04 and it also happens  on Ubuntu 20.04 and OpenSuse

'4th gen mobile intel i5 with intergrated graphics' in my laptop
'core 2 quad Q6600 with a amd HD 5450' for my mothers pc
'7th gen intel i5 with intergrated graphics' in my sisters laptop

it does not only happen on old systems

**Comment by Dorus06** [comment] 2021-06-29 17:36
it works fine on my gaming pc with a Nvidia GPU

**Comment by fayer3** [comment] 2021-06-29 18:21
duplicate of #5739

**Comment by Dorus06** [comment] 2021-06-29 18:24
ok, thanks for letting me know that this bug already has been reported!

**Closed** 2021-06-29 19:00 UTC

**Comment by kureshio** [comment] 2021-07-17 19:45
I also have the same problem.

**Comment by onlytruejames** [comment] 2021-08-03 17:08
I have the same problem
