### ISSUE TITLE
[Visual bug] 1.15.2 Minecolonies mod - some of the blocks are purple and black cubes.

### ISSUE THREAD

**Issue by badacsonyigorenyember** [sp614x/optifine#4400] opened 2020-07-21 11:42 UTC
## Description of Issue
1.15.2 Minecolonies with 1.15.2 pre30 Optifine. Some of the block in the Minecolonies mod are purple and black cubes, they have no texture. The blocks are good when I play them without optifine. In the inventory thos block are invisible. I took a printscreen of it, but i had more mods, but i tested with only Minecolonies and Optifne but it is the Optifine's fault.

## Steps to Reproduce
1. Download Minecolonies mod in 1.15.2
2. Download Optifine 1.15.2 version
3. Play the game
4. In the inventory thos block are invisible

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre30

## Installation Method
droped the JAR file into my "mods" folder

## Fabric/Forge Version
Forge 31.2.31

## Other Installed Mods
Minecolonies-0.10.771
Strucurize-0.10.313
MixinBootstrap-1.0.3
OptiForge-MC1.15.2-0.1.27

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/4953245/latest.log)

## F3 Debug Screenshot
![F3 image](https://user-images.githubusercontent.com/61948449/88050773-c5d6bf80-cb57-11ea-9e33-ed02594ce89f.png)

## Prior Testing
If you've installed using Forge/Fabric:
-It happens only with Minecolonies

**Comment by MightyLuu** [comment] 2020-07-22 12:50
tested several minecolonies versions, can confirm this for all of them.

also some citizen textures, sometimes wont load and will be displayed purple/black

**Comment by Guest5647** [comment] 2020-08-11 04:39
happens to me too when i removed optifine the textures come bacl but i need optifine for my laptop

**Comment by ravenbuilder934** [comment] 2020-11-02 17:00
Duplicate of #3903

**Closed** 2024-08-13 15:11 UTC
