### ISSUE TITLE
Blur Menu, HUD and other things with JourneyMap

### ISSUE THREAD

**Issue by FinzoYFunzo** [sp614x/optifine#6440] opened 2021-12-05 15:38 UTC
## Description of Issue
With the mod JourneyMap many things get blurry
Blurred Menu
![unknown](https://user-images.githubusercontent.com/72240238/144753253-84d7cac0-210b-43b1-a096-752c91cfb58d.png)
Normal Menu
![unknown](https://user-images.githubusercontent.com/72240238/144753026-15f16b2b-561a-4fa2-b459-879b55240848.png)

## Steps to Reproduce
Just use JurneyMap and Optifine

## OptiFine Version
preview_OptiFine_1.18_HD_U_H3_pre7

## Installation Method
Droping Optifine to Mod folder

## Fabric/Forge Version
Forge|x

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/72240238/144753175-d9793d43-8b53-41a0-9924-eb1fc8fbca7c.png)

**Comment by fayer3** [comment] 2021-12-05 15:43
duplicate of #6281

**Closed** 2021-12-05 16:19 UTC
