### ISSUE TITLE
[1.15.2 Bug] Block highlight not showing (with shaders)

### ISSUE THREAD

**Issue by LukasAppleFan** [sp614x/optifine#3856] opened 2020-05-04 13:10 UTC
## Description of Issue
When using shaders, the block highlight will not show.

![2020-05-04_14 44 11](https://user-images.githubusercontent.com/41242166/80968991-330c6b80-8e19-11ea-956e-5a0c70449f51.png)

## OptiFine Version
preview_OptiFine_1.15.2_HD_U_G1_pre15

## Installation Method
Standalone

## F3 Debug Screenshot
![2020-05-04_15 07 59](https://user-images.githubusercontent.com/41242166/80968906-0d7f6200-8e19-11ea-8437-2318159b100b.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No

## Additional Information
Shaders used : Sildurs and BSL
Resource packs : none and faithful

**Comment by bileguru** [comment] 2020-05-05 16:32
Even I am facing the same issue! Is there any fix for this yet?

**Comment by LukasAppleFan** [comment] 2020-05-06 05:44
Still present in pre16

**Comment by justinshepard** [comment] 2020-05-07 03:21
Can confirm in pre16. Screenshot attached - I'm running AMD CPU and GPU, same issue (noting contrast with OP's Intel/nVidia combo). Choice of shader does not matter, they all have this issue.
![Screenshot](https://user-images.githubusercontent.com/1413954/81250963-d8753a00-8fe7-11ea-9c14-3579f3814724.png)

**Comment by sp614x** [comment] 2020-05-29 10:41
Duplicate of #3708.

**Closed by sp614x** 2020-05-29 10:41 UTC
Labels: 1.15, shaders
