### ISSUE TITLE
Optifine white screen + no fullscreen MacOS Big Sur Issue 

### ISSUE THREAD

**Issue by FoxUSB** [sp614x/optifine#5104] opened 2020-12-13 18:21 UTC
Hello, 
I recently found out that there's a bug on Apple devices that makes Minecraft launch with a white screen. And the same thing with fullscreen. When I launch it, it automatically enters the fullscreen and it's white. 

I tried to launch it on different launchers, resolutions, and versions. It didn't work either. 

It happens with any version of OptiFine. 

Reinstalling didn't work for me either. 
I am usually playing on Forge, but there's no difference. 
I tried everything. 

What can I do? 
I saw some forums with the same issue, so I think I'm not the only one who has this problem.

**Comment by FoxUSB** [comment] 2020-12-13 18:41
Hello again! 

I kinda did fix the problem here! 
I have made a new installation with the same version of Forge (OptiFine)! 
It is still unable to process in the fullscreen (still white screen), but You can play on almost fullscreen (or just PLAY)!

**Comment by HiItsDevin** [comment] 2020-12-14 05:43
May I ask which version of Big Sur you're on, along with what Minecraft and OptiFine version, and what Mac you have?

**Comment by sp614x** [comment] 2020-12-18 15:57
Duplicate of #5034

**Closed by sp614x** 2020-12-18 15:57 UTC
Labels: bug, mac

**Comment by FoxUSB** [comment] 2020-12-19 17:08
Yes. I have the latest version of MacOs Big Sur on a 2019 iMac.
