### ISSUE TITLE
[Bug] First person has no texture while using forge

### ISSUE THREAD

**Issue by ocram9** [sp614x/optifine#4145] opened 2020-06-21 22:20 UTC
## Description of Issue
I have never seen anything like this before but in first person view there are no textures (I have no idea how to explain it, see the screenshot). This only happens while using forge (version 31.2.21). Optifine pre-30 was working fine before the hotfix. I have tested this without any mods other then Optifine.

First person:
![2020-06-22_00 11 35](https://user-images.githubusercontent.com/49008532/85236371-b9a6f780-b41d-11ea-86cf-b5ffec9f21e0.png)

Third person:
![2020-06-22_00 11 49](https://user-images.githubusercontent.com/49008532/85236373-bb70bb00-b41d-11ea-8c81-d0b8f37f9a3e.png)

## Steps to Reproduce
1. Put optifine pre-30 in the mods folder of the client
2. Start a forge server and join

## OptiFine Version
Optifine 1.15.2 pre-30

## Installation Method
I dropped the jar file in the mods folder of the client, not the server.

## Fabric/Forge Version
Forge 31.2.21

## Log Files/Crash Reports
- Latest log: https://gist.github.com/ocram9/91add6ab3dd70498f330f91ae4208fc0

## F3 Debug Screenshot
![2020-06-22_00 17 36](https://user-images.githubusercontent.com/49008532/85236387-df340100-b41d-11ea-8856-f6a28aa9f699.png)

**Comment by Volds** [comment] 2020-06-22 04:01
Getting the exact same with 31.2.0

**Comment by Mixtongent73** [comment] 2020-06-22 06:32
I got it with forge 31.1.63

**Comment by sp614x** [comment] 2020-06-22 07:08
Duplicate of #4144

**Closed by sp614x** 2020-06-22 07:08 UTC
