### ISSUE TITLE
Shader Issue with Spiders

### ISSUE THREAD

**Issue by Elwood0** [sp614x/optifine#818] opened 2017-08-06 01:18 UTC
Version: U_C4 (U_C5_pre didn't change anything)

Hello, I have been having some issues with shaders in regard to spiders. When a 32 x 32 resource pack is being used, both regular and cave spiders are seen like this...

![2017-08-05_21 01 59](https://user-images.githubusercontent.com/30761759/28999783-98f505be-7a22-11e7-8c8d-845223f9ab33.png)

The spider is either partially covered in black...

![2017-08-05_21 02 23](https://user-images.githubusercontent.com/30761759/28999784-9d657732-7a22-11e7-9250-940718ec6944.png)

Or is completely black apart from the eyes.

This occurs for any type of shader pack I use, no matter the settings, but they work perfectly without a 32 x 32 resource pack.

The resource pack is Faithful 1.12-rv2.

I am running a gtx 1060 and an intel i7 4790.

If you need any other information please let me know. 

Thank you.

**Comment by sp614x** [comment] 2017-08-08 14:14
Have you tried with internal shaders?
Are endermen also affected?

**Comment by Elwood0** [comment] 2017-08-11 15:02
Apologies for my late response.

Internal shaders work fine.

Also, the same effect does apply to endermen.

**Comment by sp614x** [comment] 2017-08-11 16:30
The eyes of the spider, enderman and end dragon are rendered on an additional layer. Many shader packs use a separate program for the eyes to make them glow in the dark.
This is probably caused by the shader pack using different transforms for the mob and for the eyes overlay.
In order to avoid the problems the shaders have to use the absolutely identical transform, otherwise there is Z-fighting. This may not be visible with 16x textures, because there the loss of acuracy is smaller.

**Comment by Elwood0** [comment] 2017-08-11 17:58
Thank you.

I have tried using Sildur's Shaders, but I got the same result.

Do you know by any chance how to disable the glowing eye effect, either in the options menu or directly in the files?

If not that is perfectly fine.

**Comment by sp614x** [comment] 2017-08-11 19:44
The separate layer eye rendering comes from vanilla and can't be disabled.
The eyes glowing in the dark is a shader specific feature and the shader pack may or may not have an option to turn it off.
Maybe only this specific resource pack has a problem and it could be fixed by replacing the spider/enderman skins with lower resolution variants.

**Comment by Elwood0** [comment] 2017-08-11 20:38
I'll try tinkering with some options and resource packs to see if I get a different result.

In any case, thanks for your help.

If you want to know the shader and resource pack I was using here are the links...

Continuum 1.3: https://continuum.graphics/continuum-downloads

Faithful Vanilla: https://mods.curse.com/texture-packs/minecraft/236821-faithful-vanilla

**Comment by sp614x** [comment] 2018-01-19 17:02
Duplicate of #1144.

**Closed by sp614x** 2018-01-19 17:02 UTC
Labels: shaders

**Comment by johannesspinnenschreck** [comment] 2021-12-21 16:08
If anyone is still having this issure, look at the spider/enderman eye textures in your resource pack and make sure there's a transparent background, if there isn't and the background is instead black or something, make it transparent to fix this.

**Comment by daflame899** [comment] 2024-09-08 19:48
Still happening sadly
