### ISSUE TITLE
[Bug] no shade here

### ISSUE THREAD

**Issue by rabbitbest** [sp614x/optifine#5889] opened 2021-06-27 01:01 UTC
## Description of Issue
With some shaderspack, creatures' including player shades are not where they should be.

## Steps to Reproduce
1. Optifine. No other mods, with Bsl, Sues, Airlocke shaderspack.
2. just on any map.
3. shades are not where right.

## OptiFine Version
1.17 pre 22~23

## Installation Method
standalone

## F3 Debug Screenshot
![2021-06-27_09 48 59](https://user-images.githubusercontent.com/86504314/123529747-6f421000-d72e-11eb-866c-79029fef598a.png)
![2021-06-27_09 56 40](https://user-images.githubusercontent.com/86504314/123529749-723d0080-d72e-11eb-8dd8-9521a5072bba.png)

## Prior Testing
It only happens with optifine and shaderpack. As all know, there is no real shade in vanilla.

## Additional Information
You can see on debug screenshot, shades are actually not exsitent, but they are some wrong places.

**Comment by Whitelisted1** [comment] 2021-06-27 01:14
Did you turn off "entity shadows" in the settings menu?

**Comment by Whitelisted1** [comment] 2021-06-27 13:57
Duplicate of #5890 (it demonstrates it more)

**Comment by KaiAF** [comment] 2021-06-27 16:53
Addressed here: #5883

**Closed by KaiAF** 2021-06-27 16:53 UTC
