### ISSUE TITLE
1.16.2 World Load Glitch

### ISSUE THREAD

**Issue by BabBabz** [sp614x/optifine#4675] opened 2020-08-23 16:06 UTC
## Description of Issue
Occasionally, when starting up a singleplayer world, the world loads up but the player is stuck in the void, aka, the screen is white and you can only see the sun and clouds. 

## Steps to Reproduce
Launch the client and open singleplayer worlds

## OptiFine Version
1.16.2 (this happened in both of the pre-releases)

## Installation Method
Used the installer

## F3 Debug Screenshot

![2020-08-23_12 03 22](https://user-images.githubusercontent.com/70105009/90983008-09e32880-e539-11ea-8183-10efa612cca0.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No

## Additional Information
Doesn't always happen; goes away with time.

**Comment by BabBabz** [comment] 2020-08-24 15:31
> i believe you can fix this by turning your render distance down below 37
> 
> (i say 37 because i saw that number somewhere associated with a rendering bug like this, i use 20 and it works fine)

Thanks, that fixed it!

**Comment by sp614x** [comment] 2020-08-26 16:17
Duplicate of #4261

**Closed by sp614x** 2020-08-26 16:17 UTC
Labels: 1.16, bug, interesting, rendering
