### ISSUE TITLE
(1.9.4) crash with Chisel

### ISSUE THREAD

**Issue by Hypsellis** [sp614x/optifine#185] opened 2016-06-22 00:16 UTC
The Chisel creative menu doesn't diplay correctly when Optifine is installed, and then Minecraft crash with this error : http://pastebin.com/6P7bpwUn
In more the log fills it in an alarming rate of errors repeted again and again when both Chisel and Optifine are installed, here is an example of what I get : http://pastebin.com/GZLGXQPB
Sometimes Minecraft crash when I load/create a world with this error : http://pastebin.com/abSaQHnR

**Comment by Drullkus** [comment] 2016-06-22 00:19
Oh, hang on, #60 might be related.

**Comment by Hypsellis** [comment] 2016-06-22 00:23
Yeah maybe.

**Comment by sp614x** [comment] 2016-06-22 12:03
OptiFine + Chisel should not crash.
Issue #60 concerns broken textures when using the forge lighting pipeline. Chisel has implemented a workaround and the rendering should be correct in the recent versions. Still open is the issue with the forge lighting pipeline

**Comment by sp614x** [comment] 2016-06-22 12:43
Tested Forge #1954 + OptiFine B6 + Chisel 0.0.5.27
- the problem only appears when using shaders.
- the iron chisel menu is broken
- the diamond chisel menu is OK
- sometimes crashes when enabling shaders
It looks like Chisel is using a custom vertex format which is not compatible with the shaders vertex format.
Custom vertex formats may be problematic with shaders as they use extended formats with additional fields (normal, midTexCoord, tangent, blockId).
Blocks and items should generally use DefaultVertexFormats.BLOCK and ITEM to avoid conflicts with shaders.

**Comment by Hypsellis** [comment] 2016-06-23 11:43
Will this error be corrected ?

**Comment by sp614x** [comment] 2016-06-23 15:25
Currently there is no easy way to fix it.
A workaround would be to automatically disable shaders when someone tries to use a custom vertex format.

**Comment by Drullkus** [comment] 2016-06-23 15:30
Ouch. That seems best for now.

**Comment by Hypsellis** [comment] 2016-06-23 19:37
There are no ways to use a normal vertex format ? Because I would want to be able to play with Chisel and shaders.

**Comment by sp614x** [comment] 2016-06-23 21:23
What is a "normal vertex format"?

**Comment by Hypsellis** [comment] 2016-06-23 22:50
I meant the shader vertex format, sorry for the misunderstanding.

**Comment by Redlotus99** [comment] 2016-07-11 00:35
I can verify this continues in 1.10.2 shaders/optifine and chisel for 1.9.4.

**Comment by Hypsellis** [comment] 2016-07-11 00:59
It has been solved with the last 1.10 versions. ;)

**Comment by Redlotus99** [comment] 2016-07-11 01:12
It wasnt as of 0.0.5.29, is it with the newest?

**Comment by Hypsellis** [comment] 2016-07-11 01:54
Yes I suppose, I didn't try with the 0.0.5.29 version since Optifine C2 hadn't been released and the C1 version made crash Minecraft. Anyway with the 0.0.6.32, it works.

**Comment by Redlotus99** [comment] 2016-07-11 02:44
Awesome I'll give it a shot

**Comment by Redlotus99** [comment] 2016-07-11 05:17
Seems this issue may be different than mine. I may open a new ticket as I am having a client crash when looking at a chisel block. This is happening with Optifine C2 and Chisel 0.0.6.32.

**Comment by tterrag1098** [comment] 2016-07-11 14:17
Custom VertexFormat was suggested by @RainWarrior, it is a forge-accepted way of doing things. But somehow it's my fault for using it? There must be a way for you to fix this on your end. Randomly blacklisting features that mods should be perfectly fine using isn't a great way to go about things.

**Comment by Hypsellis** [comment] 2016-07-11 14:46
It's exactly the same issue that mine RedLotus. And I think that optifine really need to support custom vertexformat. It creates really too much bugs and incompatibilities with many mods like chisel.

**Comment by Redlotus99** [comment] 2016-07-11 15:07
@tterrag1098 Not your fault at all. I was just posting an issue I have found. I just want to be able to use shaders and the only way I have found that works decently was with Optifine. I love Chisel and so do all the players on my server so I was hoping some sort of fix could be done by whomever to address an issue that some are having.

**Comment by Redlotus99** [comment] 2016-07-12 16:49
So So can we expect a fix for this whomever needs to do it? I miss playing with Shaders and Chisel is one of those mods that players on my server must have.

**Comment by sp614x** [comment] 2016-07-12 20:32
Why is Chisel (or some other mod) using a custom vertex format?

**Comment by Redlotus99** [comment] 2016-07-13 04:17
@sp614x I'm not sure, I was just hoping for some form of fix so I don't keep crashing.  I'm unsure where the blame lies and just really hope this can be fixed by whomever.

**Comment by mindforger** [comment] 2016-07-13 06:36
@sp614x because like tterag1098 said, because it is allowed

**Comment by Drullkus** [comment] 2016-07-13 07:28
Did github change font or something. Words feel a bit different.

Anyway, I believe it is because of our CTM system, I think. Having 47 textures for CTM is kinda uncool when you can just use 5. (except for a few rare corner cases)

**Comment by sp614x** [comment] 2016-07-14 09:31
How can a custom vertex format help CTM?
The CTM is all about replacing textures (u, v, and x, y, z replacement). The Chisel CTM can also replace one face quad with several sub-quads in order to use less CTM textures. This does not need a custom vertex format. The compact CTM (similar to Chisel CTM) is also coming to OptiFine and it does not need any vertex format changes.
The vertex format defines how the data is sent to the GPU. In order to be effective it also needs the rendering pipeline to be modified. The Shaders are complex and they use custom vertex formats because they need to send more information to the GPU. They also reorganize the rendring pipeline to work in a different way.
What custom format is Chisel using and why is it needed?

**Comment by Drullkus** [comment] 2016-07-15 07:12
Well I know that @minecreatr is working on fullbright for textures, so we can have stuff like the Antiblocks and Futura blocks render without darkness.

**Comment by Rushmead** [comment] 2016-07-23 15:13
Sorry to bump this issue, but have we come up with a solution / fix?

**Comment by Redlotus99** [comment] 2016-07-23 19:28
I've not seen one as of yet other than not to use shaders at the moment. I have been hoping for a fix.

**Comment by Rushmead** [comment] 2016-08-01 08:11
Sorry again but @sp614x or @tterrag1098 is there a potential fix anywhere?

**Comment by tterrag1098** [comment] 2016-08-01 08:22
I would implore @sp614x to read through our rendering code and find what is causing such serious issues, because as far as I can tell we do not use a custom VertexFormat (at the moment).

**Comment by Redlotus99** [comment] 2016-08-01 15:08
I too am still awaiting a fix.

**Comment by Hypsellis** [comment] 2016-08-01 18:02
It would maybe be the time to agree you all and try to fix this error together while to blame the ones against the others.

**Comment by Drullkus** [comment] 2016-08-01 18:23
That is a great compromise and I do live by the policy of trying to fix the issue in our own hands, but unfortunately I do not see a way this can be fixed on our end. :/

**Comment by Redlotus99** [comment] 2016-08-02 02:54
Maybe devs from both mods can work together for a solution. I know of at least 25 players that are awaiting this and it would be great to have this implemented. If OptiFine devs say there is no way to fix this on their side maybe @tterrag1098 and @Drullkus and @sp614x can come up with some form of solution together so that this issue doesn't continue.  

Share the code, share ideas...and maybe you guys can come to a solution. I hate not using Optifine and I'd drop Optifine over Chisel as right now we have 25 on my server that love Chisel. So please try and get  a fix in together.

**Comment by bakaschwarz** [comment] 2016-08-05 12:50
I have to agree with @Redlotus99. Not beeing able to play with shaders is not nice, but chisel found a way deep inside the hearts of me and the people on my server. I'd rather not decide between these to.

**Comment by Redlotus99** [comment] 2016-08-05 13:12
I'm just hoping this isn't a lost cause which it seems may be the case.

**Comment by Redlotus99** [comment] 2016-08-14 21:58
Please fix this it's driving me nuts along with players from 2 servers. At least look into it, Chisel is obviously using something that Forge allows so it should just be on @tterrag1098 to fix this, but if @sp614x and crew aren't going to fix it someone at least come up with some form of workaround,

**Comment by Hypsellis** [comment] 2016-08-17 14:54
Stop to be so impatient and let the modders do their work. They have a lot of work to do already so it will take time before they solve it.

**Comment by ajthemacboy** [comment] 2016-08-29 12:19
I can reproduce on 1.10.2 with latest Forge and Optimize preview.

**Comment by Hypsellis** [comment] 2016-08-29 18:27
Everybody can reproduce it with any Chisel and Optifine version since 1.9.4. The problem isn't linked to the version of the mods.

**Comment by sp614x** [comment] 2016-09-19 22:46
Tested MC 1.9.4 + Forge #2051 + OptiFine B6 for 1.9.4 + Chisel 0.0.6.4.2.
I see no crashes, even with shaders enabled. The creative menu, chisel menus and everything else is working just fine.
Is the issue still relevant?  If yes, what are the exact versions (Forge, OptiFine and Chisel) to reproduce it. Also what steps are needed to reproduce it (specific block, item, GUI, etc). 
Please, post crash reports with ONLY Forge, OptiFine and Chisel installed. Testing with 100 other mods installed does not help, as the problem may be caused by any mod, especially the core mods.

**Comment by sp614x** [comment] 2016-09-19 22:50
Also tested MC 1.10.2 + Forge #2073 + OptiFine C3 for 1.10.2 + Chisel 0.0.6.4.2.
Everything works fine, even with shaders enabled.
Are there specific steps to reproduce the problem?

**Comment by Drullkus** [comment] 2016-09-19 22:59
Yep, I think it should be patched now. Hopefully.

**Comment by tterrag1098** [comment] 2016-09-19 23:37
We fixed it yesterday. A patch that should not have been necessary, but as I was not the one that had to figure it out, I don't mind making the change.

**Comment by Redlotus99** [comment] 2016-09-20 12:53
You sir are awesome. tterrag1098 Thank you for fixing this.

**Comment by sp614x** [comment] 2016-09-20 13:07
Happy to close it

**Closed by sp614x** 2016-09-20 13:07 UTC
Labels: mods

**Comment by Drullkus** [comment] 2016-09-20 21:25
@Redlotus99 You should be thanking @minecreatr ;)

**Comment by tterrag1098** [comment] 2016-09-20 22:40
Not really, thank @vektory79 who made this random PR which pointed out the issue: https://github.com/Chisel-Team/Chisel/pull/221

**Comment by Hypsellis** [comment] 2016-09-20 23:35
Thanks a lot to all you guys for having solved this issue, you're awesome. <3

**Comment by Redlotus99** [comment] 2016-09-21 12:11
Whoever was involved in the fix, no matter how small of a role you played, myself and the many players on my server thank you.

**Comment by tterrag1098** [comment] 2017-05-03 17:56
I'm gonna do a massive necro post here, to say that Chisel now has the need for a custom vertex format, and disabling shaders does NOT fix blocks rendering invisible.
