### ISSUE TITLE
ConnectedTextures causes the client to crash

### ISSUE THREAD

**Issue by bunSakurAing** [sp614x/optifine#70] opened 2016-04-06 18:29 UTC
I use PureBDcraft resourcepacks into the server after, the client crashed
crash report:http://pastebin.com/A5TBah3u
I use the OptiFine, use the default resource, the client won't crash
I do not use OptiFine, the use of resourcepacks PureBDcraft, the client will not crash

**Comment by HeartyYF** [comment] 2016-04-10 10:20
中国同胞。-。我赌三毛是材质包中“玻璃”的连接材质的问题
I guess the problem is about Connected Textures of "Glass" in the resourcepacks.

**Comment by bunSakurAing** [comment] 2016-04-10 10:24
@HeartyYF 被发现了……确实是连接纹理的问题，关掉这个就不闪退了，但总不能一直关着吧○<--<

**Comment by sp614x** [comment] 2016-04-27 13:28
Next to the glass block being rendered, there is a modded block (not clear which mod) which has a model which returns NULL when asked for the quad list. The model should return an empty list if there are no quads, it should never return a NULL list.
I can fix it at this place, but it will crash somewhere else because everywhere (vanilla, forge, other mods) the quad list is used without a NULL check. 
The corresponding mod should be fixed to not return a NULL quad list.

**Closed** 2016-05-02 12:47 UTC
Labels: mods
