### ISSUE TITLE
My MC goes to 0 FPS 

### ISSUE THREAD

**Issue by CloudKitten** [sp614x/optifine#691] opened 2017-06-07 14:13 UTC
My Mc goes to 0 FPS whilst i have Optifine on it. Its wierd i didnt do anything. And i had it before and it worked perfectly....

Please help me out, Thanks

**Comment by Builderb0y** [comment] 2017-06-07 19:19
Smooth FPS? #583

**Comment by TxTalonTx** [comment] 2017-06-10 00:59
I'm having a very similar issue to this, but I'll post this here instead of making a new thread just in case it's the same one;

The issue started about a month ago and I don't know what caused it. I run Windows 10 and have been doing so since August of 2015.

Whenever I try to load a world or join a server, the framerate drops to 0 before the loading screen changes to the in-game screen. The frame updates once every 5-10 seconds but the game is never able to load any chunks. This _solely_ happens on OptiFine; Vanilla versions are okay.

So far, I have tried updating my video drivers, changing my Java version, changing my OptiFine version, changing my Minecraft version, and reinstalling Minecraft; reinstalling fixed it for a few days, but it's back again and I don't know why.

[Here's a pastebin of my previous log file](https://pastebin.com/hzAp61pN); be warned that it's 3051 lines (which I'm pretty sure is abnormally long) within about 74 seconds of the game running. Thanks to anybody who is able to help.

**Comment by TemperrroniPizza** [comment] 2017-06-18 21:08
I've been having the same issue, I still haven't found a fix, ever since  1.11.2 came out, OptiFine has gotten throuhg the menus, but as soon as you begin to render chunks and play the game, it tanks my pc, which has a Core i7 7700k, and a GTX 1080 (which has ample performance for this game). I've tried downgrading java, doesn't work. Reinstalling Minecraft, doesn't work.

**Comment by xCuri0** [comment] 2017-06-19 05:17
@TemperroniPizza What nvidia driver version do you have ? It seems to be a problem with your setup since i got over 100fps with creators update on a laptop. 

Do other games run correctly ?

**Comment by sp614x** [comment] 2017-06-19 12:28
Do not forget to reset all settings in the nvidia control panel, especially VSync.

**Comment by sp614x** [comment] 2017-06-22 16:14
Video Settings -> Performance -> Smooth FPS -> OFF ???

**Comment by KaiAF** [comment] 2021-03-28 18:04
Turn off Smooth FPS. Having it enabled can lead to 0 FPS which is caused by GPU Drivers. Can't be fixed by optifine.

**Closed by KaiAF** 2021-03-28 18:04 UTC
