### ISSUE TITLE
[Bug] In spectator the UI is grey

### ISSUE THREAD

**Issue by JVT038** [sp614x/optifine#3732] opened 2020-04-13 10:09 UTC
Hi,
I'm using OptiFine 1.15.2 HD U G1 pre13 in Fabric using the [Optifabric mod version 1.0.0-beta8](https://www.curseforge.com/minecraft/mc-mods/optifabric) and whenever I go in spectator mode, the F3 screen and TAB list is grey.
Example: 
![image](https://user-images.githubusercontent.com/47184046/79112703-724a1e00-7d7f-11ea-8061-f31fec1dcda1.png)

**Comment by Regnander** [comment] 2020-04-14 05:43
(Maybe) related to #3503

**Comment by sp614x** [comment] 2020-05-28 21:12
Duplicate of #3503.

**Closed by sp614x** 2020-05-28 21:12 UTC
