### ISSUE TITLE
Sign Editor Flashes

### ISSUE THREAD

**Issue by ILikePlayingGames** [sp614x/optifine#3132] opened 2019-12-07 04:01 UTC
After updating Optifine to version 1.8.9 HD U L5 from 1.8.9 HD U I7, I noticed that sometimes the sign editor will constantly flash. This happens on Hypixel skyblock when using any UI that brings up a sign editor for text entry (examples: auction house search, bank withdrawals). I've attached my Optifine settings below. Can you please look into this? Thanks!

[optionsof.txt](https://github.com/sp614x/optifine/files/3934705/optionsof.txt)

**Comment by sp614x** [comment] 2020-05-28 21:31
Duplicate of  #3694.

**Closed by sp614x** 2020-05-28 21:31 UTC
Labels: 1.8, rendering
