### ISSUE TITLE
[BUG] Wolf CEM

### ISSUE THREAD

**Issue by DvojiteV** [sp614x/optifine#3951] opened 2020-05-15 22:12 UTC
## Description of Issue
CEM for wolf seems to be bugged, on optfine for 1.14.4 it worked just fine but on 1.15.2 pre-releases wolf CEM seems to be bugged it is showing two models grouped toghether or textures are bugged idk which one of them.

## Steps to Reproduce
1. Used custom model for wolf
2. see that model in-game

## OptiFine Version
Ver. - OptiFine 1.15.2_HD_U_G1_pre17

## Installation Method
Using Forge and putting optifine inside "mods" folder

## Fabric/Forge Version
Forge

## Other Installed Mods
Just Sound Filters (0.13_for_1.15.2)

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
https://pastebin.com/TJyv9ii4 (log file if needed)

**Comment by ewanhowell5195** [comment] 2020-05-18 13:58
happens without forge

**Comment by sp614x** [comment] 2020-05-29 16:04
Duplicate of #3787.

**Closed by sp614x** 2020-05-29 16:04 UTC
Labels: 1.15, CEM
