### ISSUE TITLE
[Feature Request] Borderless Fullscreen

### ISSUE THREAD

**Issue by Zuversichtlicher** [sp614x/optifine#7595] opened 2023-12-27 17:36 UTC
## Description of the new feature

An option to play with borderless fullscreen would be great!

**Comment by ZenithRogue** [comment] 2023-12-27 17:39
My guy, you submitted a duplicate issue, when it was already the most recent open issue. (#7593 )
![image](https://github.com/sp614x/optifine/assets/11393734/617836d7-fc08-467a-a84d-00c2bd2d8864)

Closed as duplicate of #2516

**Closed by ZenithRogue** 2023-12-27 17:39 UTC
