### ISSUE TITLE
Teleporting glitches everything out in 1.15.2

### ISSUE THREAD

**Issue by werymanen** [sp614x/optifine#3976] opened 2020-05-20 22:04 UTC
## Description of Issue
You teleport to a remote location, and the game stops working. I honestly don't know what causes this issue, I discovered it while I was playing survival, and I beat the dragon, and went back home. When I tried to go back, I went through the portal, but my game didn't render, just like in the video at the bottom. One of the things I noticed is that it only happens if render distance is really high. On the video I linked, I am on 48 chunks. Later, when I stopped recording, I lowered it to 8, and then I could teleport without glitching.

## Steps to Reproduce
1. Generate a new world
2. Max your render distance
3. Teleport to a remote location

## OptiFine Version
OptiFine HD G1_pre16 Ultra

## Installation Method
Standalone installer

## Log Files/Crash Reports
Log: https://pastebin.com/vb0ydXm1

## F3 Debug Screenshot
![2020-05-20_23 50 35](https://user-images.githubusercontent.com/49951816/82501211-2f553600-9af5-11ea-8d35-e13f18ad37a6.png)
![2020-05-20_23 50 37](https://user-images.githubusercontent.com/49951816/82501215-30866300-9af5-11ea-8114-6561ba54adaa.png)
![2020-05-20_23 50 57](https://user-images.githubusercontent.com/49951816/82501217-30866300-9af5-11ea-9d9c-51361c884e18.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? No, it does not.

## Additional Information
I made a video of me going around showing the bug: 
https://drive.google.com/file/d/19kUZsfDhDcGkQnc3lHu8BPi_903orEzv/view?usp=sharing

**Comment by realjackasterisk** [comment] 2020-05-22 08:35
Duplicate of #3365

**Closed by realjackasterisk** 2020-05-22 08:35 UTC
Labels: 1.15, bug, chunks
