### ISSUE TITLE
Chunks Not Loading

### ISSUE THREAD

**Issue by xXdvdXx123** [sp614x/optifine#5184] opened 2021-01-05 18:21 UTC
## Description of Issue
Optifine doesn't render chunks in my server, only if i break bocks it renders ONLY that chunk :(

## Steps to Reproduce
1. Install Optifine 1.16.4
2. join my server and watch
3. maybe it's only my problem

## OptiFine Version
1.16.4

## Installation Method
Used the executable .jar and installed directly on the laucher

## Log Files/Crash Reports
No crashes

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
![Minecraft_ 1 16 4 - Multiplayer (3rd-party Server) 05_01_2021 19_12_16](https://user-images.githubusercontent.com/77019957/103683128-14530b80-4f8a-11eb-8b80-291157fb6e2f.png)

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? No

## Additional Information
Video is too big so i'm explaining:
I see the block hitboes but non blocks like if i were in the void, then if i break a block it loads that 16x16x16 area and nothing more :(

**Comment by sp614x** [comment] 2021-01-10 19:27
Fixed, coming in 1.16.4 pre13.

**Comment by sp614x** [comment] 2021-01-10 19:27
Duplicate of #4976

**Closed by sp614x** 2021-01-10 19:27 UTC
Labels: 1.16, cape, multiplayer
