### ISSUE TITLE
[Bug] Blue fire without animation

### ISSUE THREAD

**Issue by pedroaugusto839** [sp614x/optifine#4221] opened 2020-07-04 00:20 UTC
I installed optifine independently.
https://pastebin.com/sz6gFBgU
This bug only happens when I'm playing minecraft without optifine. I only play with optifine, no other mods.
The blue fire is only animated if the "animated terrain" option is active. In relation to red fire, this does not happen.
Note: I'm Brazilian, I made this post with the help of google translator, I'm sorry if something is wrong or out of the standard.
![2020-07-03_21 12 31](https://user-images.githubusercontent.com/67810436/86501862-729cf880-bd73-11ea-9460-d91d7d536903.png)

**Comment by sp614x** [comment] 2020-07-11 18:07
Duplicate of #4328

**Closed by sp614x** 2020-07-11 18:07 UTC
