### ISSUE TITLE
Render Entitie Issue 1.12 C5

### ISSUE THREAD

**Issue by NintendoBest** [sp614x/optifine#821] opened 2017-08-07 15:49 UTC
I don't know if you saw my last comment in my other issue, but. The visual bug is still remain.
~Coprses [Armor stand] become invisible.
Here: https://github.com/sp614x/optifine/issues/754

Please leave a comment so i can know you have look at this issue.

**Comment by sp614x** [comment] 2017-08-08 11:06
Duplicate of #754, the original issue should be used to track the problem.

**Closed by sp614x** 2017-08-08 11:06 UTC
