### ISSUE TITLE
Enabling shaders is causing an inventory glitch on Forge.

### ISSUE THREAD

**Issue by EvocatorsCollapse** [sp614x/optifine#4311] opened 2020-07-09 22:11 UTC
Currently Using:
OptiFine 1.16.1 HD U G2 pre2
Forge 1.16.1 - 32.0.59

With shaders on:
![jpaxa62kbp951](https://user-images.githubusercontent.com/63614102/87095740-e83b1580-c206-11ea-8e82-e9ec51e6bd10.png)

With shaders off:
![e0aljf0xbp951](https://user-images.githubusercontent.com/63614102/87095781-f852f500-c206-11ea-8678-e672b3a33103.png)

**Comment by Ioxom** [comment] 2020-07-09 22:13
Referring to #4277 this is a bug with forge versions above 32.0.43.

**Comment by sdhsako** [comment] 2020-07-10 11:17
![unknown](https://user-images.githubusercontent.com/68109657/87148927-399ae180-c2a7-11ea-935a-0bdafe58bedc.png)
This can also happen along with the inventory bug. (Happens at the same time)

**Comment by sp614x** [comment] 2020-07-10 12:32
Duplicate of #4277

**Closed by sp614x** 2020-07-10 12:32 UTC
