### ISSUE TITLE
[Bug] Parrot custom texture using random mobs does not work if parrot is on shoulder

### ISSUE THREAD

**Issue by Barkells** [sp614x/optifine#6564] opened 2022-01-16 17:50 UTC
## Description of Issue
I gave a parrot a custom texture when called a certain name. It works perfectly fine except when the parrot is put onto the players shoulder. I believe this bug was "fixed" back in the C8 version for 1.12.2 But it seems to be back.

## Steps to Reproduce
1. Give a parrot a custom texture for a specific name (such as "bob")
2. Then rename the parrot to that name ("bob") and then put it on the players shoulder. Go to f5 and see that the texture given is gone.

## OptiFine Version
preview_OptiFine_1.18.1_HD_U_H5_pre4

## Installation Method
Standalone installation

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/97847274/149671611-e9f5ed43-b070-469e-9132-58e02cf59b22.png)

## Prior Testing
Random textures dont work without optifine.

## Additional Information
![2022-01-16_17 49 35](https://user-images.githubusercontent.com/97847274/149671641-244cb8fb-68a0-478a-b836-5c5e15937926.png)
![2022-01-16_17 49 43](https://user-images.githubusercontent.com/97847274/149671643-d9dcbb88-fce5-40e0-8b5b-34cf719c7c3c.png)

**Comment by sp614x** [comment] 2022-05-01 21:47
Duplicate of #6223

**Closed by sp614x** 2022-05-01 21:47 UTC
