### ISSUE TITLE
[1.16] Loading screen blending methods

### ISSUE THREAD

**Issue by Michael18751** [sp614x/optifine#4299] opened 2020-07-08 19:30 UTC
Is it possible to add a blended method for the loading screen so my game would load correctly using the Mojang logo in my pack? When I set the BG to white, it renders in white fine but the blending has changed in 1.16 and it screwed it up.
![image](https://user-images.githubusercontent.com/53535277/86961552-6af0a180-c12f-11ea-952b-3f019fdf9b34.png)
This is what it looks like when I have a white BG. The image completely fades away and it is not visible at all until the fadeout.
![image](https://user-images.githubusercontent.com/53535277/86961651-93789b80-c12f-11ea-9270-120e0830d5c6.png)
As you can see, you can barely see it when the loading screen fades out.
![image](https://user-images.githubusercontent.com/53535277/86961780-cae74800-c12f-11ea-96fb-ee5e7a12768f.png)
As you can see, if the background is set to default, it will be visible but the colors look really off.
![mojangstudios(blend is broken)](https://user-images.githubusercontent.com/53535277/86961856-eb170700-c12f-11ea-8d82-f7e4c6c11420.png)
Here is the texture I used (Format changed in 1.16)

**Comment by sp614x** [comment] 2020-08-28 14:31
Duplicate of #4712 
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/color.properties#L253

**Closed by sp614x** 2020-08-28 14:31 UTC
Labels: 1.16, enhancement, gui, todo

**Comment by Michael18751** [comment] 2020-08-29 03:16
Whats the blend option to set it to the 1.15 style?
