### ISSUE TITLE
Glowing Potion and Glow Arrows etc. not functioning.

### ISSUE THREAD

**Issue by zachrocks22** [sp614x/optifine#1432] opened 2018-06-03 01:37 UTC
The glow appears to shade in the entire player entity instead of outlining it like normal. The resourcepack doesn't alter it as I tried toggling between the Default and the resourcepack of my choice and the issue still persists. When switching to just normal Minecraft the glow is displayed like normal.

**Comment by sp614x** [comment] 2018-06-03 11:10
Duplicate of #1377, #1174, #189.

The spectral effect (glowing outline) is not compatible with Fast Render and with shaders. When one of them is active an alternative "ghost" effect is used instead.

**Closed by sp614x** 2018-06-03 11:10 UTC

**Comment by selfslaughter** [comment] 2018-09-26 12:45
Is this also the case when enabling Anti-Aliasing without shaders or fast render enabled?
If so, is there any way to disable the glowing effect rather than disable anti-aliasing?
I didn't notice anything in optionsof.txt

Using 1.13.1-pre3 and our servers players have a /glow command which makes them hideous when combined with AA. :P
