### ISSUE TITLE
OptiFine HD_U_E6 for 1.13.2 crashes

### ISSUE THREAD

**Issue by m4sk1n** [sp614x/optifine#2261] opened 2019-03-20 16:35 UTC
```
Picked up _JAVA_OPTIONS:   -Dawt.useSystemAAFontSettings=gasp
[17:26:03] [main/INFO]: Loading tweak class name net.minecraft.launchwrapper.VanillaTweaker
[17:26:03] [main/INFO]: Using primary tweak class name net.minecraft.launchwrapper.VanillaTweaker
[17:26:03] [main/INFO]: Calling tweak class net.minecraft.launchwrapper.VanillaTweaker
Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
	at net.minecraft.launchwrapper.VanillaTweaker.injectIntoClassLoader(VanillaTweaker.java:16)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
```
OS: Deepin Linux 64-bit
CPU: i3-5005U
GPU: GT920M
running minecraft from official launcher
installed using official optifine installer
worked fine on arch linux afair

**Comment by sp614x** [comment] 2019-03-21 08:48
This is typically caused by custom launchers and can't be fixed by OptiFine.
Relevant: #1956, #1951, #1825, #1804, ...

**Comment by m4sk1n** [comment] 2019-03-21 08:49
>running minecraft from official launcher

**Closed by sp614x** 2019-03-21 08:48 UTC
