### ISSUE TITLE
[Optifine 1.15.2 G1 pre 16] Glowing Effect not visible when use Shaders

### ISSUE THREAD

**Issue by Domi207** [sp614x/optifine#3605] opened 2020-03-28 16:00 UTC
## Description of Issue
Players doesn't glow with the glowing effect when shaders are activated.

## Steps to Reproduce
I have activated a shader and give me the glowing effect but I doesn't glow. This is the same if other players have the glowing effekt.
## OptiFine Version
Optifine 1.15.2 G1 pre 16

## Installation Method
I install OptiFine with the Jar-Installer.

## Log Files/Crash Reports
https://pastebin.com/TtM5vK7f

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/51676231/77827376-83efbc80-7115-11ea-9cb2-e55094b32044.png)

## Prior Testing
I cant install Shaders without OptiFine.

**Comment by sp614x** [comment] 2020-05-29 10:58
Duplicate of #3662.

**Closed by sp614x** 2020-05-29 10:58 UTC
Labels: 1.15, glowing, shaders
