### ISSUE TITLE
Optifine_1.7.10_HD_UD_7 [Crash]

### ISSUE THREAD

**Issue by Darkos333** [sp614x/optifine#551] opened 2017-03-22 20:23 UTC
Crash on loading world:

[23:16:13] [Client thread/FATAL]: Unreported exception thrown!
java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkBounds(Unknown Source) ~[?:1.8.0_121]
	at java.nio.DirectIntBufferU.put(Unknown Source) ~[?:1.8.0_121]
	at shadersmod.client.ShadersTess.draw(ShadersTess.java:73) ~[ShadersTess.class:?]
	at net.minecraft.client.renderer.Tessellator.func_78381_a(Tessellator.java:169) ~[bmh.class:?]
	at net.minecraft.client.renderer.WorldRenderer.func_147891_a(WorldRenderer.java:423) ~[blo.class:?]
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:348) ~[blo.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2403) ~[bma.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1656) ~[blt.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1387) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

When I first tried Optifine HD_UD_7 (alongside Fastcraft 1.24 with fixed compability) everything worked fine for a few seconds until I decided to go to video settings and check shaders screen. Game froze instantly, screen flickered and server crashed. So I thought its something related to that particular settings screen - I reloaded Minecraft and this time I got exact same crash almost instantly after world load, without any interaction with said settings screen. I tried reloading a few more times, with exact same result: world loads, I see a few normal frames, then whole screen turns white for a while, a few another normal frames and boom - game crashed.
[Full log](https://gist.github.com/Darkos333/6f0ecef6fcd443277df684ae12b5f6e8)

**Comment by sp614x** [comment] 2017-05-18 09:29
Duplicate of #588.

FastCraft 1.25 should work:
https://forum.industrial-craft.net/thread/10820-wip-1-7-10-fastcraft-1-23-note-all-posts-of-new-members-need-to-be-approved-firs/?postID=207199#post207199

**Comment by Darkos333** [comment] 2017-05-18 11:26
Well, it seems like updating to Fastcraft 1.25 does NOT solve the problem :/
[https://gist.github.com/anonymous/909fda8618230286b7973801e625bcd3](newest log)

**Comment by sp614x** [comment] 2017-05-18 13:21
Can the crash be reproduced with a minmal number of mods installed?
Ideally only Forge, OptiFine and one conflicting mod.

The conflicting mod can be found relatively fast with a binary search:
1. Split the mods in 2 groups, test with each group
2. Keep the group that crashes, repeat step 1

At the end there should be one mod left which reproduces the crash.

**Comment by Darkos333** [comment] 2017-05-18 14:44
I started conducting some tests and it seems like I cannot reproduce the bug on a new world, even when set of mods (and its configs) is exactly the same! Frankly, when I swhich back to Optifine UD6, everything works just fine in this world. Does optifine sotre some data in worldsaves?

**Comment by Darkos333** [comment] 2017-05-18 15:26
Just tried out UD8, the bug still exists: [latest log](https://gist.github.com/Darkos333/1faff5d2fb6151032570dee377909406)

**Comment by sp614x** [comment] 2017-05-22 13:35
Can the crash be reproduced with a minimal number of installed mods? Ideally Forge, OptiFine and the conflicting mod. A fast way to find the conflicting mod is:
1. Remove half of the mods, check if crashing
2. Keep the half of the mods that reproduce the crash, repeat from 1

At the end there should be only 1 conflicting mod left.

**Comment by KaiAF** [comment] 2021-03-28 17:42
Closing this as there has been no response from the author.

**Closed by KaiAF** 2021-03-28 17:42 UTC
