### ISSUE TITLE
[Visual Glitch] Clouds getting cut off on angles.

### ISSUE THREAD

**Issue by Bruce200** [sp614x/optifine#3760] opened 2020-04-18 22:54 UTC
#Description
Clouds are rendering cut off not at render distance but at diagonals, seemingly at render distance, just in the square of regular render distance.

## Steps to Reproduce
1. Open a world in 1.15.2
2. I would recommend getting up high (such as with elytra or creative flight) but it shouldn't be necessary.
3. Look up at the sky at an angle (not on cardinal directions)

##Optifine Version
preview_OptiFine_1.15.2_HD_U_G1_pre13. 

## Installation Method
Standalone installer

## Other Installed Mods
None

## Log Files/Crash Reports
None relevant

## F3 Debug Screenshot
![2020-04-18_18 49 57](https://user-images.githubusercontent.com/53529192/79673144-a8cfd080-81a5-11ea-8135-06b7ce80d194.png)

## Prior Testing
None, but it doesn't seem like something minecraft does. I was a bit limited on time when reporting this

## Additional Information
My computer is not the best, so this may be something on my end, but it does seem to me that the horizon is too high.

**Comment by Bruce200** [comment] 2020-04-19 12:56
My bad that some of the titles aren't there. I ended up deleting and then rewriting a couple of the hashtags incorrectly. Sorry, I hope the report is still fairly easily read.

**Comment by sp614x** [comment] 2020-05-28 23:15
Duplicate of 3453.

**Closed by sp614x** 2020-05-28 23:15 UTC
Labels: 1.15, duplicate, rendering
