### ISSUE TITLE
Optifine 1.13.2 HD U E5, can't launch a second time

### ISSUE THREAD

**Issue by gnapr** [sp614x/optifine#2142] opened 2018-12-31 17:25 UTC
I downloaded E4 a few days ago and launched it once, the only setting I changed was the control for zoom, then it wasn't able to launch a second time (vanilla did), it gave me a few lines of errors; but since I did notice the message that E5 had come out, I installed that one instead of reporting that. Now this message appears alone: `Optifine 1.13.2 HD U E5, could not find or load main class net.minecraft.launchwrapper.Launch`
I'm not using any other mods, java is updated, current texture pack loaded is the latest version of Dokucraft, OS is W10. Not even vanilla works now.

So I back up and reainstall .minecraft folder. Runs fine. I reinstall optifine, runs fine and I re adjust my controls plus some graphic settings. Closed the game, Tried launching again (didn't even move back my save files or picked a texture pack) and got this:

```
[11:24:06] [main/INFO]: Loading tweak class name net.minecraft.launchwrapper.VanillaTweaker
[11:24:06] [main/INFO]: Using primary tweak class name net.minecraft.launchwrapper.VanillaTweaker
[11:24:06] [main/INFO]: Calling tweak class net.minecraft.launchwrapper.VanillaTweaker
Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
	at net.minecraft.launchwrapper.VanillaTweaker.injectIntoClassLoader(VanillaTweaker.java:16)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

```

So, what now?

**Comment by sp614x** [comment] 2019-01-10 22:46
This is typically caused by custom launchers and can't be fixed by OptiFine: #1956, #1951, #1825, #1804, ...

**Closed by sp614x** 2019-01-10 22:46 UTC
