### ISSUE TITLE
[Visual Bug] Water not rendering properly after turning behind glass

### ISSUE THREAD

**Issue by prestofuoco** [sp614x/optifine#4501] opened 2020-07-30 01:33 UTC
## Description of Issue
When turning away from a body of water and turning back, water is sometimes not rendered properly until the full unrendered parts are in view.

## Steps to Reproduce
1. Face a body of water
2. Put a glass wall between the player and the water
3. Turn away from the water
4. Turn to the water again making sure to only have part of it in view

## OptiFine Version
OptiFine 1.16.1 HD U G2 pre12

## Installation Method
Included standalone installer

## Log Files/Crash Reports
[2020-07-29-2.log.gz](https://github.com/sp614x/optifine/files/4998263/2020-07-29-2.log.gz)
[latest.log](https://github.com/sp614x/optifine/files/4998264/latest.log)

## F3 Debug Screenshot
![2020-07-29_18 24 00](https://user-images.githubusercontent.com/68255079/88869929-ee4e6180-d1c8-11ea-811c-bdd634f51e8f.png)

## Prior Testing
Does not occur in vanilla

## Additional Information
Only happens behind glass, tested behind green and white-stained glass. Could not recreate the situation in vanilla.

**Comment by sp614x** [comment] 2020-07-30 16:51
Duplicate of #4504

**Closed by sp614x** 2020-07-30 16:51 UTC
