### ISSUE TITLE
Invisible Mobs 1.16

### ISSUE THREAD

**Issue by KakashoLin** [sp614x/optifine#5196] opened 2021-01-08 05:16 UTC
## Description of Issue
It seems that select mobs will turn invisible when running Optifune. My system only has Optifune, no additional shaders or addons.

## Steps to Reproduce
It seems to pop up when loading into the world, loading into a new chunk(new entities I think), and a chance with new mobs.

## OptiFine Version
Latest as of 1/7/21

## Installation Method
Standard install as described on Optifine website.

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/5785319/latest.log)

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/77138726/103977110-21186080-513e-11eb-8a26-ae81a4c60444.png)

## Prior Testing
If you've installed standalone:
This only occurs with Optifine, invisible mobs do not occur in the vanilla version of Minecraft

## Additional Information
Mobs that have disappeared for me are slimes, and the drowned. You can hear them still but not see them or even kill them. 

Here is a big Reddit thread about the issue: https://www.reddit.com/r/Optifine/comments/hx8kfp/mobs_turning_invisible_in_116/

**Comment by KakashoLin** [comment] 2021-01-08 05:38
So the slime pictured is a captured and named mob that disappeared for me and then reappeared once I exited and reloaded. My theory is that the mobs that disappear are not just created mobs but mobs that existed in the world already before the player got there. 

For example, I had an issue with disappearing drowned but this is also a mob that has the chance of not despawning under certain rules. 

"Ocean ruins
Drowned spawn during the generation of certain ocean ruin structures. These drowned do not naturally despawn unless the world is set to Peaceful difficulty."

I noticed this around the ocean and near some destroyed buildings that had chests, guessing the ocean ruins. Players also reported issues with the ender dragon and the bastion, both which generate non-despawnable mobs that are created during map generation. This means that regular spawning mobs such as creepers, skeletons and zombies are unaffected due to this nature.

**Comment by berkkrkc09** [comment] 2021-01-08 06:08
> So the slime pictured is a captured and named mob that disappeared for me and then reappeared once I exited and reloaded. My theory is that the mobs that disappear are not just created mobs but mobs that existed in the world already before the player got there.
> 
> For example, I had an issue with disappearing drowned but this is also a mob that has the chance of not despawning under certain rules.
> 
> "Ocean ruins
> Drowned spawn during the generation of certain ocean ruin structures. These drowned do not naturally despawn unless the world is set to Peaceful difficulty."
> 
> I noticed this around the ocean and near some destroyed buildings that had chests, guessing the ocean ruins. Players also reported issues with the ender dragon and the bastion, both which generate non-despawnable mobs that are created during map generation. This means that regular spawning mobs such as creepers, skeletons and zombies are unaffected due to this nature.

No no, I definetly had some invisible creepers but the rest makes sense to me.

**Comment by KakashoLin** [comment] 2021-01-08 06:29
> > So the slime pictured is a captured and named mob that disappeared for me and then reappeared once I exited and reloaded. My theory is that the mobs that disappear are not just created mobs but mobs that existed in the world already before the player got there.
> > For example, I had an issue with disappearing drowned but this is also a mob that has the chance of not despawning under certain rules.
> > "Ocean ruins
> > Drowned spawn during the generation of certain ocean ruin structures. These drowned do not naturally despawn unless the world is set to Peaceful difficulty."
> > I noticed this around the ocean and near some destroyed buildings that had chests, guessing the ocean ruins. Players also reported issues with the ender dragon and the bastion, both which generate non-despawnable mobs that are created during map generation. This means that regular spawning mobs such as creepers, skeletons and zombies are unaffected due to this nature.
> 
> No no, I definetly had some invisible creepers but the rest makes sense to me.

Do you remember if that happened shortly after reopening the world or chunk generation/reload?

**Comment by Regnander** [comment] 2021-01-08 08:11
Related #5016

**Comment by berkkrkc09** [comment] 2021-01-08 08:23
> > > So the slime pictured is a captured and named mob that disappeared for me and then reappeared once I exited and reloaded. My theory is that the mobs that disappear are not just created mobs but mobs that existed in the world already before the player got there.
> > > For example, I had an issue with disappearing drowned but this is also a mob that has the chance of not despawning under certain rules.
> > > "Ocean ruins
> > > Drowned spawn during the generation of certain ocean ruin structures. These drowned do not naturally despawn unless the world is set to Peaceful difficulty."
> > > I noticed this around the ocean and near some destroyed buildings that had chests, guessing the ocean ruins. Players also reported issues with the ender dragon and the bastion, both which generate non-despawnable mobs that are created during map generation. This means that regular spawning mobs such as creepers, skeletons and zombies are unaffected due to this nature.
> > 
> > 
> > No no, I definetly had some invisible creepers but the rest makes sense to me.
> 
> Do you remember if that happened shortly after reopening the world or chunk generation/reload?

Actually, I think the game was open for about 3 hours when it happened.

**Comment by KakashoLin** [comment] 2021-01-08 15:26
Named slime mob disappeared after playing for a bit. I did leave my base to explore and came back and then checked after a while and noticed it was gone again.

**Comment by KakashoLin** [comment] 2021-01-09 13:56
Yeah, it looks like if you name a mob, you are able to better test the glitch. I believe the issue is originating around world load/chunk load for mobs.

**Comment by CaPo4200** [comment] 2021-01-10 22:09
It is an actual bug in optifine, I get attacked by piglins, brutes, and hoglin every time I find bastion remnants in different survival world.

**Comment by berkkrkc09** [comment] 2021-01-10 22:24
> > > So the slime pictured is a captured and named mob that disappeared for me and then reappeared once I exited and reloaded. My theory is that the mobs that disappear are not just created mobs but mobs that existed in the world already before the player got there.
> > > For example, I had an issue with disappearing drowned but this is also a mob that has the chance of not despawning under certain rules.
> > > "Ocean ruins
> > > Drowned spawn during the generation of certain ocean ruin structures. These drowned do not naturally despawn unless the world is set to Peaceful difficulty."
> > > I noticed this around the ocean and near some destroyed buildings that had chests, guessing the ocean ruins. Players also reported issues with the ender dragon and the bastion, both which generate non-despawnable mobs that are created during map generation. This means that regular spawning mobs such as creepers, skeletons and zombies are unaffected due to this nature.
> > 
> > 
> > No no, I definetly had some invisible creepers but the rest makes sense to me.
> 
> Do you remember if that happened shortly after reopening the world or chunk generation/reload?

The game had been running for about 3 hours i think.

**Comment by KakashoLin** [comment] 2021-01-11 06:14
Okay, I am able to effectively repeat this multiple times.  I noticed it happening again to my pet slime that I named yesterday. Two main things I did yesterday was going to the nether and working on a base there and going to a faraway biome for foxes. Testing today, going to the nether and back did not trigger the bug, but going to the far away biome, many chunks away triggered the bug. To make sure it was caused by this, I repeated the experiment three times, and each time the slime vanished but I could still hear it. And between each test, I saved and exited and reentered and the slime would always reappear. I attached the distance I traveled and the f3 report in case that shows something of interest. 



![2021-01-10_23 44 35](https://user-images.githubusercontent.com/77138726/104151035-85872a00-53a1-11eb-94ba-da7e596439ad.png)

![2021-01-10_23 51 44](https://user-images.githubusercontent.com/77138726/104151049-8fa92880-53a1-11eb-8356-96611d1a56a3.png)

**Comment by berkkrkc09** [comment] 2021-01-11 08:48
So if the chunk unloads, OptiFine has some hard time to reload the mobs that was in that chunk?

**Comment by KakashoLin** [comment] 2021-01-11 10:30
> So if the chunk unloads, OptiFine has some hard time to reload the mobs that was in that chunk?

I am guessing, it seems to have issues unloading and reloading mobs that were in the chunk when the player left. It seems to just affect mobs that were already in that chunk or I am also guessing render range before Optifine starts to unload them. This is why you see this happening more often with mobs that typically don't despawn due to the nature of the bug. With that said, since the issue seems to be with chunk unloading and reloading, you can have it also affect mobs that normally despawn if the player moves back into range before daylight or before that mobs despawns, i.e invisible creepers.

**Comment by RuddiMinecraft** [comment] 2021-01-13 06:06
The same thing happens to me, but they can only be killed with a bow or crossbow, this happens to me when I start the game and there were hostile mobs near me at the end of the game.
I've been through skeletons, zombies and pillagers.

**Comment by KakashoLin** [comment] 2021-01-18 23:14
Checked and the issue is still present in the latest update that was released a few days ago, and the bug is still repeatable.

**Comment by sp614x** [comment] 2021-02-13 19:15
Duplicate of #5016

**Closed by sp614x** 2021-02-13 19:15 UTC
Labels: 1.16, chunks, entities, rendering
