### ISSUE TITLE
[1.16] Invisible items with Forge versions above 32.0.39

### ISSUE THREAD

**Issue by Skirikidik** [sp614x/optifine#4285] opened 2020-07-07 04:46 UTC
## Description of Issue
Blocks do not display when broken or stored in inventory/hotbar. Do not show up at all with shaders/resource packs disabled. Appear as blur with shaders/resource packs enabled.

## Steps to Reproduce
1. Bug/issue occurs on initial load with no special steps required.

## OptiFine Version
1.16.1 G1 and G2

## Installation Method
I have Optifine installed both as a separate installation and in the mods folder for Forge. 

## Fabric/Forge Version
1.16.1

## Other Installed Mods
None at this point

## Prior Testing
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
          **Yes**
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
          **No**
- Does this happen in OptiFine standalone?
          **No**
- Does this happen in Vanilla without OptiFine?
          **No**

## Additional Information

![invisibleblock](https://user-images.githubusercontent.com/67940569/86711570-b137ea80-bfe1-11ea-93ba-1e6e19f24633.png)
![invisiblehotbar](https://user-images.githubusercontent.com/67940569/86711595-b72dcb80-bfe1-11ea-90f1-94b06bdd5548.png)
![invisibleinventory](https://user-images.githubusercontent.com/67940569/86711610-bac15280-bfe1-11ea-98a8-f77a553e4369.png)
![invisibleblockswithshaders](https://user-images.githubusercontent.com/67940569/86712687-e09b2700-bfe2-11ea-8f58-de7415be757a.png)
![invisibleblocksinfo](https://user-images.githubusercontent.com/67940569/86712703-e55fdb00-bfe2-11ea-824d-77a8cdd8a7e6.png)

**Comment by Pofasdf** [comment] 2020-07-07 20:45
THis Is happening to me too

**Comment by 200Tigersbloxed** [comment] 2020-07-08 04:38
This happens to me when using Forge with Optifine and using Shaders. If I just have a resource pack on, it works, but when there's a shader, it'll do the same thing.

**Comment by Deviouslrd** [comment] 2020-07-08 04:41
Test this on forge 32.0.25, could be the forge version which is causing this issue.

**Comment by jestifizzle** [comment] 2020-07-08 15:18
#4277 also mentioned this. Use Forge version 32.0.39

**Comment by 200Tigersbloxed** [comment] 2020-07-09 02:33
After testing on forge 32.0.25, this issue does not happen for me anymore.

**Comment by papuSpartan** [comment] 2020-07-09 05:35
Also having the same issue

**Comment by Feanor7463** [comment] 2020-07-09 07:06
I've posted a bug report on Forge Bug Report Forum, I've been answered that : 

" Optifine is closed-source software that heavily modifies core parts of the game.
Any compatibility is on them. Talk to Optifine"

**Comment by sp614x** [comment] 2020-07-09 12:53
Duplicate of #4277

**Closed by sp614x** 2020-07-09 12:53 UTC
Labels: 1.16, bug, forge, rendering
