### ISSUE TITLE
Old Launcher Crashing

### ISSUE THREAD

**Issue by NovaDeltaZ147** [sp614x/optifine#1666] opened 2018-08-16 01:12 UTC
`Exception in thread "main" joptsimple.MultipleArgumentsForOptionException: Found multiple arguments for option gameDir, but you asked for only one
	at joptsimple.OptionSet.valueOf(OptionSet.java:179)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:51)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
`
I downloaded the latest version from the website and the old-launcher-fix.zip but the launcher still won't load up Optifine 1.13.

I recently used beta 1.7.3 if that has anything to do with it.

**Comment by skmedix** [comment] 2018-08-16 10:56
Try `old-launcher-fix2.zip` from #1635 
That should fix the problem

**Comment by sp614x** [comment] 2018-08-29 20:42
Duplicate of #1635.

**Comment by sp614x** [comment] 2018-08-29 21:09
Fixed in beta4.

**Closed by sp614x** 2018-08-29 21:09 UTC
Labels: 1.13, installer
