### ISSUE TITLE
Suffocation Causes Crash

### ISSUE THREAD

**Issue by tyabaryuu** [sp614x/optifine#3417] opened 2020-02-22 03:13 UTC
The game will crash the instant you take suffocation damage from an opaque block. This does not occur on vanilla Minecraft.

**Comment by asbyth** [comment] 2020-02-22 03:14
providing a crash report would help

**Comment by tyabaryuu** [comment] 2020-02-22 03:17
> ---- Minecraft Crash Report ----
> // I bet Cylons wouldn't have this problem.
> 
> Time: 2/22/20 4:10 AM
> Description: Unexpected error
> 
> java.lang.IndexOutOfBoundsException: bitIndex < 0: -1
> 	at java.util.BitSet.set(BitSet.java:444)
> 	at net.optifine.SmartAnimations.spriteRendered(SmartAnimations.java:38)
> 	at drd.a(OverlayRenderer.java:80)
> 	at drd.a(OverlayRenderer.java:34)
> 	at dqn.renderHand(GameRenderer.java:602)
> 	at dqn.a(GameRenderer.java:543)
> 	at dqn.a(GameRenderer.java:1002)
> 	at dqn.a(GameRenderer.java:684)
> 	at dbn.d(SourceFile:989)
> 	at dbn.d(SourceFile:619)
> 	at net.minecraft.client.main.Main.main(SourceFile:204)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at java.util.BitSet.set(BitSet.java:444)
> 	at net.optifine.SmartAnimations.spriteRendered(SmartAnimations.java:38)
> 	at drd.a(OverlayRenderer.java:80)
> 	at drd.a(OverlayRenderer.java:34)
> 	at dqn.renderHand(GameRenderer.java:602)
> 	at dqn.a(GameRenderer.java:543)
> 	at dqn.a(GameRenderer.java:1002)
> 
> -- Affected level --
> Details:
> 	All players: 1 total; [dqb['tyabaryuu'/1, l='MpServer', x=32.39, y=56.00, z=-38.59]]
> 	Chunk stats: Client Chunk Cache: 1369, 992
> 	Level dimension: minecraft:overworld
> 	Level name: MpServer
> 	Level seed: 3369561681592048835
> 	Level generator: ID 01 - flat, ver 0. Features enabled: false
> 	Level generator options: {}
> 	Level spawn location: World: (8,55,8), Chunk: (at 8,3,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
> 	Level time: 2561 game time, 2561 day time
> 	Known server brands: 
> 	Level was modded: false
> 	Level storage version: 0x00000 - Unknown?
> 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
> 	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
> 	Server brand: vanilla
> 	Server type: Integrated singleplayer server
> Stacktrace:
> 	at dno.a(ClientWorld.java:611)
> 	at dbn.c(SourceFile:1921)
> 	at dbn.d(SourceFile:639)
> 	at net.minecraft.client.main.Main.main(SourceFile:204)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.15.2
> 	Minecraft Version ID: 1.15.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_51, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 899364616 bytes (857 MB) / 1979711488 bytes (1888 MB) up to 2147483648 bytes (2048 MB)
> 	CPUs: 8
> 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> 	Launched Version: 1.15.2-OptiFine_HD_U_G1_pre7
> 	Backend library: LWJGL version 3.2.2 build 10
> 	Backend API: GeForce GTX 960M/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.19, NVIDIA Corporation
> 	GL Caps: Using framebuffer using OpenGL 3.0
> 	Using VBOs: Yes
> 	Is Modded: Very likely; Jar signature invalidated
> 	Type: Client (map_client.txt)
> 	Resource Packs: vanilla, file/VanillaBDcraft 128x MC115.zip
> 	Current Language: English (US)
> 	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
> 	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre7
> 	OptiFine Build: 20200221-181745
> 	Render Distance Chunks: 16
> 	Mipmaps: 4
> 	Anisotropic Filtering: 1
> 	Antialiasing: 0
> 	Multitexture: false
> 	Shaders: null
> 	OpenGlVersion: 4.6.0 NVIDIA 442.19
> 	OpenGlRenderer: GeForce GTX 960M/PCIe/SSE2
> 	OpenGlVendor: NVIDIA Corporation
> 	CpuCount: 8

**Comment by asbyth** [comment] 2020-02-22 03:17
dupe of #3412

**Comment by sp614x** [comment] 2020-02-22 20:59
Fixed, coming in pre8.

**Closed by sp614x** 2020-02-22 20:59 UTC
