### ISSUE TITLE
[visual bug] the time of day change 

### ISSUE THREAD

**Issue by bebeltu** [sp614x/optifine#5496] opened 2021-03-26 19:12 UTC
## Description of Issue
the time of day change to the night and the commands doesnt work 

## Steps to Reproduce
just making new or just joining a wolrd just changes the time of day but the cilent says its a day

## OptiFine Version
1.16.5_HD_U_G7

## Installation Method
standalone installer

## Log Files/Crash Reports
https://pastebin.com/Pg7e0Hy1
idk what this will help with bicause it didn`t crash

## F3 Debug Screenshot
![2021-03-26_20 47 25](https://user-images.githubusercontent.com/81439139/112679770-3cf5ed80-8e75-11eb-9f13-5523b45933f6.png)

https://user-images.githubusercontent.com/81439139/112679560-fb654280-8e74-11eb-86aa-688aa1ecce14.mp4

## Prior Testing
no it doesnt happen to vanilla when creating a new world when I tried to load a world i created in the video the glich still happens but not for new world. and on fabric version same thing happens and I have a fabrick version without optifine
## Additional Information
my pc spec: 
gtx 1050
intel core i3-7100
8gb ram 
222gb ssd
1tb hdd
resourcepacks in order :
1, scicraft background desert village
2, dramatic sky
3, vanilla tweaks

and the wold so you can chec it too 

https://drive.google.com/drive/folders/1qXmoZGXEOITZ3CHSybzUH_vkxEzzl9ug?usp=sharing

and the drivers are latest

**Comment by KaiAF** [comment] 2021-03-26 19:27
This most likely is not a bug. Go to video settings > Other > Time and set it to default.

**Comment by KaiAF** [comment] 2021-03-27 01:23
Closing this as this doesn't seem to be an issue. If you still think it is, let me know.

**Closed by KaiAF** 2021-03-27 01:23 UTC
