### ISSUE TITLE
[Category] FastMath

### ISSUE THREAD

**Issue by steviebeenz** [sp614x/optifine#5580] opened 2021-04-19 20:28 UTC
## Description of Issue
Fastmath changes potential Math results causing potential extra reach/less Velocity etc making the game worse. Also causes bugs in badly coded Anticheats although this is not the main point of this issue. 
Please fix the glitch where fastmath can cause changes to ingame limitations and physics this is meant to be a purely cosmetic mod. 

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?
Compared output values

## OptiFine Version

Any

## Installation Method

Standalone, but also in the jar ver

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
- no

**Comment by KaiAF** [comment] 2021-04-19 20:36
Duplicate of #5578.

**Closed by KaiAF** 2021-04-19 20:36 UTC

**Comment by steviebeenz** [comment] 2021-04-19 20:38
@KaiAF this is a different issue, the issue here is a non cosmetic feature the issue there is Anticheat compat problems.
