### ISSUE TITLE
I'm crashing whenever I get dropped items on the ground and have an error message pop up

### ISSUE THREAD

**Issue by Aarkhos** [sp614x/optifine#5967] opened 2021-07-04 08:52 UTC
So recently I've been playing with optifine on the fabric loader alongside optifabric for it to work and some life quality mods as well such as mini hud. I had this same everything on my game and was running it for a long time with no problems. However since yesterday when I tried to run the game after updating optifine to the newest preview version available, I have this issue where my game will crash every single time I pick up certain items. I know optifine doesn't have support for fabric but since I can't figure it out at all by myself, I really need help from someone to understand what's going on here. I have done everything I could to fix the issue, including reinstalling java, deleting the .minecraft and installing everything again! It worked for the tiniest bit then the issue started to happen again. It is the 1.17 version with the preview 21 optifine for 1.17. Everything was working just fine till I decided to update it to the newest preview wich it's the pre24 one. I also put some texture packs on my game as well. Then after that whenever I run my game and pickup certain items, i'll crash every single time. So far the items that have been crashing me it's deepslate bricks. Either deepslate bricks or slabs will do it. Wich it's very weird cause I was building a huge thing with those blocks and surely I have picked up a bunch of them before and it didn't happen. Even if I do downgrade it to the optifine to the version I was using (which it's pre21), it keeps happening. Also removing all the resource packs I have on my game won't help either. I also keep getting the Open GL error 1828 or somethin' like that in chat sometimes just before I crash, but most of the time the game just dies. I also get that error when items drop on the ground sometimes but only selected items will do the crash when I pick them up. The opti fabric it is for 1.16 version though, but again I have been using it alongside optifine pre21 for the longest time on 1.17 and had no problems whatsoever. Only now i'm getting this crashs which it's very unfortunate cause then I can't play at all unless I remove optifine, which I don't really want to do cause I'm really reliant of optifine.

**Update:** Apparently the issue has something to do with mini hud. When I tried removing the mods one by one, as I removed mini hud the issue didn't happened. I still would appreciate it if anybody can see the logs and let me know what's going on for this to happen!!

## Steps to Reproduce

I don't know what do I do for this to happen really. What I did was to upgrade the preview 21 to preview 24 of the optifine for 1.17. And I added a few resource packs as well. Everything was working just fine and i've been playing for the longest time with this setup. Only now i'm getting this error. I tried downgrading the optifine back to pre21 and removed the resource packs all together but that didn't solve it. To reproduce it just have the same mods I do alongside optifine and optifabric then you drop an item into the ground and pick it up (only certain items will do, which you might have to check which ones are)

**Update:** Aparently it's something to do with compatibility with mini hud. So I'll assume to reproduce it just have minihud, optifabric and optifine on the mods folder then launch the game and drop a certain item and pick it up, then it'll crash.

## OptiFine Version

preview_OptiFine_1.17_HD_U_G9_pre21 and pre24

## Installation Method

Dropped into mods folder alongside opti fabric on a fabric instance.

## Fabric/Forge Version

fabric-loader-0.11.6-1.17

## OptiFabric Version

optifabric 1.11.1

## Other Installed Mods

itemscroller-fabric-1.17.0-0.15.0-dev.20210608.211652
litematica-fabric-1.17.0-0.0.0-dev.20210608.211719
malilib-fabric-1.17.0-0.10.0-dev.22+beta.1
minihud-fabric-1.17.0-0.19.0-dev.20210609.185508
modmenu-2.0.0-beta.7
optifabric-1.11.1
servux-fabric-1.17.0-0.1.0
tweakeroo-fabric-1.17.0-0.10.0-dev.20210608.211857
fabric api - although my friend told me to remove it from the mods folder after I was done installing optifine and it's been working that way since then but now I'm getting this error and crashing all the time. 

## Log Files/Crash Reports

I'll drop the logs I think have the issue on them but I got no idea whats going on in those logs. I cannot understand those at all so i'll just drop it here the links to the paste bin I just uploaded with them.

logs:

https://pastebin.com/dBPZWrbH
https://pastebin.com/Xe7HzZGF (I did remove the chat messages from this one cause i was playing on a server)
https://pastebin.com/74DVrgpU

I did not have the crash-reports folder but I had some hs_err_pid files which contain the errors I'm getting but have no clue what it means:

https://pastebin.com/03GaSfeS
https://pastebin.com/Pi87iDYQ
https://pastebin.com/nteceCfJ

## F3 Debug Screenshot

For the f3 menu screenshot I just open it up on a creative world. Which I also get the same issue, and it's with light blue wool I dropped on the ground to test it out. Not sure about the deepslate though I didn't test it out. It's kinda of a bummer to having it crash every single time I get items, for me to test what items cause it or not. 

https://imgur.com/a/4tPCZIb 

## Prior Testing

I did some testing. Removed the mods one by one and launched the game on each time to see if the issue would persist. Aparently it's something to do with the mini hud mod. If I run it with all the mods I have but minihud, it'll work just fine. With it It'll keep happening every single time.

## Additional Information

I'd really appreciate it if anybody would help me out to figure this out and to help me to understand the logs cause I cannot understand those at all!!! 

**Update:** I really enjoy minihud, it has some very useful features and it's a lot easier to build somethings with it. I don't really wanna play without it. I'd appreciate it if somebody who understands of this kinda of stuff could tell me what's going on with this

**Comment by Chocohead** [comment] 2021-07-04 16:14
Just to clarify, is the game actually stopping or are you just getting span in the chat?

**Comment by Aarkhos** [comment] 2021-07-05 14:54
> Just to clarify, is the game actually stopping or are you just getting span in the chat?

It does actually stop. The game will just crash whenever I pick up an item, if I have this version of mini hud and optifine on fabric instance. Which it's odd cause wasn't happening before. But since I found out that is mini hud causing it, i've gone into mini huds page into forge and I leave a comment about it there. The owner of the project replied to me saying that after someone else reported a similar issue, they went to fix it and apparently it's fixed now on this version of minihud they sent me the link to. Guess I should just close this issue now then? I posted it here cause I thought it was just an optifine error which I found out that was not.

**Comment by KaiAF** [comment] 2021-07-07 00:48
Both the chat spam and the crash is caused by Nvidia Drivers.
`Problematic frame: C  [nvoglv64.dll+0xed13d2]`
Try updating your drivers, or re-installing them. Or just revert to a past driver if that doesn't help. 
Try updating Minihud, you said it's apparently fixed. If it doesn't crash in that version, close the issue

**Closed by KaiAF** 2021-07-07 00:48 UTC
