### ISSUE TITLE
Weird corner visual glitch

### ISSUE THREAD

**Issue by OmegaMiko** [sp614x/optifine#7069] opened 2022-08-14 21:34 UTC
[##](url) Description of Issue
I was playing on a minecraft world, and i had my shaders on and i logged back into my world and then i see the weirdest thing, all of the blocks now have this weird corner thing, i dont know how to explain it

## OptiFine Version
1.19.1

## Installation Method
i dropped the jar into the mods folder. 

## Fabric/Forge Version
1.19.1

## Other Installed Mods
Xaeros minimap, Xaeros worldmap 

## Prior Testing
this does not happen when i disable my shaders.

![2022-08-14_22 33 11](https://user-images.githubusercontent.com/111251128/184555740-9c2100ae-2917-4d57-8384-e18810a5209e.png)

![2022-08-14_22 33 14](https://user-images.githubusercontent.com/111251128/184555735-67b1ea90-8094-4e97-ae41-03f2a9197590.png)

**Comment by UnknownTheLad** [comment] 2022-08-14 21:37
Duplicate of #7043

**Comment by xicromok** [comment] 2022-08-17 18:43
> [##](url) Description of Issue I was playing on a minecraft world, and i had my shaders on and i logged back into my world and then i see the weirdest thing, all of the blocks now have this weird corner thing, i dont know how to explain it
> 
> ## OptiFine Version
> 1.19.1
> 
> ## Installation Method
> i dropped the jar into the mods folder.
> 
> ## Fabric/Forge Version
> 1.19.1
> 
> ## Other Installed Mods
> Xaeros minimap, Xaeros worldmap
> 
> ## Prior Testing
> this does not happen when i disable my shaders.
> 
> ![2022-08-14_22 33 11](https://user-images.githubusercontent.com/111251128/184555740-9c2100ae-2917-4d57-8384-e18810a5209e.png)
> 
> ![2022-08-14_22 33 14](https://user-images.githubusercontent.com/111251128/184555735-67b1ea90-8094-4e97-ae41-03f2a9197590.png)

I had the same problem and I have solved it.

Apparently it's a compatibility issue between the latest versions of OptiFine and Forge, so I've decided to replace OptiFine with Rubidium + Oculus. Not only was I able to fix the texture bug, but I was also able to install all the mods I wanted with no problem.

**Comment by sp614x** [comment] 2022-08-23 10:06
Duplicate of https://github.com/sp614x/optifine/issues/7043

**Closed by sp614x** 2022-08-23 10:06 UTC
