### ISSUE TITLE
[Minecraft] Some piglin brutes are invisible inside bastion remnants

### ISSUE THREAD

**Issue by noobdude752** [sp614x/optifine#5317] opened 2021-02-12 17:20 UTC
## Description of Issue
If you find any bastion remnant in Optifine 1.16, some of the piglin brutes are invisible and will kill you in a matter of seconds.

## Steps to Reproduce
Find a bastion remnant in the Nether, and go inside. If you're in survival, chances are you'll be attacked by one.

## OptiFine Version
1.16.3, 1.16.4, 1.16.5

## Installation Method
Standalone installer

## Other Installed Mods
Railcraft 1.12.2

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
- No

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by sp614x** [comment] 2021-02-13 19:15
Duplicate of #5016

**Closed by sp614x** 2021-02-13 19:15 UTC
