### ISSUE TITLE
[1.16.1] Invisible Items

### ISSUE THREAD

**Issue by ELG-Icefish** [sp614x/optifine#4304] opened 2020-07-09 09:12 UTC
All Items get Invisible if i use any shader, even the internal one,

**Comment by sp614x** [comment] 2020-07-09 11:21
Running with Forge, Fabric or standalone?

**Comment by FireGB** [comment] 2020-07-09 14:09
I have the same problem, and I'm using forge. Perhaps it doesn't occur on standalone or fabric though?

**Comment by SoullessShadow** [comment] 2020-07-09 15:40
Sames happening to me, currently using Forge with it. Haven't tested without it but seems to be a little buggy. Here's how it looks for me:
https://imgur.com/gallery/omTXoqZ

**Comment by jennasisis** [comment] 2020-07-10 03:10
Hola, optifine 1.16.1 pre 2, no invisible items on internal shaders running standalone

**Comment by Feanor7463** [comment] 2020-07-10 12:18
Seems to be the same that #4277

**Comment by sp614x** [comment] 2020-07-10 12:36
Duplicate of #4277

**Closed by sp614x** 2020-07-10 12:36 UTC
Labels: 1.16, details needed, rendering
