### ISSUE TITLE
Internal Shaders make inventory items invisible

### ISSUE THREAD

**Issue by FireGB** [sp614x/optifine#4305] opened 2020-07-09 14:06 UTC
When turning on the internal shaders, items in your inventory will turn invisible.

**Comment by technikmc88** [comment] 2020-07-10 06:38
I have the same

**Comment by Feanor7463** [comment] 2020-07-10 12:16
Maybe same issue than #4277 ?

**Comment by sp614x** [comment] 2020-07-10 13:21
Duplicate of #4277

**Closed by sp614x** 2020-07-10 13:21 UTC
