### ISSUE TITLE
[1.15.2] Mobs don't flash red when damaged

### ISSUE THREAD

**Issue by LightZack** [sp614x/optifine#3958] opened 2020-05-16 19:58 UTC
## Description of Issue
When TNT or creepers get set off they don't flash nor do players flash red when they take damage the same with mobs both passive and aggressive.

## Steps to Reproduce
1. Set off TNT and or a creeper
2. Press f5 and see that the red flashing doesn't appear when you take damage or just hit another player/mob

## OptiFine Version
Optifine 1.15.2 Pre16-17

## Installation Method
Used the standalone installer

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No

**Comment by AlyxLight** [comment] 2020-06-09 23:22
This issue still remains in Pre23 version, no red damage flashing with any shaders applied (even default in-built OptiFine shaders), only disabling all shaders while running OptiFine fixes this.

**Comment by AlyxLight** [comment] 2020-06-16 14:05
Issue is still present in Pre26 version.

**Comment by sp614x** [comment] 2020-06-21 09:32
Duplicate of #3598

**Closed by sp614x** 2020-06-21 09:32 UTC
Labels: 1.15, shaders
