### ISSUE TITLE
Inventory bar texture bugs

### ISSUE THREAD

**Issue by Rangel777** [sp614x/optifine#3854] opened 2020-05-04 04:22 UTC
![2020-05-04_01 15 11](https://user-images.githubusercontent.com/64765346/80936031-bee4b000-8da5-11ea-895a-0539dabd9dca.png)

**Comment by Rangel777** [comment] 2020-05-04 04:23
forge last upd + optfine last upd (1.15.2)

**Comment by asbyth** [comment] 2020-05-04 06:01
known

**Comment by yezhiyi9670** [comment] 2020-05-04 10:04
Duplicate of #3837

**Comment by Regnander** [comment] 2020-05-04 12:30
>Duplicate of #3837 

Which in turn is a duplicate of #3830

**Comment by Rangel777** [comment] 2020-05-04 16:44
i didnt know, sorry

**Comment by Regnander** [comment] 2020-05-04 20:01
> i didnt know, sorry

No harm done. Don't worry about it.

**Comment by sp614x** [comment] 2020-05-05 22:42
Duplicate of #3830.

**Closed by sp614x** 2020-05-05 22:42 UTC
