### ISSUE TITLE
CEM armor on edited entity

### ISSUE THREAD

**Issue by zubiden** [sp614x/optifine#817] opened 2017-08-05 17:50 UTC
Armor uses standart entity model for displaying. 
(On screenshot edited body rotation)
![2017-08-05_20 47 21](https://user-images.githubusercontent.com/19638254/28997524-ab476c32-7a1f-11e7-8601-943651042fb1.png)

**Comment by ewanhowell5195** [comment] 2024-09-13 14:56
duplicate of #561

**Closed by ewanhowell5195** 2024-09-13 14:56 UTC
Labels: CEM
