### ISSUE TITLE
Crash on launch of pre2 on Linux mint

### ISSUE THREAD

**Issue by Ecence1** [sp614x/optifine#1818] opened 2018-09-21 01:16 UTC

**Comment by HopefulFire** [comment] 2018-09-21 04:43
I have the same issue, openjdk 10.0.2+13-1ubuntu0.18.04.2.

**Comment by giammod** [comment] 2018-09-21 06:17
I'm on Linux and it did crash te first couple times , but now it runs fine. make sure you're giving minecraft enough memory

**Comment by HopefulFire** [comment] 2018-09-21 12:14
Doesn't fix for me. What system/java were you using? Generally, I have never found it necessary to give Optifine more memory than vanilla Minecraft.

**Comment by giammod** [comment] 2018-09-21 12:34
I'm on the latest version of everything(Mint 18.2x64, Java 1.8.0_181x64)   I give Minecraft 3GB for optifine as my laptop only has 8GB total.

what is your java version ("java -version" in the terminal)?

**Comment by HopefulFire** [comment] 2018-09-21 12:49
I am on the latest version of linux mint with the latest version of openjdk
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2, mixed mode)
Vanilla minecraft server and minecraft client work just fine with latest version (+ it's supposed to be backwards-compatable, except it's not always) and I switched because I noticed a slight performance enhancement when using latest open-jdk as opposed to bundled open-jdk. My system has 8 gb, normally I allocate 2 as I don't want to go overboard with how much memory I use. The computer I use is an old quad core dell tower.
Linux Mint 19 Cinnamon 3.8.9
Kernel 4.15.0-34-generic
Intel© Core™ i5-4440 CPU @ 3.10GHz × 4
Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller
http://termbin.com/5p20

**Comment by HopefulFire** [comment] 2018-09-21 13:28
It should be noted that as most distributions come with bundled java 8 installed with minecraft (including linux mint), this is an extraordinary problem. This is only for people using /usr/bin/java (system java) as the java executable (as opposed to bundled executable) using openjdk 9+. I would like to use the faster and more secure version of java if possible, though I know mojang only officially supports java 8, the vanilla game does not crash with java 9+.

**Comment by Ecence1** [comment] 2018-09-21 13:32
so i should try updating my java?

**Comment by sp614x** [comment] 2018-09-21 13:53
Crash report or error log?

**Comment by HopefulFire** [comment] 2018-09-21 13:54
https://minecraft.net/en-us/download/alternative/
minecraft.deb _should_ work, but minecraft.tar.gz requires java 8 to be installed as opposed to java 9+. I think this issue will be fixed by sp614x eventually, but if you want to run optifine e3 pre2 right now you would either need to install java 8 on your system (linux mint uses a newer version by default) or download the .deb package and install it. If you are using the unofficial port in the software manager, I have no idea whether it comes with java 8

**Comment by HopefulFire** [comment] 2018-09-21 13:58
### Launcher Log
[0921/095453:INFO:LauncherAppBrowser.cpp(24)] Work dir is /home/jade/.minecraft

[0921/095453:INFO:ClientHandler.cpp(182)] Creating launcher window.

[0921/095453:WARNING:mainLinux.cpp(25)] X error received: type 0, serial 293, error_code 8, request_code 42, minor_code 0

[0921/095453:INFO:LauncherAppRenderer.cpp(110)] Javascript bridge extended.

[0921/095455:INFO:ClientHandler.cpp(859)] Preferences / startup: Read preferences

[0921/095455:INFO:ClientHandler.cpp(859)] Preferences: Wrote preferences

[0921/095455:INFO:ClientHandler.cpp(859)] Configurations: Loading profiles

[0921/095455:INFO:ClientHandler.cpp(859)] Configuration a65b58da85fb84d686e93a28113c4308: Wed Dec 31 1969 19:00:00 GMT-0500 (EST) < 2018-09-21T04:51:24.987Z

[0921/095455:INFO:ClientHandler.cpp(859)] Configuration 628519cf33e5e47a34eb98ac235e5026: Fri Sep 21 2018 00:51:24 GMT-0400 (EDT) < 1970-01-01T00:00:00.000Z

[0921/095455:INFO:ClientHandler.cpp(859)] Configuration OptiFine: Fri Sep 21 2018 00:51:24 GMT-0400 (EDT) < 2018-09-21T12:16:16.522Z

[0921/095455:INFO:ClientHandler.cpp(859)] Configurations: Loading settings

[0921/095455:INFO:ClientHandler.cpp(859)] Session: Read authDB

[0921/095455:INFO:LocalVersionProvider.cpp(82)] Looking for installed versions in /home/jade/.minecraft/versions

[0921/095455:INFO:ClientHandler.cpp(859)] Updating server status

[0921/095455:INFO:GameController.cpp(233)] Reinstancing game callbacks...

[0921/095455:INFO:ClientHandler.cpp(859)] Preferences: Wrote preferences

[0921/095455:INFO:ClientHandler.cpp(859)] GameStarter: Previous instance(s) found

[0921/095456:INFO:ClientHandler.cpp(859)] Session: Validated token

[0921/095456:INFO:ClientHandler.cpp(859)] Preferences: Wrote preferences

[0921/095456:INFO:ClientHandler.cpp(859)] Session: Wrote authDB

[0921/095456:INFO:ClientHandler.cpp(859)] Changing view to: main.news

[0921/095459:INFO:ClientHandler.cpp(859)] Preferences: Wrote preferences

[0921/095459:INFO:ClientHandler.cpp(859)] Matching rules for version 1.13.1-OptiFine_HD_U_E3_pre2

[0921/095459:INFO:ClientHandler.cpp(859)] No rules -> true...

[0921/095459:INFO:ClientHandler.cpp(859)] {"jvm":["-Xss1M","-Djava.library.path=${natives_directory}","-Dminecraft.launcher.brand=${launcher_name}","-Dminecraft.launcher.version=${launcher_version}","-cp","${classpath}","-Xmx4G"],"game":["--username","${auth_player_name}","--version","${version_name}","--gameDir","${game_directory}","--assetsDir","${assets_root}","--assetIndex","${assets_index_name}","--uuid","${auth_uuid}","--accessToken","${auth_access_token}","--userType","${user_type}","--versionType","${version_type}","--tweakClass","optifine.OptiFineTweaker"]}

[0921/095459:INFO:ClientHandler.cpp(859)] No rules -> true...

[0921/095459:INFO:ClientHandler.cpp(859)] No rules -> true...

[0921/095459:INFO:ClientHandler.cpp(859)] No rules -> true...

[0921/095459:INFO:ClientHandler.cpp(859)] No rules -> true...

[0921/095459:INFO:ClientHandler.cpp(859)] No rules -> true...

[0921/095459:INFO:ClientHandler.cpp(859)] No rules -> true...

[0921/095459:INFO:ClientHandler.cpp(859)] No rules -> true...

[0921/095459:INFO:ClientHandler.cpp(859)] No rules -> true...

[0921/095459:INFO:ClientHandler.cpp(859)] No rules -> true...

[0921/095459:INFO:ClientHandler.cpp(859)] No rules -> true...

[0921/095459:INFO:ClientHandler.cpp(859)] No rules -> true...

[0921/095459:INFO:ClientHandler.cpp(859)] No rules -> true...

[0921/095459:INFO:ClientHandler.cpp(859)] No rules -> true...

**Comment by HopefulFire** [comment] 2018-09-21 13:59
There are no other logs I can find...

**Comment by HopefulFire** [comment] 2018-09-21 14:01
![screenshot from 2018-09-21 08-08-41](https://user-images.githubusercontent.com/43461825/45885744-42928a00-bd85-11e8-9aeb-85e3aaf70b1c.png)

**Comment by HopefulFire** [comment] 2018-09-21 14:03
Seems to be pretty fatal, not even a crash log I can find. It crashes in the launcher it seems

**Comment by HopefulFire** [comment] 2018-09-24 01:28
I don't know if any other versions do this but pre1 and pre2 do. I haven't been using optifine as a result

**Comment by Ecence1** [comment] 2018-09-28 00:12
It is still happening  on pre4, instant crash.

**Comment by giammod** [comment] 2018-09-28 08:51
I wish we could test amongst more Linux users. I'm on Linux and it hasn't crashed since the time I mentioned earlier. pre3 and 4 work fine on my Linux. I must wonder if your crash is caused by something else.

**Comment by Ecence1** [comment] 2018-09-28 09:03
I’m gunna try checking for Linux updates

**Comment by HopefulFire** [comment] 2018-09-28 15:50
I am fully updated

**Comment by HopefulFire** [comment] 2018-09-28 15:57
I think it's the latest openjdk, because vanilla minecraft is now broken. I have a separate server running on my machine, but while I am able to use books just fine, given that I am using the same version of java, my friend on windows 10 with the java that comes with minecraft can't edit, sign, or put books in chests without getting forcibly kicked. I will try installing java 8 later to see if that fixes our problems. The reason I was not using the java that comes with minecraft is because it is missing the authentication libraries. This might just be all mojang's fault....

**Comment by HopefulFire** [comment] 2018-09-28 16:00
I would have been running both the server and the client on mojang's "official" java 8 if we were able to play online mode! Just curious, why do devs never update java/other languages?

**Comment by HopefulFire** [comment] 2018-09-28 16:04
Pre 4 also crashes

**Comment by HopefulFire** [comment] 2018-09-28 16:11
giammod, maybe you are not using latest openjdk but bundled? If you look at your task manager it should say the path you are using (after starting minecraft). If it says /usr/bin/java, you are using system java, if it uses the minecraft directory, most likely it's running jdk 8

**Comment by giammod** [comment] 2018-09-28 22:39
When you say task manager, I assume you mean system monitor, in which case I have two java processes running when I start minecraft, one is java -jar /usr/share/minecraft/minecraft.jar
and one is  /usr/lib/jvm/java-8-openjdk-amd64/jre/<and on>

How are you playing minecraft? are you launching minecraft.jar directly? or are you using the minecraft launcher you can get from "software manager"? I recommend the latter.

**Comment by Strum355** [comment] 2018-10-08 21:21
Minecraft doesnt seem to work with the OpenJDK runtime for some reason. You'll have to use the oracle runtime isntead
How to:
```
sudo add-apt-repository ppa:webupd8team/java
sudo apt update
sudo apt install oracle-java8-installer
sudo update-alternatives --config java
```
For the last one, select the number that says something like `/usr/lib/jvm/java-8-oracle/jre/bin/java`
That should solve your issue

**Comment by Ecence1** [comment] 2018-10-08 22:09
Thank you so much!

**Closed** 2018-10-12 15:13 UTC
Labels: crash, details needed

**Comment by HopefulFire** [comment] 2018-10-14 21:15
This issue should be reposted as an issue with openjdk 9+

**Comment by Rfvgyhn** [comment] 2018-12-05 02:18
Just wanted to add the Arch specific instructions for @Strum355 's instructions. Need to install [jre8](https://aur.archlinux.org/packages/jre8/) from the aur and then set optifine's launch options to point to it instead of the default open-jdk.

![optifine](https://user-images.githubusercontent.com/731861/49485702-1a99bb00-f7f9-11e8-8846-a3b9af9f0d6d.png)

**Comment by Strum355** [comment] 2018-12-05 14:16
Good idea about changing the location in optifine

**Comment by Mhowser** [comment] 2019-04-30 07:48
@Strum355 your solution does not work anymore due to Oracle requiring java users to login for getting updates. https://launchpad.net/~webupd8team/+archive/ubuntu/java
