### ISSUE TITLE
Textures not working on models 1.15.2 pre23

### ISSUE THREAD

**Issue by UnearthedPenny1** [sp614x/optifine#4080] opened 2020-06-11 23:46 UTC
## Description of Issue
Please provide as much detail as possible.

## Steps to Reproduce
1. Create an item texture.
2. Create a model for said texture via blockbench.
3. Get the model working in game.
4. The textures do not appear.
5. They appear on 1.14.4 for reference that they were made properly.

## OptiFine Version
1.15.2 pre23

## Installation Method
Standalone installer

## Log Files/Crash Reports
N/A

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/22648260/84449711-2ea74f80-ac1c-11ea-8948-d6237caa2c44.png)

## Prior Testing
If you've installed standalone:
No. Optifine specific issue

## Additional Information
As I said before, it works properly in 1.14.4 OptiFine.

**Comment by CHead2000** [comment] 2020-06-12 15:06
Having same issue with some Minecolonies blocks
![2020-06-12_10 48 10](https://user-images.githubusercontent.com/65131882/84517026-aa48e100-ac9c-11ea-91c1-7ce56a06c9ec.png)
![2020-06-12_10 48 20](https://user-images.githubusercontent.com/65131882/84517034-ac12a480-ac9c-11ea-8e42-928dbbae32df.png)
![2020-06-12_10 47 55](https://user-images.githubusercontent.com/65131882/84517041-addc6800-ac9c-11ea-9299-a9eb171b0559.png)
Log: [latest.log](https://github.com/sp614x/optifine/files/4771551/latest.log)

**Comment by sp614x** [comment] 2020-06-20 21:48
Duplicate of #4046.
Fixed in pre29.

**Closed by sp614x** 2020-06-20 21:48 UTC
Labels: 1.15, CIT, models

**Comment by HadesDeadlyTom** [comment] 2020-06-21 15:07
I still have problems with minecolonies using pre29. Is this another issue or should it work ?

**Comment by SmokePuddingEveryday** [comment] 2020-07-19 00:07
Issue still seems to be present on pre30 too.

**Comment by invocador18** [comment] 2020-09-12 20:34
The problem persists on pre30
