### ISSUE TITLE
Signs are invisible! (and probably other blocks as well)

### ISSUE THREAD

**Issue by FireGB** [sp614x/optifine#4280] opened 2020-07-06 22:33 UTC
Signs are invisible, and I assume that that other blocks are as well. I can see its hotbox when my cross hair is on it, but the actual texture is completely transparent.

**Comment by MunchkinMiester** [comment] 2020-07-07 16:01
is this an optifine issue? try f3+a or place a block

**Comment by fresnizky** [comment] 2020-07-08 02:53
This happened to me with chests on Fabulous graphic settings. Using Fancy textures show correctly

**Comment by yezhiyi9670** [comment] 2020-07-08 04:45
This happens only when using Fast Render + Fabulous. The problem that "some blocks are invisible" is actually "Entities and TileEntities are invisible".

**Comment by FireGB** [comment] 2020-07-08 17:15
Well, it’s gonna be fixed before the main release, right?

**Comment by FireGB** [comment] 2020-07-08 17:16
> is this an optifine issue? try f3+a or place a block

Yes, it’s definitely an Optifine issue, I triple checked!

**Comment by sp614x** [comment] 2020-07-09 13:26
Duplicate of #4289

**Closed by sp614x** 2020-07-09 13:26 UTC
