### ISSUE TITLE
1.15.2G1pre10 - Custom Model CIT Item Displays Custom Model in GUI But Oak Sign in hand and Item Frame

### ISSUE THREAD

**Issue by Dlpettit** [sp614x/optifine#3595] opened 2020-03-27 22:42 UTC
## Description of Issue
I Have a Few Custom Models That Use CIT Oak Signs Named But The Items Models only appear In the Gui and Not In Hand and Item Frame They still look like an Oak Sign

**Comment by sp614x** [comment] 2020-05-28 19:09
Duplicate of #3276.

**Closed by sp614x** 2020-05-28 19:09 UTC
Labels: 1.15, CIT, duplicate
