### ISSUE TITLE
[Entities Textures Bug] When reloading the chunk, the entities, are bugged

### ISSUE THREAD

**Issue by TheCiROMG** [sp614x/optifine#4422] opened 2020-07-23 13:09 UTC
## Description of Issue

when reloading the chunk, the entities, MOBS in this case, are bugged, the textures stay in place, but the entities move
It also happens with server users, their user becomes invisible but the texture is still

## Steps to Reproduce
1. Reload the chunk or move to other chunk to load
2. I happen to be killing the MOB and just at the moment of hitting it I HAVE IT IN FRONT but I HEAR IT BACK

## OptiFine Version
OptiFine 1.16.1 HD U G2 pre8 (22.07.2020)

## Installation Method
Official page, vanilla

## Log Files/Crash Reports

NO LOG FILES

## F3 Debug Screenshot

None, Sorry T.T

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

Solo pasa en vanilla, por lo que se, ya que no uso otros variantes

**Comment by sp614x** [comment] 2020-07-23 13:44
Duplicate of #4414

**Closed by sp614x** 2020-07-23 13:44 UTC
