### ISSUE TITLE
View is flipped

### ISSUE THREAD

**Issue by Snakedog49** [sp614x/optifine#1636] opened 2018-08-11 22:28 UTC
For some reason when I launched optifine up when I got into my world the entire view was flipped
![2018-08-11_17 21 22](https://user-images.githubusercontent.com/37782112/43996596-ede03548-9d8b-11e8-8753-397bf559ab8e.png)

**Comment by Dushess** [comment] 2018-08-12 00:07
Huh, i can imagine, how to walk there.

**Comment by realjackasterisk** [comment] 2018-08-12 00:45
This is caused by anti-aliasing. Disable it in video settings and it should be fixed.

**Comment by sp614x** [comment] 2018-08-26 16:18
OptiFine 1.13_HD_U_E3_alpha9
 - fixed FXAA flipping screen vertically

**Closed by sp614x** 2018-08-26 16:18 UTC
Labels: 1.13
