### ISSUE TITLE
[Bug Report] Over half of Piglin Brute's are completely invisible in Single Player worlds.

### ISSUE THREAD

**Issue by osuHylian** [sp614x/optifine#4744] opened 2020-08-31 00:48 UTC
## Description of Issue
Please provide as much detail as possible.
Roughly 60% of Piglin Brute's are completely invisible, I can hear them but I can not see them.

## Steps to Reproduce
1. Run OptiFine 1.16.2 HD U G3
2. Enter single player survival world and find a naturally spawned bastion in the nether, look around for Piglin Brute's.

## OptiFine Version
OptiFine 1.16.2 HD U G3 or any of the 1.16.2 pre versions
## Installation Method
Installer

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
It does not.

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.
I can't really post a screenshot since I can't see them but it has happened at two different bastions so I assume it's reproducible.

**Comment by osuHylian** [comment] 2020-08-31 20:08
Sorry if I'm supposed to add labels, I don't know how :/

**Comment by Regnander** [comment] 2020-09-02 15:00
Related #4322

**Comment by Teasy** [comment] 2020-12-11 11:12
Related thread:
https://github.com/sp614x/optifine/issues/5016

**Comment by sp614x** [comment] 2021-02-13 19:17
Duplicate of #5016

**Closed by sp614x** 2021-02-13 19:17 UTC
