### ISSUE TITLE
[1.15.x] glowing effects with shaders freezes screen

### ISSUE THREAD

**Issue by resinate** [sp614x/optifine#3994] opened 2020-05-26 02:12 UTC
when using any shader pack on 1.15.x if a mob has glowing white effect on, screen freezes. this doesnt happen if optifine is by itself with no shaders. no other mods or forge installed.

**Comment by sp614x** [comment] 2020-05-28 19:05
Running with Forge, Fabric or standalone?
GPU or integrated graphics?
OS?
Have you tried updating the graphics drivers?

**Comment by yezhiyi9670** [comment] 2020-05-29 00:57
Is it #3996? It sometimes cause the game to freeze.

**Comment by sp614x** [comment] 2020-06-06 12:13
This only happens for invisible entities with glowing effect.
Duplicate of #3996.

**Closed by sp614x** 2020-06-06 12:13 UTC
Labels: 1.15, details needed, glowing, shaders
