### ISSUE TITLE
Weird textures

### ISSUE THREAD

**Issue by Karl9ign** [sp614x/optifine#3347] opened 2020-02-16 15:38 UTC
I don't know how to explain, but heres pictures https://imgur.com/a/RFy0cYo

**Comment by Eletroboss** [comment] 2020-02-16 16:08
I have the same problem: a chunk doesn't load and there's a giant (sometimes flickering) mass of broken geometry. You can fix it by pressing F3+A for the time being. (Just to make it clear, I'm not a dev and that's not the official statement it's just a workaround I found)
Here are some pictures I got (ignore the server console at the top):

![Screenshot from 2020-02-14 18-54-07](https://user-images.githubusercontent.com/56803208/74608065-feb8c700-50d5-11ea-954f-820d204c1247.png)
![Screenshot from 2020-02-14 18-54-16](https://user-images.githubusercontent.com/56803208/74608069-02e4e480-50d6-11ea-8fec-1e360baa3640.png)
![Screenshot from 2020-02-15 08-06-57](https://user-images.githubusercontent.com/56803208/74608070-07110200-50d6-11ea-9528-d38420544141.png)
![Screenshot from 2020-02-15 17-19-26](https://user-images.githubusercontent.com/56803208/74608074-0bd5b600-50d6-11ea-8abc-e18497d600cc.png)
![Screenshot from 2020-02-16 15-26-08](https://user-images.githubusercontent.com/56803208/74608076-0d06e300-50d6-11ea-9f6f-59f07657778d.png)

![Screenshot from 2020-02-16 15-55-17](https://user-images.githubusercontent.com/56803208/74608090-1abc6880-50d6-11ea-93b7-6d3e0672a229.png)
![Screenshot from 2020-02-16 15-51-49](https://user-images.githubusercontent.com/56803208/74608080-11cb9700-50d6-11ea-89b4-8c0087c095d0.png)

**Comment by Eletroboss** [comment] 2020-02-16 16:08
sorry for the HUGE pictures.

**Comment by Eletroboss** [comment] 2020-02-16 16:09
I also forgot about the built-in screenshot thing. Sry.

**Comment by Eletroboss** [comment] 2020-02-17 17:21
I've found that if you get the image to flicker, it shows items (like in the 2nd-to-last image), and that it tends to occur when mining objects. I'm also on a really slow server, so that might impact the cause

**Comment by sp614x** [comment] 2020-02-17 20:54
Should be fixed in pre3.

**Closed** 2020-02-17 20:58 UTC
