### ISSUE TITLE
[1.16] Geometry shaders not working on AMD GPUs

### ISSUE THREAD

**Issue by Pomik108** [sp614x/optifine#4250] opened 2020-07-05 11:18 UTC
## Description of Issue
When using path-tracing shaders in newer versions of OptiFine and using an AMD GPU, light emitters don't get recognised and do not emit any light. To see exactly what I mean please see screenshots

## Steps to Reproduce
1. Start up minecraft with OptiFine on a PC with an AMD GPU.
2. Select a path-tracing shader in the Shaders menu.
3. You can see that light emitters (torches, glowstone) don't emit any light.

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre30 and OptiFine 1.16.1 HD U G2 pre1 + pre2

## Installation Method
OptiFine was installed as a standalone mod.

## Log Files
[latest.log of OptiFine 1.16.1 HD U G2 pre2 and latest MollyVX](https://github.com/sp614x/optifine/files/4874785/latest.log)

## F3 Debug Screenshots
OptiFine 1.15.2 HD U G1 pre30 with latest MollyVX rewrite:
![obrazek](https://user-images.githubusercontent.com/59484948/86531376-eac50480-bec0-11ea-8bbd-f79bf513ebca.png)

OptiFine 1.15.2 HD U G1 pre30 with SEUS PTGI:
![obrazek](https://user-images.githubusercontent.com/59484948/86531395-06c8a600-bec1-11ea-807f-364def7cfee5.png)

OptiFine 1.16.1 HD U G2 pre2 with latest MollyVX rewrite:
![obrazek](https://user-images.githubusercontent.com/59484948/86531406-1fd15700-bec1-11ea-8981-d3cad8b74043.png)

OptiFine 1.16.1 HD U G2 pre2 with SEUS PTGI:
![obrazek](https://user-images.githubusercontent.com/59484948/86531414-2eb80980-bec1-11ea-9fba-090741ad763c.png)

OptiFine 1.14.4 HD U F1 with MollyVX and SEUS PTGI for comparison:
![obrazek](https://user-images.githubusercontent.com/59484948/86531419-4a231480-bec1-11ea-8f36-18ddbc28b93c.png)
![obrazek](https://user-images.githubusercontent.com/59484948/86531422-50b18c00-bec1-11ea-95f8-d446c4eb1e21.png)

## Additional Information
I think this is caused by OptiFine and not the GPU itself, because path tracing works perfectly well on 1.14.4 (as seen above).

**Comment by BruceKnowsHow** [comment] 2020-07-07 21:12
Me and some AMD users were able to narrow the issue down. The problem is that geometry shaders are completely not functioning on Optifine 1.15 and 1.16 for AMD users.

We verified this using [Octray](https://github.com/BruceKnowsHow/Octray), which has interchangeable geometry shader / vertex instancing for its voxelization. Most other raytraced shaderpacks rely on `shadow.gsh`, which explains the pattern of issues.

**Comment by FazeFish565** [comment] 2020-07-19 11:37
The two exact errors that i am getting (on PTGI E12) are:
[main/ERROR]: [Shaders] OpenGL error: 1282 (Invalid operation), program: shadow, at:pre-useProgram
And
[main/ERROR]: [Shaders] OpenGL error: 1282 (Invalid operation), program: shadow, at: shadow terrain solid
As Shader developers Niemand and BruceKnowsHow how have said, it is because of triangulation not working properly on AMD cards as they relay on optifine for their triangulation while nvidia cards can do this out of the box.So this is a missing optifine feature rather than a bug.

**Comment by sp614x** [comment] 2020-07-22 16:33
Should be fixed in pre7.

**Closed by sp614x** 2020-07-22 16:33 UTC
Labels: 1.16, bug, shaders, todo
