### ISSUE TITLE
[1.15.2 pre16] Networking does not work on Manjaro (Arch) Linux

### ISSUE THREAD

**Issue by outsidefactor** [sp614x/optifine#3920] opened 2020-05-12 03:33 UTC
## Description of Issue
When trying to connect to any Multiplayer server using the pre16 (and before) 1.15.2 Optifine versions you get the following error message:
![image](https://user-images.githubusercontent.com/914827/81635271-32488a80-9454-11ea-86de-2630ece6153c.png)

## Steps to Reproduce
1. Install Minecraft on Manjaro Linux
2. Try to connect to a server

## OptiFine Version

OptiFine 1.15.2 HD U G1 pre16

## Installation Method
I used the installer

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/4613223/latest.log)

## F3 Debug Screenshot
I can't connect to a server so I can't produce the screenshot in a relevant context.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? No

## Additional Information
Running on Kernel 5.6.

**Comment by sp614x** [comment] 2020-05-12 11:35
Looks like a problem with Java 9+.
Relevant #2917.

**Comment by outsidefactor** [comment] 2020-05-13 01:27
> Looks like a problem with Java 9+.
> Relevant #2917.

I tried entering a numerical address and port to take the SRV record out of the equation and sure enough I was able to connect. I will take further discussion to issue #2917

**Comment by sp614x** [comment] 2020-06-03 21:19
Duplicate of #2917.

**Closed by sp614x** 2020-06-03 21:19 UTC
Labels: java 9+, linux
