### ISSUE TITLE
[1.15.2 optifine pre15 with forge] Some pictures are darker than normal 

### ISSUE THREAD

**Issue by Summer-94** [sp614x/optifine#3837] opened 2020-05-03 13:03 UTC
## Description of Issue
Some pictures (tools) are darker than usual.
![Annotation 2020-05-03 205044](https://user-images.githubusercontent.com/30728378/80914902-35bb8200-8d81-11ea-8dee-9c77afccf9f8.jpg)

## Steps to Reproduce
Just normally open the game, this happens for both saved game or open a new game. 

## OptiFine Version
preview_OptiFine_1.15.2_HD_U_G1_pre15

## Installation Method
drop the JAR file into "mods" folder

## Forge Version
31.1.63

## Other Installed Mods
jei-1.15.2-6.0.0.3

## Log Files/Crash Reports
debug.log: https://pastebin.com/M4pxn3Di
2020-05-03-1.log: https://pastebin.com/6FiNzwGW

## F3 Debug Screenshot
![Annotation 2020-05-03 205900](https://user-images.githubusercontent.com/30728378/80914864-0147c600-8d81-11ea-8670-7cbf197970e6.jpg)

**Comment by Summer-94** [comment] 2020-05-03 13:24
it still happens after update JEI to jei-1.15.2-6.0.0.4

**Comment by Summer-94** [comment] 2020-05-03 13:29
There is only one java exception in debug.log file:
[03May2020 21:20:58.875] [Render thread/WARN] [net.optifine.Config/]: [OptiFine] PlayerItemsLayer not registered
[03May2020 21:20:59.456] [VersionCheck/INFO] [net.optifine.Config/]: [OptiFine] java.io.FileNotFoundException: http://optifine.net/version/1.15.2/HD_U.txt

**Comment by yezhiyi9670** [comment] 2020-05-04 02:56
This is the incompatibility with Forge.

**Comment by ZekerZhayard** [comment] 2020-05-04 03:19
May be fixed by OptiForge-0.1.17

**Comment by yezhiyi9670** [comment] 2020-05-04 10:06
Workaround: Use [OptiForge 0.1.17](https://www.curseforge.com/minecraft/mc-mods/optiforge) and Forge 31.1.70+. This worked with me.

**Comment by Regnander** [comment] 2020-05-04 12:29
Related to #3830

**Comment by yezhiyi9670** [comment] 2020-05-05 09:40
Discover: If you throw affected items onto the ground, the item will look dark on one side and fine on another.

**Comment by KisaragiEffective** [comment] 2020-05-05 11:27
+1

**Comment by sp614x** [comment] 2020-05-05 22:39
Duplicate of #3830.

**Closed by sp614x** 2020-05-05 22:39 UTC
Labels: 1.15, duplicate, forge
