### ISSUE TITLE
[Category] Minecraft crashes

### ISSUE THREAD

**Issue by TTangerines** [sp614x/optifine#5935] opened 2021-06-30 08:44 UTC
## Description of Issue
Minecraft crashes every time I try to open it with optifine, it says there's an exit code 0, I'm on a Mac btw

## OptiFine Version
On pre 22, pre23 and pre24

**Comment by eezod** [comment] 2021-06-30 10:47
same here! i'm on a mac as well, every time i try to run shaders the game just crashes. i've tried uninstalling and reinstalling minecraft to see if that would fix anything but nope

**Comment by msx2v** [comment] 2021-06-30 13:16
yeah I've got the same issue as well

**Comment by Whitelisted1** [comment] 2021-06-30 14:24
Duplicate of #5900

**Comment by KaiAF** [comment] 2021-06-30 18:02
@TTangerines Are you using shaders when this happens?

**Comment by Earlz** [comment] 2021-06-30 23:41
I have this issue as well, with x86 Mac. Happens when using any shader pack including "internal". Does not crash when shader is turned to off

**Comment by Whitelisted1** [comment] 2021-07-01 00:29
> I have this issue as well, with x86 Mac. Happens when using any shader pack including "internal". Does not crash when shader is turned to off

Please reply in the "original" thread (#5900), so we have all the info in one place

**Comment by KaiAF** [comment] 2021-07-03 20:05
No reply from the author of the issue. If you are using shaders when this crashes, it's already reported here: #5900.

**Closed by KaiAF** 2021-07-03 20:05 UTC
Labels: 1.17, details needed, mac
