### ISSUE TITLE
[Interface Bug] The Interface is messed up

### ISSUE THREAD

**Issue by Diamondcyborg** [sp614x/optifine#6164] opened 2021-08-14 21:16 UTC
##The issue is when I open 1.17.1 the title screen seems to be bugged where the logo covers the entire screen and only half the accessible buttons like "Singleplayer, Multiplayer, Minecraft Realms" I made a post on Reddit that has a video of everything I'm experiencing, showing the screen and everything. If you could please fix this issue, I'm also running Windows 8.

## Steps to Reproduce
Open Minecraft
se on GitHub.** -->

## F3 Debug Screenshot
![SS 1](https://user-images.githubusercontent.com/42004124/129460182-e9086dd3-1e40-4004-b2fd-2df49b9de4c5.PNG)
![ss2](https://user-images.githubusercontent.com/42004124/129460184-a5e92cca-a292-4362-a317-c7620fba49c3.PNG)

**Comment by OxoDr-FunoxO** [comment] 2021-08-20 02:31
Me too!

**Comment by KaiAF** [comment] 2021-08-25 00:02
This could be caused by outdated/broken drivers. So you can try updating them. If it continues, send a latest.log

**Comment by KaiAF** [comment] 2021-09-03 18:13
Closing as this seems to be a driver issue, not OptiFine.

**Closed by KaiAF** 2021-09-03 18:13 UTC
Labels: details needed, interesting, 1.17
