### ISSUE TITLE
[Website Bug] Redirect bug in download.

### ISSUE THREAD

**Issue by ghost** [sp614x/optifine#4930] opened 2020-10-17 10:49 UTC
## It is a website bug. Normally when i click to download optifine button it redirects me to a shortening site and after i click skip ad it redirects me to download site. But when i click to mirror button it redirects me to optifine download page without seeing adds.
Please provide as much detail as possible.

## Steps to Reproduce
1. I click to '(mirror)' button in 'https://optifine.net/downloads' page.

## OptiFine Version
It is a website issue.

## Installation Method
It is a website issue.

## Fabric/Forge Version
It is a website issue.

## OptiFabric Version
It is a website issue.

## Other Installed Mods
It is a website issue.

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
It is a website issue.

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by sp614x** [comment] 2020-10-17 21:34
The mirror link is working correctly.
What exactly is the problem?

**Comment by HelveticaToast** [comment] 2020-10-17 22:43
The mirror is to get past the ad for if you need to, but you should click the download button and give sp614x money. It's not a bug, please close this issue.

**Comment by ZenIsBestWolf** [comment] 2021-02-01 02:51
Not a bug.

**Closed by ZenIsBestWolf** 2021-02-01 02:51 UTC
Labels: website, wontfix
