### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by aidensings** [sp614x/optifine#6434] opened 2021-12-04 22:18 UTC
## Description of Issue
all screenshots taken while playing with optifine on 1.18 end up blank. when opened in ms paint (either through the game or going into screenshots folder) just produce a white image (it appears black in the folder, so i'm assuming its entirely transparent)

## Steps to Reproduce
have an optifine preview version for 1.18 installed
take a screenshot in game

## OptiFine Version
the last two preview versions for 1.18 (pre6 and pre7)

## Installation Method
used the included standalone installer

## Log Files
[2021-12-04-2.log.gz](https://github.com/sp614x/optifine/files/7654791/2021-12-04-2.log.gz)
[2021-12-04-1.log.gz](https://github.com/sp614x/optifine/files/7654792/2021-12-04-1.log.gz)
[2021-12-04-3.log.gz](https://github.com/sp614x/optifine/files/7654793/2021-12-04-3.log.gz)

## F3 Debug Screenshot
taken with win+shift+s
![image](https://user-images.githubusercontent.com/95549651/144726088-10d9f362-f747-43fc-a00e-81302c777b8e.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine? no

## Additional Information
my brother took screenshots with optifine installed and they were fine, but i have no idea why mine don't work, but it happens only when playing with optifine, so i'm reporting it here

**Comment by fayer3** [comment] 2021-12-04 22:36
that's a problem since 1.17, reported here #5770

**Comment by sp614x** [comment] 2021-12-04 23:16
Duplicate of #5770

**Closed by sp614x** 2021-12-04 23:16 UTC

**Comment by sp614x** [comment] 2021-12-05 16:32
Fixed in 1.18, coming in next preview
