### ISSUE TITLE
Massive BlockLag/LagSpike when breaking/placing blocks that use Connected Textures

### ISSUE THREAD

**Issue by savenx** [sp614x/optifine#4473] opened 2020-07-27 00:12 UTC
## Description of Issue
There is huge lag spikes when breaking/placing blocks with a resource pack that uses connected textures often (In this case, bettervanillabuilding 1.16, Ultimacraft 1.16, KDesp 1.16... and many others)

## Steps to Reproduce
1. Take a resource pack that uses connected textures to blend natural blocks or any block
2. Place or break block, will cause massive lag spikes in most chunks

## OptiFine Version
1.16.1 pre10

## Installation Method
Only optfine installer in vanilla (1.16.1)

## F3 Debug Screenshot
https://i.imgur.com/eer1yqx.png

## Additional Information

I know that a lot of texture changes has to be done when a lot of blocks are being destroyed, but any resource pack that tries to take advantage of connected textures will suffer from huge lag. I also noticed that if you are, for instance, insta-breaking a ton of dirt that is not connected to any other block and does not use connected textures, it will still have a lot of lag. Maybe some sort of system to reduce lag with blocks that do not use connected textures with adjacent blocks could fix some of the lag experienced by many Optifine users. This is the resource pack in question that I used to test, since nearly all of it's features use connected textures: https://www.planetminecraft.com/texture-pack/bettervanillabuilding-v-6-1-12-and-1-13-4105787/
FPS walking around: 300 - 500
FPS when constantly breaking blocks: Sometimes drops to 0. Turned off connected textures and kept same resource packs and the lag disappeared. Same results for fast and fancy connected textures.

Setup: Ryzen 7 3700x
16gb ram
gtx 1060 6gb

**Comment by sp614x** [comment] 2020-07-29 11:41
Duplicate of #4464

**Closed by sp614x** 2020-07-29 11:41 UTC
