### ISSUE TITLE
GUI containers from resourcepack not being used by game

### ISSUE THREAD

**Issue by hg456wilkos** [sp614x/optifine#5788] opened 2021-06-13 00:25 UTC
## Description of Issue
For both enderchest and different individual shulker box colors, textures are not being used supplied by the resourcepack

## Steps to Reproduce
![image](https://user-images.githubusercontent.com/85708541/121791812-eaaba980-cbe5-11eb-9bfe-76b9a692584b.png)

container=shulker_box
texture=light_gray
colors=light_gray

^Light_Gray.properties continence, (the same in every other one)

## OptiFine Version
preview_OptiFine_1.17_HD_U_G9_pre21

**Comment by JimStoneCraft** [comment] 2021-06-25 15:02
My pack has custom shulker and ender chest GUI's that do not work so I can confirm.

Resource pack used - John Smith Legacy 1.17.0 v1

https://www.johnsmithlegacy.co.uk/

The log shows the properties being loaded but the texture do not show in game.

[15:38:12] [Render thread/INFO]: [OptiFine] CustomGuis: optifine/gui/container/ender_chest.properties
[15:38:12] [Render thread/INFO]: [OptiFine] CustomGuis: optifine/gui/container/shulker_box_black.properties
[15:38:12] [Render thread/INFO]: [OptiFine] CustomGuis: optifine/gui/container/shulker_box_blue.properties
[15:38:12] [Render thread/INFO]: [OptiFine] CustomGuis: optifine/gui/container/shulker_box_brown.properties
[15:38:12] [Render thread/INFO]: [OptiFine] CustomGuis: optifine/gui/container/shulker_box_cyan.properties
[15:38:12] [Render thread/INFO]: [OptiFine] CustomGuis: optifine/gui/container/shulker_box_gray.properties
[15:38:12] [Render thread/INFO]: [OptiFine] CustomGuis: optifine/gui/container/shulker_box_green.properties
[15:38:12] [Render thread/INFO]: [OptiFine] CustomGuis: optifine/gui/container/shulker_box_light_blue.properties
[15:38:12] [Render thread/INFO]: [OptiFine] CustomGuis: optifine/gui/container/shulker_box_light_gray.properties
[15:38:12] [Render thread/INFO]: [OptiFine] CustomGuis: optifine/gui/container/shulker_box_lime.properties
[15:38:12] [Render thread/INFO]: [OptiFine] CustomGuis: optifine/gui/container/shulker_box_magenta.properties
[15:38:12] [Render thread/INFO]: [OptiFine] CustomGuis: optifine/gui/container/shulker_box_orange.properties
[15:38:12] [Render thread/INFO]: [OptiFine] CustomGuis: optifine/gui/container/shulker_box_pink.properties
[15:38:12] [Render thread/INFO]: [OptiFine] CustomGuis: optifine/gui/container/shulker_box_purple.properties
[15:38:12] [Render thread/INFO]: [OptiFine] CustomGuis: optifine/gui/container/shulker_box_red.properties
[15:38:12] [Render thread/INFO]: [OptiFine] CustomGuis: optifine/gui/container/shulker_box_white.properties
[15:38:12] [Render thread/INFO]: [OptiFine] CustomGuis: optifine/gui/container/shulker_box_yellow.properties

**Comment by Ari-RERA-43** [comment] 2021-06-25 15:20
Is custom GUIs enabled in quality settings?

**Comment by JimStoneCraft** [comment] 2021-09-30 03:56
Looks like this is fixed in OptiFine HD U H1 pre4

https://github.com/sp614x/optifine/issues/6094

**Closed** 2021-09-30 08:31 UTC
Labels: bug, resource pack, 1.17
