### ISSUE TITLE
[OF 1.15.2_HD_U_G1_pre10] Target item frame is not highlighted when pointed at with a shader chosen

### ISSUE THREAD

**Issue by denhyde** [sp614x/optifine#3620] opened 2020-03-30 09:38 UTC
## Description of Issue
With shaders enabled and any shader chosen, when pointed at, the target item's frame is not highlighted when pointed at. It makes it difficult to build. When shader option is set to Off or Internal, item frames are displayed correctly. This wasn't the case with the same shaders with pre9.
OS: macOS 10.15.4 Catalina

## Steps to Reproduce
1. Launch Minecraft
2. Choose Optifine 1.15.2-OptiFine_HD_U_G1_pre10 profile
3. Choose Options > Video Settings > Shaders
4. Choose any shader, e.g. Sildurs
5. Done > Done > Done
6. Choose Multiplayer > enter the chosen world

## OptiFine Version
1.15.2_HD_U_G1_pre10

## Installation Method
Standalone OptiFine installer

**Comment by HiItsDevin** [comment] 2020-03-30 09:41
Can you possibly provide some visual aide? [screenshot]

**Comment by denhyde** [comment] 2020-03-30 10:30
With shaders set to OFF, the target grass block is highlighted with black wireframe:
![shaders_off](https://user-images.githubusercontent.com/12459640/77902751-9e42ab00-7279-11ea-9c64-2747604734da.png)

Wish shaders set to Sildurs Vibrant Shaders v1.24 Medium.zip, target grass block is not highlighted:
![sildurs_vibrant_shaders_v1 24_medium](https://user-images.githubusercontent.com/12459640/77902785-a8fd4000-7279-11ea-850b-bc4ab6120910.png)

Many thanks!

**Comment by Cheetopants1111** [comment] 2020-04-01 03:45
This is also the issue with my version as well (1.15.2_HD_U_G1_pre10). Makes building way more annoying

**Comment by sp614x** [comment] 2020-05-30 12:32
Duplicate of #3600.

**Closed by sp614x** 2020-05-30 12:32 UTC
Labels: 1.15, shaders
