### ISSUE TITLE
Color issue with water over kelp [1.18.2_HD_U_H6_pre1]

### ISSUE THREAD

**Issue by Zertopion** [sp614x/optifine#6659] opened 2022-03-07 13:44 UTC
Optifine Version: **1.18.2_HD_U_H6_pre1**
Texture Pack: None
Shader Pack: None
Mods: None
Biome: Ocean

![2022-03-07_14 37 51](https://user-images.githubusercontent.com/78325862/157045223-9b037fec-b0f4-498f-888a-c76f8456b9ce.png)
![2022-03-07_14 37 28](https://user-images.githubusercontent.com/78325862/157045235-63ceabbc-0975-4298-bfed-e7b88339f06e.png)
![2022-03-07_14 37 48](https://user-images.githubusercontent.com/78325862/157045246-8f21dc59-09f6-402e-a94b-8d74ef2a1be7.png)

**Comment by Zertopion** [comment] 2022-03-07 13:47
Same issue with sea grass

**Comment by fayer3** [comment] 2022-03-07 13:54
Duplicate of #6646 
Why does nobody check at least the first page of issues before sumbmitting a new one.

**Closed** 2022-03-07 13:57 UTC
