### ISSUE TITLE
[Bug] No textures render in inventory with shaders enabled - 1.16.1 pre2

### ISSUE THREAD

**Issue by jestifizzle** [sp614x/optifine#4273] opened 2020-07-06 15:08 UTC
## Description of Issue
Using preview_OptiFine_1.16.1_HD_U_G2_pre2 with latest forge and MultiMC launcher, textures do not render in inventory when shaders are enabled. The texture held in hand is also bugged with a rainbow like texture. The block does render perfectly when placed.

## Steps to Reproduce
1. Enable a shader in Video Settings, Shaders.

## OptiFine Version
preview_OptiFine_1.16.1_HD_U_G2_pre2

## Installation Method
Copy and pasted preview_OptiFine_1.16.1_HD_U_G2_pre2.jar file into mods folder.

## Forge Version
32.0.47

## Log Files/Crash Reports
https://pastebin.com/fc1mbdkn

## F3 Debug Screenshot
![2020-07-06_16 18 30](https://user-images.githubusercontent.com/13499407/86607887-1ff95180-bfaa-11ea-8a01-83df7242e3f7.png)
![2020-07-06_16 19 06](https://user-images.githubusercontent.com/13499407/86607916-28ea2300-bfaa-11ea-9586-92d51ff860ed.png)
![2020-07-06_16 19 18](https://user-images.githubusercontent.com/13499407/86607922-2c7daa00-bfaa-11ea-8193-68bb7e214be1.png)
![2020-07-06_16 19 30](https://user-images.githubusercontent.com/13499407/86607936-30a9c780-bfaa-11ea-97a1-5fe32e1c0700.png)
![2020-07-06_16 19 33](https://user-images.githubusercontent.com/13499407/86607857-1374f900-bfaa-11ea-939d-ef49561b8be7.png)

## Prior Testing
- Does this happen without other mods installed? 
Yes.

- Does this happen without any mods at all?
Yes.

- Does this happen in Vanilla without OptiFine?
No.

## Additional Information
Shaders used to test: 
- BSL V7.1.04.1
- Chocapic13 V8 Ultra
- SEUS PTGI E11
- Sildurs Vibrant v1.27 Medium

I noticed another issue very similar to this, however that issue was using a custom resource pack. Mine occurs with the vanilla resource pack.

**Comment by EdgyPotato** [comment] 2020-07-06 15:24
Duplicate of #4267 & #4266

**Comment by jestifizzle** [comment] 2020-07-07 08:17
Some extra test info: The textures work if optifine is installed without forge. It is only when both forge and optifine are present that the bug occurs.

**Comment by sp614x** [comment] 2020-07-10 13:25
Duplicate of #4277

**Closed by sp614x** 2020-07-10 13:25 UTC
Labels: 1.16, forge, shaders
