### ISSUE TITLE
Optifine forge 1.14.2 Incompatible Report

### ISSUE THREAD

**Issue by rocwang70046** [sp614x/optifine#2529] opened 2019-06-24 14:15 UTC
[24六月2019 22:12:38.512] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Tamura1, --version, 1.14.2-forge-26.0.63, --gameDir, C:\Users\Administrator\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Administrator\AppData\Roaming\.minecraft/assets, --assetIndex, 1.14, --uuid, c6cd0c7f70e04a0bbfb091790bcc4360, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 26.0.63, --fml.mcVersion, 1.14.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20190603.175704]
[24六月2019 22:12:38.515] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher starting: java version 1.8.0_51 by Oracle Corporation
[24六月2019 22:12:38.661] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[24六月2019 22:12:38.883] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file Mod File: C:\Users\Administrator\AppData\Roaming\.minecraft\mods\OptiFine_1.14.2_HD_U_F1_pre14_MOD.jar is missing mods.toml file
[24六月2019 22:12:38.883] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: File C:\Users\Administrator\AppData\Roaming\.minecraft\mods\OptiFine_1.14.2_HD_U_F1_pre14_MOD.jar has been ignored - it is invalid
[24六月2019 22:12:39.541] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.14.2-forge-26.0.63, --gameDir, C:\Users\Administrator\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Administrator\AppData\Roaming\.minecraft\assets, --username, Tamura1, --assetIndex, 1.14, --uuid, c6cd0c7f70e04a0bbfb091790bcc4360, --accessToken, ????????, --userType, mojang, --versionType, release]
[24六月2019 22:12:40.896] [Client thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: Tamura1
[24六月2019 22:12:41.453] [Client thread/INFO] [net.minecraftforge.fml.ModLoader/CORE]: Loading Network data for FML net version: FML2
[24六月2019 22:12:46.597] [Client thread/WARN] [net.minecraft.client.GameSettings/]: Skipping bad option: lastServer:
[24六月2019 22:12:46.622] [Client thread/INFO] [net.minecraft.client.Minecraft/]: LWJGL Version: 3.2.1 build 12
[24六月2019 22:12:48.144] [modloading-worker-4/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 26.0.63, for MC 1.14.2 with MCP 20190603.175704
[24六月2019 22:12:48.144] [modloading-worker-4/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v26.0.63 Initialized
[24六月2019 22:12:50.168] [Client thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[24六月2019 22:12:50.288] [Client thread/INFO] [com.mojang.realmsclient.plugin.RealmsPluginImpl/]: Built for minecraft version 1.14.2
[24六月2019 22:12:52.130] [modloading-worker-9/INFO] [com.sk89q.worldedit.forge.ForgeWorldEdit/]: WorldEdit for Forge (version 7.0.1-SNAPSHOT;4384-078d6f6) is loaded
[24六月2019 22:12:52.157] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[24六月2019 22:12:52.915] [Client thread/INFO] [STDOUT/]: [com.mamiyaotaru.voxelmap.Map:<init>:422]: CATEGORY ORDER IS 7
[24六月2019 22:12:53.131] [Client thread/INFO] [com.mamiyaotaru.voxelmap.textures.TextureAtlas/]: Created: 256x256 waypoints-atlas
[24六月2019 22:12:53.397] [Client thread/INFO] [com.mamiyaotaru.voxelmap.textures.TextureAtlas/]: Created: 256x128 chooser-atlas
[24六月2019 22:12:53.474] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Found status: BETA Current: 26.0.63 Target: 26.0.63
[24六月2019 22:12:53.762] [Client thread/INFO] [com.mamiyaotaru.voxelmap.textures.TextureAtlas/]: Created: 512x256 mobs-atlas
[24六月2019 22:12:53.850] [Client thread/INFO] [com.mamiyaotaru.voxelmap.textures.TextureAtlas/]: Created: 64x64 pings-atlas
[24六月2019 22:12:56.930] [Client thread/WARN] [net.minecraft.client.GameSettings/]: Skipping bad option: lastServer:
[24六月2019 22:12:57.348] [Client thread/INFO] [net.minecraft.client.audio.SoundSystem/]: OpenAL initialized.
[24六月2019 22:12:57.350] [Client thread/INFO] [net.minecraft.client.audio.SoundEngine/SOUNDS]: Sound engine started
[24六月2019 22:12:57.550] [Client thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512 textures-atlas
[24六月2019 22:12:58.055] [Client thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x128 textures-atlas
[24六月2019 22:12:58.151] [Client thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256 textures/particle-atlas
[24六月2019 22:12:58.155] [Client thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256 textures/painting-atlas
[24六月2019 22:12:58.156] [Client thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128 textures/mob_effect-atlas

**Comment by sp614x** [comment] 2019-06-24 15:27
Duplicate of  #2457, #2207.

**Closed by sp614x** 2019-06-24 15:27 UTC
