### ISSUE TITLE
Scoreboard Values getting deleted

### ISSUE THREAD

**Issue by MushroomManToad** [sp614x/optifine#301] opened 2016-10-25 12:29 UTC
Hi! My name is MushroomManToad, and I am a major fan on your mod. It actually is the only reason my computer can take Minecraft. However, I am a command blocker, and I have encountered an feature twice now that is scoreboard-breaking. In order to improve performance, it seems, your Mod takes the extra step of deleting scoreboard scores of unloaded entities rather than just storing them. This causes issues for survival mode enhancing contraptions when the player unloads the chunks with entities with – say – cooldown timers on them. If the timer gets deleted, I think you can picture just what can go wrong. I don’t know if there is an option to disable this feature already included in the settings, and if there is, please let me know. I appreciate you taking the time to read this.

Respectfully submitted,

MushroomManToad

**Comment by sp614x** [comment] 2016-10-25 13:23
You can try to set "Video Settings -> Performance -> Smooth World" to OFF.

**Comment by MushroomManToad** [comment] 2016-10-25 22:04
Thanks! That worked. I figured an issue like this wouldn't have been overlooked for such a long time as this mod has been out.

**Comment by MushroomManToad** [comment] 2016-10-30 22:27
Actually... It didn't work. I had just tested it in an area that I guess was too close to spawn.

**Comment by sp614x** [comment] 2016-11-07 15:52
How can it be reproduced? 
Setup, commands, etc?

**Comment by MushroomManToad** [comment] 2017-08-05 13:59
Hi! Sorry, I totally forgot about this for... umm... several months... Anyway, all you have to do to test it is add a scoreboard objective, add some random value of it to an armor stand outside of the spawn chunks, open the scoreboard objective in the sidebar display slot. And then fly away from the armor stand until its chunks unload. The entire score for that armor stand will be wiped.

Not sure if it has been fixed in current versions yet, but it definitely still existed as of the final version of  Optifine for 1.9

**Comment by I3ladeDragon** [comment] 2017-12-16 09:17
Sounds like it is this bug:

https://bugs.mojang.com/projects/MC/issues/MC-96131?filter=allopenissues

I am having this happen.

**Comment by Jiingy** [comment] 2023-03-27 02:16
Cannot reproduce this issue.

Armor stand is given a dummy scoreboard with a value of 1, once flying away, the armor stand's scoreboard remains.
![2023-03-26_21 14 47](https://user-images.githubusercontent.com/69827559/227824648-3d0376f1-40ff-4f5c-b354-3b3c5247c7ce.png)
![2023-03-26_21 15 12](https://user-images.githubusercontent.com/69827559/227824650-c2f32cc3-2fed-49dd-922e-bc8aab246d16.png)

This was tested with smooth world on.

**Comment by Jiingy** [comment] 2023-07-17 23:09
Closing this issue for the following reasons:
1. Has not been reproduced here on GitHub
2. Seeing as `https://bugs.mojang.com/browse/MC-96131` describes this behavior, it is likely a vanilla issue
3. The issue listed above on Mojira was marked also marked as "Cannot Reproduce"

If anyone else runs into this issue or is able to reproduce it, the issue can be reopened.

**Closed by Jiingy** 2023-07-17 23:09 UTC
Labels: details needed, performance, not reproducible
