### ISSUE TITLE
1.14.3 Unable to Launch

### ISSUE THREAD

**Issue by Explorare** [sp614x/optifine#2644] opened 2019-07-18 08:47 UTC
**Issue**
No java process was created launching using [BMCL](https://github.com/bangbang93/BMCL). This issue may be a dumplicated of #2550 . No jar file was rgenerated under `/.minecraft/versions/1.14.3-OptiFine_HD_U_F1` after a successful installation, just a json file, a .minecraft sub folder and a class_cash.zip. So is it a launcher related issue?

Thanks

**Logs**
```
[16:29:55] [main/INFO]: Initialized cache system in 65834700 ns
[16:29:55] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[16:29:55] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[16:29:55] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
[16:29:55] [main/ERROR]: Unable to launch
java.lang.NullPointerException: null
	at optifine.OptiFineTweaker.acceptOptions(OptiFineTweaker.java:29) ~[OptiFine-1.14.3_HD_U_F1.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:136) [launchwrapper-2.0.jar:2.0.2]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:23) [launchwrapper-2.0.jar:2.0.2]
```

**Environment**
System: Windows 10 1903
Java: 1.8.0_221
Minecraft: 1.14.3
OptiFine: 1.14.3_HD_U_F1
BMCL: 4.8

**Comment by sp614x** [comment] 2019-07-18 08:55
Duplicate of #2617, #2615.

The JAR is not needed.
The OptiFine JSON profile inherits from the vanilla 1.14.3 profile and the launcher takes the JAR from the parent profile.

**Closed by sp614x** 2019-07-18 08:55 UTC

**Comment by Explorare** [comment] 2019-07-18 08:59
So is the issue happened due to the lack of support this new feature/design on BMCL?

**Comment by sp614x** [comment] 2019-07-18 09:28
The official launcher don't need the JAR.
Optifine is designed to work with the official launcher.

**Comment by Explorare** [comment] 2019-07-18 09:29
Got it. Thanks. : )
