### ISSUE TITLE
[bug] Armor textures are missing

### ISSUE THREAD

**Issue by Almo7tar** [sp614x/optifine#5936] opened 2021-06-30 10:54 UTC
## Description of Issue
For some reason, armor textures  looks **purple and black**(THIS happens with every single armor when I wear them) , but in vanilla Minecraft it's fine

## OptiFine Version
1.17 HD U G9 pre24.jar

## Installation Method
standalone installer

## F3 Debug Screenshot

![image](https://user-images.githubusercontent.com/86718696/123947934-98baa000-d9a9-11eb-9a11-1007c129d6cb.png)

### **Same thing with armor stands**
![image](https://user-images.githubusercontent.com/86718696/123948336-f818b000-d9a9-11eb-9ada-242b1a356d9d.png)

_**Compared to vanilla**_

![image](https://user-images.githubusercontent.com/86718696/123948128-ca336b80-d9a9-11eb-83ca-9dd9ed6d3708.png)
![image](https://user-images.githubusercontent.com/86718696/123948395-08308f80-d9aa-11eb-976e-53ac6e4b29c5.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine? :NO

## Additional Information
I tried using downloadable resource packs and I tried to replace the texture folder inside
OptiFine 1.17 HD U G9 pre24.jar
but nothing works, I'm also not using any shaders

**Comment by fayer3** [comment] 2021-06-30 12:14
Duplicate of #5806

**Closed** 2021-06-30 18:01 UTC
