### ISSUE TITLE
[BUG] Intermitent Crashing after Some gameplay on 1.17.1

### ISSUE THREAD

**Issue by Nparte777** [sp614x/optifine#6127] opened 2021-08-04 11:56 UTC
## Description of Issue
On the OptiFine HD U G9 pre32 release and the previous one's for minecraft 1.17.1 i have faced random crashes with code: 0
## Steps to Reproduce
- Switching windows
- Randomly during gameplay

## OptiFine Version
OptiFine HD U G9 pre32 

## Installation Method
Executeable jar 

## Log Files/Crash Reports
https://pastebin.com/VuJdFQb1

https://pastebin.com/SPqc26pC

## F3 Debug Screenshot
![2021-08-03_21 25 35](https://user-images.githubusercontent.com/43001632/128176229-7ebeab2d-4e4f-402a-b460-b4199c4b7a90.png)

## Prior Testing

- Does this happen in Vanilla without OptiFine?
No

- Does this happen in OptiFine standalone?
Yes

**Comment by BigBootyHerring** [comment] 2021-08-07 16:18
Having the same issue.

**Comment by KaiAF** [comment] 2021-08-25 00:26
It seems like what's causing the issue is outdated/broken Nvidia drivers.
`Problematic frame:
C  [nvoglv64.dll+0xe82860]`

Try updating them or reinstalling them. Unfortunately, this isn't something that can be fixed by OptiFine itself, so I am going to close the issue.

**Closed by KaiAF** 2021-08-25 00:26 UTC
