### ISSUE TITLE
Optifine + Vsync + JEI 412 causes terrible long loading times

### ISSUE THREAD

**Issue by MatthiasMann** [sp614x/optifine#501] opened 2017-02-21 23:30 UTC
Using forge-1.10.2-12.18.3.2234
jei_1.10.2-3.14.6.412.jar
CraftTweaker-1.10.2-3.0.20.jar
EnderIO-1.10.2-3.1.171.jar
OptiFine_1.10.2_HD_U_D6.jar

When removing Optifine or disabling Vsync the loading time is fast again (~5 seconds vs 15 minutes). 

Details in https://github.com/mezz/JustEnoughItems/issues/746

**Comment by mezz** [comment] 2017-02-21 23:36
This issue is related to https://github.com/sp614x/optifine/issues/304 but not the same.
I have removed the progress bar stuff while itemstack tooltips are collected, which fixes the above issue.

When Optifine with vsync is added, it seems to cause LWJGL to slow down more on the global lock used for display and keyboard for some reason.

**Comment by sp614x** [comment] 2017-02-22 12:11
Seems to be the same as https://github.com/sp614x/optifine/issues/304.
There is a race between the SplashThread and the JEI tooltip creation for the LWJGL lock: [details](https://github.com/mezz/JustEnoughItems/issues/746#issuecomment-281649165)
The VSync is only escalating the problem by keeping the SplashThread longer busy while waiting for the monitor refresh.
The best solution would be for the SplashThread to add a `Thread.sleep(20)` in the loop. This should stop it from constantly getting the LWJGL lock and it should free the CPU to do the actual mod loading.

**Comment by sp614x** [comment] 2017-02-24 09:57
Duplicate of https://github.com/mezz/JustEnoughItems/issues/746

**Closed by sp614x** 2017-02-24 09:57 UTC
