### ISSUE TITLE
Emissive blocks not working

### ISSUE THREAD

**Issue by xA-51x** [sp614x/optifine#6888] opened 2022-06-30 23:47 UTC
I was planning to update emissive blocks pack but couldn't test it out because well it isn't working. So far only items work.
![2022-06-30_19 36 23](https://user-images.githubusercontent.com/108496849/176796263-5f06ce0a-e785-4558-b27e-9bb93a5bf9c1.png)
Im using the latest preview version of OptiFine (OptiFine 1.19_HD_U_H8_pre2)

**Comment by SeaOfPixels** [comment] 2022-07-01 13:28
Duplicate of https://github.com/sp614x/optifine/issues/6854

**Closed** 2022-07-01 18:51 UTC
