### ISSUE TITLE
[1.13 alpha] Crashes when starting game

### ISSUE THREAD

**Issue by suchdotaplayer** [sp614x/optifine#1662] opened 2018-08-15 18:55 UTC
I get this when I try to open the game
"could not find or load main class net.minecraft.a.m"
exit code (1)
That's all. there's not a crash log about it
Any idea?

**Comment by Chrishunk** [comment] 2018-08-15 21:04
I also have this problem if I can solve <3

**Comment by Chrishunk** [comment] 2018-08-15 21:07
but what it seems to be is this error, being caused by the pirate launcher. maybe some launchers have already said updates to fix this bug. I just do not know which ones.

**Comment by suchdotaplayer** [comment] 2018-08-15 21:09
Oh my secret! Yes, you are right. Maybe i'll have to buy minecraft but I can't afford it yet :(

**Comment by skmedix** [comment] 2018-08-15 22:38
Duplicate of #1635

**Comment by suchdotaplayer** [comment] 2018-08-15 22:47
SKMEDIX solve my problem, thank you so much dude, is there a way i can thank you?

**Closed** 2018-08-21 00:40 UTC
