### ISSUE TITLE
[Bug Report] CEM Animation Scale not working

### ISSUE THREAD

**Issue by Clashbestie** [sp614x/optifine#5145] opened 2020-12-26 22:18 UTC
## Description of Issue
Using `"xy.sx": "-1"` does nothing

## Steps to Reproduce
1. Install Optifine for 1.16
2. Paste this JEM File:
  - [cat.jem](https://pastebin.com/fTsE3ZcS)
 3. Use it as cat.jem
 4. The cat should be show upside down, but its not:
  - [screenshot](https://imgur.com/a/MuUZ3Zs)
5. in 1.14.4 it works
  - [screenshot](https://imgur.com/a/L03MLOT)

## OptiFine Versions
1.16.4-OptiFine_HD_U_G5/vanilla
1.14.4-OptiFine_HD_U_F5/vanilla

## Installation Method
Standallone installer

## Log Files/Crash Reports
No warnings or errors in the logs/game output

## F3 Debug Screenshot
[F3](https://imgur.com/a/cAYNfbp)

**Comment by sp614x** [comment] 2020-12-27 14:25
Duplicate of #4166

**Closed by sp614x** 2020-12-27 14:25 UTC
