### ISSUE TITLE
Immersive Engineering Rendering breaking when using optifine

### ISSUE THREAD

**Issue by mindforger** [sp614x/optifine#86] opened 2016-04-19 07:18 UTC
can you have a look at Immersive Engineering and what the heck is going on?

https://cloud.githubusercontent.com/assets/16712394/12343036/d9b70c84-bb0e-11e5-932c-afe0367b4131.png

this is called an improved blast furnace and supposed to look like a giant vase but the rendering fucks up pretty bad when using optifine

also many of the multiblocks have lighting issues as they are rendered ISRBH (hopefully i spelled it right) and become randomly darker whenever you get close to them while certain surrounding faces are covered ... nothing that can be reproduced with a certain logic .. it happens pretty random but often 

support from IE is limited as optifine has very low documentation on how to work with it or on how to debug ... 
i will not let this become a shitstorm but going closed source is not helping with modding

**Comment by sp614x** [comment] 2016-04-19 08:22
How should it look like (screenshot)?

**Comment by mindforger** [comment] 2016-04-19 08:45
http://ftb.gamepedia.com/Improved_Blast_Furnace

**Comment by mindforger** [comment] 2016-04-19 08:46
stupid close and comment button -.-

**Comment by malte0811** [comment] 2016-04-19 14:32
Is there a download for a deobf version of Optifne anywhere? I think I know how to fix this, but I don't want to have to build for every test and I don't want to work with obfuscated code either.

**Comment by sp614x** [comment] 2016-04-20 14:47
If this is 1.7.10 and it happens randomly, then "Chunk Loading -> Default" might fix it?

**Comment by malte0811** [comment] 2016-04-20 15:21
It isn't happening randomly, it happens every time, and default chunk loading does not appear to change anything.
I am going to explain a bit of the involved IE code and some observations I made while testing:
Most multiblocks are rendered by a single block, usually in the middle. The detection for this block in case of the advanced blast furnace triggers for the "default" TileEntity (`new TileEntityBlastFurnaceAdvanced()`). This causes the blast furnace to be rendered from every block of the multiblock. Forming the multiblock is done by [this](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/blocks/multiblocks/MultiblockBlastFurnaceAdvanced.java#L112-L122) code: It sets the block and edits the TileEntity afterwards. Apparently these changes are send to the client precisely if Optifine is not present, the NBT data of the client side TE is the default one if Optifine is installed. Relogging fixes it since it forces the NBT data to be synced. Another interesting observation is that it happens for all stone multiblocks, but not for any of the metal multiblocks that I tested, I will look into differences between the metal- and the stone multiblocks now.

**Comment by malte0811** [comment] 2016-04-20 16:29
Update: still no idea what actually causes this, but NBT data does not seem to be synced at all for the coke oven (I am using a coke oven for testing since it is a little less complex, but has the same problem). This seems to be the cause for the reported issue as well as for BluSunrize/ImmersiveEngineering#703.
@sp614x Two questions:
1. Does Optifine use ASM to edit mod classes/Is it certain that the code I write is the code that runs?
2. Does Optifine change how NBT syncing is done? `TileEntity.markDirty` and `World.markBlockForUpdate` usually cause NBT data to be synced, that does not appear to be working for stone multiblocks in my test instance.

**Comment by malte0811** [comment] 2016-04-20 16:45
And second update: I have found a fix, but it appears to be a bug on Optifines side: `Block.hasTileEntity(int metadata)` is sometimes called with 0 as the metadata instead of 1. The block used for stone multiblocks does not have a tile entity for metadata 0, causing half of Minecraft to believe that there is a TileEntity and the other half that there is no TE. The calls with 0 as metatadata are done in the server thread and have `net.minecraft.block.Block.func_149716_u(Block.java:511)` as the stack trace element directly above IE's code.

**Comment by sp614x** [comment] 2016-04-20 16:49
Full stack trace of the metadata 0 call?

**Comment by malte0811** [comment] 2016-04-20 17:45
http://pastebin.com/AfL4SibU

**Comment by sp614x** [comment] 2016-04-21 07:07
OptiFine is not using ASM and is not modifiying external classes.

**Comment by sp614x** [comment] 2016-04-21 08:12
"Video Settings -> Performance -> Lazy Chunk Loading -> OFF" could help.
Cleaned up: http://pastebin.com/rVDwHYEy

**Comment by mindforger** [comment] 2016-04-21 10:47
maybe it's my imagination, but this sounds more like a workaround than a solution?!

**Comment by malte0811** [comment] 2016-04-21 14:43
> "Video Settings -> Performance -> Lazy Chunk Loading -> OFF" could help.

Does not seem to change anything... I can work around it from IE by making `hasTileEntity()` return true independent of metadata, but it isn't really a "nice" solution.

**Comment by sp614x** [comment] 2016-04-21 15:01
Problem found, testing the bugfix.

**Comment by sp614x** [comment] 2016-04-21 16:29
Fixed in preview D4 for 1.7.10: http://optifine.net/adloadx?f=preview_OptiFine_1.7.10_HD_U_D4_pre.jar

**Comment by sp614x** [comment] 2016-04-21 16:34
Seems to work: http://i.imgur.com/hpp07JC.png

**Closed** 2016-04-21 19:54 UTC
