### ISSUE TITLE
[Bug] In-game crash when using Sphax's PureBDCraft

### ISSUE THREAD

**Issue by Notegun** [sp614x/optifine#6237] opened 2021-09-09 19:00 UTC
## Description of Issue
When Sphax's PureBDCraft (128x 1.17.1) is used in the resource pack menu and you load inside the game it crashes.

## Steps to Reproduce
1. Install the resource pack and enable it
2. Join a world
3. 1 second of working then crash

## OptiFine Version
Latest, 1.17.1-OptiFine_HD_U_G9

## Installation Method
Standalone Installer

## Log Files/Crash Reports
Strangly enough, no crash txt. Although, the launcher did think it was a error code 0.
[2021-09-09-2.log.gz](https://pastebin.com/DekrH178)
[hs_err_pid17244.log](https://pastebin.com/ssHP3ZtW) (game crashed crash report)

## F3 Debug Screenshot
https://imgur.com/a/Bn78ZXo

## Prior Testing
Doesn't happen with it disabled. It is a consistent crash, I have tried numerous times.
- Does this happen in Vanilla without OptiFine?
No.

## Additional Information
I hope this is enough info, I haven't really tried to make any bug reports ever so
It happens without shaders and with, screenshots just had them on

**Comment by fayer3** [comment] 2021-09-09 22:11
duplicate of #5918
don't set mipmaps to max or disable Terrain Animated until this is fixed.

**Comment by Peca21** [comment] 2021-09-10 12:23
Also you pasted .gz file, you need to paste .log and the second link is not working

**Closed** 2021-09-15 23:16 UTC
