### ISSUE TITLE
Missing chunk/textures

### ISSUE THREAD

**Issue by ghost** [sp614x/optifine#5404] opened 2021-03-04 11:20 UTC
## Description of Issue

When i enable anisotropic filtering and antialiasing on any settings they provide i get chunks that doesnt seem to load or missing textures (pictures in post). They texture pack is up to date and to fix this i need to turn both anisotropic filtering and antialiasing off. 
When i just use minecraft default textures the issues does not happend even when i turn anisotropic filtering and antialiasing on.

## Steps to Reproduce

Video settings -> Quality -> anisotropic filtering on any setting and antialiasing on any setting which turns them both on.
They both seems to activate the issue even when one is off and the other on.

Texture pack: John Smith Legacy 1.16.5 v11.

## OptiFine Version

OptiFine HD U G7.

## Installation Method

standalone installer.

## Other Installed Mods

I have no other mods.

## F3 Debug Screenshot

(Fps seems to be very low also with this issue) when i turn those 2 settings off i play at a stable 60 fps.

![asdadasdasdasdadas](https://user-images.githubusercontent.com/80039290/109955481-d4d34200-7ce2-11eb-9a31-d8792d567114.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

No the issue does not appear without Optifine.

## Additional Information

I would like to know if this is a known issue and or being worked on.

**Comment by KaiAF** [comment] 2021-03-04 20:31
I have tested this on two resource packs. And it seems to only happen on the texture pack "John Smith Legacy". Don't know why, but since it is reproducible, I will still label this as a bug.

**Comment by KaiAF** [comment] 2022-01-08 21:09
Closing in favor of: #6549

**Closed by KaiAF** 2022-01-08 21:09 UTC
Labels: bug, chunks
