### ISSUE TITLE
Emissive textures don't work 1.15.2

### ISSUE THREAD

**Issue by SporeHarvest** [sp614x/optifine#3665] opened 2020-04-03 09:06 UTC
I have made myself a small texture pack for optifine 1.14.4 and have currently noticed that the emissive textures do not work. I haven't changed much about them except for changing the locations of the files to match the 1.15.2 folder structure.

I would appreciate if you would fix this bug and thank you for working on such a great mod.

**Comment by NiemandTV** [comment] 2020-04-03 09:19
Duplicate of https://github.com/sp614x/optifine/issues/3596 which is a duplicate of https://github.com/sp614x/optifine/issues/3500.

**Closed** 2020-05-28 21:44 UTC
