### ISSUE TITLE
[Shaders] Low FPS on AMD Radeon GPU (OptiFine HDUG1 Pre13)

### ISSUE THREAD

**Issue by Borsa-too** [sp614x/optifine#3723] opened 2020-04-10 08:49 UTC
![i9AbOz5 - Imgur](https://user-images.githubusercontent.com/63447221/78977647-c1dae080-7b18-11ea-965d-e2d08fe552f7.png)

**Comment by sp614x** [comment] 2020-06-09 08:21
Duplicate of #3650.

**Closed by sp614x** 2020-06-09 08:21 UTC
Labels: 1.15, performance, shaders
