### ISSUE TITLE
[1.15.2-pre9] CIT and armor change aren't working properly

### ISSUE THREAD

**Issue by KotoHacker** [sp614x/optifine#3440] opened 2020-02-23 09:22 UTC
![2020-02-23_12 16 52](https://user-images.githubusercontent.com/61041788/75109706-ea754c80-5636-11ea-9817-abcc4326b293.png)
Only inventory icons work. "Outside" does not show anything. Neither the model nor its armor.

**Comment by iGalaxyYT** [comment] 2020-02-26 05:10
Experiencing this same issue.

**Comment by sp614x** [comment] 2020-05-29 09:38
Duplicate of #3318.

**Closed by sp614x** 2020-05-29 09:38 UTC
Labels: 1.15, CIT
