### ISSUE TITLE
game crashes (in multiplayer)

### ISSUE THREAD

**Issue by nousername363** [sp614x/optifine#6905] opened 2022-07-02 08:43 UTC
## Description of Issue
playng multiplayer sometimes crashes the game when playing

## Steps to Reproduce
1. What do you do...  playing multiplayer
2. ...to find this bug? too many players, using elytra, runing shaders, turn on resourse pack, too many mobs (xp farms)

## OptiFine Version
OptiFine HD U H8 pre2

## Installation Method
standalone installer

## Log Files/Crash Reports
carash code: -1
crash log: https://pastebin.com/0DAEv54i

## Prior Testing
it works fine without optifine it start crashing with optifine

## Additional Information

![image](https://user-images.githubusercontent.com/52288266/176993444-27609478-2e5f-4bac-8ef1-87e27785ece1.png)

**Comment by Skw972** [comment] 2022-07-02 12:54
Same for me.

**Comment by DanYami** [comment] 2022-07-02 14:15
same thing here
[crash-2022-07-02_16.02.05-client.txt](https://github.com/sp614x/optifine/files/9033095/crash-2022-07-02_16.02.05-client.txt)
Apparently it's connected textures? keeps appearing in the crash logs
Didn't crash rightaway when I disabled em

**Comment by UnknownTheLad** [comment] 2022-07-02 14:18
Duplicate of #6858

**Comment by KaiAF** [comment] 2022-07-03 02:41
Reported #6858

**Closed by KaiAF** 2022-07-03 02:41 UTC
