### ISSUE TITLE
[Graphics] Particles become visible through walls

### ISSUE THREAD

**Issue by Skullslice** [sp614x/optifine#6528] opened 2021-12-31 23:06 UTC
## Description of Issue
When moving around particles in my world seem to flash through walls. I keep seeing my torches and glow squids through walls whenever im mining. It happens for 30-150 ms intervals

## Steps to Reproduce
use a lot of particle emitters in a world and stand behind a wall or in a cave and look around to enable xray particle hacks

## OptiFine Version
1.18.1 OptiFine HD U H5 pre4

## Installation Method
forge mods folder / 1.18.1-forge-39.0.7

## Prior Testing
No, only happened after installing optifine.

**Comment by Regnander** [comment] 2022-01-02 13:51
Are you using any shaders?

**Comment by KaiAF** [comment] 2022-01-08 21:31
Send a F3 menu screenshot

**Comment by CommandoEchino** [comment] 2022-01-25 02:06
I'm having the same issue. No, I am not using a shader. There are reports of this across Reddit. I am using a GTX1650S and a 5800X, if it matters.

https://www.reddit.com/r/Minecraft/comments/rjdtjt/when_i_break_blocks_and_pick_up_the_item_these/

https://www.reddit.com/r/Minecraft/comments/o8po3j/help_i_can_see_the_minecraft_particles_through/

**Comment by Skullslice** [comment] 2022-01-26 10:21
Sorry for the late reply. Happens regardless of shaders being on or off. I
think forge should be updated by now so when I'm at my PC I will give the
new forge version a go. First time I've ever encountered anything like this.

**Comment by Totomio** [comment] 2022-02-03 09:59
Hi Skullslice,, i have the same issue, plus like CommandoEchino said this glitch occurs while i pick up a block on the ground it triggered  source light flashnig like glowsquid or light emitter entity like torch etc ... Same problems with all shaders except with path traced one, like seus ptgi. Tested with last forge version 39.0.64 and optifine HD U H5 pre4.

**Comment by CommandoEchino** [comment] 2022-02-03 17:57
> Hi Skullslice,, i have the same issue, plus like CommandoEchino said this glitch occurs while i pick up a block on the ground it triggered source light flashnig like glowsquid or light emitter entity like torch etc

Totomio, I am also able to see particles like smoke from campfires and the particles from mining the blocks themselves in the same way. Do you experience this as well? If you're wondering what it looks like, go to the third Reddit post I sent.

**Comment by CommandoEchino** [comment] 2022-02-03 17:59
@KaiAF @Regnander I believe that we have provided sufficient additional details for you to take a second look at this post. This is a serious issue that really needs to be rectified.

**Comment by fayer3** [comment] 2022-02-03 19:23
couldn't reproduce this with only Optifine_1.18.1_HD_U_H5_pre4 and Forge 1.18.1 39.0.64
could reproduce it though when adding Flywheel 1.18 0.6.0
F3 screenshot (picking up the dark oak log there):
![2022-02-03_20 13 23](https://user-images.githubusercontent.com/8282299/152414005-ca4b2dce-b929-40d9-971c-75b56609192f.png)

**Comment by Totomio** [comment] 2022-02-04 08:30
@CommandoEchino, i can see smoke aswell, we have the exact same issue, only seus ptgi 3.0 don't have this problem. i will see your post.

**Comment by Regnander** [comment] 2022-02-04 12:25
> I believe that we have provided sufficient additional details for you to take a second look at this post. This is a serious issue that really needs to be rectified.

sp614x is the lone developer of this mod - not Kai and me.
I just tend to browse through bug reports and ask for more details when needed in order to ease the workflow for sp614x.

**Comment by mindforger** [comment] 2022-02-04 12:30
are you all using ANY mods? i am not using optifine (still following the repo) and i have the same issue some rare times
maybe it is a specific mod we share and optifine amplifies the issue or it is related?

**Comment by CommandoEchino** [comment] 2022-02-06 00:25
> are you all using ANY mods? i am not using optifine (still following the repo) and i have the same issue some rare times maybe it is a specific mod we share and optifine amplifies the issue or it is related?

I am using the [Simple Voice Chat](https://modrepo.de/minecraft/voicechat/overview) mod.

**Comment by KazIsKool** [comment] 2022-02-08 18:16
I also have this issue, it happens when I pick up items. I see torches, campfires, glowsquid, etc

**Comment by mindforger** [comment] 2022-02-08 19:27
Sorry, i missed the response, simple voice chat yeah, i can test that without for a few days

**Comment by CommandoEchino** [comment] 2022-02-09 07:04
> Sorry, i missed the response, simple voice chat yeah, i can test that without for a few days

Wait holy crud I think this might be it, I removed the mod and the bug stopped!

If you remove it and it also gets rid of the bug, we need to contact the SimpleVoiceChat devs, because that's where the problem likely is. I would hypothesize that it's an issue with the custom texture pack that's bundled with the plugin itself.

BTW, have you tried running the SimpleVoiceChat mod with just Forge, no OptiFine? I haven't yet, but I'm going to try ASAP and update it here.

**Comment by mindforger** [comment] 2022-02-09 07:47
since it is hard to reproduce in the first case without OF, i would consider the bug gone since i deactivated voice chat
but i can still only hardly imagine what a voice chat mod can do, to cause this ...

**Comment by fayer3** [comment] 2022-02-09 12:38
can people here try this with the new pre5?
I couldn't reproduce it with flywheel and that.

**Comment by KazIsKool** [comment] 2022-02-09 20:04
I don't have simple voice chat and it happens to me

**Comment by fayer3** [comment] 2022-02-09 20:37
@KazIsKool also with pre5?

**Comment by KazIsKool** [comment] 2022-02-09 20:45
@fayer3 No I'm using H4

**Comment by fayer3** [comment] 2022-02-09 20:48
can you try H5 pre5, that fixed it in my case

**Comment by CommandoEchino** [comment] 2022-02-10 20:53
> can you try H5 pre5, that fixed it in my case

Same here, H5 pre5 seems to have totally fixed it. Most likely due to this bulletpoint:

> - fixed custom colors for block breaking particles (#6480)

I also figured out the exact procedure to reproduce the bug:

1. Install Forge. Even version 39.0.75 works.
2. Drag Optifine and a mod with some textures built into it (like Simple Voice Chat or Flywheel)
3. Launch the Forge profile
4. Close MC, restart it
5. Open a world. The graphical bug will occur when breaking and then picking up a block.

**Comment by fayer3** [comment] 2022-02-10 22:05
> - fixed custom colors for block breaking particles

that was already part of the previous versions.
it's probably to do with the
>  - compatible with Forge 39.0.66

**Comment by CommandoEchino** [comment] 2022-02-10 23:20
> > * fixed custom colors for block breaking particles
> 
> that was already part of the previous versions. it's probably to do with the
> 
> > * compatible with Forge 39.0.66

That does make sense, but I still wonder which particular fix did the trick.

**Comment by longestsauce** [comment] 2022-02-28 20:55
I'm having the same issue. Not just light particles but bubbles too. Happens whenever I pick up a block regardless if I broke it or if it was dropped. 
Both CurseForge and Optifine are 1.18.1.
using Xaero's Minimap mod from CurseForge.

**Comment by CommandoEchino** [comment] 2022-02-28 21:24
> Both CurseForge and Optifine are 1.18.1. using Xaero's Minimap mod from CurseForge.

Which particular version of OptiFine and CurseForge are you using?

OptiFine versions are formatted like this: 
```
OptiFine_HD_U_H[number]
OptiFine_HD_U_H[number]_pre[number]
```
e.g. OptiFine_HD_U_H4, or OptiFine_HD_U_H5_pre5

CurseForge versions are formatted like this:
```
39.[number].[number]
```
e.g. 39.0.64 

This thread seems to have come to the conclusion that updating to OptiFine_HD_U_H5_pre5 resolves the issue we've all collectively experienced. Even pre4 had it. Please try updating and let us know if that works.

**Comment by HoodedDeath** [comment] 2022-03-11 08:25
I came here to add more information, and following the previous comment's suggestion of
> Please try updating and let us know if that works.

I have just updated to HD U H5 and tested again, resulting in resolution, including while internal shaders are active.

For my full list of mods at the time of testing:
- Forge Mod Loader version 39.1.2
- Borderless Window 1.4.0
- Cloth Config 6.1.50-forge
- Configured 1.5.3
- JEI 9.4.1.112
- Optifine HD U H5
- Sound Physics Forge 1.0.4
- Voice Chat Forge 2.2.10
- Xaeros Minimap 21.23.1
- Xaeros World Map 1.19.1

It does appear that as of H5, this issue is fixed.

**Comment by Jiingy** [comment] 2023-07-17 23:18
This was fixed in H5 as others have pointed out

**Closed by Jiingy** 2023-07-17 23:18 UTC
Labels: details needed
