### ISSUE TITLE
idk it crashed

### ISSUE THREAD

**Issue by nolangrossi** [sp614x/optifine#6883] opened 2022-06-30 19:32 UTC
The game crashed whilst accessing legacyrandomsource from multiple threads
Error: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
Exit Code: -1

**Comment by UnknownTheLad** [comment] 2022-06-30 19:32
Duplicate of #6858

Feel free to close.

**Closed** 2022-06-30 22:54 UTC
