### ISSUE TITLE
java(tm) platform se binary has stopped working 

### ISSUE THREAD

**Issue by VatroxPlays** [sp614x/optifine#3488] opened 2020-03-01 13:51 UTC
title

**Comment by BBftw** [comment] 2020-03-01 14:08
Gonna need a lot more info than that. What version are you running, do you have any mods, what triggers the issue, etc.

**Comment by HiItsDevin** [comment] 2020-03-02 06:31
Can you please provide a log or something, just more detail in general other than just posting "java(tm) platform se binary has stopped working" That really doesn't help much.

**Comment by sp614x** [comment] 2020-03-02 22:29
This is a native crash and can't be fixed by OptiFine.
Usually caused by bug in graphics drivers or other native libraries.

**Closed by sp614x** 2020-03-02 22:29 UTC
