### ISSUE TITLE
[1.17] Armor Textures

### ISSUE THREAD

**Issue by IranMine123** [sp614x/optifine#5806] opened 2021-06-14 22:28 UTC
## Description of Issue
Hi. I'm IranMine123. there is a bug... Armor textures not load and have black-purple texture

## Steps to Reproduce
Wearing Armors

## OptiFine Version
HD U G9 pre21 1.17

## Installation Method
Just download Optifine, Install and play...

**Comment by KaiAF** [comment] 2021-06-15 03:55
can you send a F3 debug menu screenshot of this happening?

**Comment by Ahmed4PS** [comment] 2021-06-20 05:14
This issue happened to me too
Install method : put optifine in mods file with fabric
Also then i try just install optifine on vanilla Minecraft without any mod
What i try to fix :
Add a resources pack
Delete 1.17 and reinstall it
Why i am think it's from optifine 100%
Cuz i try add fabric 
And try 
Then fabric api
Then voxelmap 
And all is done fine 
And i try optifine with vanilla mc without anymod
In this case when i add optifine it happen

**Comment by Ahmed4PS** [comment] 2021-06-20 05:57
F3 debug
![image](https://user-images.githubusercontent.com/79106287/122663781-8f5d5680-d1a5-11eb-9d6f-8a22f0cfe882.png)

**Comment by IranMine123** [comment] 2021-06-20 22:10
![۲۰۲۱-۰۶-۲۱_۰۲ ۳۹ ۵۳](https://user-images.githubusercontent.com/74745380/122689710-00e6e480-d23a-11eb-8587-b185a5f08fb5.png)
Sorry for Persian numbers

**Comment by KaiAF** [comment] 2021-06-20 22:32
I have spent around 30 minutes, I cannot reproduce this at all. I have tried adding a resource pack, nothing. I have toggled every setting. Still nothing. This is an interesting issue.

**Comment by IranMine123** [comment] 2021-06-20 23:38
OMG I found a big and interesting issue :D xD

**Comment by Ahmed4PS** [comment] 2021-06-21 13:50
What is good to mention that i don't use any resources pack or shaders 
And it's not from fabric 
It's from optifine

**Comment by IranMine123** [comment] 2021-06-29 22:25
OMG this issue still not fixed on pre24 too Pls Fix that Thx

**Comment by Ari-RERA-43** [comment] 2021-06-29 22:26
@IranMine123, @Ahmed4PS, Does it happen with default video settings?

**Comment by IranMine123** [comment] 2021-06-29 22:42
> @IranMine123, @Ahmed4PS, Does it happen with default video settings?

Yes I also turned Video settings to default but still didn't work

**Comment by MetalDirt58** [comment] 2021-07-02 22:11
I also have this issue, it's weird because I even reinstalled the .minecraft folder (I made a backup of course) and still got the issue

**Comment by Ahmed4PS** [comment] 2021-07-07 08:40
nothing new? @KaiAF

**Comment by IranMine123** [comment] 2021-07-16 15:06
Still have this issue on 1.17.1 U_G9_pre29 
nothing new? @KaiAF

**Comment by IranMine123** [comment] 2021-07-16 15:07
![۲۰۲۱-۰۷-۱۶_۱۹ ۳۴ ۲۴](https://user-images.githubusercontent.com/74745380/125968986-ebaf45b8-d68c-44fd-9595-836bffeb98d1.png)

**Comment by Fadroz** [comment] 2021-07-18 05:00
Hi
I have realized something 
Both people who sent f3 menu had some numbers in arabic
This is something with 1.17 because there windows language is arabic 
And I also have this problem and my windows language is arabic 
And someone I found on YouTube who had this problem had his channel name in arabic 
So maybe windows system language have something to do with this bug

**Comment by Fadroz** [comment] 2021-07-18 05:02
Also #5936 had some numbers in the f3 menu in arabic
So even more proof that this bug have something to do with your system language

**Comment by detrio1** [comment] 2021-07-18 13:02
Although I am an Arabic speaker, and I have an Arabic keyboard layout, this issue happened to me while my system language has always been set to English. It then disappeared without trying any fix. However it still happens to my friend, his system language is also English, I don't know why or what causes it, I have tried setting the system language to Arabic, and it didn't happen.

**My Installation:**
- I used fabric, along with optifabric
- OptiFine_1.17_HD_U_G9_pre20

**My friend's installation:**
- OptiFine_1.17_HD_U_G9_pre20 without any api.

**Comment by Fadroz** [comment] 2021-07-26 14:24
I changed my system language to English and the issue was fixed for me
Although I haven't set it back to arabic so idk if it will be fixed if I do that

**Comment by IranMine123** [comment] 2021-07-26 14:28
Anyway to fix it without changing system language from arabic/persian to english?

**Comment by Fadroz** [comment] 2021-07-26 14:41
Maybe there are but I haven't found any

**Comment by MetalDirt58** [comment] 2021-08-04 13:39
@KaiAF The way to replicate this bug is to change your Windows display language to arabic

**Comment by IranMine123** [comment] 2021-08-05 04:30
Thanks for your Helps... but still don't close this issue because its not fixed for Arabic/Persian Numbers and must be fix.

**Comment by IranMine123** [comment] 2021-08-05 04:42
How to fix Armor missing textures (Optifine #5806)

1. Go to **Settings**
2. Select **Time & Language**
3. Select **Region**
4. Change **Regional Format** to **English (United States)**
5. then Restart your Minecraft

**Comment by basimtm** [comment] 2021-08-16 13:39
Hello i wanna mention couple things.
This problem was happening to me in any update above 1.8.9 not only 1.17 for some reasons,
Also you don't have to change your whole windows language to english you can just change the numbers format to english from the control panel and the problem will be fixed

**Comment by Fadroz** [comment] 2021-08-16 13:45
Weird 
For me it was only happening with 1.17 optifine 
Vanilla 1.17 was fine

**Comment by IranMine123** [comment] 2021-08-17 10:05
> Weird
> For me it was only happening with 1.17 optifine
> Vanilla 1.17 was fine

that's happened for me too...

**Comment by IranMine123** [comment] 2021-08-17 10:10
in Version 1.16.5 Optifine just use English number format but in 1.17, they added Arabic/Persian number format for Game (You can check with F3)
I think Optifine Creators forgot to add ability for armors coding (using numbers for armors) can support Arabic/Persian number format.

**Comment by basimtm** [comment] 2021-08-18 15:30
Weird cuz after i updated to 1.17 i think all previous updates also were switched to arabic numbers
Even 1.8.9 i think I'm not sure cuz optifine was working fine in 1.8.9

**Comment by sp614x** [comment] 2021-08-30 21:34
Fixed, coming in next version.

**Closed by sp614x** 2021-08-30 21:34 UTC
Labels: bug, details needed, interesting, 1.17
