### ISSUE TITLE
[Suggestion] Custom Blur using CIT (custom screen view)

### ISSUE THREAD

**Issue by athorii** [sp614x/optifine#4913] opened 2020-10-13 19:46 UTC
Hello,
This suggestion consist into adding **"Custom Blur"** which is the **pumpkin blur modified when associated to predefined names** (within the texture pack, in the .properties file) like the armor, items and so on (example of hypixel skyblock packs).
This would actually change what you're viewing by remplacing the existing pumpkin blur.
Some of you might want to know what uses could be made of this feature, well it can be used for minigames in servers, or even in survival in order to be more rp, create some futurist helmet view or things like that.
_Since the CIT already exists and has a ton of item it can modify, this modification shouldn't be to hard to make I believe._

It would look like this : 
type=blur
texture=
nbt.display.Name=

Thanks for reading (please give me your opinion on this)  

Examples : 
![image](https://user-images.githubusercontent.com/72823390/95908451-64f90500-0d9d-11eb-9b8f-e15fc53db760.png)
![image](https://user-images.githubusercontent.com/72823390/95908507-77733e80-0d9d-11eb-955a-8bc6f32ae241.png)
_(sources : https://www.reddit.com/r/Minecraft/comments/19q1ff/made_a_futuristic_tactical_hud_pumpkinblur/ and https://www.reddit.com/r/Minecraft/comments/1cm5vk/with_the_texture_pack_gerudoku_wearing_a_pumpkin/ )_

**Comment by Regnander** [comment] 2020-10-17 08:11
Duplicate of #3119

**Comment by KaiAF** [comment] 2021-04-04 03:38
Duplicate of #3119

**Closed by KaiAF** 2021-04-04 03:38 UTC
Labels: custom guis, enhancement
