### ISSUE TITLE
[Bug] The hotbar is all white.

### ISSUE THREAD

**Issue by Grumfumbly** [sp614x/optifine#4235] opened 2020-07-04 16:37 UTC
When you go in game, the hotbar is all white.
(https://user-images.githubusercontent.com/67836504/86516976-20032100-bdf3-11ea-9590-ca284f4174bd.png)

**Comment by tajemniktv** [comment] 2020-07-05 21:12
#4203

**Comment by sp614x** [comment] 2020-07-11 16:24
Duplicate of #4203

**Closed by sp614x** 2020-07-11 16:24 UTC
