### ISSUE TITLE
Game crashes when loading existing world after installing Optifine in Forge

### ISSUE THREAD

**Issue by Thesmexypotato** [sp614x/optifine#7429] opened 2023-06-22 13:37 UTC
## Description of Issue
So i just installed optifine for 1.20.1 and it is compatible with my forge version. However when I try to load into my creative building world the game crashes with error code -1. This doesn't happen with any other world or any new worlds. My save file isn't corrupt as the world still opens in minecraft optifine (no forge) and in forge without optifine. The only difference between the worlds is that this one has a lot of things going on like multiple beacons and complex structures so maybe the save is too complicated? I've also tried turning off my shaders but that didn't work. Maybe it's just because the optifine version is still preview and not totally optimised. I would have accepted that answer but it's just that other worlds load just fine.

## Steps to Reproduce
1. Install OptiFine HD U I5 pre4 into Forge 47.0.3 as a mod
2. Open Minecraft
3. Open my build world

## OptiFine Version
OptiFine HD U I5 pre4

## Installation Method
Put optifine .jar file into mods folder

## Fabric/Forge Version
47.0.3

## Other Installed Mods
worldedit-mod-7.2.15
Farsight-Mod-Forge-1.20.1
Better-Fps-Mod-Forge-1.20.1

## Log Files/Crash Reports
[crash-2023-06-22_23.16.53-client.txt](https://github.com/sp614x/optifine/files/11834481/crash-2023-06-22_23.16.53-client.txt)

## F3 Debug Screenshot
NA

## Prior Testing
Tried running with only optifine and no other mods, didn't work.
Works on every other save.
Works when loading on standalone optifine.
Works in vanilla.

## Additional Information
I'd really appreciate help or insight, even if it's just to wait for an optimal version of Optifine.

**Comment by Lolothepro** [comment] 2023-06-22 14:03
Duplicate of https://github.com/sp614x/optifine/issues/7425

**Closed** 2023-06-22 15:18 UTC
