### ISSUE TITLE
Seus Shader geometry bug

### ISSUE THREAD

**Issue by JeffreyHansen** [sp614x/optifine#3894] opened 2020-05-07 21:45 UTC
Within 70 meters of a block, all lighting from light sources are invisible.

**Comment by sp614x** [comment] 2020-05-28 19:46
Which OptiFine version?

**Comment by yoyotam3** [comment] 2020-06-06 12:57
I believe JeffreyHansen is referring to SEUS PTGI in Optifine 1.15.2. Apparently this is caused by geometry shaders not working in the current Optifine 1.15.2 prereleases, but I'm not sure.

**Comment by Jiingy** [comment] 2023-07-19 01:01
Closing as this issue is 3 years old with no update to the vague information provided.

**Closed by Jiingy** 2023-07-19 01:01 UTC
Labels: shaders, details needed
