### ISSUE TITLE
the hotbar texture is broken

### ISSUE THREAD

**Issue by coldberet** [sp614x/optifine#4211] opened 2020-07-03 20:49 UTC
i installed optifine for 1.16.1, everything works fine except for the hotbar.
it's completely white even without any texture packs. i've tried restarting minecraft / redownloading optifine to no avail.

**Comment by FishyFissh** [comment] 2020-07-03 20:55
A "fix" is by turning antialising off in your shader

**Comment by sp614x** [comment] 2020-07-03 20:55
Duplicate of #4203

**Closed by sp614x** 2020-07-03 20:55 UTC
Labels: 1.16, shaders
