### ISSUE TITLE
Configurable shadow buffer formats

### ISSUE THREAD

**Issue by SergeantSarcasm** [sp614x/optifine#1712] opened 2018-08-25 20:00 UTC
Currently (afaik) shadow buffers such as shadowcolor0 and shadowcolor1 are forced at 8 bit with no ability to change it. Giving us the option to change that to even just RGBA16 (preferably the same formatswe can use for the 8 colortextures) would allow us devs to store more useful information in buffers of different resolution than the standard view, such as precompute atmospheric scattering for use in IBL, further encoding of useful shadow information, better color depth for said encoded information and/or precomputational data, etc..

**Comment by sp614x** [comment] 2018-08-26 09:27
Duplicate of #944?

**Comment by SergeantSarcasm** [comment] 2018-08-26 15:04
Guess so, forgot it exists. Is this still a possibility?

**Comment by Blockstate** [comment] 2018-08-29 22:54
That sounds really useful, definitely would love to see this added.

**Comment by sp614x** [comment] 2021-01-18 16:53
Duplicate of #5221

Coming in next preview.
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L492

**Closed by sp614x** 2021-01-18 16:53 UTC
Labels: shaders
