### ISSUE TITLE
Optifine 1.12 crashes MC. Connected textures problem.

### ISSUE THREAD

**Issue by xinarivar** [sp614x/optifine#907] opened 2017-09-23 10:56 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 9/23/17 1:25 PM
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
at codechicken.lib.model.bakery.ModelBakery.lambda$static$0(ModelBakery.java:66)
at codechicken.lib.model.bakery.ModelBakery.getCachedModel(ModelBakery.java:232)
at codechicken.lib.model.bakery.CCBakeryModel.func_188616_a(CCBakeryModel.java:41)
at ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1364)
at ConnectedTextures.isNeighbourOverlay(ConnectedTextures.java:1231)
at ConnectedTextures.getConnectedTextureOverlay(ConnectedTextures.java:780)
at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:557)
at ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:399)
at ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:299)
at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:113)
at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:89)
at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:60)
at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:108)
at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:107)
at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:74)
at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:54)
at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:60)
at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:296)
at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
at java.lang.Thread.run(Unknown Source)
A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
at codechicken.lib.model.bakery.ModelBakery.lambda$static$0(ModelBakery.java:66)
at codechicken.lib.model.bakery.ModelBakery.getCachedModel(ModelBakery.java:232)
at codechicken.lib.model.bakery.CCBakeryModel.func_188616_a(CCBakeryModel.java:41)
at ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1364)
at ConnectedTextures.isNeighbourOverlay(ConnectedTextures.java:1231)
at ConnectedTextures.getConnectedTextureOverlay(ConnectedTextures.java:780)
at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:557)
at ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:399)
at ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:299)
at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:113)
at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:89)
at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:60)
at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:108)
at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:107)

-- Block model being tesselated --
Details:
Block: minecraft:log[axis=y,variant=spruce]
Block location: World: (1254,4,234), Chunk: (at 6,0,10 in 78,14; contains blocks 1248,0,224 to 1263,255,239), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
Using AO: true
Stacktrace:
at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:74)
at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:54)

-- Block being tesselated --
Details:
Block type: ID #17 (tile.log // net.minecraft.block.BlockOldLog)
Block data value: 1 / 0x1 / 0b0001
Block location: World: (1254,4,234), Chunk: (at 6,0,10 in 78,14; contains blocks 1248,0,224 to 1263,255,239), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
Stacktrace:
at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:60)

-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [EntityPlayerSP['harekl'/3, l='MpServer', x=1254.24, y=4.00, z=230.24]]
Chunk stats: MultiplayerChunkCache: 289, 289
Level seed: 0
Level generator: ID 01 - flat, ver 0. Features enabled: false
Level generator options:
Level spawn location: World: (1256,4,230), Chunk: (at 8,0,6 in 78,14; contains blocks 1248,0,224 to 1263,255,239), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
Level time: 4871 game time, 4871 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Forced entities: 44 total; [EntityItem['item.item.leather'/514335, l='MpServer', x=1240.88, y=4.00, z=212.36], EntityItem['item.item.porkchopRaw'/514334, l='MpServer', x=1242.30, y=4.00, z=223.48], EntityItem['item.tile.cloth.white'/514343, l='MpServer', x=1283.54, y=4.00, z=220.23], EntityItem['item.item.chickenRaw'/514337, l='MpServer', x=1252.67, y=4.00, z=204.60], EntityItem['item.item.feather'/514336, l='MpServer', x=1254.17, y=4.00, z=203.97], EntityItem['item.tile.cloth.white'/514351, l='MpServer', x=1261.79, y=4.00, z=196.65], EntityItem['item.item.beefRaw'/514350, l='MpServer', x=1247.98, y=4.00, z=196.39], EntityItem['item.item.leather'/514349, l='MpServer', x=1247.14, y=4.00, z=195.39], EntityPlayerSP['harekl'/3, l='MpServer', x=1254.24, y=4.00, z=230.24], EntityItem['item.item.porkchopRaw'/514348, l='MpServer', x=1273.67, y=4.00, z=201.89], EntityItem['item.item.porkchopRaw'/514347, l='MpServer', x=1221.82, y=4.00, z=221.36], EntityItem['item.item.chickenRaw'/514346, l='MpServer', x=1239.42, y=4.00, z=201.37], EntityItem['item.item.feather'/514345, l='MpServer', x=1238.70, y=4.00, z=200.63], EntityItem['item.item.muttonRaw'/514344, l='MpServer', x=1283.04, y=4.00, z=221.05], EntityItem['item.tile.cloth.white'/514359, l='MpServer', x=1217.88, y=4.00, z=206.13], EntityItem['item.item.muttonRaw'/514358, l='MpServer', x=1223.32, y=4.00, z=204.70], EntityItem['item.item.porkchopRaw'/514356, l='MpServer', x=1258.54, y=4.00, z=190.68], EntityItem['item.tile.cloth.white'/514354, l='MpServer', x=1223.99, y=4.00, z=205.12], EntityItem['item.item.chickenRaw'/514353, l='MpServer', x=1235.66, y=4.00, z=199.99], EntityItem['item.item.muttonRaw'/514352, l='MpServer', x=1262.63, y=4.00, z=195.23], EntityItem['item.item.porkchopRaw'/514367, l='MpServer', x=1317.79, y=4.00, z=202.21], EntityItem['item.item.chickenRaw'/514366, l='MpServer', x=1199.37, y=4.00, z=191.33], EntityItem['item.item.feather'/514365, l='MpServer', x=1199.37, y=4.00, z=190.70], EntityItem['item.item.porkchopRaw'/514364, l='MpServer', x=1315.35, y=4.00, z=203.30], EntityItem['item.item.porkchopRaw'/514362, l='MpServer', x=1314.68, y=4.00, z=206.61], EntityPlayerSP['harekl'/3, l='MpServer', x=1254.46, y=4.00, z=230.00], EntityItem['item.item.leather'/514361, l='MpServer', x=1213.79, y=4.00, z=201.19], EntityItem['item.item.muttonRaw'/514360, l='MpServer', x=1216.62, y=4.00, z=206.08], EntityItem['item.item.chickenRaw'/514374, l='MpServer', x=1194.97, y=4.00, z=191.20], EntityItem['item.item.feather'/514373, l='MpServer', x=1194.63, y=4.00, z=190.22], EntityItem['item.item.chickenRaw'/514372, l='MpServer', x=1198.40, y=4.00, z=187.67], EntityItem['item.item.feather'/514371, l='MpServer', x=1196.68, y=4.00, z=189.28], EntitySheep['Sheep'/75079, l='MpServer', x=1182.50, y=4.00, z=156.50], EntityItem['item.item.muttonRaw'/514369, l='MpServer', x=1198.77, y=4.00, z=188.61], EntityChicken['Chicken'/75078, l='MpServer', x=1188.50, y=4.00, z=161.50], EntityItem['item.tile.cloth.white'/514368, l='MpServer', x=1199.40, y=4.00, z=189.40], EntitySheep['Sheep'/75081, l='MpServer', x=1174.50, y=4.00, z=152.50], EntitySheep['Sheep'/75080, l='MpServer', x=1178.50, y=4.00, z=152.50], EntityChicken['Chicken'/75093, l='MpServer', x=1195.50, y=4.00, z=190.50], EntityChicken['Chicken'/75092, l='MpServer', x=1197.50, y=4.00, z=188.50], EntityChicken['Chicken'/75094, l='MpServer', x=1198.50, y=4.00, z=191.50], EntityChicken['Chicken'/75098, l='MpServer', x=1181.50, y=4.00, z=233.50], EntitySheep['Sheep'/75100, l='MpServer', x=1175.50, y=4.00, z=271.50], EntityPig['Pig'/75102, l='MpServer', x=1175.50, y=4.00, z=273.50]]
Retry entities: 0 total; []
Server brand: fml,forge
Server type: Integrated singleplayer server
Stacktrace:
at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:57)
at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
Minecraft Version: 1.12.1
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_144, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 841383744 bytes (802 MB) / 1993908224 bytes (1901 MB) up to 2093809664 bytes (1996 MB)
JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.41 Powered by Forge 14.22.1.2481 Optifine OptiFine_1.12.1_HD_U_C5 25 mods loaded, 25 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State     | ID                  | Version                 | Source                            | Signature                                |
|:--------- |:------------------- |:----------------------- |:--------------------------------- |:---------------------------------------- |
| UCHIJAAAA | minecraft           | 1.12.1                  | minecraft.jar                     | None                                     |
| UCHIJAAAA | mcp                 | 9.19                    | minecraft.jar                     | None                                     |
| UCHIJAAAA | FML                 | 8.0.99.99               | forge-1.12.1-14.22.1.2481.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJAAAA | forge               | 14.22.1.2481            | forge-1.12.1-14.22.1.2481.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJAAAA | bibliocraft         | 2.4.3                   | BbiblioCraft-2.4.3.jar            | None                                     |
| UCHIJAAAA | chameleon           | 1.12-4.1.3              | Chameleon-4.1.3.jar               | None                                     |
| UCHIJAAAA | chiselsandbits      | 14.7                    | ChiselsAndBits-14.7.jar           | None                                     |
| UCHIJAAAA | codechickenlib      | 3.1.2.297               | CodeChickenLib-3.1.2.297.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
| UCHIJAAAA | redstoneflux        | 2.0.1                   | RedstoneFlux-2.0.1.2.jar          | d4f1503fbacd9b9fb767720420c5395104239ec9 |
| UCHIJAAAA | cofhcore            | 4.3.5                   | CoFHCore-4.3.5.13.jar             | None                                     |
| UCHIJAAAA | cofhworld           | 1.0.1                   | CoFHWorld-1.0.1.8.jar             | None                                     |
| UCHIJAAAA | waila               | 1.8.20                  | Hwyla-1.8.20.jar                  | None                                     |
| UCHIJAAAA | ironchest           | 1.12-7.0.31.818         | IronChest-7.0.31.818.jar          | None                                     |
| UCHIJAAAA | jei                 | 4.7.8.95                | JEI-4.7.8.95.jar                  | None                                     |
| UCHIJAAAA | journeymap          | 1.12.1-5.5.0b4          | JourneyMap-5.5.0b4.jar            | None                                     |
| UCHIJAAAA | mantle              | 1.12-1.3.1.21           | Mantle-1.3.1.21.jar               | None                                     |
| UCHIJAAAA | quickleafdecay      | 1.2.4                   | QuickLeafDecay-1.2.4.jar          | None                                     |
| UCHIJAAAA | storagedrawers      | 1.12-5.2.5              | StorageDrawers-5.3.2.jar          | None                                     |
| UCHIJAAAA | refinedstorage      | 1.5.18                  | RefinedStorage-1.5.18.jar         | None                                     |
| UCHIJAAAA | tconstruct          | 1.12-2.7.3.30           | TConstruct-2.7.3.30.jar           | None                                     |
| UCHIJAAAA | tinkertoolleveling  | 1.12-1.0.2b.DEV.1a79301 | TConstructToolLeveling-1.0.2b.jar | None                                     |
| UCHIJAAAA | thermalfoundation   | 2.3.5                   | ThermalFoundation-2.3.5.14.jar    | None                                     |
| UCHIJAAAA | thermaldynamics     | 2.3.5                   | ThermalDynamics-2.3.5.12.jar      | None                                     |
| UCHIJAAAA | thermalexpansion    | 5.3.5                   | ThermalExpansion-5.3.5.19.jar     | None                                     |
| UCHIJAAAA | wailaharvestability | 1.1.11                  | WailaHarvestability-1.1.11.jar    | None                                     |

Loaded coremods (and transformers): 
GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
Pulsar/tconstruct loaded Pulses: 
	- TinkerCommons (Enabled/Forced)
	- TinkerWorld (Enabled/Not Forced)
	- TinkerTools (Enabled/Not Forced)
	- TinkerHarvestTools (Enabled/Forced)
	- TinkerMeleeWeapons (Enabled/Forced)
	- TinkerRangedWeapons (Enabled/Forced)
	- TinkerModifiers (Enabled/Forced)
	- TinkerSmeltery (Enabled/Not Forced)
	- TinkerGadgets (Enabled/Not Forced)
	- TinkerOredict (Enabled/Forced)
	- TinkerIntegration (Enabled/Forced)
	- TinkerFluids (Enabled/Forced)
	- TinkerMaterials (Enabled/Forced)
	- TinkerModelRegister (Enabled/Forced)
	- chiselsandbitsIntegration (Enabled/Not Forced)
	- wailaIntegration (Enabled/Not Forced)

Launched Version: 1.12.1-forge1.12.1-14.22.1.2481
LWJGL: 2.9.4
OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
GL Caps: Using GL 1.3 multitexturing.

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: realisticcloudsfaithful.zip (incompatible), moddedfaithful-1.12-rv2.zip, faithful-1.12-rv3.zip
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz
OptiFine Version: OptiFine_1.12.1_HD_U_C5
Render Distance Chunks: 8
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.200.1062.1004
OpenGlRenderer: AMD Radeon HD 6900 Series
OpenGlVendor: ATI Technologies Inc.
CpuCount: 4

**Comment by Thorf13** [comment] 2017-10-23 10:43
I've been suffering from the same error. Mine appears to be with rendering a Forestry multifarm. The game works normally with Optifine removed, or indeed with Optifine loaded in areas away from the multifarm. But as soon as I get close to the multifarm with Optifine loaded, I get this error every time.

[crash-2017-10-23_02.34.48-client.txt](https://github.com/sp614x/optifine/files/1406712/crash-2017-10-23_02.34.48-client.txt)

**Comment by sp614x** [comment] 2017-10-23 13:11
What happens is:
- OptiFine asks which texture should be used to render the block model (needed for CTM)
- Forestry crashes
```
java.lang.NullPointerException: Tesselating block model
	at forestry.core.tiles.TileUtil.getTile(TileUtil.java:54)
	at forestry.core.tiles.TileUtil.getTile(TileUtil.java:65)
	at forestry.farming.models.ModelFarmBlock.getWorldKey(ModelFarmBlock.java:69)
	at forestry.farming.models.ModelFarmBlock.getWorldKey(ModelFarmBlock.java:22)
	at forestry.core.models.ModelBlockCached.getModel(ModelBlockCached.java:42)
	at forestry.core.models.ModelBlockDefault.func_188616_a(ModelBlockDefault.java:98)
	at ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1364)
```

The original crash is identical, but the CodeChicken library crashes.

The problem is outside of OptiFine and it can't be fixed by OptiFine.

**Closed by sp614x** 2017-10-23 13:11 UTC
Labels: forge, mods
