### ISSUE TITLE
[OF 1.15.2 pre18] Random entities texture for endermen eyes not working.

### ISSUE THREAD

**Issue by Ratchet97** [sp614x/optifine#3610] opened 2020-03-28 19:07 UTC
## Description of Issue
Random entities for my endermen are not working. Emissive texture is included but I dont know how it effects it.

## Steps to Reproduce
Intal this resource pack (taken from mine) containing enderman random entity texture and spawn many endermen to see if some spawn with different eye color.
[endermen eyes bug.zip](https://github.com/sp614x/optifine/files/4399740/endermen.eyes.bug.zip)

## Installation Method
 standalone installer

## Additional Information
Worked fine in 1.14.4 optifine versions. 

![94984](https://user-images.githubusercontent.com/48301568/77831394-44ce6500-712f-11ea-9991-4e2508f02b71.jpg)
![2020-03-27_18 28 35](https://user-images.githubusercontent.com/48301568/77831395-4566fb80-712f-11ea-8fa2-01fee890054f.png)

**Comment by Ratchet97** [comment] 2020-03-29 20:46
Enderman random entity resource pack included for reproducing the bug. Simply install.

**Comment by Ratchet97** [comment] 2020-04-01 13:51
Still a bug in pre12.

Should I write a new bug report for pre12 regarding this issue?

**Comment by Ratchet97** [comment] 2020-04-02 14:35
Still a bug in pre13.

**Comment by Ratchet97** [comment] 2020-05-02 23:04
Still a bug in pre14.

**Comment by Ratchet97** [comment] 2020-05-03 13:08
Also a bug in pre15.

**Comment by Ratchet97** [comment] 2020-05-06 18:04
Still a bug in pre16.

**Comment by Ratchet97** [comment] 2020-05-15 19:43
Still a bug in pre17.

**Comment by Ratchet97** [comment] 2020-05-20 01:12
Still a bug in pre18.

**Comment by Ratchet97** [comment] 2020-06-03 00:38
Still a bug in pre19.

**Comment by Ratchet97** [comment] 2020-06-06 20:07
Still a bug in pre21.

(missed on pre20)

**Comment by Ratchet97** [comment] 2020-06-07 21:57
Still a bug in pre23.

**Comment by sp614x** [comment] 2020-06-09 08:30
Duplicate of #3451

**Closed by sp614x** 2020-06-09 08:30 UTC
Labels: 1.15, random entities
