### ISSUE TITLE
Blocks not visible

### ISSUE THREAD

**Issue by Mario-Cu** [sp614x/optifine#5696] opened 2021-06-08 17:46 UTC
Hi, Ice blocks, honey blocks and tainted cristal are not visible in the game, you can just see the hitbox

**Comment by arnonGPMC** [comment] 2021-06-08 18:14
Try to Remove The Block And Replace It

**Comment by KaiAF** [comment] 2021-06-08 18:16
Closing this issue as there is another issue with more information. This is caused by Render Regions.

**Comment by KaiAF** [comment] 2021-06-08 18:16
https://github.com/sp614x/optifine/issues/5698

**Closed by KaiAF** 2021-06-08 18:16 UTC
Labels: 1.17
