### ISSUE TITLE
[Error] Optifine Installer

### ISSUE THREAD

**Issue by Dawid102** [sp614x/optifine#6372] opened 2021-11-09 20:57 UTC
On installer OptiFine_1.8.9_HD_U_M5.jar

Error:
File not found C:\Users\...\AppData\Roaming\.minecraft\launchers_profiles.json

Solution:
After installing minecraft launcher from microsoft store file have name: launcher_profiles_microsoft_store.json

Changing file name to launchers_profiles.json worked
And I had to change name back to launcher_profiles_microsoft_store.json

**Comment by WhoAteMyButter** [comment] 2021-11-10 05:05
Duplicate of #6355

**Closed** 2021-11-13 00:13 UTC
