### ISSUE TITLE
[1.17 pre24 Shader Bug] Crashes when using  shaders on Mac 

### ISSUE THREAD

**Issue by gPm3** [sp614x/optifine#5933] opened 2021-06-29 22:43 UTC
## Description of Issue
When I press on the shader that I want to use it will load up and then Minecraft will completely lock up and I cannot leave the shader options menu. In order to unlock the game, I have to force quit Minecraft. If I have a shader on already and go to open on a world it just crashes. (This issue also occurs with the internal shaders) (Optifine shaders do work on my MacBook in 1.16 with only a few drops in frames so I can confirm that this is a problem with only the 1.17 version of optifine.) I personally believe that part of the reason why this happened is that mac cannot handle the wip 1.17 shaders and crashed because of their unfinished state but I am not an expert and will leave it to you to see

## Steps to Reproduce
1. Have Mac
2. Open up Minecraft
3. Go to the shaders option
4. Click on any shader
5. The Game will then lock up

## OptiFine Version
1.17 G9 pre24

## Installation Method
I installed the version by opening it in finder and pressing install

## Prior Testing
This only happens in 1.17 optifine though in 1.16 it is almost unplayable because of lag with some intense shaders
- This issue only occurs with optifine (obviously)

## Please fix this
I personally think that if it is possible making shaders playable on mac would be a substantial improvement

**Comment by Whitelisted1** [comment] 2021-06-29 22:58
Duplicate of #5900

**Closed** 2021-06-29 23:06 UTC
