### ISSUE TITLE
[Bug] OptiFine 1.18.2 H9_pre1 Incompatible with Forge 40.1.80 (ResourceCaching is removed)

### ISSUE THREAD

**Issue by ZenIsBestWolf** [sp614x/optifine#7136] opened 2022-10-12 17:30 UTC
## Description of Issue

When loaded via Forge 40.1.80, OptiFine attempts to access the ResourceCache, a class that was removed from Forge 40.1.80.
The use of this feature is a hot-button issue it seems, see https://github.com/MinecraftForge/MinecraftForge/pull/9026 for more information.
## Steps to Reproduce
1. Put OptiFine into your mods folder with Forge 40.1.80
2. Boot game

## OptiFine Version

H9_pre1

## Installation Method

Forge

## Fabric/Forge Version

40.1.80, specific to it

## Other Installed Mods

None.

## Log Files/Crash Reports

https://pastebin.com/xK5wX2Qi

**Comment by KillNagaThul** [comment] 2022-10-15 13:47
the same error since forge version 40.1.80, no version of Optifine works. Only Forge version 40.1.79 is stable with OptiFine HD U H9 pre1:
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 15/10/22 15:09
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraftforge/resource/ResourceCacheManager
	at net.minecraft.server.packs.VanillaPackResources.<init>(VanillaPackResources.java:505) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.resources.DefaultClientPackResources.<init>(DefaultClientPackResources.java:20) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading}
	at net.minecraft.client.resources.ClientPackSource.<init>(ClientPackSource.java:77) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:396) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.resource.ResourceCacheManager
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:138) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.server.packs.VanillaPackResources.<init>(VanillaPackResources.java:505) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.resources.DefaultClientPackResources.<init>(DefaultClientPackResources.java:20) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading}
	at net.minecraft.client.resources.ClientPackSource.<init>(ClientPackSource.java:77) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:396) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:API base de Windows 32 avanzado:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:Biblioteca de controles de la experiencia del usuario:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.19041.867 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DLL de API de cliente DNS:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:API auxiliar para IP:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Archivo DLL de cliente API BASE de Windows NT:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Archivo DLL de cliente API BASE de Windows NT:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.2209.7 (WinBuild.160101.0800):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:10.0.19041.1151 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.19041.610 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE para Windows:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.19041.985 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Ayudante de los datos de rendimiento DLL de Windows:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Tiempo de ejecución de llamada a procedimiento remoto:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Archivo DLL común del shell de Windows:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Archivo DLL de cliente API USER de Windows multiusuario:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.28.29913.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Servicios HTTP de Windows:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:DLL de 32 bits de Windows Socket 2.0:10.0.19041.1081 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		Wldp.dll:Directiva de bloqueo de Windows:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.19041.2075 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Biblioteca de primitivas criptográficas de Windows:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM para Windows:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:Servicio cliente DHCP:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:Cliente DHCPv6:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:API de modo usuario de FWP/IPsec:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:Java(TM) Platform SE binary:17.0.4.1:Oracle Corporation
		javaw.exe:Java(TM) Platform SE binary:17.0.4.1:Oracle Corporation
		jemalloc.dll
		jimage.dll:Java(TM) Platform SE binary:17.0.4.1:Oracle Corporation
		jli.dll:Java(TM) Platform SE binary:17.0.4.1:Oracle Corporation
		jna2235098452435602104.dll:JNA native library:6.1.2:Java(TM) Native Access (JNA)
		jsvml.dll:Java(TM) Platform SE binary:17.0.4.1:Oracle Corporation
		jvm.dll:Java HotSpot(TM) 64-Bit server VM:17.0.4.1:Oracle Corporation
		kernel.appcore.dll:AppModel API Host:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:Java(TM) Platform SE binary:17.0.4.1:Oracle Corporation
		management_ext.dll:Java(TM) Platform SE binary:17.0.4.1:Oracle Corporation
		mdnsNSP.dll:Bonjour Namespace Provider:3,1,0,1:Apple Inc.
		msvcp140.dll:Microsoft® C Runtime Library:14.28.29913.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Proveedor de servicios de Microsoft Windows Sockets 2.0:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:Proveedor de correcciones de compatibilidad (shim) de nomenclaturas de correo electrónico:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:Java(TM) Platform SE binary:17.0.4.1:Oracle Corporation
		nio.dll:Java(TM) Platform SE binary:17.0.4.1:Oracle Corporation
		ntdll.dll:DLL del nivel de Windows NT:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:DLL de objetos de rendimiento del sistema Windows:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:Proveedor de espacio de nombres PNRP:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.19041.844 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.320 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.320 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Biblioteca de utilidades de Shell:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.28.29913.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:Java(TM) Platform SE binary:17.0.4.1:Oracle Corporation
		win32u.dll:Win32u:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:API de almacenamiento de Microsoft WinRT:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:Java(TM) Platform SE binary:17.0.4.1:Oracle Corporation
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.4.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 854484696 bytes (814 MiB) / 1174405120 bytes (1120 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 4,01
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1b80
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2225
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 3,20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 3,20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 39896,55
	Virtual memory used (MB): 12854,00
	Swap memory total (MB): 23552,00
	Swap memory used (MB): 857,15
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.18.2-forge-40.1.84
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.18.2_HD_U_H9_pre1
	OptiFine Build: 20220823-161442
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 0

**Comment by ZenIsBestWolf** [comment] 2022-10-17 18:03
Yep can confirm temp. solution is to downgrade to Forge 40.1.79

**Comment by joe-vettek** [comment] 2022-10-24 06:55
thanks KillNagaThul. I fixed my conflict temparily.

**Comment by sp614x** [comment] 2022-11-14 09:59
Fixed in latest preview.

**Closed by sp614x** 2022-11-14 09:59 UTC
Labels: forge, todo, crash, 1.18
