### ISSUE TITLE
Crash with Optifine [Custom Sky Color]

### ISSUE THREAD

**Issue by Vyraal1** [sp614x/optifine#1093] opened 2017-12-23 18:40 UTC
Not exactly sure what's the cause of this crash or how to fix it - it sometimes occurs, and it sometimes doesn't.
https://pastebin.com/aWDicrNL

**Comment by sp614x** [comment] 2017-12-23 23:23
Duplicate of https://github.com/sp614x/optifine/issues/603
This seems to be a known limitation of Forge when extending enums: MinecraftForge/MinecraftForge#2787
To fix this JED should extend the enum as early as possible, for example in a static block in the main mod file.

**Closed by sp614x** 2017-12-23 23:23 UTC
Labels: crash, forge, mods

**Comment by Vyraal1** [comment] 2017-12-24 16:18
Hi, I just talked with the JED dev and he was wondering if it was possible if:

> masa: Of course there would also be the option that Optifine would stop using a switch on the DimensionType, due to it being an enum that mods need to modify...

Is this something that is do-able? Otherwise I can go back and see if another solution can be worked out.
