### ISSUE TITLE
[1.17] OptiFine OpenGL 3.2 Core profile required for some legacy Intel Linux drivers and macOS

### ISSUE THREAD

**Issue by 0-x-2-2** [sp614x/optifine#5739] opened 2021-06-09 18:36 UTC
OpenGL 3.2 compatibility profile is not supported by some unmaintained Intel GPU drivers on Linux. 

Some of these GPUs however do not support GL 3.2 at all on Windows and only GL 3.1 while others support both core profile 3.2 and compatibility profile on Windows but only GL 3.3 in core profile and 3.0 in compatibility profile on Linux.

So I suggest a fallback mode for OptiFine that would be for when GL 3.2+ compatibility profile is not supported that would disable some legacy features and tell the user why that feature was disabled but I assume would only be legacy shaders or shaders entirely because currently OptiFine 1.17 works on macOS while requesting compatibility profile despite macOS only supporting GL 3.2+ in core profile or GL 2.1 legacy profile.

Here is what happens in the logs for the game when the request for OpenGL 3.2 in legacy mode is requested but perhaps on macOS the request is ignored entirely and it will just crash and burn as soon as you attempt to use any legacy OpenGL so perhaps some more advanced detection method will be required other than requesting legacy mode then requesting core profile.
```
[10:33:05] [Render thread/WARN]: Failed to create window: 
dpq$a: GLFW error 65543: GLX: Failed to create context: GLXBadFBConfig
	at dpq.b(Window.java:334) ~[dpq.class:?]
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokePPPP(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at dpq.<init>(Window.java:132) ~[dpq.class:?]
	at enw.a(SourceFile:21) ~[enw.class:?]
	at dvo.<init>(SourceFile:483) ~[dvo.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:179) [Main.class:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.2.jar:2.2]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.2.jar:2.2]
```

Intel HD Graphics 3000 (SNB GT2) - i5-2400 (OpenGL 3.1 on Windows and OpenGL 3.3 in core profile with OpenGL 3.0 in legacy profile on Linux)
```
CORE PROFILE MODE:

OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 20.2.6
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

COMPATIBILITY MODE:

OpenGL version string: 3.0 Mesa 21.1.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
```

Intel HD Graphics 3000 (SNB GT2) - i3-2350M (OpenGL 3.3 in core profile with OpenGL 3.0 in legacy profile on Linux)
```
CORE PROFILE MODE:

OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 20.2.6
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:

COMPATIBILITY MODE:

OpenGL version string: 3.0 Mesa 20.2.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
```

[3.0 Mesa 20.2.6.txt](https://github.com/sp614x/optifine/files/6626063/3.0.Mesa.20.2.6.txt)
[3.0 Mesa 21.1.2.txt](https://github.com/sp614x/optifine/files/6626064/3.0.Mesa.21.1.2.txt)

**Comment by MayaValentia** [comment] 2021-06-09 22:48
Can reproduce on an AMD Radeon HD 8490 on 1.17 OptiFine HD U G9 pre18. Looks like this is not Intel specific.

System is a Dell Optiplex 990, i5-2400, 16GB RAM, AMD Radeon HD 8490, running on Debian bullseye (unstable). All packages are up to date. Vanilla Minecraft runs fine, but Minecraft does not run after installing OptiFine.

Minecraft log:
[log.txt](https://github.com/sp614x/optifine/files/6627248/log.txt)

Output of `glxinfo | grep OpenGL`: 
```
OpenGL vendor string: X.Org
OpenGL renderer string: AMD CAICOS (DRM 2.50.0 / 5.10.0-7-amd64, LLVM 11.0.1)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 20.3.5
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.1 Mesa 20.3.5
OpenGL shading language version string: 1.40
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 20.3.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
```

**Comment by 0-x-2-2** [comment] 2021-06-10 12:13
Seems like this works for some people but I am not sure why unless there is not much of a difference between GL 3.2 and GL 3.1/3.0 perhaps OptiFine could fall back to as far as GL 3.0 or GL 3.1 on Linux/Windows so these GPUs would also work on Windows? But if there really is no API difference between GL 3.0 and GL 3.2, I am not sure why these drivers don't support the compatibility profile with GL 3.2.

`env MESA_GL_VERSION_OVERRIDE=3.2 minecraft-launcher`

@MayaValentia Can you confirm if this lets you run the game and the performance is the same or better as using core profile with vanilla?

**Comment by astrosticks** [comment] 2021-06-10 22:48
@0-x-2-2 I am having a similar issue as @MayaValentia as far as I can launch 1.17 vanilla but not 1.17 optifine without getting the error `GLX: Failed to create context: GLXBadFBConfig`. Running the command you provided allows the game to launch. I am getting ~12fps on vanilla and ~45fps with OptiFine.

**Comment by pattontim** [comment] 2021-06-11 03:10
Same issue here with the GLX: Failed to create context: GLXBadFBConfig on start.
Intel HD Graphics 5500
i5-5200U
Using the override works. 

`server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.6
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.0.8
OpenGL core profile shading language version string: 4.60
OpenGL version string: 3.0 Mesa 20.0.8
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 20.0.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
    GL_EXT_shader_implicit_conversions, GL_EXT_shader_integer_mix, `

I deleted my optifine settings and used default, still get error.
FPS with optifine and defaults: 15-21, median 17
FPS with no optifine and with defaults: 6-13, median 10

**Comment by MayaValentia** [comment] 2021-06-11 04:32
@0-x-2-2 after using the command you provided above, I can confirm the game does run. Below are some statistics that I observed:

FPS with OptiFine enabled: min:29fps max:75fps average:57fps
Vanilla FPS: min:20fps max:75fps average:56fps
Vanilla FPS (while using provided command): min:20fps max:71fps average:45fps

It appears that OptiFine after using the command produces around the same performance as vanilla Minecraft with core profile.

**Comment by 0-x-2-2** [comment] 2021-06-14 16:48
Perhaps the game/optifine could fallback then without any problems :) to GL 3.0 or 3.1

**Comment by Dozer257** [comment] 2021-06-15 20:02
I have Minecraft Java Edition on Ubuntu 16.04 (Xfce Desktop) and I do get this issue as well when I try to run Optifine 1.17 pre21. I am running Ubuntu on a Chromebook using crouton just so you know.

I found something interesting that may or may not help the optifine devs to fix this.

```
[10:33:05] [Render thread/WARN]: Failed to create window: 
dpq$a: GLFW error 65543: GLX: Failed to create context: GLXBadFBConfig
```

I'm no expert but I think this means that the game does launch but without the window. I can prove this because when I try relaunching the game, Minecraft tells me that the game is already running in this directory. This means that the game did launch but without a window.

Again I'm no expert but it may give the developers a place to start from to try and fix this lol.

**Comment by KubaTMofficial** [comment] 2021-06-17 19:12
So any help? Manjaro 21.0.7

**Comment by Bombardier-C-Kram** [comment] 2021-06-17 19:42
For me, running `env MESA_GL_VERSION_OVERRIDE=3.2 minecraft-launcher` in bash, fixed my problem. I actually was able to edit my minecraft-launcher.desktop file to fix the problem permanently.

**Comment by KubaTMofficial** [comment] 2021-06-18 06:44
> For me, running `env MESA_GL_VERSION_OVERRIDE=3.2 minecraft-launcher` in bash, fixed my problem. I actually was able to edit my minecraft-launcher.desktop file to fix the problem permanently.

ok thank you, i was just stupid because i had at the end minectagy-launcher when i was using package minecraft-launcher-ot for minecraft

**Comment by TheAtticYT** [comment] 2021-06-18 17:36
Is there some way to do that in windows?

**Comment by Bombardier-C-Kram** [comment] 2021-06-21 22:37
> Is there some way to do that in windows? Like in wsl or something?

Maybe? I think you can provide env vars in the command line, but it has been a while since I have used windows

**Comment by TheAtticYT** [comment] 2021-06-21 22:53
I figured out that you can make a bat file with this code:
set MESA_GL_VERSION_OVERRIDE=3.2
MinecraftLauncher.exe
In the Minecraft Launcher directory so C:\Program Files (x86)\Minecraft Launcher then make sure you have mesa for windows [https://fdossena.com/?p=mesa/index.frag](https://fdossena.com/?p=mesa/index.frag) and that should work.

**Comment by 0-x-2-2** [comment] 2021-06-23 17:22
> Is there some way to do that in windows? Like in wsl or something?

Mesa on windows is usually not hardware accelerated afaik and is just software rendering unlike this on linux, so I would not recommend using windows at all for Minecraft if you have this GPU as it is not supported at all.

**Comment by claude0001** [comment] 2021-06-28 20:11
I have this issue on two Linux (Debian 8) machines. One with a quite ancient Radeon Mobility 3470:

> ~> glxinfo | grep OpenGL
> OpenGL vendor string: X.Org
> OpenGL renderer string: Gallium 0.4 on AMD RV620 (DRM 2.49.0 / 4.9.0-0.bpo.15-amd64, LLVM 3.8.1)
> OpenGL core profile version string: 3.3 (Core Profile) Mesa 13.0.6
> OpenGL core profile shading language version string: 3.30
> OpenGL core profile context flags: (none)
> OpenGL core profile profile mask: core profile
> OpenGL core profile extensions:
> OpenGL version string: 3.0 Mesa 13.0.6
> OpenGL shading language version string: 1.30
> OpenGL context flags: (none)
> OpenGL extensions:
> OpenGL ES profile version string: OpenGL ES 3.0 Mesa 13.0.6
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

and a relatively modern setup with integrated Intel HD 5500:

> ~> glxinfo | grep OpenGL
> OpenGL vendor string: Intel Open Source Technology Center
> OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
> OpenGL core profile version string: 4.5 (Core Profile) Mesa 13.0.6
> OpenGL core profile shading language version string: 4.50
> OpenGL core profile context flags: (none)
> OpenGL core profile profile mask: core profile
> OpenGL core profile extensions:
> OpenGL version string: 3.0 Mesa 13.0.6
> OpenGL shading language version string: 1.30
> OpenGL context flags: (none)
> OpenGL extensions:
> OpenGL ES profile version string: OpenGL ES 3.1 Mesa 13.0.6
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

Both machines run Vanilla Minecraft 1.17 just fine, as well as all Optifine releases up to 1.16.5. Optifine 1.17 (tested up to pre24) fails with "GLFW error 65543: GLX: Failed to create context: GLXBadFBConfig".

The above proposed workaround of launching Minecraft using `env MESA_GL_VERSION_OVERRIDE=3.2 minecraft-launcher` does **not** work for me on either machine: I get the same error message.

Actually, the Minecraft log still says 

> [...]
> 21:57:02.009   Backend library: LWJGL version 3.2.2 build 10
> 21:57:02.545   OpenGL Compatibility Profile
> 21:57:02.556   [OptiFine] (Reflector) Method not present:
>                      net.minecraftforge.fml.loading.progress.EarlyProgressVisualization.handOffWindow
> 22:02:07.444   Failed to create window:
>                      dpq$a: GLFW error 65543: GLX: Failed to create context: GLXBadFBConfig 
> [...]

even with the override set. This surprises me, as, from reading [https://docs.mesa3d.org/envvars.html](url), I thought with `env MESA_GL_VERSION_OVERRIDE=3.2 minecraft-launcher` I would force MESA to report a 3.2 **Core** profile (not Compat) ...

Any help is appreciated.

**Comment by 0-x-2-2** [comment] 2021-07-01 16:14
> I would force MESA to report a 3.2 Core profile (not Compat)

No this forces OpenGL "3.2" compatibility profile and it should work if your GPU supports 3.1 or 3.0 already.

**Comment by 0-x-2-2** [comment] 2021-07-01 16:18
> The above proposed workaround of launching Minecraft using `env MESA_GL_VERSION_OVERRIDE=3.2 minecraft-launcher` does **not** work for me on either machine: I get the same error message.

Perhaps the environment variable was not set and this will only work with mesa drivers.
```bash
export MESA_GL_VERSION_OVERRIDE=3.2
minecraft-launcher
```

**Comment by claude0001** [comment] 2021-07-01 16:34
> No this forces OpenGL "3.2" compatibility profile and it should work if your GPU supports 3.1 or 3.0 already.

Are you sure about this? According to https://docs.mesa3d.org/envvars.html `MESA_GL_VERSION_OVERRIDE=X.Y` sets a **core** profile for X.Y>=3.2 and `MESA_GL_VERSION_OVERRIDE=X.YCOMPAT` is needed for setting a compatibility profile if X.Y >= 3.2.
Anyway, also the latter did not work for me. 

To be honest, I do not understand why this workaround would work at all: If my driver (as per `glxinfo`, see above) supports only a 3.0 compatibility profile, isn't wrongly reporting 3.2-COMPAT bound to cause problems? Also, why does vanilla 1.17 run fine using (as far as I know) 3.2-Core (not Compat)? Why can't Optifine do the same?

> Perhaps the environment variable was not set and this will only work with mesa drivers.
> export MESA_GL_VERSION_OVERRIDE=3.2
> minecraft-launcher

I am using the mesa DRI drivers on both machines, as can be seen from the `glxinfo` snippets above. I tried exporting the env variable to be sure. Did not help. Thanks for the idea anyway!

**Comment by claude0001** [comment] 2021-07-01 21:09
So I checked this empirically on my systems: Indeed the documentation (as so often) is right: Setting `MESA_GL_VERSION_OVERRIDE=3.2` causes MESA to report a 3.2-_Core_ profile. For faking a 3.2-_Compatibility_ profile `MESA_GL_VERSION_OVERRIDE=3.2COMPAT` is required:

> ~> env MESA_GL_VERSION_OVERRIDE=**3.2** glxinfo | grep OpenGL
> OpenGL vendor string: Intel Open Source Technology Center
> OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
> OpenGL core profile version string: 3.2 (Core Profile) Mesa 13.0.6
> OpenGL core profile shading language version string: 4.50
> OpenGL core profile context flags: (none)
> OpenGL core profile profile mask: core profile
> OpenGL core profile extensions:
> OpenGL version string: **3.2 (Core Profile) Mesa 13.0.6**
> OpenGL shading language version string: 4.50
> OpenGL context flags: (none)
> **OpenGL profile mask:** **core profile**
> OpenGL extensions:
> OpenGL ES profile version string: OpenGL ES 3.1 Mesa 13.0.6
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10 

as opposed to

> ~> env MESA_GL_VERSION_OVERRIDE=**3.2COMPAT** glxinfo | grep OpenGL
> OpenGL vendor string: Intel Open Source Technology Center
> OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
> OpenGL core profile version string: 3.2 Mesa 13.0.6
> OpenGL core profile shading language version string: 4.50
> OpenGL core profile context flags: (none)
> OpenGL core profile profile mask: compatibility profile
> OpenGL core profile extensions:
> OpenGL version string: **3.2 Mesa 13.0.6**
> OpenGL shading language version string: 4.50
> OpenGL context flags: (none)
> **OpenGL profile mask:** **compatibility profile**
> OpenGL extensions:
> OpenGL ES profile version string: OpenGL ES 3.1 Mesa 13.0.6
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

By running the Vanilla Minecraft 1.17 client, I could also check that my environment variables are indeed picked up correctly: When I run the launcher with `export MESA_GL_VERSION_OVERRIDE=3.2; ./minecraft_launcher`, the debug overlay (F3) of Vanilla shows the OpenGL version string "3.2 (Core Profile) Mesa 13.0.6". 

After launching with `export MESA_GL_VERSION_OVERRIDE=3.2COMPAT; ./minecraft_launcher` the debug screen shows "3.2 Mesa 13.0.6", in perfect agreement with what `glxinfo` tells me.

Still, neither override allows me to run Optifine 1.17-pre24 on either machine, even though my MESA drivers support OpenGL core profiles up to 3.3 and 4.5, respectively.

I think I have now understood that Optifine needs the "3.2-COMPAT" profile (as opposed to 3.2-CORE of the Vanilla client) mainly for shaders (which I do not use). Would it be possible to just disable shaders if the driver reports COMPAT support < 3.2 and then run on 3.2-CORE like the official client?

I am under the impression that this issue affects a lot of Linux users, so some kind of fallback mode would be good, otherwise we'll have to give up on Optifine after many happy years :-(

**Comment by 0-x-2-2** [comment] 2021-07-01 22:44
Many OptiFine features currently get disabled if you force core profile but nothing should stop optifine from running in compatibility profile as nothing has changed since GL 3.0 and 3.2.

**Comment by adiantek** [comment] 2021-07-07 01:01
It also affects Windows ARMv8 (like Surface Pro X): https://github.com/sp614x/optifine/issues/5978 and everything with [OpenCL™ and OpenGL® Compatibility Pack](https://devblogs.microsoft.com/directx/announcing-the-opencl-and-opengl-compatibility-pack-for-windows-10-on-arm/)

**Comment by claude0001** [comment] 2021-07-07 18:04
For me, the problem persists with 1.17-pre25.

I'm close to giving up on Optifine because of this. Its main purpose used to be to enable Minecraft to run on outdated hardware. Now the inverse is true: Vanilla 1.17+ runs just fine, but Optifine is unhappy with my hardware.

**Comment by Stereo528** [comment] 2021-07-21 20:10
Supposedly there is a fix for this in 1.17.1 G9 pre30
![image](https://user-images.githubusercontent.com/52116771/126553511-18240897-7119-4639-b6ac-0f46b06a4e00.png)

**Comment by claude0001** [comment] 2021-07-22 20:02
For me, the problem persists with 1.17.1-pre30.

Still, the "MESA_GL_VERSION_OVERRIDE=3.2" workaround does not help.

Honestly, this problem has caused me to give up on Optifine for Fabric/Sodium, which just works on all my systems. But for the sake of the good old times, I will keep monitoring this thread and test new builds if they seem promising.

**Comment by KaiAF** [comment] 2021-07-29 03:01
I'm going to pin the issue so that the developer can see it. This of course does not mean that this bug has a priority compared to other bugs.

**Comment by astrosticks** [comment] 2021-07-29 19:45
@KaiAF I don't mean to sound disrespectful, but I believe that this issue should have the bug label and not the enhancement label since it is essentially a regression of supported platforms between Optifine for 1.16 vs 1.17.

**Comment by KaiAF** [comment] 2021-07-29 19:54
that's why I removed the enhancement label and added the bug label last night

**Comment by astrosticks** [comment] 2021-07-29 19:56
Agghh I read it backwards, sorry!

**Comment by hamoodisbeyyer** [comment] 2021-08-12 04:06
im a debian linux and whenever i run minecraft with optifine it tells me to have up to date drivers when i use the command given by the suggsted website it starts putting these ~ then says END as you can see capitalized

**Comment by sp614x** [comment] 2021-08-20 19:12
In pre34 the fallback to OpenGL compatibility profile is removed.
It uses only core profile on all platforms.

**Closed by sp614x** 2021-08-20 19:12 UTC
Labels: bug, 1.17

**Comment by claude0001** [comment] 2021-08-21 09:41
Solved for me on my Intel GPU with Mesa 13 on Linux kernel 3.13:

> OpenGL vendor string: Intel Open Source Technology Center
> OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
> OpenGL core profile version string: 4.5 (Core Profile) Mesa 13.0.6
> OpenGL core profile shading language version string: 4.50
> OpenGL core profile context flags: (none)
> OpenGL core profile profile mask: core profile
> OpenGL core profile extensions:
> OpenGL version string: 3.0 Mesa 13.0.6
> OpenGL shading language version string: 1.30

Still have to test on my AMD graphics system, but I guess that will work now, too. Thanks.

**Comment by RIC217** [comment] 2022-03-01 20:31
> `env MESA_GL_VERSION_OVERRIDE=3.2 minecraft-launcher`

worked for me ! Thank you !

**Comment by rafaelgramoschi** [comment] 2022-07-30 15:07
FOR UBUNTU/LINUX (EXTREMELY SLOW):

`glxinfo | grep OpenGL`
RESULT: OpenGL version string: 2.1

OpenGL 3.x is nt supported on Intel Ironlake. You will need at least Intel Sandy Bridge to get modern OpenGL on Intel GPUs.

You can just try
`LIBGL_ALWAYS_SOFTWARE=1 glxinfo | grep OpenGL`
and see if you get a better version.
RESULT: OpenGL version string: 3.1

You can get OpenGL 3.1 (YOUR version might be different) from mesa's llvmpipe or softpipe software renderers by setting the LIBGL_ALWAYS_SOFTWARE=1 environment variable. However, since this will not use the GPU at all, it will be rather slow.

`env LIBGL_ALWAYS_SOFTWARE=1 MESA_GL_VERSION_OVERRIDE=4.5 minecraft-launcher`
