### ISSUE TITLE
[Forge & Shaders] Using any shaders on FTB: Revelation crashes the game while loading

### ISSUE THREAD

**Issue by tasses** [sp614x/optifine#4106] opened 2020-06-16 14:42 UTC
## Description of Issue
The game crashes while loading shaders in a singleplayer world in FTB: Revelation. World runs very smoothly (150 fps) without shaders. Unfortunately the game crashes to launcher (MultiMC) during the loading process. Have not had this problem with Optifine and these shaders (Sildur's Medium) in other instances.

## Steps to Reproduce
1. Play FTB Revelation with Optifine.
2. Load Sildur's Medium shaders.
3. Crash game.

## OptiFine Version
OptiFine_1.12.2_HD_U_F5

## Installation Method
I downloaded the mod and put it into my mods folder (using MultiMC).

## Fabric/Forge Version
Forge 14.23.5.2846 for 1.12.2.

## Other Installed Mods
/dank/null | TheRealp455w0rd | 1.0.0
Actually Additions | Ellpeck | 1.0.0
Actually Baubles | Jacky1356400 | 1.0.0
Advanced Machines | Chocohead | 3.0.0
Advanced Solar Panels | Chocohead | 3.0.0
AE2 Wireless Terminals (AE2WTLib) | TheRealp455w0rd
Akashic Tome | Vazkii | 1.0.0
AppleSkin | squeek502 | 1.0.0
Applied Energistics 2 | AlgorithmX2 | 1.0.0
ArchitectureCraft | darkevilmac | 1.0.0
Aroma1997's Dimensional World | Aroma1997 | 1.0.0
Aroma1997Core | Aroma1997 | 1.0.0
Astral Sorcery | HellFirePvP | 1.0.0
AutoRegLib | Vazkii | 1.0.0
B.A.S.E | lanse505 | 1.0.0
Bad Wither No Cookie - Reloaded | kreezxil | 1.0.0
Baubles | azanor | 1.0.0
BdLib | bdew | 1.0.0
Better Advancements | Way2muchnoise | 1.0.0
Better Builder's Wands | Portablejim | 1.0.0
BiblioCraft | JDSinclair | 1.0.0
Binnie Core | Binnie | 1.0.0
Binnie's Botany | Binnie | 1.0.0
Binnie's Design | Binnie | 1.0.0
Binnie's Extra Bees | Binnie | 1.0.0
Binnie's Extra Trees | Binnie | 1.0.0
Binnie's Genetics | Binnie | 1.0.0
Biomes O' Plenty | GlitchfiendMods | 3.0.0
Blockcraftery | elucent | 1.0.0
Blood Magic | WayOfTime | 2.0.0
Bookshelf | darkh4x | 1.0.0
Botania | Vazkii | 1.0.0
Brandon's Core | brandon3055 | 1.0.0
bspkrsCore | bspkrs | 7.6.0.1
BuildCraft | Covert_Jaguar | 3.0.0
Career Bees | RWTema | 1.0.0
CC: Tweaked (ComputerCraft fork) | Daniel Ratcliffe, Aaron Mills, SquidDev | 3.0.0
Chameleon | jaquadro | 1.0.0
Chest Transporter | CubeX2 | 1.0.0
Chisel | tterrag1098 | 1.0.0
Chisels & Bits | AlgorithmX2 | 1.0.0
Clumps | Jaredlll08 | 1.0.0
CodeChickenLib | covers1624 | 1.0.0
CoFH Core | TeamCoFH | 1.0.0
CoFH World | TeamCoFH | 1.0.0
Compact Solar Arrays | cpw | 1.0.0
Construct's Armory | TheIllusiveC4 | 2.0.0
Controlling | Jaredlll08 | 1.0.0
Cooking for Blockheads | BlayTheNinth | 1.0.0
CraftTweaker JEI Support | Jaredlll08 | 1.0.0
CraftTweaker-2 | Jaredlll08 | 1.0.0
CT-GUI (CraftTweaker) | Jaredlll08 | 1.0.0
ConnectedTexturesMod (CTM) | tterrag | 1.0.0
Custom Main Menu | lumien231 | 1.0.0
Dark Utilities | darkh4x | 1.0.0
Deep Resonance | McJty | 1.0.0
Default Options | BlayTheNinth | 1.0.0
Diet Hoppers | RWTema | 1.0.0
Dirt2Path | marwat208 | 1.0.0
Draconic Evolution | brandon3055 | 1.0.0
ElecCore | Elec332 | 1.0.0
ElecCoreLoader | Elec332
Ender IO | CrazyPants | 2.0.0
EnderCore | tterrag1098 | 2.0.0
EnderStorage | covers1624 | 1.0.0
Engineer's Doors | Nihiltres | 2.0.0
Engineers Workshop Reborn | modmuss50 | 1.0.0
Environmental Tech | ValkyrieofNight | 1.0.0
ET Lunar | ValkyrieofNight | 1.0.0
Exchangers | Jacky1356400 | 1.0.0
Extra Utilities 2 | RWTema | 1.0.0
Extreme Reactors | ZeroNoRyouki | 1.0.0
FastWorkbench | Shadows_Of_Fire | 2.0.0
Fence Jumper | TheRealp455w0rd | 1.0.0
Flat Colored Blocks | AlgorithmX2 | 1.0.0
Flux Networks | Ollie_Lansdell | 1.0.0
FoamFix | asiekierka | 1.0.0
FoamFixCore | asiekierka | 1.0.0
Forestry | SirSengir, mezz | 1.0.0
Forge Microblocks | ChickenBones
Forge Mod Loader | cpw, LexManos, Player
Forge Multipart CBE | ChickenBones | 2.0.0
FTB Guides | LatvianModder (FTB Team) | 2.0.0
FTB Launcher Notifier | LatvianModder (FTB Team)
FTB Library | LatvianModder (FTB Team) | 1.0.0
FTB Utilities | LatvianModder (FTB Team) | 1.0.0
FTB Utilities: Backups | LatvianModder (FTB Team) | 3.0.0
Gendustry | bdew | 1.0.0
Gravitation Suite | Chocohead | 3.0.0
Guide-API | TehNut | 1.0.0
Harvest (Simple Harvest) | TehNut | 2.0.0
Immersive Cables | SanAndreasP | 3.0.0
Immersive Engineering | BluSunrize | 1.0.0
Immersive Petroleum | Flaxbeard | 1.0.0
Industrial Foregoing | Buuz135 | 1.0.0
Industrial Wires | malte0811 | 2.0.0
IndustrialCraft 2 | Player | 1.0.0
Initial Inventory | Jaredlll08 | 2.2.0
Integration Foregoing | Jackyy, Buuz135 | 2.5.0
Inventory Tweaks | Kobata | 1.0.0
Iron Backpacks | gr8pefish | 1.0.0
Iron Chests | progwml6 | 1.0.0
JEI Bees | bdew | 1.0.0
JEI Integration | SnowShock35 | 1.0.0
JourneyMap | techbrew | 1.0.0
Just Enough HarvestCraft | mrAppleXZ | 1.0.0
Just Enough Items (JEI) | mezz | 1.0.0
Just Enough Resources | Way2muchnoise | 1.0.0
Let's Encrypt Craft | CloudyPSP
Long Fall Boots | NanoHeart | 1.0.0
Magic Bees | MysteriousAges | 1.0.0
Mantle | mDiyo | 1.0.0
McJtyLib | McJty | 1.0.0
MCMultiPart | amadornes | 1.0.0
Minecraft Coder Pack | MCP Team
Minecraft Forge | LexManos, cpw, fry | 1.0.0
Minecraft MultiPart Plugin | ChickenBones
MineTogether | Creeperhost | 1.0.0
MineTogetherServer | Creeperhost
Mod Name Tooltip | mezz | 1.0.0
ModTweaker | Jaredlll08 | 1.0.0
More Overlays | feldim2425 | 2.0.0
Morph-o-Tool | Vazkii | 1.0.0
Morpheus | Quetzi | 1.0.0
Mouse Tweaks | YaLTeR97 | 1.0.0
MrTJPCore | MrTJP | 2.0.0
MTLib | Jaredlll08 | 1.0.0
Mystical Lib | EpicSquid, Elucent
Natura | mDiyo | 1.0.0
Nature's Compass | ChaosTheDude | 1.0.0
Nice (xNICEx) | McJty, xVipstarsx | 1.0.0
Not Enough Wands | romelo333 | 1.0.0
NotEnoughIDs | fewizz | 1.0.0
OpenBlocks | OpenMods Team | 2.0.0
OpenModsLib | OpenMods Team | 2.0.0
OpenModsLibCore | OpenMods Team
p455w0rd's Library | TheRealp455w0rd | 1.0.0
Pam's HarvestCraft | MatrexsVigil | 1.0.0
Patchouli | Vazkii
Phosphor Lighting Engine | jellysquid | 3.2.0
Placebo | Shadows_of_Fire | 1.0.0
Platforms | ShetiPhian | 1.0.0
Project Red Core | MrTJP, ChickenBones, covers1624 | 2.0.0
Project Red Compat | MrTJP, ChickenBones | 3.1.0
Quark | Vazkii | 1.0.0
Quick Leaf Decay | lumien231 | 1.0.0
Railcraft | Covert_Jaguar | 3.0.0
RandomPatches | TheRandomLabs | 3.0.0
Ranged Pumps | raoulvdberge | 1.0.0
ReAuth | TechnicianLP | 1.0.0
Reborn Core | modmuss50 | 1.0.0
Reborn Storage | modmuss50 | 2.1.0
Redstone Arsenal | TeamCoFH | 1.0.0
Redstone Flux | TeamCoFH | 1.0.0
Refined Storage | raoulvdberge | 2.1.0
Refined Storage Addons | raoulvdberge | 2.1.0
Reliquary | P3pp3rF1y | 1.0.0
Resource Loader | lumien231 | 1.0.0
RFTools | McJty | 1.0.0
RFTools Control | McJty | 1.0.0
RFTools Power | McJty | 2.0.0
Rustic | mangoose3039 | 1.0.0
Shadowfacts' Forgelin | Shadowfacts | 1.0.0
ShadowMC | Shadowfacts | 2.0.0
ShetiPhianCore | ShetiPhian | 1.0.0
Simple Void World | modmuss50 | 1.0.0
Simply Jetpacks 2 | Tomson124 | 2.0.0
Snad | TheRoBrit | 1.0.0
Sonar Core | Ollie_Lansdell | 1.0.0
Soul Shards Respawn | TehNut | 3.0.0
Steve's Carts 2 (Reborn) | modmuss50 | 1.0.0
Storage Drawers | jaquadro | 1.0.0
Storage Drawers Extras | jaquadro | 1.0.0
Tesla Core Lib | Face_of_Cat | 1.0.0
Tesla Core Lib Registries | Face_of_Cat
Thaumcraft 6 | Azanor | 2.0.0
Thaumcraft Inventory Scanning | BlayTheNinth | 2.0.0
Thaumic JEI | Buuz135 | 2.0.0
The Lost Cities | McJty | 1.0.0
The One Probe | McJty | 1.0.0
The Twilight Forest | Benimatic | 2.0.0
Thermal Cultivation | TeamCoFH | 1.0.0
Thermal Dynamics | TeamCoFH | 1.0.0
Thermal Expansion 5 | TeamCoFH | 1.0.0
Thermal Foundation | TeamCoFH | 1.0.0
Thermal Innovation | TeamCOFH | 2.0.0
Thut Core | Thusmose | 1.0.0
Thut's Elevators | Thusmose | 1.0.0
Tinkers' Tool Leveling | bonusboni
Tinkers' Construct | boni, KnightMiner | 1.0.0
TipTheScales | Jaredlll08 | 1.0.0
TOP Addons | DrManganese | 1.0.0
TorchMaster | xalcon | 1.0.0
Translocators | covers1624 | 2.0.0
TreeCapitator | DaftPVF, bspkrs | 1.43.0
UniDict | WanionCane | 1.0.0
Universal Modifiers (ValkyrieLib) | ValkyrieofNight
ValkyrieLib | ValkyrieofNight | 1.0.0
WanionLib | WanionCane | 1.0.0
Waystones | BlayTheNinth | 1.0.0
Wireless Crafting Terminal 2 | TheRealp455w0rd | 1.0.0
Woot | Ipsis | 2.2.0
XNet | McJty | 1.0.0
Xtones | TehNut | 1.0.0
YABBA | LatvianModder | 1.0.0
ZeroCore

## Log Files/Crash Reports
https://paste.ee/p/XA3em

## F3 Debug Screenshot
N/A (crash)

## Prior Testing
If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   **- Only OptiFine and Forge** - Modpack. Need Optifine for shaders.
- Does this happen in OptiFine standalone?
   **- No.**
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine
   **- Seems like a lot of work for what looks like a shader crash.**

**Comment by sp614x** [comment] 2020-06-18 15:47
```
java.lang.NoSuchFieldError: field_191308_b
	at net.optifine.config.ConnectedParser.parseEntities(ConnectedParser.java:1248)
	at net.optifine.shaders.EntityAliases.loadEntityAliases(EntityAliases.java:164)
	at net.optifine.shaders.EntityAliases.update(EntityAliases.java:89)
	at net.optifine.shaders.Shaders.loadShaderPackProperties(Shaders.java:1086)
	at net.optifine.shaders.Shaders.loadShaderPack(Shaders.java:948)
	at net.optifine.shaders.Shaders.setShaderPack(Shaders.java:871)
```

**Comment by sp614x** [comment] 2020-06-18 15:52
Duplicate of #3452, #3187, #3140, #3044

**Closed by sp614x** 2020-06-18 15:52 UTC
