### ISSUE TITLE
[Bug] Chunk Loading Issues

### ISSUE THREAD

**Issue by Gavins38** [sp614x/optifine#4229] opened 2020-07-04 13:02 UTC
so i saw that optifine released for 1.16.1
i got it to improve my performance but the chunks wont load anything in servers or singleplayer
this doesnt happen when i dont use optifine the chunks load fine
in the image below ith been sitting there for 20 minutes
this also happind with 1.15.2 optifine also where chunks wouldnt load
it doesnt happen with any other versions except 1.15 and 1.16 i dont understand why

![image](https://user-images.githubusercontent.com/67829574/86513052-110d7600-bdd5-11ea-91fb-5b1e03b74f0b.png)

for refrance heres a image without using optifine
![2020-06-30_13 15 00](https://user-images.githubusercontent.com/67829574/86513134-c2141080-bdd5-11ea-8a7f-905d18ae2539.png)

**Comment by deprale** [comment] 2020-08-09 10:05
same

**Comment by KaiAF** [comment] 2021-04-04 03:44
Seems to be a duplicate of #4908.

**Closed by KaiAF** 2021-04-04 03:44 UTC
