### ISSUE TITLE
OptFine_1.14.2_hd_u_F1_pre15_MOD.jar is OptiFine, witch is unsupported

### ISSUE THREAD

**Issue by deathishere420** [sp614x/optifine#2539] opened 2019-06-26 05:48 UTC
[00:44:17] [main/INFO]: ModLauncher starting: java version 1.8.0_51 by Oracle Corporation
[00:44:18] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[00:44:18] [main/WARN]: Mod file Mod File: C:\Users\adew7\AppData\Roaming\.minecraft\mods\OptiFine_1.14.2_HD_U_F1_pre15_MOD.jar is missing mods.toml file
[00:44:18] [main/WARN]: File C:\Users\adew7\AppData\Roaming\.minecraft\mods\OptiFine_1.14.2_HD_U_F1_pre15_MOD.jar has been ignored - it is invalid
[00:44:19] [main/INFO]: Launching target 'fmlclient' with arguments [--version, 1.14.2-forge-26.0.63, --gameDir, C:\Users\adew7\AppData\Roaming\.minecraft, --assetsDir, C:\Users\adew7\AppData\Roaming\.minecraft\assets, --username, Gushwin, --assetIndex, 1.14, --uuid, d19ec72b4d474c7cb5ae31ac50ed2746, --accessToken, ????????, --userType, mojang, --versionType, release]

**Comment by sp614x** [comment] 2019-06-26 14:00
Duplicate of #2457, #2207.

**Closed by sp614x** 2019-06-26 14:00 UTC
