### ISSUE TITLE
CIT for Lingering Potion overlays does not work properly

### ISSUE THREAD

**Issue by DataCrusader** [sp614x/optifine#782] opened 2017-07-21 04:15 UTC
I've been trying to give different textures to different potions and strengths, and I've double-checked many times that everything is correct, but when I try to apply my own overlay to my Lingering Potion, it just doesn't work. No idea why this is happening, as it SHOULD work.

Looked for similar issues, and I found this: https://github.com/sp614x/optifine/issues/655
Basically explains everything perfectly, also is months old and never fixed and that's why I'm bringing it up again now.

**Comment by sp614x** [comment] 2017-07-22 15:10
So, duplicate of #655.
Closing it, no need for two issues on the same topic.

**Closed by sp614x** 2017-07-22 15:10 UTC
