### ISSUE TITLE
[1.14.4] Parrot CEM doesn't work when on players shoulder

### ISSUE THREAD

**Issue by Zartrix** [sp614x/optifine#2989] opened 2019-10-19 14:58 UTC
Like the title says, the parrot CEM won't load in when the parrot is on a player's shoulder.

Edit: Maybe add a "parrot_shoulder" CEM so we can also change the position of where the parrot will sit on a player.

**Comment by sp614x** [comment] 2019-10-21 15:34
Duplicate of #2295

**Closed by sp614x** 2019-10-21 15:34 UTC
