### ISSUE TITLE
Nametagged zombies disappearing

### ISSUE THREAD

**Issue by notnotnami** [sp614x/optifine#5296] opened 2021-02-05 11:07 UTC
I have two nametagged zombies in my world but when I turn on OptiFine they disappear.
When turning it off they are visible again.

I've experienced this bug in OptiFine 1.16.4 and 1.16.5

**Comment by sp614x** [comment] 2021-02-05 11:55
Duplicate of  #5016

**Closed by sp614x** 2021-02-05 11:55 UTC
