### ISSUE TITLE
Clouds are obstructed by large box

### ISSUE THREAD

**Issue by cam-reno** [sp614x/optifine#5057] opened 2020-11-22 23:45 UTC
## Description of Issue
there is a rectangle box on the screen that does not display clouds and you can still see them on the top area of the screen

## Steps to Reproduce
1. look up at the sky with clouds on

## OptiFine Version
1.16.4 HD U G5

## Installation Method
Used the .jar installer from the [official website](https://optifine.net/downloads)

## F3 Debug Screenshot
With OptiFine 
 ![2020-11-22_18 24 55](https://user-images.githubusercontent.com/74881572/99920305-9ba53200-2cf0-11eb-9c9c-e4e7ba867af0.png)
Vanilla
![2020-11-22_18 36 05](https://user-images.githubusercontent.com/74881572/99920482-c643ba80-2cf1-11eb-8675-a6cb40761150.png)
![2020-11-22_18 36 11](https://user-images.githubusercontent.com/74881572/99920484-c93eab00-2cf1-11eb-95ce-9f62a4162d85.png)

## Prior Testing
Does not occur in Vanilla 1.16.4

## Additional Information
moving clouds to off may help in seeing the glitch.

## Screenshots
Vanilla
![2020-11-22_18 35 04](https://user-images.githubusercontent.com/74881572/99920441-7f55c500-2cf1-11eb-82a7-fd385ab7c4f9.png)
![2020-11-22_18 35 10](https://user-images.githubusercontent.com/74881572/99920445-87ae0000-2cf1-11eb-9ec6-0320f6b70fd5.png)
OptiFine
![2020-11-22_18 26 48](https://user-images.githubusercontent.com/74881572/99920497-e4111f80-2cf1-11eb-9532-971d636439d7.png)
![2020-11-22_18 26 50](https://user-images.githubusercontent.com/74881572/99920502-ed9a8780-2cf1-11eb-9154-42b63f337f79.png)
![2020-11-22_18 26 57](https://user-images.githubusercontent.com/74881572/99920506-f8551c80-2cf1-11eb-830c-6288d50d0e08.png)

**Comment by fayer3** [comment] 2021-02-11 14:27
probably duplicate of #3453

**Comment by KaiAF** [comment] 2021-03-29 13:18
Duplicate of #3453

**Closed by KaiAF** 2021-03-29 13:18 UTC
