### ISSUE TITLE
Oprifine Crash! FTB Infinity Evolved with OptiFine!

### ISSUE THREAD

**Issue by Shoxxo** [sp614x/optifine#670] opened 2017-05-25 11:29 UTC
I would inform, that OptiFine has a Problem with FTB!

```quote
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 25.05.17 13:24
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/TextureMap
	at fastcraft.Z.<clinit>(F:11)
	at fastcraft.ab.<clinit>(F:16125)
	at fastcraft.HC.j(F:70)
	at net.minecraft.client.renderer.texture.DynamicTexture.func_110564_a(DynamicTexture.java)
	at net.minecraft.client.renderer.texture.TextureUtil.<clinit>(TextureUtil.java:460)
	at net.minecraft.client.shader.Framebuffer.func_147605_b(Framebuffer.java:104)
	at net.minecraft.client.shader.Framebuffer.func_147613_a(Framebuffer.java:56)
	at net.minecraft.client.shader.Framebuffer.<init>(Framebuffer.java:37)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.TextureMap
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at fastcraft.Z.<clinit>(F:11)
	at fastcraft.ab.<clinit>(F:16125)
	at fastcraft.HC.j(F:70)
	at net.minecraft.client.renderer.texture.DynamicTexture.func_110564_a(DynamicTexture.java)
	at net.minecraft.client.renderer.texture.TextureUtil.<clinit>(TextureUtil.java:460)
	at net.minecraft.client.shader.Framebuffer.func_147605_b(Framebuffer.java:104)
	at net.minecraft.client.shader.Framebuffer.func_147613_a(Framebuffer.java:56)
	at net.minecraft.client.shader.Framebuffer.<init>(Framebuffer.java:37)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4149390840 bytes (3957 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx4096m -XX:+UseG1GC -XX:MaxGCPauseMillis=4
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 560 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.33, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Sphax PureBDcraft 128x MC17.zip]
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D7
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 382.33
	OpenGlRenderer: GeForce GTX 560 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by sp614x** [comment] 2017-05-25 21:25
Duplicate of #588.

FastCraft 1.25 should work:
https://forum.industrial-craft.net/thread/10820-wip-1-7-10-fastcraft-1-23-note-all-posts-of-new-members-need-to-be-approved-firs/?postID=207199#post207199

**Closed by sp614x** 2017-05-25 21:25 UTC
