### ISSUE TITLE
[1.16.5_HD_U_G8][CEM] G8 randomly changed enderdragon and blue wither texture path, and break half of CEM and "half of the game" when using CEM

### ISSUE THREAD

**Issue by TBlazeWarriorT** [sp614x/optifine#5666] opened 2021-05-24 03:12 UTC
## Description of Issue
G8 broke/changed CEM enderdragon file path. Can be seen using the Zinkenite Mobs resource pack (dragon will be glitched in G8 but not in G7).

OptiFine G7 enderdragon texture path with CEM: \minecraft\textures\entity\enderdragon\dragon.png 
OptiFine G8 path: minecraft\optifine\cem\dragon.png

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?
Try to make a custom model with a custom texture for the ender dragon in optifine G8 or use Zinkenite Mobs resource pack. The Ender Dragon will be white and flickering, with a missing texture, all black, or half invisible, depending on if you're using shaders.

## OptiFine Version
Only happens in 1.16.5 G8

## Installation Method
Standalone

## Fabric/Forge Version
Not using

## Other Installed Mods
None

## Log Files/Crash Reports
[enderdragon_log.txt](https://github.com/sp614x/optifine/files/6529550/enderdragon_log.txt)

## F3 Debug Screenshot
Dragon will look like this if you use the G7 path instead of the new path...?
![image](https://user-images.githubusercontent.com/25572454/119290658-5e7c1700-bc23-11eb-950a-47878bc3828b.png)

## Additional Information
At first I thought it was just fully broken, but looking at latest.log told me how to bandaid the (?)bug

**Comment by TBlazeWarriorT** [comment] 2021-05-24 20:16
Seems like G8 also broke blue-wither-phase textures. I'm done, going back to G7.

**Comment by TBlazeWarriorT** [comment] 2021-05-24 20:36
Also found out that using a CEM skeleton (like Zinkenite's) works perfectly fine, but breaks Skeleton Skulls in G8.
After that, I've concluded that G8 not only broke half of CEM, but also breaks half of the game when CEM is being used.

I've uninstalled G8 after this, totally unusable, honestly. Has added more negative "features" (since every bug seems to be a feature that comes to stay) than positive ones.

**Comment by TBlazeWarriorT** [comment] 2021-06-03 04:57
Fixed the title, was a bit tilted when I wrote it and the last comment, sorry. Title is clearer now

**Comment by ewanhowell5195** [comment] 2021-07-28 16:15
this is not a bug, and is actually a bug **fix**

this is caused by models having textures in them, but the textures not being found in the CEM folder. This didnt occur in previous versions, as these entities had a bug were they werent able to load textures from the CEM folder.

To fix your models, you need to remove the texture line from the model, or move the texture into the CEM folder.

**Comment by TBlazeWarriorT** [comment] 2021-07-28 16:32
> 
> 
> this is not a bug, and is actually a bug **fix**
> 
> this is caused by models having textures in them, but the textures not being found in the CEM folder. This didnt occur in previous versions, as these entities had a bug were they werent able to load textures from the CEM folder.
> 
> To fix your models, you need to remove the texture line from the model, or move the texture into the CEM folder.

alright, interesting to know. It wasn't explicit on the changelog so I couldn't know to begin with, and breaking previous packs is kind of a supicious decision. If it's in theory correct now, then it is. I'll just stick to G7 because it's less effort, G8 was too complicated of a release.

**Comment by ZenithRogue** [comment] 2022-03-22 18:29
as noted by @ewanhowell5195, this is actually a fix, closing issue for cleanup

**Closed by ZenithRogue** 2022-03-22 18:29 UTC
Labels: CEM, 1.16
