### ISSUE TITLE
[Bug] Glowing effect does not work

### ISSUE THREAD

**Issue by limitedDev** [sp614x/optifine#3755] opened 2020-04-18 09:44 UTC
## Description of Issue
The glowing effect does not work. It appears in the Effects list, but dosn't add the accual effect

## Steps to Reproduce
1. Apply the effect to a player or mob
2. Watch

## OptiFine Version
preview_OptiFine_1.15.2_HD_U_G1_pre13

## Installation Method
I used the installer, which is provided by OptiFine (doubbleclicked the .jar)

## Log Files/Crash Reports
No relevant Log files (client does not crash)

## F3 Debug Screenshot
screenshot:
![f3 screenshot](https://user-images.githubusercontent.com/63902031/79634246-8d46d480-8169-11ea-8659-fa0b6d2f2b77.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? No it does not.

## Additional Information
![Annotation 2020-04-18 113119](https://user-images.githubusercontent.com/63902031/79634287-d9921480-8169-11ea-8390-080be5ab8d1e.png)
![2020-04-18_11 09 18](https://user-images.githubusercontent.com/63902031/79634288-da2aab00-8169-11ea-9df9-ad859452106e.png)
![2020-04-18_11 09 16](https://user-images.githubusercontent.com/63902031/79634289-db5bd800-8169-11ea-950f-c209e1b94eac.png)

**Comment by KawaiiZapic** [comment] 2020-04-18 10:20
I have this problem too.
It causes by Performance->Fast Render,just turn off it.

**Comment by Regnander** [comment] 2020-04-18 12:39
Related #3662

**Comment by sp614x** [comment] 2020-05-29 10:58
Duplicate of #3662.

**Closed by sp614x** 2020-05-29 10:58 UTC
Labels: 1.15, glowing
