### ISSUE TITLE
ExtraPlanets haven't support

### ISSUE THREAD

**Issue by KrauzeBartek** [sp614x/optifine#1362] opened 2018-04-22 07:55 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.174.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.7-1.12.2-anarchy.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 4/22/18 9:53 AM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 53
	at CustomColors.getWorldSkyColor(CustomColors.java:1526)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:2278)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1639)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at CustomColors.getWorldSkyColor(CustomColors.java:1526)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:2278)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1639)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['Bartek'/1751, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [GCEntityClientPlayerMP['Bartek'/1751, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2737)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 963632384 bytes (918 MB) / 1445462016 bytes (1378 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 17, allocated: 1, tallocated: 10
	FML: MCP 9.42 Powered by Forge 14.23.3.2670 Optifine OptiFine_1.12.2_HD_U_D1 21 mods loaded, 21 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version                  | Source                                    | Signature                                |
	|:--------- |:------------------- |:------------------------ |:----------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2                   | minecraft.jar                             | None                                     |
	| UCHIJAAAA | mcp                 | 9.42                     | minecraft.jar                             | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99                | forge-1.12.2-14.23.3.2670.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.3.2670             | forge-1.12.2-14.23.3.2670.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | micdoodlecore       |                          | minecraft.jar                             | None                                     |
	| UCHIJAAAA | foamfixcore         | 7.7.4                    | minecraft.jar                             | None                                     |
	| UCHIJAAAA | custommainmenu      | 2.0.8                    | CustomMainMenu-MC1.12.2-2.0.8.jar         | None                                     |
	| UCHIJAAAA | galacticraftcore    | 4.0.1.174                | GalacticraftCore-1.12.2-4.0.1.174.jar     | None                                     |
	| UCHIJAAAA | galacticraftplanets | 4.0.1.174                | Galacticraft-Planets-1.12.2-4.0.1.174.jar | None                                     |
	| UCHIJAAAA | mjrlegendslib       | 1.12.2-1.1.3             | MJRLegendsLib-1.12.2-1.1.3.jar            | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJAAAA | extraplanets        | 1.12.2-0.3.3             | ExtraPlanets-1.12.2-0.3.3.jar             | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJAAAA | foamfix             | 0.9.7-1.12.2             | foamfix-0.9.7-1.12.2-anarchy.jar          | None                                     |
	| UCHIJAAAA | waila               | 1.8.24                   | Hwyla-1.8.24-B39_1.12.jar                 | None                                     |
	| UCHIJAAAA | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                  | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | jei                 | 4.9.0.163                | jei_1.12.2-4.9.0.163.jar                  | None                                     |
	| UCHIJAAAA | journeymap          | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar               | None                                     |
	| UCHIJAAAA | metalchests         | v1.2.2.g3d3d54b          | MetalChests-v1.2.2.g3d3d54b.jar           | None                                     |
	| UCHIJAAAA | resourceloader      | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar         | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJAAAA | treechopper         | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar              | None                                     |
	| UCHIJAAAA | wailaharvestability | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar     | None                                     |
	| UCHIJAAAA | wearablebackpacks   | 3.1.2                    | WearableBackpacks-1.12.2-3.1.2.jar        | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.174.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.7-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GTX 960M/PCIe/SSE2'
	Launched Version: forge-14.23.3.2670
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960M/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_D1
	OptiFine Build: 20180323-135452
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 391.35
	OpenGlRenderer: GeForce GTX 960M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by sp614x** [comment] 2018-04-23 09:35
Duplicate of #1093 and #603.
This is a known limitation of Forge when extending enums: MinecraftForge/MinecraftForge#2787
The enum should be extended as early as possible, for example in a static block in the main mod file.
It should be fixed in the mod which adds new dimensions.

**Closed by sp614x** 2018-04-23 09:35 UTC
