### ISSUE TITLE
Mipmap selector

### ISSUE THREAD

**Issue by Studio528-real** [sp614x/optifine#2836] opened 2019-08-31 14:15 UTC
Any time i click the mipmap thing to change it without sliding it (or even sliding it) almost instantly reloads textures and if you have a big pack on that can take a little while. sometimes i even try to slide it and it just insta reloads without even actually sliding the bar.

**Comment by sp614x** [comment] 2019-08-31 16:49
Duplicate of #2626.

**Closed by sp614x** 2019-08-31 16:49 UTC
