### ISSUE TITLE
[Feature Request] Add option to specify Minecraft Client Jar Path in OptiFine Installer

### ISSUE THREAD

**Issue by Lolothepro** [sp614x/optifine#7823] opened 2024-12-05 12:06 UTC
## Description of the new feature

(something like `java -jar ./OptiFineInstaller.jar --minecraftpath=`)

**Comment by ZenithRogue** [comment] 2024-12-05 20:54
duplicate of #5323

**Closed by ZenithRogue** 2024-12-05 20:54 UTC
