### ISSUE TITLE
Different frame count of albedo and normals animation lead to crash

### ISSUE THREAD

**Issue by YourMotherr** [sp614x/optifine#6029] opened 2021-07-14 17:30 UTC
## Description of Issue
So i'm using BSL shaders with faith forge and it keeps crashing for no reason, no framerate drops or anything its probably a bug for 1.17

## Steps to Reproduce
1. Use BSL shaders
2. Run it with faith forge on 1,17

## OptiFine Version
preview_OptiFine_1.17_HD_U_G9_pre25

## Installation Method
I dropped it into the mods folder but i tried standalone optifine and it crashed too

## Fabric/Forge Version
fabric-loader-0.11.6-1.17

## OptiFabric Version
optifabric-1.11.9

## Other Installed Mods
has nothing to do with it

## Log Files/Crash Reports
https://pastebin.com/2BZFthen

## F3 Debug Screenshot
game crashed i can't take one

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine? no, shaders need optifine

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? Yes
- Does this happen in OptiFine standalone? Yes
- Does this happen in Vanilla without OptiFine? no
- Have you tried using a binary search to find which mods cause this issue? its optifine 100%

## Additional Information
it crashed randomly even though there is no framedrops or any kind of lag its just a random crash

**Comment by Ari-RERA-43** [comment] 2021-07-14 18:28
That log appears to be from Fabric

**Comment by Ari-RERA-43** [comment] 2021-07-14 18:29
Does this happen on pre28?

**Comment by YourMotherr** [comment] 2021-07-15 08:43
> Does this happen on pre28?

isn't that for 1.17.1?

**Comment by fayer3** [comment] 2021-07-15 11:59
are you using any resourcepack? and does it still crash without one?

**Comment by YourMotherr** [comment] 2021-07-15 14:50
> are you using any resourcepack? and does it still crash without one?

the crash only happens when i combine BSL shaderpack with faithforge resourcepack
i cant use the resourcepack without the shader pack so no
i can use the shaderpack without the resourcepack but it looks worse without it

**Comment by fayer3** [comment] 2021-07-16 00:41
tested some with faithforge
do you have a stonecutter near you? for me the stonecutter causes this crash

**Comment by YourMotherr** [comment] 2021-07-16 02:40
> tested some with faithforge
> do you have a stonecutter near you? for me the stonecutter causes this crash

no i haven’t gone near one, i’ve just been near diamond block, emerald block, iron block, gold block, black glass, and sea lantern just to test the reflection and it crashes

**Comment by fayer3** [comment] 2021-07-16 12:09
do you have smart animations enabled or disabled?
I had it enabled, which caused it to crash only if the stone cutter was in view distance, but when I disabled it it crashed immediately. somethings wrong with the rendering of that model.
to temporarily fix this you can either enable smart animations and not go near stone cutter, or disable 'Video Settings->Animations->Terrain Animated' which disables the animations

**Comment by fayer3** [comment] 2021-07-16 12:15
I think I found the cause of this, the stonecutter_saw.png albedo has a 3 frame animation, but the stonecutter_saw_n.png has only a 2 frame animation. somehow the game thinks there are also 3 frames for the normals, and when trying to access it it crashes.

**Comment by YourMotherr** [comment] 2021-07-16 13:07
> I think I found the cause of this, the stonecutter_saw.png albedo has a 3 frame animation, but the stonecutter_saw_n.png has only a 2 frame animation. somehow the game thinks there are also 3 frames for the normals, and when trying to access it it crashes.
> edit: adding a 3rd frame to the normals fixes this issue, so somethings wrong with the readout of how many frames there are.

works perfectly now thank you

**Comment by fayer3** [comment] 2021-07-16 18:49
you should keep this open, since this sis an issue with optifine, that should be fixed

**Comment by moew123-dev** [comment] 2021-07-17 14:21
im on a mac and have the same problem on any server.

**Comment by fayer3** [comment] 2021-07-17 16:09
> 
> 
> I'm on a mac and have the same problem on any server. But no mods just a crash

if you use shaders then that's a different crash.
@YourMotherr it would be best to rename the issue to `Different frame count of albedo and normals animation lead to crash`

**Comment by YourMotherr** [comment] 2021-07-17 17:18
> I think I found the cause of this, the stonecutter_saw.png albedo has a 3 frame animation, but the stonecutter_saw_n.png has only a 2 frame animation. somehow the game thinks there are also 3 frames for the normals, and when trying to access it it crashes.
> edit: adding a 3rd frame to the normals fixes this issue, so somethings wrong with the readout of how many frames there are.

how can i add a 3rd frame?

**Comment by fayer3** [comment] 2021-07-17 18:47
- open the `stonecutter_saw_n.png` with any image editing software
- change the size to 64x192
- copy the lower half of the image to the new space.
or replace it with this file I already made: 
![stonecutter_saw_n](https://user-images.githubusercontent.com/8282299/126046815-74958b4b-6f41-4c53-aaaa-ad26c76a72a8.png)

**Comment by YourMotherr** [comment] 2021-07-17 21:58
> * open the `stonecutter_saw_n.png` with any image editing software
> * change the size to 64x192
> * copy the lower half of the image to the new space.
>   or replace it with this file I already made(probably needs to be renamed, since github removes the name):
>   ![stonecutter_saw_n](https://user-images.githubusercontent.com/8282299/126046815-74958b4b-6f41-4c53-aaaa-ad26c76a72a8.png)

i replaced the file after renaming it stonecutter_saw and it crashed

**Comment by fayer3** [comment] 2021-07-17 22:09
extract the resourcepack to a folder and replace it there. use that as your resourcepack and not the original zip

**Comment by Whitelisted1** [comment] 2021-07-17 22:52
If you are fine with the animation not being there, you can try turning off "Textures animated" or other animations if that doesn't work

hope this helps

**Comment by YourMotherr** [comment] 2021-07-18 13:58
> extract the resourcepack to a folder and replace it there. use that as your resourcepack and not the original zip

got it

**Comment by YourMotherr** [comment] 2021-09-25 21:02
@fayer3 found some bugs, can you help me?

**Comment by sp614x** [comment] 2021-09-29 13:51
Fixed, coming in next review

**Closed by sp614x** 2021-09-29 13:51 UTC
Labels: bug, shaders, 1.17
