### ISSUE TITLE
Nothing generates exept entities

### ISSUE THREAD

**Issue by Kawu030** [sp614x/optifine#3621] opened 2020-03-30 10:13 UTC
Sometimes when i m starting my world or when i use the nether portal nothing loaded exept entities. Reloging and quittng the game doesnt work. The minecraft version is 1.15.2 and the optifine version 1.15.2 HD U G1 pre10. I tryed using fabric(1.15.2),  optifine alone, Optifabric and older 1.15.2 optifine versions. This only happens using any kind of optifine and with fabric alone or without mods it works. Im not using any other mod or shader/ressource pack combined with optifine and my computer should be good enough for minecraft.
Thank you for your help!!

![2020-03-30_12 01 22](https://user-images.githubusercontent.com/62856540/77901362-c46b4980-727f-11ea-8e5d-608cd578faa9.png)

**Comment by RandomGuyJCI** [comment] 2020-03-30 14:02
This is probably a duplicate of #3612

**Comment by nyaNezt** [comment] 2020-03-30 17:03
What a sigh of relief! Im not the only one getting this problem. I was like 99% sure its just my slow laptop, but it might not be the case! Also i forgot that shift+f3 or alt+f3 exists, i will do that next time when uploading f3 screenshots. Thanks for mentionintg it, i check my issue from time to time and it showed that you mentioned it here.

**Comment by sp614x** [comment] 2020-05-29 10:33
Should be working with latest preview.

**Closed by sp614x** 2020-05-29 10:33 UTC
Labels: 1.15, chunks
