### ISSUE TITLE
[Shader] Too shiny enchanted items

### ISSUE THREAD

**Issue by JosFlix7** [sp614x/optifine#3722] opened 2020-04-10 01:36 UTC
## Description of Issue
When you open a world the effect of the enchanted item is not shown, but when opening the inventory it becomes too bright. To remove the luminescence effect you must restart the game. I tried different textures and the same thing happens. It only happens with shaders.

Here a demo video: https://drive.google.com/open?id=10uKEzI4suhzeolebV-z0uQomb7U2io-K
Texture used in the video: Paper Cut Out
Shaders used: SEUS Renewed v1.0.1

F3 Debug whit my hardware info:
![2020-04-09_20 42 08](https://user-images.githubusercontent.com/51174949/78954773-bea50d80-7aa2-11ea-8414-8638f4fe716a.png)

## Steps to Reproduce
1. Open a World
2. Open your inventory

## OptiFine Version
1.15.2-OptiFine_HD_U_G1_pre13

## Installation Method
Standalone

**Comment by NiemandTV** [comment] 2020-04-10 08:39
SEUS Renewed never fully supported the enchantment overlay. Afaik it works on held items and that's it; it doesn't even move.

In shaders that do support it, the effect is broken because blending isn't implemented yet/doesn't work yet, which is known.

**Comment by vgilabert** [comment] 2020-04-25 13:52
Hi, is there any way to fix the glare effect due to this shine ? Because in dark area it become hard to see...

**Comment by naeqirelle2020** [comment] 2020-06-05 06:45
I can't reproduce this, most likely fixed in latest preview (pre-19)

**Comment by sp614x** [comment] 2020-06-06 18:40
Should be fixed in latest preview.

**Closed by sp614x** 2020-06-06 18:40 UTC
Labels: 1.15, shaders
