### ISSUE TITLE
[1.16.5] OptiFine causes input lag

### ISSUE THREAD

**Issue by luckeYpublic** [sp614x/optifine#5479] opened 2021-03-23 16:54 UTC
Hi!

So I recently built a new PC, and I realized that my Minecraft has some input lag if I am using the Optifine profile. Basically if I open a chest, or place a block, or get hurt from fall damage I can see it has some delay on it. I've been playing with Optifine for years now, but didn't experience something like this before, and in Vanilla there is no input lag. It also happens when I use OptiFabric. Can somebody help me? I'll link a video, so you can see for yourself.

Thanks!
Miklós

https://drive.google.com/file/d/1aMFtygdb37h4iKAXFdAsf98mexLLaP63/view?usp=sharing

OptiFine Version
OptiFine 1.16.5_HD_U_G7

Installation Method
I tried it with the jar installer, and tried with OptiFabric too. 

Fabric/Forge Version
fabric-installer-0.7.2

OptiFabric Version
optifabric-1.9.6

F3 Debug Screenshot
https://drive.google.com/file/d/1sFMdTlBz1R6GzJQ7pAZAjPaavJWKdNfe/view?usp=sharing

- This happens in OptiFine standalone.
- This happens in OptiFabric.
- This not happens in Vanilla without OptiFine.

**Comment by KaiAF** [comment] 2021-03-23 18:16
Try lowering your settings i.e render distance. I think this could be caused by the tick rate, not sure.

**Comment by Truhard** [comment] 2021-03-23 18:40
Pretty sure this was fixed in preview

>  - fixed input lag with lazy chunk loading (#5348)

**Comment by luckeYpublic** [comment] 2021-03-23 19:04
> Try lowering your settings i.e render distance. I think this could be caused by the tick rate, not sure.

Thank you for helping! Well I lowered my render distance, and it's starts the lag around 12 chunks. It's very strange, because I have a stronger computer now then before, and I usually played with 20-24 chunks, and never experienced this.

**Comment by Kirian-Kun** [comment] 2021-03-23 19:06
did u try turning off lazy chunk loading? i had some kind of delay too and disabling that helped me

**Comment by KaiAF** [comment] 2021-03-23 19:15
Yeah, try turning off lazy chunk loading to see if that helps.

**Comment by luckeYpublic** [comment] 2021-03-23 19:23
> did u try turning off lazy chunk loading? i had some kind of delay too and disabling that helped me
> Yeah, try turning off lazy chunk loading to see if that helps.

Wow! Thank you guys very much for helping, it looks like that it solved the problem!

**Closed** 2021-03-23 19:33 UTC
Labels: 1.16

**Comment by Truhard** [comment] 2021-03-25 23:41
Lol, I made a comment about the lazy chunk loading days ago on this thread but deleted it thinking it was unrelated. Glad you got it sorted out though :)
