### ISSUE TITLE
[Crash] Minidumps are not enabled by default on client versions of Windows

### ISSUE THREAD

**Issue by TI1TED** [sp614x/optifine#4024] opened 2020-06-03 10:21 UTC
## Description of Issue
I understand this is likely more an issue with Java, however after reinstalling Java JRE's and JDK's countless times (drivers, Minecraft, and OptiFine too) I am still having this issue months on.
OptiFine works fine on Singleplayer, however when attempting to connect to a multiplayer server, what I noticed is that with a lot of players on (I tried Cubecraft, Hypixel, the typical minigame servers with lobbys) and sometimes even small servers with my friends, the game will crash either instantly or with less players, usually after a few minutes.

## Steps to Reproduce
1. Launched OptiFine, went to Cubecraft
2. and then it crashed.

## OptiFine Version
1.15.2-OptiFine_HD_U_G1_pre18
However it happens on every single **standalone** OptiFine install. Through other clients such as Badlion, OptiFine works fine.
 
## Installation Method
Standalone, however the issue also occurs with the mod version for both Forge and Fabric.

## Fabric/Forge Version
fabric-loader-0.8.2+build.194-1.15.2

## OptiFabric Version
optifabric-1.0.0-beta8

## Other Installed Mods
https://pastebin.com/srBGi305

## Log Files/Crash Reports
https://pastebin.com/66q8YWvf - Crash Report
https://pastebin.com/APx9SSSG - Minecraft latest.log

## F3 Debug Screenshot
https://imgur.com/a/hISc04a

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No. This does not occur in Vanilla or without OptiFine

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge - Yes
   - Only OptiFine, OptiFabric, and Fabric - Yes
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself. - No
- Does this happen in OptiFine standalone? - Yes
- Does this happen in Vanilla without OptiFine? - Yes
- Have you tried using a binary search to find which mods cause this issue? - Yes, OptiFine lol.
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing. - Tested, it's 100% OptiFine.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine - Nope.

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

Please help. It's been months like this.

**Comment by sp614x** [comment] 2020-06-04 08:50
Crash details:
```
# Problematic frame:
# C  [SHELL32.dll+0x580b]
...
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  java.net.SocketOutputStream.socketWrite0(Ljava/io/FileDescriptor;[BII)V+0
j  java.net.SocketOutputStream.socketWrite([BII)V+44
j  java.net.SocketOutputStream.write([BII)V+4
```

This is a native crash in the JVM/OS network stack and can't be fixed by OptiFine.
It could be caused by external tools (antivirus, network tools, etc.) that try to monitor the network traffic.
Changing the Java version may help.

**Closed by sp614x** 2020-06-04 08:50 UTC
Labels: 1.15, crash
