### ISSUE TITLE
Optifine dont use my dedicated gpu (RTX 3050)

### ISSUE THREAD

**Issue by lionipslp** [sp614x/optifine#7642] opened 2024-03-20 22:14 UTC
When I open minecraft from the launcher without using optifine, the game uses my gpu, but when i open it using optifine (with the same launcher) it runs with my integrated CPU graphics. so optifine is running my game at 40 FPS. without it, the game runs at 200FPS but i cant apply shadders.

Optifine Version 1.20.4 HD_U_17 pre5

I tried giving priority, assigning java to use the GPU and assigning the version of optifine (from the folder versions of .minecraft) to priority. but dont work.

**Comment by sp614x** [comment] 2024-03-20 22:23
Duplicate of #6941

**Closed by sp614x** 2024-03-20 22:23 UTC
