### ISSUE TITLE
[Enhancement] Fix vanilla ambient occlusion

### ISSUE THREAD

**Issue by yezhiyi9670** [sp614x/optifine#4125] opened 2020-06-20 03:05 UTC
In vanilla the ambient occlusion is wrong sometimes. This can be easily inspected while mining.

I hope Optifine can fix it. [MC-43968](https://bugs.mojang.com/browse/MC-43968) might help.

**Comment by asbyth** [comment] 2020-06-20 03:26
dupe of #1287

**Closed** 2020-06-20 20:40 UTC
Labels: 1.15, bug, duplicate, lighting
