### ISSUE TITLE
Crash With Galacticraft

### ISSUE THREAD

**Issue by kenijey** [sp614x/optifine#1419] opened 2018-05-22 15:27 UTC
1.12.2 HD U D3 works fine without crash, but if i try E1 pre (18.05.2018) it crashes at the main menu when the game opens directly.
[crash-2018-05-22_18.13.50-client.txt](https://github.com/sp614x/optifine/files/2027341/crash-2018-05-22_18.13.50-client.txt)
[crash-2018-05-22_18.13.45-client.txt](https://github.com/sp614x/optifine/files/2027342/crash-2018-05-22_18.13.45-client.txt)
Using Forge 2705

**Comment by SteveKunG** [comment] 2018-05-29 10:36
Same here, with Forge 2705

**Comment by kenijey** [comment] 2018-06-08 11:30
still happening, with Forge 2705 and latest optifine preview (06.06.2018)
[crash-2018-06-08_14.30.07-client.txt](https://github.com/sp614x/optifine/files/2084160/crash-2018-06-08_14.30.07-client.txt)

**Comment by sp614x** [comment] 2018-06-08 12:03
Some of the core mods is incorrectly patching one of the optifine modified classes:
```
Loaded coremods (and transformers): 
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.177.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.12_mc1.12.2.jar)
  ServerPropertiesLAN (ServerPropertiesLAN-2.65.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.3-universal.jar)
  VanillaFixLoadingPlugin (VanillaFix-1.0.8-88.jar)
  CreativePatchingLoader (CreativeCore_v1.9.22_mc1.12.2.jar)
  OpticPatchingLoader (OpticManager+v1.1.5+mc1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.13.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  MMFMLCorePlugin (MultiMine-1.12.2.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  IGCMPatchingLoader (IGCM_v1.2.0pre-4_mc1.12.2.jar)
  BCModPlugin (backpacks+1.12.2+-+3.5.2.jar)
```

**Comment by kenijey** [comment] 2018-06-08 12:05
@SteveKunG can you provide the crash report or tell the mods you've used please? i will count common ones then try which causes so it will be easier to do.

**Comment by SteveKunG** [comment] 2018-06-08 15:30
After update OptiFine to latest preview, Its no longer crash anymore.
![image](https://user-images.githubusercontent.com/6128413/41166854-7875a010-6b6b-11e8-8f3c-55293c8f0bf2.png)

**Comment by kenijey** [comment] 2018-06-08 18:16
you have optifine D3 and E1 together? and why don't you update foamfix?

**Comment by SteveKunG** [comment] 2018-06-08 19:02
OK. Can confirm, it crash when in Main Menu.
https://pastebin.com/dma2ef52

My current mod pack.
![image](https://user-images.githubusercontent.com/6128413/41175816-8a6bca0c-6b88-11e8-9b44-d7e4d128bba2.png)

This is caused by Galacticraft. I will create issue at there.

**Comment by kenijey** [comment] 2018-06-08 19:30
great. now i will find which mod causes. i think it's galacticraft.

**Comment by kenijey** [comment] 2018-06-08 22:36
yeah, it's galacticraft. but i didn't update galacticraft, this crash started happening after updating optifine. whatever. problem is clear...
@micdoodle8

**Comment by kenijey** [comment] 2018-06-08 22:37
[crash-2018-06-09_01.36.27-client.txt](https://github.com/sp614x/optifine/files/2086370/crash-2018-06-09_01.36.27-client.txt)
here is a naked crash report only with optifine and galacticraft.

**Comment by sp614x** [comment] 2018-06-20 12:58
Looks like Galacticraft is patching RenderChunk.rebuildChunk() which OptiFine is also changing.
This can only be fixed in Galacticraft.

**Closed by sp614x** 2018-06-20 12:58 UTC
Labels: crash, forge, mods

**Comment by radfast** [comment] 2018-06-25 22:54
@sp614x  hi I'm Galacticraft co-developer.

It appears you have changed it again in latest E1 - at least I can't reproduce the reported issue.  In E1 as downloaded today, the local variable named `block` in `RenderChunk.rebuildChunk()` is still at local variable index 19.

> Looks like Galacticraft is patching RenderChunk.rebuildChunk() which OptiFine is also changing.

Yes we patch things, I don't think Optifine is the only mod to patch vanilla code.

It would help compatibility with other mods if you can start to **publish** your patches open source on Github, that way it's easier for us to see if you changed something in a patch.  The patches can be seen in your downloaded binaries of course, but it's way harder for other mod authors to see what is changing if the changes are not trackable.

**Comment by radfast** [comment] 2018-06-25 23:07
Fixed from Galacticraft build 181 - it was just a problem with our existing detection code not detecting Optifine as installed with release E1, because the test we run to detect Optifine got changed...

**Comment by sp614x** [comment] 2018-06-26 10:01
The Config class is intentionally letf unchanged so external mods can still detect if OptiFine is installed. 
The rest of the OptiFine classes have been reorganized in new packages.

**Comment by booty-bumping** [comment] 2019-02-16 03:45
@radfast BTW, this problem may have resurfaced somewhere between snapshot 181 and 190. [See the /r/FeedTheBeastCrashes thread](https://www.reddit.com/r/FeedTheBeastCrashes/comments/ar36k4/optifine_crashes_when_in_main_menu/)
