### ISSUE TITLE
Minecraft's window turns black after leaving fullscreen mode

### ISSUE THREAD

**Issue by kamild1996** [sp614x/optifine#428] opened 2017-01-22 09:08 UTC
At first I thought it's an issue with vanilla, but after checking mods one by one I figured it's an issue with OptiFine. Simply, after leaving fullscreen mode, the game's window turns black. Resizing the window in any way fixes that.
I know at least one other person who has the same issue. We both have a Radeon RX480, mentioning it since it may be related.

Screenshot: ![optifine black screen](https://cloud.githubusercontent.com/assets/5320414/22181316/66b8883c-e08a-11e6-985f-01dd3c16fbc6.jpg)

Log: [latest.txt](https://github.com/sp614x/optifine/files/721820/latest.txt)

EDIT: Also confirmed to not be an issue with Forge, the issue is happening when I install OptiFine with the installer (double-clicking the OptiFine jar file).

**Comment by HalfOfAKebab** [comment] 2017-01-22 10:56
Can confirm. Also running with an RX 480.

**Comment by sp614x** [comment] 2017-01-22 11:58
Are you using a custom Fullscreen Mode?
Video Settings -> Other -> Fullscreen Mode

**Comment by kamild1996** [comment] 2017-01-22 12:48
Nope. Changing it to a different resolution doesn't help either.
If this is something you cannot reproduce, I'll be happy to help with the testing.

**Comment by kamild1996** [comment] 2017-01-25 18:22
If this helps to find a source of the problem, I'd like to mention that the problem doesn't appear anymore with the [Fullscreen Windowed](https://mods.curse.com/mc-mods/minecraft/227441-fullscreen-windowed-borderless-for-minecraft) mod installed.

**Comment by sp614x** [comment] 2017-01-26 09:43
The Fullscreen Windowed mode is not fullscreen for the graphics card. It uses a maximized window without borders. Therefore the OS can easily switch to other windows without changing the graphics mode.

**Comment by Tsoccerguy3** [comment] 2017-03-09 01:57
This is a old bug , its not a big deal to drag the right window frame a few pixels , until the window contents appear , but I can see that its a problem for new players I have helped . A new player will try Optifine for first time and see the black screen , then out of frustration will determine it doesn't work , then remove Optifine forever . I have helped hundreds of players on my server over the years with this same bug , that's right the bug has been there for years. It my be a line of code in Optifine that effects AMD only . I also tested a laptop with nvidia graphics and the bug is not there .

Steps to recreate

This happens on windows 10 any monitor display resolution .
A clean installation of minecraft .
Install Optifine to Minecraft with installer
Run Optifine Profile
Open any map , new or old with Optifine default settings
F11 into full screen and F11 into windowed mode to get the black window , repeat F11 untill your satisfied the bug is there

The only exception to the bug here is in 1.7.10 where F11 into full screen will not scale the window to use the whole monitor. The window frame will simply anchor itself to the top left corner and the rest of monitor is black. This i tested on Linux mint 18.1 with nvidia proprietary drivers.

The simplest of solutions , is to use the minecraft vanilla code to handle window scaling and resizing , It works for AMD , Intel and nVidia . The Fullscreen-Windowed-Minecraft mod , doesn't fix the problem either . There is the Optifine bug in their GIT issues as well , get Optifine author to fix. 

Conclusion 👍 
This seems to be an issue that effects AMD cards and possibly Intel graphics

**Comment by Tsoccerguy3** [comment] 2017-04-03 02:35
I found that this bug does not happen with OptiFine_1.7.10_HD_U_D7 . This may be a clue to fixing this bug in other versions . The other point is it is only present using AMD Hardware.

**Comment by Tsoccerguy3** [comment] 2017-04-08 03:54
preview_OptiFine_1.11.2_HD_U_B8_pre.jar dated April 7 is flashing between these 2 windows very quickly 
![1capture](https://cloud.githubusercontent.com/assets/22108822/24825473/16d48b92-1bed-11e7-976d-94e909fee584.PNG)
![capture](https://cloud.githubusercontent.com/assets/22108822/24825475/1aeb6d90-1bed-11e7-857f-14b662cee0d5.PNG)

**Comment by sp614x** [comment] 2017-04-25 12:52
@Tsoccerguy3 Thanks for the info.
Are all OptiFine versions after 1.7.10 affected?
Is OptiFine D7 for 1.7.10 working correctly?
Any effect if VSync is enabled/disabled?

**Comment by Tsoccerguy3** [comment] 2017-05-04 03:51
Yes OptiFine_1.7.10_HD_U_D7 works flawlessly , The bug is fixed in OptiFine_1.11.2_HD_U_B8 May 3,17
with AMD R9 280x Driver version non-whql-win10-64bit-radeon-software-crimson-relive-17.4.4-apr26

**Comment by sp614x** [comment] 2017-05-04 22:07
Can the issue be closed now or are there other MC version for which there is no bugfix?

**Comment by Tsoccerguy3** [comment] 2017-05-19 13:12
All is working correctly On Windows 10 1703 - Creators update , in All Optifine versions HD_U_B8 and higher , using latest AMD video drivers

**Closed** 2017-05-19 14:46 UTC

**Comment by ChrisAmm** [comment] 2017-06-11 21:41
Had similar issue on Intel HD3000. After Windows update installed KB4013418 (for 1607), Optifine  would produce the error above: Black out on full screen and very extremely slow (non-functional) on windowed display. Uninstalling KB4013418 fixed both issues. However, Win 10 Update 1703 caused Optifine to reproduce the error. Uninstalled/Reinstalled Optifine (B9) with no success. 
On a separate machine (Alienware 15 R2), after creator update 1703, Optifine functional but does not result in increased fps on intel HD620, and rather significant decreases in fps noted when running on built-in NVIDIA 970M
