### ISSUE TITLE
optifine crash 1.13.2

### ISSUE THREAD

**Issue by Elaidet** [sp614x/optifine#2094] opened 2018-12-09 03:57 UTC
oigan pe mi maicra dejo de funcionar la verdad no se porque pero aqui les dejo lo que aparece
[21:57:20] [main/INFO]: Loading tweak class name net.minecraft.launchwrapper.VanillaTweaker
[21:57:20] [main/INFO]: Using primary tweak class name net.minecraft.launchwrapper.VanillaTweaker
[21:57:20] [main/INFO]: Calling tweak class net.minecraft.launchwrapper.VanillaTweaker
Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
	at net.minecraft.launchwrapper.VanillaTweaker.injectIntoClassLoader(VanillaTweaker.java:16)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by Elaidet** [comment] 2018-12-09 04:08
resuelvan mi duda pe

**Comment by ozals** [comment] 2018-12-09 04:10
puedes mandar un photo de tu menu f3?

**Comment by sp614x** [comment] 2018-12-10 16:12
This is typically caused by custom launchers and can't be fixed by OptiFine: #1956, #1951, #1825, #1804, ...

**Closed by sp614x** 2018-12-10 16:12 UTC
