### ISSUE TITLE
[GUI] Random Panorama doesn't work

### ISSUE THREAD

**Issue by richardatsley** [sp614x/optifine#7533] opened 2023-08-22 21:20 UTC
## Description of Issue
The documentation describes a method for creating randomized panoramas that don't seem to function properly, when making new panoramas and placing them in the appropriate folders (optifine/gui/background(n)) no changes occur.

## Steps to Reproduce
Create custom panoramas

place "panorama" 1-6 in the designated folders described by the documentation

:(!

## OptiFine Version
OptiFine HD U I5

## Installation Method
Jar installation

## F3 Debug Screenshot

![2023-08-22_17 16 46](https://github.com/sp614x/optifine/assets/110047599/d08db17c-f5d6-4920-9ee3-e2b436d15e17)

Either this or the ability to use the "anim" function with panoramas would be really nice, thank you for your time :)!

It's also entirely possible this _does_ work but the documentation doesn't actually go in-depth into the "background.properties" file to make such an item function

**Comment by ewanhowell5195** [comment] 2023-10-06 14:20
duplicate of #2052

**Comment by Jiingy** [comment] 2023-10-06 16:59
Closing as duplicate

**Closed by Jiingy** 2023-10-06 16:59 UTC
