### ISSUE TITLE
World not Rendering

### ISSUE THREAD

**Issue by BenAgain452** [sp614x/optifine#3881] opened 2020-05-06 16:22 UTC
## Description of Issue
Every pre-version of 1.15 has done this for me so far, none of the chunks load in any world made before 1.15. This happens whether I update the map to 1.15 in Optifine or vanilla MC. Newly created worlds can render many chunks, but is very slow at loading new ones, and seems to hit a wall where it cant do it anymore about 300-500 blocks from spawn. I do not have other mods installed. Attempting to move through where blocks would be results in getting caught and jiggling just like if a single chunk failed to render. [Someone on Reddit](https://www.reddit.com/r/Minecraft/comments/frdnqo/1152_with_optifine_upon_loading_my_world/) appears to have the same issue. I tried teleporting like they did, and it did successfully render the one chunk I arrived in. Changing any graphics settings does nothing. Sometimes, I can still see a few item frames.

## OptiFine Version
1.15.2 HD U G1 pre16, and all previous 1.15 pre's
 -EDIT: Tested pre17, still behaving the same.

## Installation Method
Installer

## Other Installed Mods
None. I do have Vivecraft as a separate installation.

## Log Files/Crash Reports
[latest.log](https://github.com/sp614x/optifine/files/4587809/latest.log)

## F3 Debug Screenshot
![2020-05-06_11 54 04](https://user-images.githubusercontent.com/64915095/81199487-b69c9880-8f90-11ea-8192-1db12f108093.png)
![2020-05-06_11 54 51](https://user-images.githubusercontent.com/64915095/81199491-b7352f00-8f90-11ea-8e5b-34a49a379c5b.png)
![2020-05-06_11 55 15](https://user-images.githubusercontent.com/64915095/81199490-b69c9880-8f90-11ea-8b86-6108c0337574.png)

**Comment by realjackasterisk** [comment] 2020-05-22 08:17
Duplicate of #3365

**Closed by realjackasterisk** 2020-05-22 08:17 UTC
Labels: chunks, forge
