### ISSUE TITLE
Your graphics driver doesn't support framebuffer objects

### ISSUE THREAD

**Issue by ItsmeFawaz** [sp614x/optifine#2658] opened 2019-07-22 11:20 UTC
My pc is really old and normal minecraft doesn't work on it as it instantly crashes when the minecraft instance opens. It worked when I used optifine but since the 1.14.3 F1 pre 15 update it doesn't work anymore and shows this crash report. 

and FastRender is enabled in optionsof.txt in my .minecraft folder 
https://pastebin.com/3TSw6itP

**Comment by sp614x** [comment] 2019-07-24 10:28
What is the last working OptiFine version?

**Comment by sp614x** [comment] 2019-07-25 08:31
Duplicate of #2671.

**Closed by sp614x** 2019-07-25 08:31 UTC
Labels: crash, vanilla
