### ISSUE TITLE
1.16.4 [SHADERS] black clouds (With SEUS Renewed, Chocapic, Sildurs,..)

### ISSUE THREAD

**Issue by Kyle-Business** [sp614x/optifine#5203] opened 2021-01-10 09:20 UTC
## Description of Issue
Whenever i use shaders i get these black clouds in the sky. Doesn't matter which shaderpack i use, tried SEUS Renewed, Chocapic, Sildurs and a few others. All with the same result ; Black clouds. I use OF 1.16.4. 
![2021-01-09_16 58 28](https://user-images.githubusercontent.com/23700602/104119055-5df67a00-532d-11eb-9e0e-2f753b691b10.png)
![2021-01-09_16 31 14](https://user-images.githubusercontent.com/23700602/104119058-62bb2e00-532d-11eb-9352-de2222cd0957.png)

**Comment by PedroC1999** [comment] 2021-02-10 18:09
I am also experiencing this

**Comment by KaiAF** [comment] 2021-04-04 03:52
I am not able to reproduce this. This could be because you changed the settings in the specific shader? I don't know

**Comment by coleperrine** [comment] 2021-04-10 03:12
Having this issue as well. Definitely the shader but playing with settings hasn't lead me to what's causing it.

**Comment by KaiAF** [comment] 2021-05-31 01:52
Closing this issue as there hasn't been any response from the author of the issue.

**Closed by KaiAF** 2021-05-31 01:52 UTC
Labels: details needed, shaders
