### ISSUE TITLE
[Crash Report] Randomly Crashes the Game

### ISSUE THREAD

**Issue by ToxicBaum** [sp614x/optifine#6895] opened 2022-07-01 13:43 UTC
## Description of Issue
I cant give any detailed description here because it crashes Randomly

## Steps to Reproduce
just play the game

## OptiFine Version
OptiFine HD U H8 pre1

## Installation Method
Download the .jar, Run it, click install

## Log Files/Crash Reports
[crash-2022-07-01_15.36.45-client.txt](https://github.com/sp614x/optifine/files/9029265/crash-2022-07-01_15.36.45-client.txt)

## F3 Debug Screenshot
![2022-07-01_15 42 43](https://user-images.githubusercontent.com/69435611/176906541-882f8dc1-67b7-4f37-a7d3-b3b2f858f7ae.png)

## Prior Testing
doesnt happen in vanilla

**Comment by UnknownTheLad** [comment] 2022-07-01 13:48
Duplicate of #6858

**Comment by ToxicBaum** [comment] 2022-07-01 13:51
ok

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows

Von: ***@***.***>
Gesendet: Freitag, 1. Juli 2022 15:48
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [sp614x/optifine] [Crash Report] Randomly Crashes the Game (Issue #6895)


Duplicate of #6858<https://github.com/sp614x/optifine/issues/6858>

**Closed** 2022-07-01 18:50 UTC
