### ISSUE TITLE
[Category] Some Area not rendering

### ISSUE THREAD

**Issue by iHSeven** [sp614x/optifine#3852] opened 2020-05-03 20:27 UTC
## Description of Issue
When I leave the server and rejoin fast the area around me don't render
## Steps to Reproduce
1. What do you do... 
2. ...to find this bug?
just leave server and join rly fast
## OptiFine Version
Self-explanatory. 
1.15.2_HD_U_G1_pre15
## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?
by dropping optifine into mods folder
## Fabric/Forge Version
**If OptiFine is installed as standalone, you can remove this section.**
forge-1.15.2-31.1.63-launcher

## Other Installed Mods
*Every* single mod you have installed, besides OptiFine. Please don't leave anything out, even if you think it has nothing to do with the issue at hand. For long lists of mods, use Pastebin. 
-BetterSprinting-1.15.2-v3.1.0 , ClothConfig2-2.0, inventoryprofiles-forge-1.15.2-0.2.1, 
-journeymap-1.15.2-5.7.0beta1, LightOverlay-4.3, malilib-forge-1.15.2-0.10.0-dev.20+beta,
-minihud-forge-1.15.2-0.19.0-dev, ShulkerTooltip-1.9.3, SoundFilters-0.13_for_1.15.2
**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

https://pastebin.com/2RFHAXcK

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.
![2020-05-03_23 11 22](https://user-images.githubusercontent.com/64751493/80924779-9c499b80-8d93-11ea-82d0-e93dfc821682.png)
![2020-05-03_23 11 16](https://user-images.githubusercontent.com/64751493/80924782-a10e4f80-8d93-11ea-84e5-323e3769b2b8.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? No
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all? No
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?  No
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed? i think the mod causing this problem journeymap 
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by yezhiyi9670** [comment] 2020-05-04 02:41
It is Journeymap incompatibility. Duplicate of #3731.

**Comment by sp614x** [comment] 2020-06-09 08:08
Duplicate of #3731.

**Closed by sp614x** 2020-06-09 08:08 UTC
Labels: 1.15, chunks, forge, mods
