### ISSUE TITLE
[BUG] 1.16.4_HD_U_G5 + cofh core:  Display issues when breaking blocks

### ISSUE THREAD

**Issue by UnixRonin** [sp614x/optifine#5065] opened 2020-11-27 02:50 UTC
## Description of Issue
Reporting here JUST IN CASE it is CoFH Core exposing an Optifine issue, and not CoFH Core itself.

With Minecraft 1.16.4, Forge 1.16.4-35.1.0, CoFH Core 1.16.3-1.0.4, and ANY shader, including Optifine's own internal shader, when any block is broken using a tool, the block damage overlay covers the entire screen.  On some shaders (BSL_v7.2 for example) the damage overlay and the world are both invisible, and all that is visible while breaking a block is the skyblock.

A tool must be used, even only a wooden axe.  For some reason it does not occur when breaking a block with bare hands.

## Installation Method
JAR file in mods folder

## Fabric/Forge Version
forge-1.16.4-35.1.0

## Other Installed Mods
cofh_core-1.16.3-1.0.4.jar required to reproduce

## F3 Debug Screenshot
https://www.caerllewys.net/public/minecraft/2020-11-26_21.44.18.png

## Prior Testing
If you've installed using Forge/Fabric:
- Does this happen without other mods installed?

ONLY Forge + OptiFine + cofh_core + any shader, including internal, is required to reproduce the bug.

- Does this happen in Vanilla without OptiFine?
No.  The specified combination is both necessary and sufficient.  Without optifine, or without cofh_core, no bug.

**Comment by berkkrkc09** [comment] 2020-11-27 06:43
Yeah this happened to me too. What is broken i wonder? I hope one of them fixes the bug soon.

**Comment by DeVviL** [comment] 2020-12-11 13:24
The problem is known, the solution is #5023

**Comment by berkkrkc09** [comment] 2020-12-21 17:43
But isn't this a workaround and not a solution? This still needs fixing like in the line I paste down here. 

**This line is taken from cofh_core-client.toml:**
 #If TRUE, Area Effect Block breaking will be rendered. Disable if you are using buggy mods such as OptiFine which apparently with this. Please also report the issue to OptiFine.

**Comment by Mei-Len666** [comment] 2020-12-23 17:29
I'm having the same problem.

**Comment by sp614x** [comment] 2020-12-27 19:10
Duplicate of #4088

**Closed by sp614x** 2020-12-27 19:10 UTC
Labels: 1.16, mods, shaders
