### ISSUE TITLE
[Feature Request] Optifine api to disable some optifine mods in servers.

### ISSUE THREAD

**Issue by Nosenaar** [sp614x/optifine#5112] opened 2020-12-18 03:38 UTC
The idea is to have an api to disable some mods, that may seem cheating to some people in vanilla expierences. I saw the list of features, and I saw only three that are a real problem for people that want their server 100% vanilla. First, the dynamic lights, that could prevent people from using torches. Secondly, the zoom feature. This is pretty much a hotkey to the fov feature, and you can even combine it, having a non legal zoom, and having a hotkey for a zoom feature like that; makes that more people would use it in pvp, or running; because less people would do it the vanilla way, and go to fov and lower it. Giving the server the possibility of disabling the zoom feature, would solve the spyglass problem. For the future, I don't want my users having a free spyglass! Thirdly, the no fog feature. In servers that are tournaments of speedrunning, or UHC; the no fog feature is a really game changer, specially in the nether, where you can find fortress, a structure that is very rare in these 1.16 updates, easier. The no fog and zoom feature, actually ended up creatng a problem in the twitch rivals event, where some teams (knowing or not knowing) cheated with nofog and the zoom feature.

This api would be a plugin that makes the server able to disable all the mods that affect gameplay, but not performance. Badlion client has an api too, that lets you disable almost any of their mods to all the users of your server. It really helps out to things like minimap, or hotkey features; that could break or be used to cheat. The badlion api is a simple plugin with a simple config, and it just works perfectly.

**¿But why don't just kick the optifine users and make your users use other mod, like sodium that has those features?**
Simply because optifine is better, and people prefers it. In very large servers, this could get a lot of people out of optifine mod, and get into another alternatives, or get people out of the server. **Optifine and the servers loses without an api!**

**Comment by KaiAF** [comment] 2021-03-25 22:49
Duplicate of #5260

**Closed by KaiAF** 2021-03-25 22:49 UTC
