### ISSUE TITLE
Gui items not rendering

### ISSUE THREAD

**Issue by Yoinkium** [sp614x/optifine#4263] opened 2020-07-05 21:42 UTC
everything in the gui and items/blocks that is dropped does not render

## Steps to Reproduce
i log in to minecraft after downloading optifine start up a new/old world and it happens from the get go. (i do play on mac os though)
2. no clue sry

## OptiFine Version
both OptiFine 1.16.1 HD U G2 pre2 and OptiFine 1.16.1 HD U G2 pre1

## Installation Method
i droped the jar into the mods folder

## Fabric/Forge Version
**forge 1.16.1  32.0.47*

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
no it does not, only when i use shaders

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
yes
   - Only OptiFine and Forge
yes when shaders are enabled
   - Only OptiFine, OptiFabric, and Fabric
no
- Does this happen without any mods at all?
no
   - Only Forge/Fabric by itself.
no
- Does this happen in OptiFine standalone?
no
- Does this happen in Vanilla without OptiFine?
no
- Have you tried using a binary search to find which mods cause this issue?
no, no other mods
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
no
   - Does the issue still happen with only the remaining mods installed?
no
      - Forge/Fabric and remaining mods, without OptiFine
no

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by sp614x** [comment] 2020-07-09 13:38
Duplicate of #4277

**Closed by sp614x** 2020-07-09 13:38 UTC
