### ISSUE TITLE
Pistons Gliching when extending

### ISSUE THREAD

**Issue by AwsAlex** [sp614x/optifine#3906] opened 2020-05-09 18:11 UTC
Description of Issue
When i use pistons with optifine the pistons extend but flash and in a clock using pistons the extend multiple times for no reason.

## Steps to Reproduce
1. Open minecraft using optifine load a superflat world
2. make a piston clock with 1 redstone torch one redstone dust a block and a piston

## OptiFine Version
1. OptiFine 1.15.2 HD U G1 pre16. and below to 1.12.2 latest version i have not checked other versions

## Installation Method
i use multimc so i instaled fabric and optifabric and tried it out with the jar and i got the same glichy output

## Fabric/Forge Version
Fabric Version: 0.8.2+build.194

## OptiFabric Version
**optifabric verion 1.0.0-beta8

## Other Installed Mods
Fabric Api, Immersive Portals amd Optifabric

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by sp614x** [comment] 2020-05-12 11:41
Duplicate of #3041.

**Closed by sp614x** 2020-05-12 11:41 UTC
Labels: duplicate
