### ISSUE TITLE
Item/Block Lighting Issues

### ISSUE THREAD

**Issue by MeinKraft** [sp614x/optifine#3838] opened 2020-05-03 13:14 UTC
## Description of Issue
Some items/blocks in inventory/creative menus appear too dark

## OptiFine Version
preview_OptiFine_1.15.2_HD_U_G1_pre15

## Installation Method
drop the JAR file into your "mods" folder

## Fabric/Forge Version
Forge 31.1.63

## Other Installed Mods
jei-1.15.2-6.0.0.4

## F3 Debug Screenshot
[https://imgur.com/a/XAWFtI7](https://imgur.com/a/XAWFtI7)

## Prior Testing
Items in inventory still appear dark, creative, normal and inside JEI

**Comment by lesterlo** [comment] 2020-05-03 16:15
I have this problem too, most of the thing in the inventory is dark.

**Comment by MeinKraft** [comment] 2020-05-04 01:17
so the YAMDA thing appears not to be Optifine,  But the inventory items still appear dark when Optifine is installed

**Comment by sp614x** [comment] 2020-05-05 22:40
Duplicate of #3830.

**Closed by sp614x** 2020-05-05 22:40 UTC
Labels: 1.15, duplicate, forge
