### ISSUE TITLE
When screenshoting (F2) the result is always an empty picture

### ISSUE THREAD

**Issue by Hejkal147** [sp614x/optifine#6005] opened 2021-07-10 20:11 UTC
## Description of Issue
Whenever I screenshot with F2, the result is like the backround of .png file.

## Steps to Reproduce
Press F2

## OptiFine Version
pre26 1.17

## Installation Method
I went on the website, clicked on the latest 1.17 preview version (pre26)
and it redirected me to AdFoc.us website where it downloaded the file, after that I put it into my fabric mod folder, with the latest optifabric version and then i loaded up the game. Worked smooth, no issues.

## Fabric/Forge Version
Fabric 0.7.4

## OptiFabric Version
Optifabric 1.11.9

## Other Installed Mods
boosted-brightness-2.1.0
fabric-api-0.36.0+1.17
horse-stats-vanilla-4.1.8
litematica-fabric-1.17.0-0.0.0-dev.20210616.033538
malilib-fabric-1.17.0-0.10.0-dev.22+beta.1
worldedit-fabric-mc1.17-7.2.6-beta-01
Xaeros_Minimap_21.12.5.1_Fabric_1.17.1
XaerosWorldMap_1.14.5.2_Fabric_1.17.1
note: I tried optifine standalone and its the same issue. F2 doesnt work :D 
## Log Files/Crash Reports
I dont get any crashes or log files

## F3 Debug Screenshot
I can't screenshot it when I can't screenshot... But I'll try my best to use print screen, maybe it'll be good too
![2021-07-10 (3)](https://user-images.githubusercontent.com/87244731/125175317-920f0280-e1cb-11eb-84d6-a4c4d7627221.png)

## Prior Testing
It vanilla it works perfectly, but when i use optifine (even standalone) it does it.
I can assure you, that none of the mods are the cause, because even with standalone optifine it does it.

## Additional Information
I don't have anything else to say about this :)

**Comment by Ari-RERA-43** [comment] 2021-07-10 20:15
Can you send the blank/backround screenshot?

**Comment by Stereo528** [comment] 2021-07-10 20:26
also possibly set Screenshot Resolution to 1x instead of anything higher

**Comment by Hejkal147** [comment] 2021-07-11 08:50
> 
> 
> Can you send the blank/backround screenshot?
Here it is, its the latest one I did yesterday on the latest pre optifine version
![2021-07-10_21 58 31](https://user-images.githubusercontent.com/87244731/125188879-c3241d00-e235-11eb-8266-8b76e28522d4.png)

**Comment by Hejkal147** [comment] 2021-07-11 08:53
I also noticed that when creating a new world, the world picture is blank too.

**Comment by Hejkal147** [comment] 2021-07-11 08:57
> 
> 
> also possibly set Screenshot Resolution to 1x instead of anything higher

Yes, I tried to. But my only options are: Default, 2x, 3x and 4x. Trying every option results in the same problem. It was on default when i looked.

**Comment by fayer3** [comment] 2021-07-11 10:55
Duplicate of  #5770

**Closed** 2021-07-11 19:16 UTC
