### ISSUE TITLE
World loading bug

### ISSUE THREAD

**Issue by CreefYT** [sp614x/optifine#3557] opened 2020-03-20 22:41 UTC
When I join any Singleplayer World a few chunks get loaded, but the rest is just emptiness. This is not just in Worldgeneration. one chunk seems just not to load the textures, so you can easily update that chunk but then after that youre stuck
![2020-03-20_23 32 50](https://user-images.githubusercontent.com/62450107/77211449-4e8b1380-6b04-11ea-9e85-48b0fbfa4a65.png)

**Comment by schrodingerspsycho** [comment] 2020-03-20 22:43
Post a F3 screenshot

**Comment by realjackasterisk** [comment] 2020-03-21 21:25
More details please. What version? Using Forge? What other mods? etc

**Comment by realjackasterisk** [comment] 2020-05-22 08:12
Author has not replied in over 2 months, and given the existing information, I can only assume this is a duplicate of #3365.

**Closed by realjackasterisk** 2020-05-22 08:12 UTC
Labels: bug, chunks, details needed
