### ISSUE TITLE
[1.15.2 pre16] Entities do not display red flash when damaged on "(internal)" shader

### ISSUE THREAD

**Issue by Amciak** [sp614x/optifine#3909] opened 2020-05-09 23:55 UTC
## Description of Issue
The damage animation do not show the red flash while using shaders including the "(internal)" one
![2020-05-09_23 05 41](https://user-images.githubusercontent.com/65096560/81487779-352f5980-9261-11ea-91ea-5418fed6d81f.png)

## OptiFine Version
OptiFine 1.15.2 HD U G1 pre16

**Comment by sp614x** [comment] 2020-05-30 12:38
Duplicate of #3598.

**Closed by sp614x** 2020-05-30 12:38 UTC
Labels: 1.15, duplicate, shaders
