### ISSUE TITLE
Can't Figure Out How To Download OptiFine On My Computer

### ISSUE THREAD

**Issue by Qauppi** [sp614x/optifine#5710] opened 2021-06-08 20:02 UTC
Over the past few months I have attempted to download multiple versions of OptiFine on my Windows 10 computer.
- I go to optifine.net/downloads
- I click on whatever version I'm looking for (in the image I tried 1.17)
- Download it
- Open the folder
- Allow changes to my computer

And the I get that error message V V V

![image](https://user-images.githubusercontent.com/79272275/121249347-7c2bbc00-c872-11eb-8b6c-f06e03334a8b.png)

I'm not good with computers and would appreciate it if someone knew what to do. I couldn't find anyone else with this issue anywhere :(

**Comment by KaiAF** [comment] 2021-06-08 20:20
Download Jarfix https://johann.loefflmann.net/jarfix

**Comment by sp614x** [comment] 2021-06-08 22:51
Duplicate of #3925, #4923

**Closed by sp614x** 2021-06-08 22:51 UTC
