### ISSUE TITLE
[BetterSnow][1.15.2] Bettersnow does not render grass sides as snowy

### ISSUE THREAD

**Issue by yezhiyi9670** [sp614x/optifine#3855] opened 2020-05-04 12:05 UTC
## Description of Issue

When a transparent block is "snow_hacked" by Better Snow, the grass block under it will not be rendered as snowy. This looks glitchy. This can be even more weird with Better Grass.

## Steps to Reproduce

1. Create a map.
2. Enable Better Snow. Place two adjacent grass blocks. Cover one with snow and the other with a flower. Now you can see the flower is "snow_hacked".  
❎ The side of the grass block which is under the flower is not rendered as snowy.

## OptiFine Version

1.15.2 G1 pre15

## Installation Method

Both.

## Log Files/Crash Reports

This is likely not needed. Ask for it if you need it.

## F3 Debug Screenshot

![image](https://user-images.githubusercontent.com/39194383/80963769-36681d00-8e42-11ea-80fa-b5d2ec454849.png)

## Prior Testing

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge **Very likely**
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself. **No**
- Does this happen in OptiFine standalone? **Very likely**
- Does this happen in Vanilla without OptiFine? **No**

## Additional Information

I know the `snowy` state of grass block is a BlockState. This issue should be fixed by visually changing the texture of the sides of that grass block, instead of changing the BlockState of that grass block. Otherwise it will not work on servers.

**Comment by Regnander** [comment] 2020-05-04 12:31
Related #3713

**Comment by naeqirelle2020** [comment] 2020-05-31 22:01
Tested, Still a bug

**Comment by sp614x** [comment] 2020-06-09 08:40
Duplicate of #3713

**Closed by sp614x** 2020-06-09 08:40 UTC
Labels: 1.15, bug, rendering
