### ISSUE TITLE
Bug on enchanted items

### ISSUE THREAD

**Issue by Juan8616** [sp614x/optifine#5908] opened 2021-06-27 21:58 UTC
## Description of Issue
The enchanting animation isn't rendered with some shaders

## Steps to Reproduce
I just use some shaders, and my enchanted items were black, or changing black - purple - black- purple

## OptiFine Version
Optifine 1.17 pre 23

## Installation Method
I use the standalone version

## Other Installed Mods
I have not mods

## Additional Information
Here's an image:
![2021-06-27_11 53 26](https://user-images.githubusercontent.com/76629257/123560599-db416a00-d768-11eb-8508-8f5cc1beb34f.png)

**Comment by Whitelisted1** [comment] 2021-06-27 22:09
Similar/duplicate of #5891

**Closed** 2021-06-27 22:20 UTC
