### ISSUE TITLE
OpenGL Error: 1281 (Invalid value)

### ISSUE THREAD

**Issue by Quavelen** [sp614x/optifine#1289] opened 2018-03-14 20:42 UTC
Just want to make it clear that this isn't a crash, nor is it a "problem". Simply a minor annoyance that spams the ingame chat.

___

**Edit:** It seems my faulty memory got the best of me. This issue had been occurring for a long time, and I finally got around to posting an issue today. I hadn't actually tested it/tried to reproduce it for over a year. So my original memories on the matter were rather inaccurate. This actually happens simply by enabling the "Clear Water" option, within the Quality category.

So um, as the title states, I'm receiving an error message in my chat. ~~It only occurs after I have enabled, and then disabled a shader via OptiFine. Once the shader (any shader) is disabled,~~ submerging myself in water causes this message to appear at a steady rate in my chat. It occurs with OptiFine alone, no modifications whatsoever. I'm able to consistently reproduce this exact error, with the same exact steps every time.

Whilst this error appears slowly in the ingame chat, it is generated at a mad rate within the console. Here is what's spammed in the launcher's log: https://i.imgur.com/lXURzsD.png

```
19:50:22 | game | [19:50:22] [main/ERROR]: @ Post render
19:50:22 | game | [19:50:22] [main/ERROR]: 1281: Invalid value
19:50:22 | game | [19:50:22] [main/ERROR]: ########## GL ERROR ##########
19:50:22 | game | [19:50:22] [main/ERROR]: @ Post render
19:50:22 | game | [19:50:22] [main/ERROR]: 1281: Invalid value
19:50:22 | game | [19:50:22] [main/ERROR]: ########## GL ERROR ##########
19:50:22 | game | [19:50:22] [main/ERROR]: @ Post render
19:50:22 | game | [19:50:22] [main/ERROR]: 1281: Invalid value
19:50:22 | game | [19:50:22] [main/ERROR]: ########## GL ERROR ##########
19:50:22 | game | [19:50:22] [main/ERROR]: @ Post render
19:50:22 | game | [19:50:22] [main/ERROR]: 1281: Invalid value
19:50:22 | game | [19:50:22] [main/ERROR]: ########## GL ERROR ##########
19:50:22 | game | [19:50:22] [main/ERROR]: @ Post render
19:50:22 | game | [19:50:22] [main/ERROR]: 1281: Invalid value
19:50:22 | game | [19:50:22] [main/ERROR]: ########## GL ERROR ##########
```

Scrolling through the log, there are 150+ of these errors *per second* - according to the timestamps. I'd like to assume that this would cause a noticeable bit of lag, on lower-end PCs. I haven't personally noticed anything on mine. Here's a pastebin of some of it, where you can see the massive spam yourself:  https://pastebin.com/jgzmKYym

So, I'm going to assume that since this problem occurs without shaders or anything else enabled whatsoever, that it is indeed an OptiFine issue. Mind you, I can delete and regen the OptiFine preferences and whatnot and this error will vanish. ~~As explained above, I will then simply need to enable a shader (such as SEUS Renewed) and then disable it.~~ Then, submerge myself completely and watch as the spam begins. Could this please be looked into?

**Comment by Tsoccerguy3** [comment] 2018-03-14 22:41
This is a driver issue and occurs in JVM outside the game . Update your Graphics Diver and see if the latest driver works .

**Comment by Quavelen** [comment] 2018-03-14 23:29
>Update your Graphics Diver 

The Nvidia driver 391.01 is the most recent driver available, which was released on the 26th of February, 2018.

>Not all hardware can support all GL features 

I can guarantee you my 1080 Ti can support anything OpenGL might ask for.

> Just curious why you did not post you system specs . ?

Because it has nothing to do with specs, driver version, or anything of the sort. It occurs consistently throughout every system build I've ever used. However, just to humour you, I'll post my current specs:

* i7-7700k @5.0GHz
* GTX 1080 Ti (Driver version 391.01)
* 32GB DDR4 @2667MHz
* 256GB M.2 NVMe SSD
* Windows 10 Pro 64-Bit (Version 1709, build 16299.309)


I don't mean to sound rude; it's just that this isn't an isolated thing, as I said.

**Comment by Dushess** [comment] 2018-03-14 23:38
Just to be sure, MC hardlinked to dedicated GPU?

**Comment by Quavelen** [comment] 2018-03-14 23:51
>Just to be sure, MC hardlinked to dedicated GPU?

Yup, here's a screenshot of F3 showing the game using my graphics card: https://i.imgur.com/YoJ8GGN.png

**Comment by Dushess** [comment] 2018-03-15 00:25
Ok, that's not this thing...

**Comment by sp614x** [comment] 2018-03-15 10:51
Can you post F3 screenshot without the launcher console?
The line `T:inf vsync ...` is interesting.
Have you tried to reset the video settings (Video Settings -> Other -> Reset)?
You can try to enable/disable: VBOs and "Performance -> Render Regions".

**Comment by Quavelen** [comment] 2018-03-15 17:48
>Can you post F3 screenshot without the launcher console?

Yup, here you go: https://i.imgur.com/BNAl4cD.png

>The line T:inf vsync ... is interesting.

I didn't realise I had cut it off, sorry lol. 

>Have you tried to reset the video settings (Video Settings -> Other -> Reset)?

Yup, I mentioned regenerating/reinstalling the files, too. It just happens regardless, if I enable clear water.

>You can try to enable/disable: VBOs and "Performance -> Render Regions".

Okay, just tried that and the error still occurs. =/

**Comment by KazWolfe** [comment] 2018-03-15 17:58
Likely related to #516 and #1058, which are still open. 

According to some various sources online, `1281` errors are related to invalid texture sizes. You can attempt to disable Clear Water as a workaround, though this may not be desirable.

Try disabling all other mods (at least temporarily) and see if this issue resolves itself - sometimes there are conflicts with other mods, especially ones that also touch the rendering code.

From what I gathered from reading through various forums, this seems to be pretty common with Clear Water and *some* other as-of-yet undetermined factor. People have reported things all over the place, from disabling other mods, removing HD texture packs, etc.

**Comment by Quavelen** [comment] 2018-03-15 18:28
>Try disabling all other mods (at least temporarily) and see if this issue resolves itself - sometimes there are conflicts with other mods, especially ones that also touch the rendering code.

Um. Like I said in the opening post:

>>It occurs with OptiFine alone, no modifications whatsoever. I'm able to consistently reproduce this exact error, with the same exact steps every time.


My screenshots provided are all without any mods; you can clearly see that. It's just OptiFine itself, with clear water enabled. I'd also like to mention that this error does not happen at all, with Shaders enabled - such as SEUS Renewed: https://i.imgur.com/GpZQoNC.png

**Comment by Tsoccerguy3** [comment] 2018-03-18 20:32
sp614x is not going to be able help you, first the log is not a Minecraft log , The error occurs outside the game in JVM and its a function call to the video driver from inside the JVM . My guess its a Nvidia Bug .
Your Hardware seems to be cutting edge . Post a bug report on Nvidia bug site

**Comment by Quavelen** [comment] 2018-03-19 06:39
>the log is not a Minecraft log
It's clearly a Minecraft log. How is a message taken from the "Minecraft game output" not Minecraft? How is an ingame chat message that reads "OpenGL Error: 1281 (Invalid value)" not Minecraft?

As I said to you on your first reply:

>> It occurs consistently throughout every system build I've ever used. 

It only happens with OptiFine, and only when Clear Water is enabled. It does not happen with vanilla minecraft, nor with shaders enabled. This *clearly* indicates it is an OptiFine bug. 

> come across as self entitled 

I'm sorry you think me getting frustrated with you people, sounds like I'm self entitled. All I did was report an obvious OptiFine bug, and answer every question you asked. All it takes is for you to actually bother to read what I've typed out, for you to realise you are wrong.

**Comment by sp614x** [comment] 2018-03-19 13:32
Can you try to disable Fast Render and Anisotropic Filtering?

**Comment by Quavelen** [comment] 2018-03-19 15:04
>Can you try to disable Fast Render and Anisotropic Filtering?

Yup, it sadly still happens. =/

>Does this happen on one specific world or on different worlds?

Strangely, I don't get this in a creative world. Switching to survival causes it to happen regardless of the world, though.

>Does it affect single-player or multi-player or both?

I hadn't thought to test single player - I rarely ever play in single player. It seems this only happens on multi-player on a server, whilst within survival mode. In single player, I would like to note that the game output said this when toggling the clear water option:

```
14:56:05 | game | [14:56:05] [main/INFO] [shadersmod.common.SMCLog]: [Shaders] Save ShadersMod configuration.
14:56:23 | game | [14:56:23] [main/INFO] [Config]: [OptiFine] ClearWater (client) relighted 132169 chunks
14:56:29 | game | [14:56:29] [main/INFO] [Config]: [OptiFine] ClearWater (client) relighted 132169 chunks
14:56:59 | game | [14:56:59] [Server thread/INFO] [Config]: [OptiFine] ClearWater (server) relighted 179766 chunks
```

And this, when toggling it in multi-player:

```
15:01:46 | game | [15:01:46] [main/INFO] [Config]: [OptiFine] ClearWater (client) relighted 207304 chunks
15:01:46 | game | [15:01:46] [main/INFO]: [CHAT] �eOpenGL Error�f: 1281 (Invalid value)
15:02:05 | game | [15:02:05] [main/INFO] [Config]: [OptiFine] ClearWater (client) relighted 207304 chunks
15:02:05 | game | [15:02:05] [main/INFO]: [CHAT] �eOpenGL Error�f: 1281 (Invalid value)
```



Whilst underwater, or near water, the client hangs for a second or two before saying this. Would that maybe have something to do with it?

**Comment by sp614x** [comment] 2018-03-20 11:17
Can't reproduce the problem in multiplayer survival with or without clear water.
That may be something specific to the server you play on, for example an NPC with invalid skin or another side effect of server plugins.

**Comment by Quavelen** [comment] 2018-03-20 20:40
@sp614x 

Okay, I'm an idiot. With the encouragement of a friend, I went and tested it extensively in a single player world, and now I understand why this has happened across all devices and all servers. In every single instance this occured, I was wearing a helm with the respiration enchant over the maximum level of 3.

With it enchanted from 1-3, it's fine. However, anything 4 and above causes the error spam. I'd like to note that this *does not* happen without OptiFine, and it *does not* happen if I have a shaderpack enabled via OptiFine. It only occurs with OptiFine by itself, and with Respiration 4+ on a helm underwater.

Thank you for bothering to respond to me thus far. Is this an issue you can resolve? Or is it something quirky with Mojang's code?

**Comment by sp614x** [comment] 2018-03-20 23:32
Fixed, coming in next preview D1.

**Comment by Quavelen** [comment] 2018-03-21 03:26
>Fixed, coming in next preview D1.

Awesome, thank you! =)
I'm glad it was something you could fix.

**Comment by sp614x** [comment] 2018-03-21 11:35
Fixed in preview D1 for 1.12.2

**Closed by sp614x** 2018-03-21 11:35 UTC

**Comment by darthvader45** [comment] 2018-07-12 19:53
Weird, I've encountered this with E1 for 1.12.2, and Clear Water is disabled.  Happens regardless of what I'm doing.  No idea what could cause it.
[latest.txt](https://github.com/sp614x/optifine/files/2188541/latest.txt)

**Comment by VL4DST3R** [comment] 2018-07-17 17:55
Same for me, E1 for 1.12.2, Clear Water disabled. D1 did not have this problem.

**Comment by darthvader45** [comment] 2018-07-17 18:02
I'm definitely gonna need this fixed, otherwise I may have lag issues that
cannot be solved.  Please, investigate this.

Golden rule in Minecraft: Never dig straight down.

**Comment by VL4DST3R** [comment] 2018-07-17 18:37
Should we post this as a new/separate issue? Since this one is marked as closed

**Comment by sp614x** [comment] 2018-07-17 19:06
@darthvader45 
```
[main/INFO] [FML]: Forge Mod Loader has identified 30 mods to load
```
Probably a conflict with one of the installed mods.

**Comment by VL4DST3R** [comment] 2018-07-17 20:12
I too have a fair amount of mods loaded, also i use shaders. @darthvader45 do you?

**Comment by darthvader45** [comment] 2018-07-17 20:54
No shaders.  No way a mod could cause conflicts, as the only ones dealing
with any sort of OpenGL are Better Foliage and Dynamic Surroundings'
graphical effects.  I've run those mods several times and not had this
error.

Golden rule in Minecraft: Never dig straight down.

**Comment by VL4DST3R** [comment] 2018-07-17 21:11
I also use those 2 mods (among others). Maybe they do have some sort of incompatibility with the latest optifine version? Do you still get the errors if you remove them?

**Comment by darthvader45** [comment] 2018-07-18 01:43
I'll check tomorrow afternoon, after work.

Golden rule in Minecraft: Never dig straight down.

**Comment by vcsolanki** [comment] 2018-07-18 03:48
I don't know about the fix in the code!!
but there is a option to disable showing opengl errors in chat box... (In Latest OptiFine for 1.12.2)

goto **Option > Video Settings > Other > Show GL Error**

Turn off that settting.
this options tooltip did say that some error cant be fixed!!

Now the error just goto log file, not on screen.

**Comment by A-T-L-A-S** [comment] 2019-01-15 12:00
Turning off VBOs fixed it for me...

**Comment by axemwa** [comment] 2019-08-02 01:44
I also get these errors in client logs in 1.13.2
https://pastebin.com/8D40d81q

**Comment by Mizumaky** [comment] 2020-11-25 19:42
Playing **Valhelsia 3** modpack, the error started regularly popping up when in area with Mekkanism and Immersive Engineering blocks (eg a spinning windmill etc) and Minecolonies stuff around. Dissappeared after _turning off_ **Render reagions**.

**Comment by cha0sbuster** [comment] 2021-02-27 19:32
> Playing **Valhelsia 3** modpack, the error started regularly popping up when in area with Mekkanism and Immersive Engineering blocks (eg a spinning windmill etc) and Minecolonies stuff around. Dissappeared after _turning off_ **Render regions**.

Can confirm, disabling Render Regions also makes it go away. I suspect Mekanism in particular, as it occurred at my base with Mekanism stuff. Playing FTB Endeavour.

**Comment by joelparis003** [comment] 2021-06-01 08:03
OpenGL error 1281 might be related to shaders – graphic settings that are mainly imported by the user in the modded Minecraft. Corrupt or faulty settings trigger the error. Also, syncing issues, updates, old files can be the triggers. Do not forget about Java scrip usage in the game application.
Read More: https://windows-club.com/how-to-fix-opengl-error-1281/

**Comment by futbol-libre-tv** [comment] 2026-02-01 15:10
<p><a href="https://futbollibrestv.org/">Futbol Libre TV</a> ayuda a disfrutar el f&uacute;tbol online de manera c&oacute;moda y r&aacute;pida. Libre Futbol re&uacute;ne el contenido en un solo espacio. Futbol Libre se enfoca en ofrecer claridad, accesibilidad y una experiencia amigable para el aficionado.</p>
