### ISSUE TITLE
OptiFine makes textures go wild when playing with Forge

### ISSUE THREAD

**Issue by Arcticzomb** [sp614x/optifine#4267] opened 2020-07-06 05:05 UTC
Textures go wild when held in your hand and are invisible in the hot bar/inventory/creative inventory/JEI menu etc.

## Steps to Reproduce
1. What do you do... 
2. ...to find this bug?

OptiFine 1.16.1 HD U G2 pre2

Dropped it into the mods folder for Forge

JEI

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

No. Optifine works completely fine in vanilla.

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   Yes
- Does this happen without any mods at all?
   Yes
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

Summary: Basically, OptiFine 1.16.1 HD U G2 pre2 works fine in vanilla minecraft. When I drop the 
OptiFine 1.16.1 HD U G2 pre2.jar file into the mods folder for Forge, the textures become wierd.(pictures will be included) It effects mods such as JEI (Only mod I tested with) and possibly others. It makes it so that textures in your hot bar, inventory, creative inventory, JEI menu and other things are all invisible with the exception of shulker boxes, chests, banners and other a few other things.
![1](https://user-images.githubusercontent.com/67886055/86557611-4bcdf600-bf1c-11ea-9146-9f7ca45dc181.JPG)
![2](https://user-images.githubusercontent.com/67886055/86557625-56888b00-bf1c-11ea-8339-e226038da217.JPG)
![Capture](https://user-images.githubusercontent.com/67886055/86557626-5a1c1200-bf1c-11ea-86dd-0df7424fc95e.JPG)

**Comment by EdgyPotato** [comment] 2020-07-06 15:25
Duplicate of #4266

**Comment by yezhiyi9670** [comment] 2020-07-08 04:42
Only with shaders?

**Comment by Deviouslrd** [comment] 2020-07-08 04:43
Also what forge version?

**Comment by yezhiyi9670** [comment] 2020-07-10 04:59
Forge versions over 32.0.44 (inclusive) are broken because of the "model system improvements".

**Comment by sp614x** [comment] 2020-07-10 13:25
Duplicate of #4277

**Closed by sp614x** 2020-07-10 13:25 UTC
Labels: 1.16, forge, shaders
