### ISSUE TITLE
[Category] Custom skies are janky during night time

### ISSUE THREAD

**Issue by illusionDoge** [sp614x/optifine#7352] opened 2023-04-08 04:33 UTC
## Description of Issue
When you use a resource pack that changes the overworld sky with the latest version of optifine (1.19.4), during night time in game the sky tends to speed up, and if you have player bobbing enabled, the sky will move along with the player. 

## Steps to Reproduce
1. Find a resource pack that changes the sky textures
2. enable player bobbing (Options> Video Settings> Details> View Bobbing: ON)
3. use /time set midnight, or wait until night time in game

## OptiFine Version
1.19.4

## Installation Method
Standard Installer

## F3 Debug Screenshot 
![2023-04-07_23 31 04](https://user-images.githubusercontent.com/109191426/230703178-05c634f1-dbc7-4903-94a2-a6c63fbacbf3.png)

https://user-images.githubusercontent.com/109191426/230703180-36f4d571-7bb6-44d2-922c-d3a21f71a694.mp4

(Footage)

## Prior Testing
Only occurs with optifine

## Additional Information
This issue does not occur in previous versions such as 1.19.2 and lower

**Comment by Jiingy** [comment] 2023-04-08 06:43
Can confirm this issue

**Comment by UsernameGeri** [comment] 2023-04-29 13:32
Does this happen with other packs too? I couldn't reproduce the issue, so I would assume it's hardware related, or at least driver related.

**Comment by illusionDoge** [comment] 2023-05-02 03:25
> Does this happen with other packs too? I couldn't reproduce the issue, so I would assume it's hardware related, or at least driver related.

Down Below is a link to a random 'fancy sky' resource pack that i found online, download it and use it on 1.19.4 with **Bobbing Enabled** 
then set time to night and walk around similar to the footage of the original post. you can compare night to day and see how the night sky behaves differently. Since i don't know how to manually work skies in optifine, it is fair to assume that its a resource pack issue?

SIDE NOTE:
Also i'm unsure if its my hardware since i've asked friends to repeat the steps with the outcome being the same for them.
if you can't reproduce it then oh well ¯\_(ツ)_/¯

LINK:
https://www.9minecraft.net/fancy-skies-resource-pack/

**Comment by UsernameGeri** [comment] 2023-05-02 15:55
Yeah so it's an issue with the pack. It has this parameter `axis=0.0 -0.1 0.0` which is incorrect. If you change it to `axis=0.0 -1.0 0.0`, that will fix it. The docs say:
> the rotation axis can be any vector except 0 0 0. Normalization is not required.
but that is incorrect, you _need_ to specify a **one unit length vector**. So I guess the bug is that the vector is not getting normalized.

**Comment by Jiingy** [comment] 2023-07-16 21:30
Closing this issue in favor of #7235

**Closed by Jiingy** 2023-07-16 21:30 UTC
Labels: custom sky, 1.19
