### ISSUE TITLE
Optifine Causing Invisible Inventory Items and Visual Bug

### ISSUE THREAD

**Issue by cherixberry** [sp614x/optifine#4266] opened 2020-07-06 05:01 UTC
## Description of Issue
Please provide as much detail as possible.
Using any of the texture packs I have as well as with 2 different shaders, all my inventory items are invisible and whichever item I'm holding appears with rainbow lines and is unrecognizable. 

## Steps to Reproduce
1. Have a texture pack
2. Enable a shader
3. Open inventory (with items) and have an item in your hand

## OptiFine Version
1.16.1 preview G1 and G2

## Installation Method
Used with MultiMC launcher

## Fabric/Forge Version
Latest Forge via MultiMC launcher

## Other Installed Mods
No other mods, resource packs I tested were:
Dokucraft Light 1.16
Clarity 1.16
Depixel 1.16
DragonDance v0.6.1 (1.16)
Wolfhound 1.16

Shaders tested:
Sildurs Vibrant Shaders v1.27 High
KUDA Shaders v6.1

## F3 Debug Screenshot
No debug screenshots, but here's a gif of using the shader with inventory bugged out, as well as closeup screenshots of the visual bugs.

https://gyazo.com/e52a25423e1090faea8b921b182be94c

https://gyazo.com/580dc5c61b7aea34b8bc4034d4639b24

https://gyazo.com/95f641ee86bd2e80de8847e5c78e4821

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
Yes

- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
Without Optifine or with shaders off, no it doesn't happen

- Does this happen in Vanilla without OptiFine?
No

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.
There was a similar bug in v1.15.2 Optifine where the dirt texture was broken when dirt was in hand. It would become transparent when character moved. This happened with several different texture packs. Not sure if this is related.

**Comment by sp614x** [comment] 2020-07-10 13:26
Duplicate of #4277

**Closed by sp614x** 2020-07-10 13:26 UTC
Labels: 1.16, forge, shaders
