### ISSUE TITLE
Optine pre 25 and pre 26 cause blue screen flash with CoFH Core 1.15.2

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [sp614x/optifine#4103] opened 2020-06-16 03:39 UTC
## Description of Issue
Using CoFH Core for 1.15.2 with Optifine pre 24, 25 and 26 causes a blue screen flash when mining or cutting down trees with an axe.

## Steps to Reproduce
1. Use Optifine pre24, 25 or 26 with Cofh Core 1.15.2-0.4.0b and Forge 31.1.63.
2. Try to mine or chop a tree down and screen flashes.

## OptiFine Version
Optifine pre 24, 25 or 26.
## Installation Method
Dropped jar in mod folder with Cofh core .jar.

## Fabric/Forge Version
Forge 31.1.63

## Other Installed Mods
No other mods. Just those three.

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
No crash. Just a rendering issue.

## Prior Testing
Does not happen in vanilla.
Does NOT happen with pre 23 or earlier!

If you've installed using Forge/Fabric:
Only happens with Optifinr and CoFH Core.

## Additional Information
I love OF.

**Comment by Kynolin** [comment] 2020-06-20 16:12
This is most likely a duplicate of #4088. Using internal shaders, the screen will fill with a white background and display the dark block breaking pattern. When I used SEUS, I got a weird transparent color which I'm assuming is what you're seeing.

**Comment by sp614x** [comment] 2020-06-21 19:47
Duplicate of #4088

**Closed by sp614x** 2020-06-21 19:47 UTC
Labels: 1.15, forge, mods
