### ISSUE TITLE
[graphical bug] shaders is glitched

### ISSUE THREAD

**Issue by kuddyh3ct0r** [sp614x/optifine#7043] opened 2022-08-01 17:15 UTC
I only have OptiFine_1.19_HD_U_H9 in the mods folder, no texturepacks and turned on shaders and this happened.
![2022-08-01_10 10 56](https://user-images.githubusercontent.com/109633944/182205628-165ecead-d5be-48b6-9343-c645846c509e.png)

**Comment by LeonMosey** [comment] 2022-08-01 17:56
Same problem. All of my members "213" Users on my server using Optifine With Shaders.. however they reporting the same problems like u with HD U H9

**Comment by methatronc** [comment] 2022-08-01 19:37
Same problem here using forge 41.1.0 with OptiFine 1.19_HD_U_H9, without texture packs.
![image](https://user-images.githubusercontent.com/58328740/182231345-251c936f-36ea-4976-9f84-bd67e71327fd.png)

**Comment by nfacha** [comment] 2022-08-01 22:38
![2022-08-01_22 36 40](https://user-images.githubusercontent.com/8540172/182257279-366da427-209a-4c3b-abd4-58f15936bb59.png)
Also happening here

**Comment by methatronc** [comment] 2022-08-02 11:03
@kuddyh3ct0r @LeonMosey @nfacha could you please identify what mods are causing these glitches on your ends ?
For me as I said it was creativecore + ambiantsounds, perhaps if we can identify common mods we'll have more clues for sp614x to solve this.

**Comment by LeonMosey** [comment] 2022-08-02 11:31
@methatronc HAY Im currently not using any mods except from the common compination "forge and optifine . So in my case the glitch is not from any mods

**Comment by nfacha** [comment] 2022-08-02 11:34
Also not using any additional mods, just optifine.
Tried multiple shaders and all have the same issue so I would assume its not a shader issue

**Comment by mimi-min** [comment] 2022-08-02 12:08
Glad I'm not the only one seeing this issue! 

The same thing happened before when I used the wrong version of OptiFine for my version of Minecraft (1.19 vs 1.19.1), but matching the versions helped with that before. 

Now I'm trying to use it with Forge using the new version (H9),  and I'm getting the weird result like before.

Minecraft: 1.19
Forge: 41.1.0
OptiFine: 1.19_HD_U_H9

**Comment by Katsurandom** [comment] 2022-08-04 01:29
Its a Forge Problem, tried witouth forge and it works just fine, so yet again.....Its forge the problem, either we use mods or we use shaders it seems.........

**Comment by nfacha** [comment] 2022-08-04 08:54
> Its a Forge Problem, tried witouth forge and it works just fine, so yet again.....Its forge the problem, either we use mods or we use shaders it seems.........

I still get this issue with no additional mods

**Comment by Katsurandom** [comment] 2022-08-04 12:06
> 

Use it witouth the forge launcher, even a profile witouth mods triggers that error (At least for me), I used the normal launcher to test it and it doesn't show any rendering error

**Comment by GetTarabusted** [comment] 2022-08-07 16:07
Got the same problem
Forge 41.1.0 + Optifine H9 is OK 

Forge 42.0.9 + Optifine H9 wont run (crash at startup)

Forge 42.0.9 + Optifine H9pre1 is fine until i turn on the shaders (SEUS renewed or even the internal one) and i get the same glitches are the pictures above. It happened with 2 mods (a minimap and a inventory one) but I can reproduce the bug with only Forge+Optifine

Forge 43.0.0 + Optifine H9pre1 is the same as previous entry, same visual glitches

**Comment by King-Malakk4201** [comment] 2022-08-08 17:28
@GetTarabusted I am having this graphical issue running it on Forge 41.1.0 without mods.

**Comment by mcnuggets343** [comment] 2022-08-09 01:25
playing on the same versions as everyone else and getting this issue even with internal shaders. as soon as i stop using forge it goes away though, even tried fabric and it works fine.

**Comment by xicromok** [comment] 2022-08-09 01:39
> playing on the same versions as everyone else and getting this issue even with internal shaders. as soon as i stop using forge it goes away though, even tried fabric and it works fine.

So it's definitely a Forge issue?

**Comment by iWeluca** [comment] 2022-08-09 09:21
same issue here! i'm using the latest version of forge that supports 1.19.2 and was told that the 1.19.1 pre version of optifine was supposed to be compatible with the 1.19.2 version of forge but i guess not! not sure what causes this bug but it sure sucks that i cannot use shaders on my latest version survival world
Duplicate of #

**Comment by xicromok** [comment] 2022-08-10 01:15
> Glad I'm not the only one seeing this issue!
> 
> The same thing happened before when I used the wrong version of OptiFine for my version of Minecraft (1.19 vs 1.19.1), but matching the versions helped with that before.
> 
> Now I'm trying to use it with Forge using the new version (H9), and I'm getting the weird result like before.
> 
> Minecraft: 1.19 Forge: 41.1.0 OptiFine: 1.19_HD_U_H9
> 
> Edit: This happens with or without shaders.
> 
> Edit 2: I temporarily rolled OptiFine back to H8 and Forge back to 41.0.63, had some issues with mods, so I put them back to the latest versions and now it seems to be fixed. Odd.

I have installed Forge version 41.0.63 and OptiFine HD U H8 and the problem is fixed but some mods are not working. Just like you. How exactly have you put them in the latest versions? Have you reinstalled Forge 41.1.0 without removing the previous version or how? Maybe if I follow the same procedure it will work.

**Comment by iWeluca** [comment] 2022-08-10 05:00
You need to make sure the forge mods you are trying align with the game
version

**Comment by SidewardJet** [comment] 2022-08-16 20:51
Does anybody have a solution to this yet?

**Comment by mindforger** [comment] 2022-08-17 05:19
i can only confirm this being an forge issue of some kind, since i play on vanilla with forge for optifine and shaders and minimap ... the minimap was added later but the issue arose without any mods installed besides optifine and shaders

by the characteristics of the bug, it could be something where textures get rearranged or something in meory or something like that, the issue always presents itself when i turn off the shader and turn on again ... all i have to do to fix is restart minecraft

using multi MC for Version 1.19.1, forge 42.0.9, and the latest preview 9 of OF with seus renewed 1.0.1 and faithfullPBRx64 resourcepack

**Comment by xicromok** [comment] 2022-08-17 18:44
> Does anybody have a solution to this yet?

I have solved it, read above how.

**Comment by xicromok** [comment] 2022-08-17 18:46
> i can only confirm this being an forge issue of some kind, since i play on vanilla with forge for optifine and shaders and minimap ... the minimap was added later but the issue arose without any mods installed besides optifine and shaders
> 
> by the characteristics of the bug, it could be something where textures get rearranged or something in meory or something like that, the issue always presents itself when i turn off the shader and turn on again ... all i have to do to fix is restart minecraft
> 
> using multi MC for Version 1.19.1, forge 42.0.9, and the latest preview 9 of OF with seus renewed 1.0.1 and faithfullPBRx64 resourcepack
> 
> edit: this also happens to all my friends playing with roughly the same setup, but other shaders and resource packs

I'm sure it's not a Forge issue, but more of an OptiFine issue. As soon as I have replaced OptiFine with other alternatives (even more efficient as they provide better optimization) the problem has disappeared. You should see for yourself :)

**Comment by mindforger** [comment] 2022-08-18 05:04
yes and no, it is a cross interaction of some kind (since OF without forge does work fine) .. instead of promoting other mods in great disrespect of what spx614 did all the year for free (besides donation from those who wanted to donate) you should either provide more information to help him debug the issue or simply shut up

and as i told, by my testings it looks like something gets messed up when switching between modes and almost every time on the very first run after installation, restarting the game after it glitched out seems to work just fine for everyone i know at least

**Comment by Katsurandom** [comment] 2022-08-18 05:51
> > i can only confirm this being an forge issue of some kind, since i play on vanilla with forge for optifine and shaders and minimap ... the minimap was added later but the issue arose without any mods installed besides optifine and shaders
> > by the characteristics of the bug, it could be something where textures get rearranged or something in meory or something like that, the issue always presents itself when i turn off the shader and turn on again ... all i have to do to fix is restart minecraft
> > using multi MC for Version 1.19.1, forge 42.0.9, and the latest preview 9 of OF with seus renewed 1.0.1 and faithfullPBRx64 resourcepack
> > edit: this also happens to all my friends playing with roughly the same setup, but other shaders and resource packs
> 
> I'm sure it's not a Forge issue, but more of an OptiFine issue. As soon as I have replaced OptiFine with other alternatives (even more efficient as they provide better optimization) the problem has disappeared. You should see for yourself :)

Since this thread is for Optifine, any and all "solutions" that don't include Optifine working fine after it, aren't really "A solution"

If Optifine witouth forge works fine, and Optifine with forge doesn't. Then its a Forge problem, if all the problems only happen or trigger when Forge is in the equation (modded or not) then its a Forge Problem

Calling a "Solution" to stop using optifine it isn't really a solution, just like calling stop using Forge a solution isn't a solution either.........

**Comment by Deuuis** [comment] 2022-08-20 08:07
> I only have OptiFine_1.19_HD_U_H9 in the mods folder, no texturepacks and turned on shaders and this happened. ![2022-08-01_10 10 56](https://user-images.githubusercontent.com/109633944/182205628-165ecead-d5be-48b6-9343-c645846c509e.png)

Hey! Had the same problems two days ago, all textures were glitched just as your pic shows. I started Minecraft in a version with only OptiFine (without Forge) and activated shaders and played on multiplayer (did that without any problems). The odd part is, once I restarted the game the next day in the modded version of 1.19 (with OptiFine, Forge and other mods) it applied the shaders automatically without any texture glitches.
At first I thought I started the wrong version but all the mods were working and the shaders did as well! I don't know if the glitch will show up again once you change the shader in the loaded modded version though. 

![minecraftScreenshot1](https://user-images.githubusercontent.com/111632204/185735582-2435a3f2-03a6-45e4-b6d1-9b3ef3501531.png)

**Comment by profyonan** [comment] 2022-08-20 18:33
> > I only have OptiFine_1.19_HD_U_H9 in the mods folder, no texturepacks and turned on shaders and this happened. ![2022-08-01_10 10 56](https://user-images.githubusercontent.com/109633944/182205628-165ecead-d5be-48b6-9343-c645846c509e.png)
> 
> Hey! Had the same problems two days ago, all textures were glitched just as your pic shows. I started Minecraft in a version with only OptiFine (without Forge) and activated shaders and played on multiplayer (did that without any problems). The odd part is, once I restarted the game the next day in the modded version of 1.19 (with OptiFine, Forge and other mods) it applied the shaders automatically without any texture glitches. At first I thought I started the wrong version but all the mods were working and the shaders did as well! I don't know if the glitch will show up again once you change the shader in the loaded modded version though.
> 
> ![minecraftScreenshot1](https://user-images.githubusercontent.com/111632204/185735582-2435a3f2-03a6-45e4-b6d1-9b3ef3501531.png)

yea the same thing happened to me, but i turned off my shader, and turned it back on(in forge) and it broke again so...

**Comment by sp614x** [comment] 2022-08-20 19:25
The problem is that enabling/disabling shaders with Forge needs a restart.
Fixed in 1.19.1_H9, for all other 1.19.x versions just restart the game after enabling shaders.

**Closed by sp614x** 2022-08-20 19:25 UTC

**Comment by xicromok** [comment] 2022-08-21 21:23
> > > i can only confirm this being an forge issue of some kind, since i play on vanilla with forge for optifine and shaders and minimap ... the minimap was added later but the issue arose without any mods installed besides optifine and shaders
> > > by the characteristics of the bug, it could be something where textures get rearranged or something in meory or something like that, the issue always presents itself when i turn off the shader and turn on again ... all i have to do to fix is restart minecraft
> > > using multi MC for Version 1.19.1, forge 42.0.9, and the latest preview 9 of OF with seus renewed 1.0.1 and faithfullPBRx64 resourcepack
> > > edit: this also happens to all my friends playing with roughly the same setup, but other shaders and resource packs
> > 
> > 
> > I'm sure it's not a Forge issue, but more of an OptiFine issue. As soon as I have replaced OptiFine with other alternatives (even more efficient as they provide better optimization) the problem has disappeared. You should see for yourself :)
> 
> Since this thread is for Optifine, any and all "solutions" that don't include Optifine working fine after it, aren't really "A solution"
> 
> If Optifine witouth forge works fine, and Optifine with forge doesn't. Then its a Forge problem, if all the problems only happen or trigger when Forge is in the equation (modded or not) then its a Forge Problem
> 
> Calling a "Solution" to stop using optifine it isn't really a solution, just like calling stop using Forge a solution isn't a solution either.........

Well, the problem is that there is a visual bug that does not allow to see the textures correctly when applying shaders. As I have explained the visual error disappeared for me, therefore I have solved the problem. But, as you say! Haha

**Comment by nima462** [comment] 2022-08-25 10:43
There is finally a solution, If you download the 43.1.1 version of forge for 1.19.2 and the new version of optifine (not the preview version), It should work.
