### ISSUE TITLE
[Bug] Enchanted Armor no Animation or not Shining in latest optifine for 1.17 with BSL Shaders

### ISSUE THREAD

**Issue by dijgamingph** [sp614x/optifine#5984] opened 2021-07-07 15:50 UTC
## Description of Issue

Hi Devs, I just noticed on the latest release for the 1.17 that the enchanted armor are not animated or not shining on players POV. but on the hot keys and in the inventory it has animations. I'm using optifine with BSL Shaders but when i set it to vanilla it works fine.

## Steps to Reproduce
1. What do you do...
just equip any enchanted armor or weapon
2. ...to find this bug?

## OptiFine Version

preview_OptiFine_1.17_HD_U_G9_pre25

## Installation Method

I double clicked on the jar file and install it.

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
no, it works fine in vanilla

**Comment by Whitelisted1** [comment] 2021-07-07 16:38
Duplicate of #5846, so if you really are updated I guess this is still an issue

**Comment by dijgamingph** [comment] 2021-07-07 17:31
> Duplicate of #5846, so if you are really updated I guess this is still an issue

Hi! Thanks, Yes just updated Optifine just now. I'll just wait for the fix. Thank you

**Closed** 2021-07-07 19:42 UTC
