### ISSUE TITLE
Crash with JustEnoughItems

### ISSUE THREAD

**Issue by oneskres** [sp614x/optifine#344] opened 2016-11-22 09:58 UTC
When you open the inventory, the game crashes. For me, it only happens when I scroll through some pages. Removing opitfine fixed the crash.

[fml-client-2.log.txt](https://github.com/sp614x/optifine/files/606003/fml-client-2.log.txt)

**Comment by sp614x** [comment] 2016-11-22 11:17
Duplicate of https://github.com/sp614x/optifine/issues/22.
Fixed in OptiFine D4 for 1.10.2.

**Closed by sp614x** 2016-11-22 11:17 UTC
