### ISSUE TITLE
If I go below Y=62, everything below me disappears (Optifine 1.18.1 HD U H5 pre4)

### ISSUE THREAD

**Issue by user1-github** [sp614x/optifine#6532] opened 2022-01-01 14:27 UTC
In Optifine 1.18.1 HD U H5 pre4, If I go below Y=62, everything below me disappears as you can see in the screenshot. Previously I was using Optifine 1.18 HD U H3 and I didn't experience this issue in that version.
![2022-01-01_16 09 44](https://user-images.githubusercontent.com/56021366/147852746-9574504e-f375-40cd-91a8-d357ab05e91b.png)

**Comment by Theoretical-Enday** [comment] 2022-01-02 02:50
![QQ截图20220102114934](https://user-images.githubusercontent.com/73912246/147864744-19b03a82-deb5-4fbd-8222-dbb106cb0035.png)
Same 1.18.1 HD U H5 pre4

**Comment by DTT213** [comment] 2022-01-02 13:44
Same. this happen to me when i use shader with custom sky.

**Comment by nhasdarjian** [comment] 2022-01-05 21:18
I also experience this issue, it means I either play without shaders or just don't go underground.
This seems like it might have to do with the new 1.18.1 fog cylinders; maybe shader packs need to be updated to account for it?

**Comment by TheJulianJES** [comment] 2022-01-05 21:33
@nhasdarjian Did disabling "Custom Sky" not help you?

**Comment by KaiAF** [comment] 2022-01-08 21:33
I can't reproduce this, is this an issue that only happens in modded?

**Comment by nhasdarjian** [comment] 2022-01-09 05:02
> @nhasdarjian Did disabling "Custom Sky" not resolve the issue for you?

Yes, it fixed the issue. Thanks!

> I can't reproduce this, is this an issue that only happens in modded?

I am downloading Optifine through TLauncher and then just applying a shader with a custom sky. I also have a resource pack installed, and both the shader and resource pack have custom sky data.

**Comment by TheJulianJES** [comment] 2022-01-09 05:37
It happens in Vanilla. It's fixed by disabling "Custom Sky". It only occurs when I'm using the BDcraft resource pack (which probably includes custom sky resources), but I also haven't tried any other resource packs.

**Comment by user1-github** [comment] 2022-01-09 16:57
> I can't reproduce this, is this an issue that only happens in modded?

I'm using Misa x64 resource pack which also has custom sky. So in order to reproduce the issue, you just need to use a resourcepack with custom sky.

**Comment by Archilyte** [comment] 2022-01-29 22:08
can confirm. its the custom sky from texture packs, combined with any shaders.

**Comment by Archilyte** [comment] 2022-02-01 21:06
> can confirm. its the custom sky from texture packs, combined with any shaders.

to elaborate on this, it only happens when BOTH resourcepacks with sky data (like a custom skybox), and shaders (which what im assuming is custom sky settings) cause this to happen

**Comment by Dariusz17** [comment] 2022-02-06 10:41
im also have that problem, disabling "Custom Sky" resolve the issue but at cost of sky quality.

**Comment by Archilyte** [comment] 2022-02-06 12:32
> im also have that problem, disabling "Custom Sky" resolve the issue but at cost of sky quality.

or dialing shaders, either works

**Closed** 2022-02-08 14:59 UTC
Labels: bug, shaders, details needed, 1.18
