### ISSUE TITLE
[textures] connected textures not working

### ISSUE THREAD

**Issue by meparkpa** [sp614x/optifine#7018] opened 2022-07-22 02:58 UTC
## Description of Issue
I'm playing on 1.19 with lunar client which has optifine in it. I have the connected textures setting on fancy but the textures are not connected (for glass at least).

## Steps to Reproduce
1. open a world on 1.19 using lunar client with optifine.
2. put some glass next to each other

**Comment by sp614x** [comment] 2022-07-24 19:53
Duplicate of #7019

**Closed by sp614x** 2022-07-24 19:53 UTC
