### ISSUE TITLE
[Category] all armors are pink 

### ISSUE THREAD

**Issue by Wyqo** [sp614x/optifine#5983] opened 2021-07-07 13:42 UTC
OptiFine HD U G9 pre25
idk why my armors are pink 
![Uploading Java-runtime-alpha Screenshot 2021.06.26 - 17.11.19.79.png…]()

**Comment by Ari-RERA-43** [comment] 2021-07-07 13:50
This is a duplicate of #5806. Close this issue.

**Closed** 2021-07-07 19:44 UTC
