### ISSUE TITLE
[Bug] Entities and player not rendering shadows with BSL Shaders

### ISSUE THREAD

**Issue by KnightofRen161** [sp614x/optifine#5906] opened 2021-06-27 21:25 UTC
## Description of Issue
Entities and the player don't show shadows with BSL Shaders.

## Steps to Reproduce
1. Load game with BSL Shaders
2. ...to find this bug?

## OptiFine Version
OptiFine HD U G9 pre23

## Installation Method
Jar installer.

## F3 Debug Screenshot
![2021-06-27_17 22 33](https://user-images.githubusercontent.com/86574834/123559811-5c4e3080-d76c-11eb-82fc-9aac3638096f.png)

## Additional Information
![2021-06-27_17 24 04](https://user-images.githubusercontent.com/86574834/123559833-7e47b300-d76c-11eb-9f06-975850594951.png)

**Comment by sp614x** [comment] 2021-06-27 21:29
Duplicate of #5883

**Closed by sp614x** 2021-06-27 21:29 UTC
