### ISSUE TITLE
White Texture Bug for 1.15.2

### ISSUE THREAD

**Issue by jottgi** [sp614x/optifine#3583] opened 2020-03-27 05:59 UTC
![bugopti](https://user-images.githubusercontent.com/62737586/77726548-8f849b80-6fce-11ea-8234-d54973acb5be.png)

Unloaded chunks appear as white I think, I am not fully sure what's happening here but it does seem broken.

**Comment by Jeypi00** [comment] 2020-03-27 22:44
Experiencing the same problem with BSL Shaders (tried multiple versions).[
![2020-03-27_23 36 23](https://user-images.githubusercontent.com/62748623/77806373-cfa65580-7084-11ea-9c94-4ed9ad7a5970.png)
](url)

**Comment by Volasaurus** [comment] 2020-04-27 07:50
Still experiencing this as well.

**Comment by fgRuslan** [comment] 2020-05-16 13:23
This is still an issue :(

**Comment by sp614x** [comment] 2020-05-29 12:11
Duplicate of #3659.

**Closed by sp614x** 2020-05-29 12:11 UTC
Labels: 1.15, bug, rendering, shaders
