### ISSUE TITLE
[Bug] Dark item icons and chunks not loading

### ISSUE THREAD

**Issue by ClovisLowell** [sp614x/optifine#3869] opened 2020-05-05 17:45 UTC
I'm using the Optifine Forge mod with a few mods, and I disabled all of them except Optifine, and it didn't fix the bug. I disabled Optifine and re-enabled all of my mods, and the problem was fixed. 
![Minecraft_ 1 15 2 5_5_2020 1_41_36 PM](https://user-images.githubusercontent.com/64861428/81097885-81337480-8ed6-11ea-8d2c-adf482151a47.png)
(The end of the world)
![Minecraft_ 1 15 2 - Singleplayer 5_5_2020 1_41_56 PM](https://user-images.githubusercontent.com/64861428/81097888-81cc0b00-8ed6-11ea-8b7a-0ee19b9440c1.png)
(The darkened items)

**Comment by sp614x** [comment] 2020-05-05 22:44
Duplicate of #3830.

**Closed by sp614x** 2020-05-05 22:44 UTC
