### ISSUE TITLE
[Suggestion] 3D Armor

### ISSUE THREAD

**Issue by MoonTheBird** [sp614x/optifine#4907] opened 2020-10-13 04:35 UTC
I just want to be able to use custom models for armor

**Comment by Regnander** [comment] 2020-10-13 13:17
Duplicate of #1606, #561 and #291

**Comment by MajorMoonjump** [comment] 2020-10-15 23:55
those were literal years ago and appear to have been abandoned

**Comment by Cart3r1234** [comment] 2020-10-16 00:01
It does still have the to-do list tag

**Comment by MastaNub** [comment] 2020-11-26 19:20
Bedrock already has 3D armour. Nice.

**Comment by KaiAF** [comment] 2021-03-28 19:00
Already suggested #1606, #561 and #291.

**Closed by KaiAF** 2021-03-28 19:00 UTC
