### ISSUE TITLE
[1.15.2] No Block Break Animation on Most Blocks with Sildur's Vibrant Shaders

### ISSUE THREAD

**Issue by seeruk** [sp614x/optifine#3600] opened 2020-03-28 09:14 UTC
## Description of Issue

With certain shaders enabled, block breaking animations on certain blocks don't trigger. They appear on beds for me, but not for things like stone and dirt, etc. (In fact, beds are the only thing I've seen them on so far...)

## Steps to Reproduce

1. Enable (e.g. Sildur's Vibrant) shaders (tested with Sildur's Vibrant Extreme VL v1.27, v1.262, v1.25, v1.24 and v1.23)
2. Go punch some stuff.

## OptiFine Version

* preview_OptiFine_1.15.2_HD_U_G1_pre10
* preview_OptiFine_1.15.2_HD_U_G1_pre11
* preview_OptiFine_1.15.2_HD_U_G1_pre12
* preview_OptiFine_1.15.2_HD_U_G1_pre13
* preview_OptiFine_1.15.2_HD_U_G1_pre14
* preview_OptiFine_1.15.2_HD_U_G1_pre15
* preview_OptiFine_1.15.2_HD_U_G1_pre16
* preview_OptiFine_1.15.2_HD_U_G1_pre17

## Installation Method

Standalone installer.

## F3 Debug Screenshot

![2020-03-28_09 13 31](https://user-images.githubusercontent.com/2083033/77819659-6f3f0480-70d4-11ea-9f76-b8e32c776f7f.png)

(Just noticed I'm using Java 12 there, I've also just tried it with the bundled JRE and the same issue persists).

## Prior Testing

If you've installed standalone:

- Does this happen in Vanilla without OptiFine? 
    No

## Additional Information

I'm opening this as an OptiFine issue because these same shaders are working fine on older versions of Minecraft, so I'm assuming it's an OptiFine issue, not a shader issue.

**Comment by C3inx** [comment] 2020-03-28 15:56
I was having the same issue, but when I tested it the animation showed up just fine with BSL. When using SEUS, again, the animation didn't work.

**Comment by Legoman99573** [comment] 2020-03-28 18:25
This happens to all shaders and has been tested with most popular ones.

**Comment by seeruk** [comment] 2020-03-28 18:39
Yeah it's quite interesting... I've only experienced it using Sildur's Vibrant shaders. Sildur's Enhanced Default was fine, so was BSL and SEUS PTGI - unless it's intermittently doing it.

**Comment by LucaDragon5** [comment] 2020-03-28 19:35
yeah, it's a little bit annoying

**Comment by C3inx** [comment] 2020-03-28 19:45
Yeah. From some more testing, it was broken for SEUS, while Chocapic13's shaders, Continuum, and KUDA all worked as expected.

**Comment by Legoman99573** [comment] 2020-03-28 19:49
I would count it as smart animations break in some cases with shaders.

**Comment by seeruk** [comment] 2020-03-28 20:52
> It seems very unlikely for this to be an optifine issue at this point...

I'm not convinced it's the shaders, considering if you go back to an older version of the game and OptiFine (e.g. 1,14.4) it all works fine. The breaking animations work in 1.15.2 ordinarily, so that really leaves OptiFine. Maybe it's some kind of abstraction that needs to be updated to support 1.15.2.

**Comment by Legoman99573** [comment] 2020-03-28 23:55
There is a temporary workaround. Switching to the shader and then restarting minecraft causes them to animate like normal again.

**Comment by adriengivry** [comment] 2020-04-01 22:10
@Legoman99573 I do not understand your workaround. What do you mean by "Switching to the shader"?

**Comment by atirit** [comment] 2020-04-02 03:21
@Legoman99573 That doesn't work for me.

**Comment by atirit** [comment] 2020-04-02 04:37
The blocks that show the animation seem to be the same ones not affected by the "whiteworld" option, e.g. chests and beds.

**Comment by Legoman99573** [comment] 2020-04-02 10:58
@atirit i have been able to get it to work fine again on an AMD Radeon 580 GPU. But this bug report aside, this was patched in preview 11 and also preview 12

**Comment by seeruk** [comment] 2020-04-02 10:59
I tried it on pre12 earlier and was still experiencing the issue, sadly.

**Comment by Legoman99573** [comment] 2020-04-02 11:02
> I tried it on pre12 earlier and was still experiencing the issue, sadly.

Which Sildurs shader version?

**Comment by seeruk** [comment] 2020-04-02 11:02
1.27

**Comment by seeruk** [comment] 2020-04-02 11:05
Given it a go on both my PC (RTX 2080) and MacBook Pro (Radeon Pro 5500M) to try both AMD and NVIDIA and I don't get block breaking animations in both, SIldur's 1.27 on 1.15.2 pre12

**Comment by Legoman99573** [comment] 2020-04-02 11:07
Weird. It seems to be only with sildurs shader. They may need to update the shader for it to work properly or there will be a fix on release since they did say they are working on some bug fixes

**Comment by adriengivry** [comment] 2020-04-02 13:23
Doesn't work for me with 2080Ti + Ryzen 9 3900X :(

**Comment by seeruk** [comment] 2020-04-02 14:02
Still present in pre13, just to keep on top of the current state of this one.

**Comment by rocketsalad02** [comment] 2020-04-02 19:12
Can confirm the issues on a RX Vega 64 / Ryzen 3700X with recent drivers on Sildurs Shaders as well as SEUS. In addition, the block outlines disappear on an irregular basis - I assume it has to do with the missing block animation.
Have to mention that there were **no issues for like the first 2 hours of testing with shaders**, both bugs appeared after a restart with no settings changed.

**Comment by atirit** [comment] 2020-04-03 22:43
With SEUS PTGI the breaking animation's color is inverted for me on everything except bells as far as I could tell, but it still appears.

**Comment by Sugehart** [comment] 2020-04-04 03:33
Having similar issues, I noticed that the block breaking animation is actually being displayed on a different side than the one i'm break, which is quite odd. the colors are also inverted on the cracks. Also, it seems I can't get my light overlay mods to work, any help with that would be nice.

**Comment by marcusnewton** [comment] 2020-04-04 03:43
Can confirm, getting this bug on mc v1.15.2 and sildurs v1.27

**Comment by douira** [comment] 2020-04-10 20:49
I have no block breaking animation and no block outlines either (only at certain viewing angles)

**Comment by asbyth** [comment] 2020-04-10 20:55
known

**Comment by TrendyUsername** [comment] 2020-04-13 16:01
Still present in pre13 with NVIDIA Quadro RTX 4000 w. TU104.

**Comment by atirit** [comment] 2020-04-14 03:01
I should probably provide my specs too: OptiFine 1.15.2 HD U G1 pre13 and Minecraft 1.15.2 on 1070 Max-Q using Sildur's Vibrant Shaders v1.27.

**Comment by MrShroo** [comment] 2020-04-21 08:17
There is actually a braking animation its hard to see though if you turn on white world, you will be able to see it

**Comment by GreyPupJax** [comment] 2020-04-23 07:19
While in 1.15.2 on pre13 and using SVS v1.27, I have no block breaking textures or block highlights, save specific angles as previously mentioned. Chests and beds do have them, but still no block highlights. I also noticed that using Chocapic13 V8 U the breaking textures are present but grey-scale/inverted, and still no block highlights. I'm running on an GTX 1060.

**Comment by NitrousoxideN2O** [comment] 2020-04-23 15:59
Can confirm, pre13 with NVidia GeForce GTX 1060

**Comment by MastaCoder** [comment] 2020-04-25 21:45
Same issue here, pre13

**Comment by noncom** [comment] 2020-05-02 00:20
Same stuff here, RTX 2080, MC 1.15.2, Forge 31.1.64, optifine pre13, SEUS-1.0.1. Symproms:
- no block damage effect, unless looking under a very sharp angle, and even then it's inverted in color, like it's white crevices instead of dark
- no monster hurt effect (blinking red when hurt)
- spider red glowing eyes are as invisible as the block breaking damage -- the more direct eye-to-eye you have with the spider, the less you see its eyes. But if the spider is turned closer to 90 degrees from looking at you, you can see the trace of the eyes texture
- clouds are pure dark on Fancy settings, with some render issues, like their insides sometimes contain rendering artifacts. I guess the clouds should be white, so it suspiciously looks like the same bug with transparent textures.

All in all I'd say that something is broken for transparency on textures. I'm not sure what exacty but something like maybe texture format or color spaces so that the color information gets inverted, alpha maybe gets broken, and the normals of the normals texture are rotated for some 90 degrees.

**Comment by Deviouslrd** [comment] 2020-05-02 03:00
As far as I know, these are all issues with shaders and optifine, since its all in preview versions.

**Comment by douira** [comment] 2020-05-02 07:58
@Deviouslrd we know these are issues with the shaders and optifine. That's why we're reporting this issue here so the author knows about it and can fix it. (That's the point of previous versions isn't it)

**Comment by marcusnewton** [comment] 2020-05-02 08:31
Capturing more evidence that people are having this problem can't hurt.

**Comment by SirKillz** [comment] 2020-05-03 03:07
Still seems to be present in Pre14

**Comment by briant852** [comment] 2020-05-03 04:07
I have the same issue. Was using sildurs shader lite version on version 1.14 of Minecraft and everything was working fine. Moved over to the latest version and all of a sudden certain details like breaking blocks and attacking mobs don't seem to be showing up. If anyone knows how to fix this it would be greatly appreciated.

**Comment by lulscum** [comment] 2020-05-03 04:54
Same thing with preview OptiFine 1.15.2 HD U G1 pre13 , Sildurs Vibrant Shaders v1.27 

> no block damage effect, unless looking under a very sharp angle, and even then it's inverted in color, like it's white crevices instead of dark

> no monster hurt effect (blinking red when hurt)

> spider red glowing eyes are as invisible as the block breaking damage -- the more direct eye-to-eye you have with the spider, the less you see its eyes. But if the spider is turned closer to 90 degrees from looking at you, you can see the trace of the eyes texture

**Comment by BorisCryptoWave** [comment] 2020-05-03 10:56
Still no block break animation with 1.15.2 pre15

**Comment by Friend-Slayer666** [comment] 2020-05-04 01:49
Just tested it on pre15, no block breaking nor block outline.

**Comment by GreyPupJax** [comment] 2020-05-04 04:32
Ironically enough, in the Optifine twitter screenshot announcing forge compatibility, the player is using Sildurs Shader. I'm guessing the developer either isn't aware of this issue, or presumes its an end-user error. It would be nice to have some acknowledgement that this is in fact a known bug, at the very least.

**Comment by mashirochan** [comment] 2020-05-04 19:20
Block breaking animations are still broken with OptiFine 1.15.2 HD U G1 pre15 and Sildur's Vibrant shaders v1.27 Extreme-Volumetric lighting. Running up to date versions of Fabric and OptiFabric but disabling those and returning to a regular Optifine profile makes no difference.

> 
> 
> Ironically enough, in the Optifine twitter screenshot announcing forge compatibility, the player is using Sildurs Shader. I'm guessing the developer either isn't aware of this issue, or presumes its an end-user error. It would be nice to have some acknowledgement that this is in fact a known bug, at the very least.
> 
> I even loaded up the exact same scenario as the screenshot (Sildurs Vibrant V1.19 medium, Optifine pre14, forge 31.1.63) and it this issue is STILL PRESENT. LOL?!?

How is that in the slightest bit ironic? What does forge compatibility have to do with a known bug not being fixed yet? They didn't title the post "Forge compatibility, 100% bug free!!11" or anything.. This is not a social forum, please keep your childish comments elsewhere.

**Comment by GreyPupJax** [comment] 2020-05-04 21:29
My point was that this *isnt* a confirmed bug by the developers at this point. It has not been addressed. If it has, please kindly direct me to where. Despite the fact that in the scenario present in the screenshot, the issue would've present, nothing has been said. It had nothing to do with it being forge, it was a statement that the person was using Sildurs which is currently broken, without so much as a mention of it.

**Comment by seeruk** [comment] 2020-05-05 08:21
Both of y'all are making pointless comments really. I'm almost certain sp is aware of the issue, I'm sure he's looked through these comments himself, and it's been mentioned on Discord countless times. He's just busy working on fixing this and the many other remaining bugs. There are a ton of bugs not "confirmed" by sp, some that have been fixed too.

One thing I would say @GreyPupJax is that you are using a version of OptiFine that doesn't officially support Forge there in your other comment, and you're using a version of Sildur's Vibrant shaders that's 8 versions behind - it's always a good idea to confirm you're experiencing an issue with the most up-to-date versions of the relevant software, and that there are no obvious reasons why something wouldn't work (though in this case, it still doesn't work with or without forge, on the latest Sildur's Vibrant shaders, and the latest OptiFine pre-release).

**Comment by GreyPupJax** [comment] 2020-05-06 06:56
I know to use the most current versions of everything, and I do. Again, my point was that was what the *dev* was using in their screenshot. Its really not even that big of a deal, I'm just confused why they haven't made any mention of it at this point seeing as its been almost a month.

**Comment by LarkspurBetula** [comment] 2020-05-08 17:27
anyone find a fix to this problem?

**Comment by SmolKidd** [comment] 2020-05-11 21:03
Got the exact same issues. Also couldn't see the fishing line on a thrown fishing rod,, which was weird as well. Medium shaders with OptiFine 1.15.2 HD U G1 pre16.

**Comment by soloHolo** [comment] 2020-05-18 12:39
I'm having this issue using pre17 with sildurs shaders

**Comment by BorisCryptoWave** [comment] 2020-05-19 17:02
Still having the issue with pre18

**Comment by FireController1847** [comment] 2020-05-20 02:59
Getting this issue with SEUS Remastered 1.0.1, so I'm not sure it's exclusive to Siluders (OptiFine 1.15.2 pre18)

**Comment by Deviouslrd** [comment] 2020-05-20 03:01
It is not limited/exclusive to sildur's, since it is a optifine bug. I think almost every shaderpack has this issue, unless a workaround has been achieved in some.

**Comment by ChipmunkV** [comment] 2020-05-23 09:37
I've noticed that the usual thin black rectangle that highlights the "bounding box" of the block is sometimes missing too. It coincides with not seeing the block-breaking if you start breaking the block. But when you see the bounding box the block-breaking is seen too, the breakage has some wrong color (during the day it saturates to white).

(using SEUS-Renewed-v1.0.1 shaders)

P.S. what the hell? Do you really live like animals here without the source code for the mod? With source code it takes about only a day to at least identify a problem like that even if you know nothing about minecraft. Come on! Is it Microsoft again with its territorial bullshit?

**Comment by seeruk** [comment] 2020-05-23 10:32
@ChipmunkV OptiFine is closed-source. This repository is just used as an issue tracker. It's a fairly common way of gathering issues without having to use something else like JIRA - a lot of developers already have GitHub accounts anyway.

**Comment by NitrousoxideN2O** [comment] 2020-05-24 07:53
@ChipmunkV Optifine actually has to be closed source according to the EULA as it contains parts of Minecraft's native graphics engine

**Comment by ChipmunkV** [comment] 2020-05-24 16:00
It looks like Optifine calls **gbuffers_textured** fragment shader instead of the **gbuffers_damagedblock**. The **gbuffers_textured** shader renders into the depth buffer, but in place of the depth buffer Optifine has supplied the composite buffer (which creates holes in the blocks and we see the sky through the cracks).

The cracks themselves aren't always rendered because of some problem with glPolygonOffset() function (the one that allows the decals to hang slightly above the polygons). It's called like glPolygonOffset(-1, -10), but to make the cracks stand out from any angle only glPolygonOffset(-1, -10000) worked.

@seeruk I'm talking about this specific bug. For this one it takes a day to identify. (things can take long, or they may not; but with the source you'll know more precisely how much)

@NitrousoxideN2O that's what I called Microsoft's bullshit.

**Comment by FireController1847** [comment] 2020-05-24 16:13
> @NitrousoxideN2O that's what I called Microsoft's bullshit.

This is a discussion for somewhere outside of this thread. Let's focus on the actual issue, shall we?

**Comment by ChipmunkV** [comment] 2020-05-24 16:30
@FireController1847 don't quote me on that question. Better focus the critique on people whose entire comments are dedicated to that question instead of the issue.

**Comment by FireController1847** [comment] 2020-05-24 16:36
@ChipmunkV First of all, if you don't want to be quoted on it don't say it. Second of all, this has nothing to do with the issue. Issues have been locked and closed because they waste time discussing about something that the owner has made clear isn't going to be changed. I'd rather have this issue fixed and then closed, without being locked and closed prematurely. Even small comments like that continue the debate in a form, even if the majority of your message was about the actual issue. Just leave it out entirely and discuss it in another issue.

**Comment by ChipmunkV** [comment] 2020-05-24 16:53
Can get correct cracks in the first type of block when not touching the depth buffer in the shader, but not for the others: in the same scene cobblestone breaks fine, but not planks and dirt.

@FireController1847 I can't omit the context. Three people have found their favorite topic in my footnote and started a hypocrisy contest. Stop trolling me, just let it go.

**Comment by Phoenixdotexe** [comment] 2020-06-06 22:59
> 
> 
> It looks like Optifine calls **gbuffers_textured** fragment shader instead of the **gbuffers_damagedblock**. The **gbuffers_textured** shader renders into the depth buffer, but in place of the depth buffer Optifine has supplied the composite buffer (which creates holes in the blocks and we see the sky through the cracks).
> 
> The cracks themselves aren't always rendered because of some problem with glPolygonOffset() function (the one that allows the decals to hang slightly above the polygons). It's called like glPolygonOffset(-1, -10), but to make the cracks stand out from any angle only glPolygonOffset(-1, -10000) worked.
> 
> @seeruk I'm talking about this specific bug. For this one it takes a day to identify. (things can take long, or they may not; but with the source you'll know more precisely how much)
> 
> @NitrousoxideN2O that's what I called Microsoft's bullshit.

So I'm playing on 1.12.2 with OptiFine 1.12.2 HD U F5 and if I use SEUS remastered the only problem I have is that I can see the sky through the cracks in some blocks (I think it only happens with wood blocks)

Is there a way to fix this?

**Comment by seeruk** [comment] 2020-06-07 08:08
Hey @Phoenixdotexe, you might want to open a separate issue for this? It could be a bug with the shaders, or maybe with OptiFine - this issue is specifically for 1.15, and specifically about no block-breaking animations. It sounds like you're having a different issue.

**Comment by sp614x** [comment] 2020-06-07 16:38
The animation is fixed to use correct program in pre23.
Sildur's Vibrant still have problems with the UV mapping, to be fixed.

**Comment by sp614x** [comment] 2020-06-12 14:58
The block break blocking animation with bump/parallax mapping is fixed in pre24.
The breaking animation on block entities (chests, signs, ...) is still not working. In 1.15 the block entities use the entity vertex format, not the block vertex format as it was in 1.14. The entity format doesn't have extended attributes yet.

**Closed** 2020-06-13 09:40 UTC
Labels: 1.15, bug, shaders

**Comment by SafetyInPillsSophie** [comment] 2025-05-25 02:10
This is still happening in 1.21.1 and I have been losing my mind trying to figure out how to fix it for like a week and a half lol
