### ISSUE TITLE
[Category] Crash with Forge Optifine and one mod

### ISSUE THREAD

**Issue by benten2000** [sp614x/optifine#7050] opened 2022-08-03 12:54 UTC
## Description of Issue
Game crashes with Optifine installed when added to the latest Direwolf20 1.18.2 pack, hopefully narrowed it down to with only one mod installed when it keeps happening.

## Steps to Reproduce
Fresh Minecraft, forge and this mod with optifine installed and run.

## OptiFine Version
OptiFine_1.18.2_HD_U_H7

## Installation Method
Clean install of Minecraft 1.18.2, latest Forge 40.1.68, with optifine and the possible problematic mod valhelsia_core-forge-1.18.2-0.4.0

## Fabric/Forge Version
Forge 40.1.68

## Other Installed Mods
valhelsia_core-forge-1.18.2-0.4.0

## Log Files/Crash Reports
https://pastebin.com/y6W5L6gJ

## Prior Testing
Game loads fine with Optifine installed if valhelsia_core-forge-1.18.2-0.4.0 (mod is needed for Forbidden and Arcanus)

**Comment by labradoe** [comment] 2022-08-08 16:56
Duplicate of #7009. It doesn't matter what mods you're running. Optifine is crashing up world load with Forge versions above 40.1.58.

**Comment by sp614x** [comment] 2022-08-23 11:08
Fixed in latest preview.

**Closed by sp614x** 2022-08-23 11:08 UTC
Labels: forge, crash, 1.18
