### ISSUE TITLE
when i die im unable to respawn

### ISSUE THREAD

**Issue by AquaAzul** [sp614x/optifine#5888] opened 2021-06-27 00:23 UTC
## Description of Issue
when i die in survival and i press the "respawn" button but it greys out for a bit before going back to normal as if i didnt press it. ive tried pressing it multiple times, but it doesnt work. i end up having to exit to the title screen and reloading the world

## Steps to Reproduce
1. die in survival (i was using /kill and with keep inventory on)
2. press the respawn button
## OptiFine Version
1.17

## Installation Method
installed through the website and clicking on the instalation 

## Log Files/Crash Reports
it didnt crash

## Prior Testing
i didnt test this

![2021-06-26_21 51 56](https://user-images.githubusercontent.com/86539387/123529239-f3fa4300-d6c8-11eb-8d5a-885e4720bfc0.png)

**Comment by KaiAF** [comment] 2021-06-27 00:26
I tried this on the latest preview version (pre 23) and it works just as intended.

**Comment by KaiAF** [comment] 2021-06-30 20:48
closing as I cant reproduce this, and no one else has this issue.

**Closed by KaiAF** 2021-06-30 20:48 UTC
Labels: 1.17, details needed, not reproducible
