### ISSUE TITLE
[1.13 beta3/beta4] OpenGL Error Log Spam

### ISSUE THREAD

**Issue by Artur96** [sp614x/optifine#1734] opened 2018-08-30 20:18 UTC
The game log keeps on getting spammed with the following:
```
[21:00:18] [main/ERROR]: [Shaders] OpenGL error: 1281 (Invalid value), program: gbuffers_water (none), at: pre-useProgram
[21:00:18] [main/INFO]: OpenGL debug message, id=1281, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_VALUE error generated. neither <first> nor <count> can be negative.
[21:00:18] [main/INFO]: OpenGL debug message, id=1281, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_VALUE error generated. neither <first> nor <count> can be negative.
[21:00:18] [main/INFO]: OpenGL debug message, id=1281, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_VALUE error generated. neither <first> nor <count> can be negative.
```
After around thirty minutes of gameplay, the log file grows to over a gigabyte in size!
Also, the game seems to freeze for a few seconds and proceed to crash after a random amount of time,  with no crash log.
I know this may not be helpful, but I don't know where to look for more verbose information.

I am using the built-in shaders with PureBDcraft x256 texture pack.

**Comment by sp614x** [comment] 2018-09-05 12:14
Tested PureBDcraft + internal shaders, works OK, no OpenGL errors.
Does this happen without shaders?

**Comment by Artur96** [comment] 2018-09-05 13:34
Turns out the issue occurs when using the PureBDcraft texture pack. Shaders being on or off doesn't affect this.
Setup as printed by the mod:
```
[14:22:39] [main/INFO]: LWJGL Version: 3.1.6 build 14
[14:22:40] [main/INFO]: [OptiFine] 
[14:22:40] [main/INFO]: [OptiFine] OptiFine_1.13_HD_U_E3_beta4
[14:22:40] [main/INFO]: [OptiFine] Build: 20180829-225136
[14:22:40] [main/INFO]: [OptiFine] OS: Linux (amd64) version 4.18.5-arch1-1-ARCH
[14:22:40] [main/INFO]: [OptiFine] Java: 1.8.0_181, Oracle Corporation
[14:22:40] [main/INFO]: [OptiFine] VM: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
[14:22:40] [main/INFO]: [OptiFine] LWJGL: 3.3.0 X11 GLX EGL clock_gettime evdev shared
[14:22:40] [main/INFO]: [OptiFine] OpenGL: GeForce GTX 1070/PCIe/SSE2, version 4.6.0 NVIDIA 396.54, NVIDIA Corporation
[14:22:40] [main/INFO]: [OptiFine] OpenGL Version: 4.6.0
[14:22:40] [main/INFO]: [OptiFine] Maximum texture size: 32768x32768
[14:22:40] [VersionCheck/INFO]: [OptiFine] Checking for new version
[14:22:40] [main/INFO]: [Shaders] ShadersMod version: 2.4.12
[14:22:40] [main/INFO]: [Shaders] OpenGL Version: 4.6.0 NVIDIA 396.54
[14:22:40] [main/INFO]: [Shaders] Vendor:  NVIDIA Corporation
[14:22:40] [main/INFO]: [Shaders] Renderer: GeForce GTX 1070/PCIe/SSE2
[14:22:40] [main/INFO]: [Shaders] Capabilities:  2.0  2.1  3.0  3.2  4.0 
[14:22:40] [main/INFO]: [Shaders] GL_MAX_DRAW_BUFFERS: 8
[14:22:40] [main/INFO]: [Shaders] GL_MAX_COLOR_ATTACHMENTS_EXT: 8
[14:22:40] [main/INFO]: [Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 32
```

**Comment by sp614x** [comment] 2018-09-05 14:28
Maybe a linux issue
`OS: Linux (amd64) version 4.18.5-arch1-1-ARCH`

**Comment by Tadruien** [comment] 2018-09-08 00:16
Happens to me on Windows 10, so it is not just a linux issue. Happens with 64, 128 and 256 PureBDcraft

Been happening to me since Beta 4, on Beta 7 now and issue still here.

Does not make a difference whether shaders are on or off. 

```
[18:07:36] [main/INFO]: LWJGL Version: 3.1.6 build 14
[18:07:37] [main/INFO]: [OptiFine] 
[18:07:37] [main/INFO]: [OptiFine] OptiFine_1.13.1_HD_U_E3_beta7
[18:07:37] [main/INFO]: [OptiFine] Build: 20180907-181839
[18:07:37] [main/INFO]: [OptiFine] OS: Windows 10 (amd64) version 10.0
[18:07:37] [main/INFO]: [OptiFine] Java: 1.8.0_162, Oracle Corporation
[18:07:37] [main/INFO]: [OptiFine] VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[18:07:37] [main/INFO]: [OptiFine] LWJGL: 3.3.0 Win32 WGL EGL VisualC DLL
[18:07:37] [main/INFO]: [OptiFine] OpenGL: GeForce GTX 1070/PCIe/SSE2, version 4.6.0 NVIDIA 397.93, NVIDIA Corporation
[18:07:37] [main/INFO]: [OptiFine] OpenGL Version: 4.6.0
[18:07:37] [main/INFO]: [OptiFine] Maximum texture size: 32768x32768
[18:07:37] [VersionCheck/INFO]: [OptiFine] Checking for new version
[18:07:37] [main/INFO]: [Shaders] OpenGL Version: 4.6.0 NVIDIA 397.93
[18:07:37] [main/INFO]: [Shaders] Vendor:  NVIDIA Corporation
[18:07:37] [main/INFO]: [Shaders] Renderer: GeForce GTX 1070/PCIe/SSE2
[18:07:37] [main/INFO]: [Shaders] Capabilities:  2.0  2.1  3.0  3.2  4.0 
[18:07:37] [main/INFO]: [Shaders] GL_MAX_DRAW_BUFFERS: 8
[18:07:37] [main/INFO]: [Shaders] GL_MAX_COLOR_ATTACHMENTS_EXT: 8
[18:07:37] [main/INFO]: [Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 32
[18:07:37] [main/INFO]: [Shaders] Load shaders configuration.
[18:07:37] [main/INFO]: [Shaders] No shaderpack loaded.
[18:07:38] [VersionCheck/INFO]: [OptiFine] Version found: E3_beta7
[18:07:38] [main/INFO]: Reloading ResourceManager: Default, PureBDcraft 256x MC113.zip
[18:07:38] [main/INFO]: [OptiFine] *** Reloading textures ***
[18:07:38] [main/INFO]: [OptiFine] Resource packs: PureBDcraft 256x MC113.zip

...

[18:07:59] [main/INFO]: OpenGL debug message, id=1281, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_VALUE error generated. neither <first> nor <count> can be negative.
[18:07:59] [main/INFO]: OpenGL debug message, id=1281, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_VALUE error generated. neither <first> nor <count> can be negative.
[18:07:59] [main/INFO]: OpenGL debug message, id=1281, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_VALUE error generated. neither <first> nor <count> can be negative.
[18:07:59] [main/INFO]: OpenGL debug message, id=1281, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_VALUE error generated. neither <first> nor <count> can be negative.
[18:07:59] [main/INFO]: OpenGL debug message, id=1281, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_VALUE error generated. neither <first> nor <count> can be negative.
[18:07:59] [main/INFO]: OpenGL debug message, id=1281, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_VALUE error generated. neither <first> nor <count> can be negative.
[18:07:59] [main/INFO]: OpenGL debug message, id=1281, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_VALUE error generated. neither <first> nor <count> can be negative.
```

**Comment by pau101** [comment] 2018-09-10 04:09
I've just experienced this as well (win10), and have made a minimal resource pack
 that reproduces this issue: [Issue #1734 Reproduction.zip](https://github.com/sp614x/optifine/files/2365096/Issue.1734.Reproduction.zip) (Only contains a dirt overlay over stone)

Entering a standard world with this pack produces the log messages as reported above.

**Comment by sp614x** [comment] 2018-09-14 12:29
The test resource pack works for me, no errors generated.

**Comment by pau101** [comment] 2018-09-14 17:36
I checked in beta8 and same issue occurs.
I also took a closer look at the error logging code and noticed an error in `Config#checkGlError`, that is resulting in the "location" not being included in the message, which would be helpful here.
```java
String messageLog = String.format("OpenGL error: $s (%s), at: %s", errorCode, errorText, loc);
```
So of course `$s` should be `%s`.

**Comment by christofin** [comment] 2018-09-17 20:02
Looks like the same issue is occurring in Beta9 and Pre-1. No texture packs, I'm only using the latest version of Sildur's Vibrant Shaders (Extreme + No Volumetric lighting). Haven't tried anything else yet. Specific version is 1.172.

**Comment by chland** [comment] 2018-10-02 08:04
There seems to be a similar issue with a different error: https://github.com/sp614x/optifine/issues/1831

This whole log-spamming is pretty bad as it generates hundreds of thousands of errors in the log-file until you run out of diskspace.

**Comment by sp614x** [comment] 2018-10-18 14:39
Should be fixed in pre8.The OpenGL errors spamming the log is fixed in pre8.
The errors in pre8 come with a stack trace so there is a higher chance that their source can be fixed.

**Closed by sp614x** 2018-10-18 14:39 UTC
Labels: 1.13, details needed, shaders
