### ISSUE TITLE
[1.15.2] [CIT] Custom Models and Armor

### ISSUE THREAD

**Issue by TheJumper99** [sp614x/optifine#3602] opened 2020-03-28 13:30 UTC
## Description of Issue
Custom models of Items only show the scale parrametas in the inventory. Every other feature dosn't work. Also Armor textures don't show up. only the Item Textures

## Steps to Reproduce
I fond it in my own pack but look at Itembond:
https://www.curseforge.com/minecraft/texture-packs/itembound-16x

## OptiFine Version
1.15.2 pre 10

## Installation Method
Installer

**Comment by CalamityGreen** [comment] 2020-03-30 18:30
Same thing

**Comment by ThatsCube** [comment] 2020-04-06 16:39
Same problem, **custom textures (cit)** are not displayed **when worn (for armor)** while in the inventory they can be seen. I also have another problem, when the **base object is a player's head**, you **only see the icon** and when it is held in **your hand you see the head and not the modified texture.** I hope it is because it is still a "beta" version of Optifine.

**Comment by VoxPopuliZombiemold** [comment] 2020-05-03 15:49
I just wanted to contribute and add that I am also experiencing the above issue with armor, and am a bit surprised this issue has made it this far into the dev builds, especially considering the completion percentage.

Anyway, keep up the great work. I hugely appreciate the work behind Optifine.

**Comment by Helwdrokin** [comment] 2020-05-12 10:46
apparently elytra textures work normally. only the armor textures have a problem

**Comment by bloggy** [comment] 2020-05-12 18:02
For me custom models only work when you have it in inventory. In your hand it's not showing correctly:
https://i.imgur.com/QMgOWtv.png

**Comment by realjackasterisk** [comment] 2020-05-17 20:34
Duplicate of #3588.

**Closed by realjackasterisk** 2020-05-17 20:34 UTC

**Comment by MindCreeper03** [comment] 2020-05-26 13:47
> 
> 
> Same problem, **custom textures (cit)** are not displayed **when worn (for armor)** while in the inventory they can be seen. I also have another problem, when the **base object is a player's head**, you **only see the icon** and when it is held in **your hand you see the head and not the modified texture.** I hope it is because it is still a "beta" version of Optifine.

This is because armor actually has 2 textures, one being the item texture and another being the layer texture. The layered texture is then used with a file called e.g. lapis_helmet_**layer**.properties. The armor is usually on 2 layers.
