### ISSUE TITLE
[1.21.1 Bug] Settings menu is buggy and unresponsive

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#7751] opened 2024-09-15 00:30 UTC
## Description of Issue
The 1.21.1 OptiFine previews have an issue where the settings menu isn't updated in real time, causing a desync where you have to wait a while after changing a setting before closing the settings menu for the setting to actually be changed. This is most apparent when attempting to change the render distance.

## Steps to Reproduce
1. Open Minecraft
2. Attempt to change render distance and then close the menu within a reasonable time
3. Note how the setting has not changed

## OptiFine Version
OptiFine 1.21.1_HD_U_J1_pre12

## Video demonstration

https://github.com/user-attachments/assets/7a4487dc-e0a7-4fab-9d8b-7be407c77a12

**Comment by Lolothepro** [comment] 2024-09-15 09:47
duplicate of https://github.com/sp614x/optifine/issues/7675

**Comment by sp614x** [comment] 2024-09-15 11:44
Duplicate of #7675

**Closed by sp614x** 2024-09-15 11:44 UTC
