### ISSUE TITLE
why do my shaders look like this?

### ISSUE THREAD

**Issue by vobrant** [sp614x/optifine#7494] opened 2023-07-20 10:20 UTC
![image](https://github.com/sp614x/optifine/assets/140066815/ee4a1902-b8f9-4af5-8bf4-dc72794a27c3)
when i enable my shaders they look like this , im currently using mods in this screenshot so im assuming maybe its a mod thats doing it but i'd like to know if its mnot and how i can fix it

**Comment by Regnander** [comment] 2023-07-21 20:33
This looks like the same problem at #7384

**Comment by Jiingy** [comment] 2023-07-29 04:41
Duplicate of https://github.com/sp614x/optifine/issues/7384

**Closed by Jiingy** 2023-07-29 04:41 UTC
Labels: duplicate
