### ISSUE TITLE
[REQUEST] Random Entities NBT-Tag

### ISSUE THREAD

**Issue by E-T-31** [sp614x/optifine#6482] opened 2021-12-15 23:10 UTC
Hey,
I recently tried to create sheep that keep their color when sheared (instead of all of them being white).
![colored_sheared_sheep](https://user-images.githubusercontent.com/84208813/146277678-9a504daf-32f9-49ce-b64a-19d140690f24.png)

I created the textures & all, but sadly couldn't find a way to implement them based on the sheep's color. That's why I suggest to add a "nbt.\<tag>=\<value>" property that could access the NBT-tags of an entity (i.e. "Color" for the sheep in this case), as is the case with "Custom Items".

Alternatively, a property "woolColors.\<n>=\<colors>" could work pretty much the same as "collarColors.\<n>=\<colors>" already does for "Random Entities" and serve the same purpose.

Thanks for your time & work.
Regards, E_T_31.

Edit: Check out #6481 for a compiled list

**Comment by ewanhowell5195** [comment] 2021-12-15 23:17
duplicate of #6481

**Closed** 2021-12-16 00:09 UTC
