### ISSUE TITLE
Crash occurred within the shader mod

### ISSUE THREAD

**Issue by DuelMonster** [sp614x/optifine#283] opened 2016-10-02 20:08 UTC
[crash-2016-10-01_22.34.51-client.txt](https://github.com/sp614x/optifine/files/505222/crash-2016-10-01_22.34.51-client.txt)

**Comment by frebib** [comment] 2016-10-16 13:42
This is caused by the Malisis Doors versions compatible with 1.10. As far as I know it's in the process of being fixed. In the meanwhile MalisisDoors v5.0.4 & MalisisCore 4.1.1 work fine in 1.10 despite being built for 1.9.4

**Comment by sp614x** [comment] 2016-10-17 14:52
Duplicate of #295.

**Closed by sp614x** 2016-10-17 14:52 UTC
Labels: mods, shaders
