### ISSUE TITLE
Suggestion: Biome Specific CEM models

### ISSUE THREAD

**Issue by r543** [sp614x/optifine#849] opened 2017-08-17 20:42 UTC
I guess this would be a addon to Random Skins, probably done via a .properties file.
You'd be able to set Biome specific skins to Mobs, those get set on spawn/birth of them, this way you could have desert camouflaged Creepers and Spiders for example or theme certain skins towards certain biomes without them looking out of place if randomly spawned in other environments.

**Comment by MisterQuiggly** [comment] 2017-08-17 22:19
You already can have biome specific mob textures

**Comment by r543** [comment] 2017-08-17 22:41
Oh, sorry, wasn't aware of that but thought it might be, sorry. Did read about it now in the documentation, sweet that we have this, wonder if the same is possible for custom models through.

**Comment by r543** [comment] 2017-08-18 12:22
Thanks for the title change sp614x

**Comment by Coolboy21** [comment] 2017-08-18 19:00
Duplicate of #572?

**Comment by sp614x** [comment] 2017-08-18 20:28
Yes, duplicate of #572

**Closed by sp614x** 2017-08-18 20:28 UTC
Labels: CEM, enhancement
