### ISSUE TITLE
[Feature request] Shared texture maps between blocks

### ISSUE THREAD

**Issue by JsMarq96** [sp614x/optifine#5086] opened 2020-12-04 20:33 UTC
A lot of the blocks on the resourcepacks share the same normal and specular maps, so maybe a config file like the one that Mojang has enabled on Bedrock([https://help.minecraft.net/hc/en-us/articles/360051308931-Minecraft-Texture-Set-Documentation](url)) could be nice, taking into account that some resource packs are quite heavy, both on size and GPU memmory.
I don't know it this has already been discussed, I could not find it on the issues!

**Comment by Luracasmus** [comment] 2020-12-04 21:01
Similar to #4564

**Comment by sp614x** [comment] 2020-12-22 17:17
Duplicate of #4564

**Closed by sp614x** 2020-12-22 17:17 UTC
