### ISSUE TITLE
[Misc] Killing tamed parrots crash the game

### ISSUE THREAD

**Issue by BogdanBosoi** [sp614x/optifine#4317] opened 2020-07-10 12:31 UTC
## Description of Issue
When killing tamed parrots the game crashes (the world is saved then the client closes automatically).
Tried killing the parrot with the sword and with lava / fire damage.

## Steps to Reproduce
1. Spawn a parrot (egg or command, step 2 can be skipped if you spawn the parrot automatically tamed)
2. Tame the parrot
3. Kill the parrot

## OptiFine Version
OptiFine 1.16.1 HD U G2 pre2

## Installation Method
Used the standalone installer on Minecraft 1.16.1 (No mods or used other variants for forge / fabric)

## Log Files/Crash Reports
Log file: [2020-07-10-5.log](https://github.com/sp614x/optifine/files/4903037/2020-07-10-5.log)
Crash report file: [crash-2020-07-10_15.15.42-client.txt](https://github.com/sp614x/optifine/files/4903039/crash-2020-07-10_15.15.42-client.txt)

## F3 Debug Screenshot
![2020-07-10_15 15 38](https://user-images.githubusercontent.com/37671547/87153773-acfd1d00-c2c0-11ea-9f17-325fa4a830b0.png)

The screenshot is taken right after the parrot was killed. After ~0.5 seconds the game crashed.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No, the bug doesn't happen on Vanilla Minecraft.
- Does this happen in OptiFine standalone?
I don't tried with optifabric or on other means that are not the equivalent to installing OptiFine with the standalone installer.
- Does this happen in Vanilla without OptiFine?
No, this doesn't happen on vanilla Minecraft

## Additional Information
This is what I think:
Judging by the type of error (NullPointerException) and the fact that it crashes in the call stack on some shoulder method it seems that it may try checking for all tamed entities and which of them stands on the player's shoulder, but because that list might be empty, it throws some loved null pointer errors.

**Comment by sp614x** [comment] 2020-07-10 12:33
Duplicate of #4214

**Closed by sp614x** 2020-07-10 12:33 UTC
