### ISSUE TITLE
[1.7] Shiny Potions with Fast Render!

### ISSUE THREAD

**Issue by Batman5300** [sp614x/optifine#745] opened 2017-07-03 22:22 UTC
Hey, I was wondering if there was a way you could get rid of the shiny potions **with** fast render on in 1.7.x. I know a lot of people have made videos about this and state its a bug in Optifine 1.7 and say to turn off fast render to remove the shiny potions, but I wanted to know if there was another way to get rid of the shiny potions instead of turning fast render off in order for the people who don't have the type graphics card, like myself, have the potions glint texture without covering the whole inventory slot.
(Shiny Potions Example: http://imgur.com/a/VJwg4) 

Well, a Minecraft PvPer named, Fyu made a mod called Shiny Pots in order for some graphic cards, that can have no shiny potions with fast render on, in order for them to have shiny potions. But to the people who have shiny pots with fast render on and with Fyu's Shiny Pots Mod, it does remove the shiny potions, but there is no more enchanted glint texture like everything that is enchanted default (Golden [Notch] apple, potions, enchantment books, etc.) will look exactly the same but without the enchanted glint texture.
(Example: https://vid.me/WeB0)

EDIT: Apparently six months ago, somebody else experienced this as well, based on the link below, and @sp614x mentioned that he could back port the fix to 1.7.x, but he didn't and only fixed the bug. Now I am not saying its his fault for causing this, but I just think he forgot to, Hopefully, he will backport it once he sees this post!

#409
[https://github.com/sp614x/optifine/issues/409](url)

**Comment by trollworkout** [comment] 2017-07-04 04:36
yeah this is still happening . disable fast render fixed the issue.

**Comment by Batman5300** [comment] 2017-07-04 06:51
@trollworkout, I acknowledge that this is still happening and I now fast render disables fixes this issue, but I just want to know if there is a another way to disable it with enabling fast render or make @sp614x fixed this bug.

**Comment by trollworkout** [comment] 2017-07-04 07:15
@Batman5300  not that I know of.  You can also disable the glint altogether and re-enable fast render.

**Comment by sp614x** [comment] 2017-07-04 07:19
So far I can't reproduce the problem. 
Testing Forge #1614 + OptiFine preview E3 and the enchanted items are OK with Fast Render ON or OFF. 
There was another case for this bug when Vignette is OFF, but this also works correctly.

**Comment by trollworkout** [comment] 2017-07-04 11:08
@sp614x  1.7.10  Forge 1614 Optifine 1.7.10 HD u D8 (this is the latest link provided) it is reproduceable 

![image](https://user-images.githubusercontent.com/6987027/27827778-f7c81d20-6086-11e7-95df-a9462deb8b9a.png)

![image](https://user-images.githubusercontent.com/6987027/27827907-847b9198-6087-11e7-8f6c-d559ce5437e5.png)

**Comment by trollworkout** [comment] 2017-07-04 11:14
but also in the preview E3 notice the background 

![image](https://user-images.githubusercontent.com/6987027/27828090-72cfe13c-6088-11e7-9ec5-2e0033b1adbc.png)

**Comment by sp614x** [comment] 2017-07-04 11:16
Which other mods are installed?

**Comment by trollworkout** [comment] 2017-07-04 11:34
@sp614x  I have a shit ton but is not the mods. It does the same thing with other mods. Is optifine doing it for some reason I am not sure exactly why or how. You might have a different built for E3

**Comment by sp614x** [comment] 2017-07-04 12:11
Still can you reproduce it with Forge + OptiFine only?
Does resetting video settings help (it can be something else in combination with Fast Render)?

**Comment by sp614x** [comment] 2017-07-04 13:28
Tested with OptiFine D8 for 1.7.10, everything OK with Fast Render ON and OFF.
This is probably a conflict with some of the installed mods.

**Comment by Batman5300** [comment] 2017-07-04 16:53
@sp614x In your graphics card, you see it perfectly fine either Fast Render ON and OFF, but there are some graphics cards, like NVIDIA, will produce this bug, I don't believe its one of @trollworkout's installed mods, its a thing without mods.

**Comment by Batman5300** [comment] 2017-07-04 17:06
![2017-07-04_10 01 58](https://user-images.githubusercontent.com/20810419/27838525-1afb910a-60a0-11e7-8143-2b5ef18634a2.png)

![2017-07-04_10 03 43](https://user-images.githubusercontent.com/20810419/27838533-247c4abc-60a0-11e7-8e34-4e919abf1219.png)

As you can see in this screenshot, this is Vanilla Minecraft with no mods, and the potions do not have the enchanted glint all over it while in the second screenhot you can see the potions' enchanted glint is all over it.

**Comment by trollworkout** [comment] 2017-07-04 18:52
@Batman5300  @sp614x  I'm on NVIDIA. I was reading in a different post there's something to do with FXAA  ? I am not sure exactly. It only does it for certain items  for example books are unaffected but most potions are.

**Comment by Batman5300** [comment] 2017-07-04 21:22
![minecraft 07 04 2017 - 14 19 53 01](https://user-images.githubusercontent.com/20810419/27842997-0a9060b0-60c4-11e7-9a39-849c7d0021e1.png)

This is what it looks like with reset video settings with fast render off in Minecraft 1.7.10,

![minecraft 07 04 2017 - 14 20 06 02](https://user-images.githubusercontent.com/20810419/27843003-22a72698-60c4-11e7-8b47-7a4a32505c08.png)
 
This is what it looks like with reset video settings with fast render on in Minecraft 1.7.10.

**Comment by trollworkout** [comment] 2017-07-04 21:51
@Batman5300  click on Shader I wanna see what video card is being reported  and what driver version you got

**Comment by sp614x** [comment] 2017-07-04 22:27
@Batman5300 Linux?

**Comment by Batman5300** [comment] 2017-07-04 23:17
![minecraft 07 04 2017 - 16 13 46 03](https://user-images.githubusercontent.com/20810419/27844257-c8ac0cb6-60d3-11e7-8aaf-bd29e020e50a.png)

We are using the same graphics card, but I am not using the Ti version.

@sp614x, no I am not using a Linux computer. My computer is Windows 10 64 bit. Also, here is the manual crash details that you were asking for,
  
[https://pastebin.com/VqhNmyM6](url)

**Comment by trollworkout** [comment] 2017-07-05 02:23
@Batman5300  Exactly same card and exactly same driver and exactly same issue with Optifine.   Ti is simply a slightly faster overlocked version so it doesn't really matter.

@sp614x  That might narrow it down. Perhaps something to do with this?

**Comment by sp614x** [comment] 2017-07-05 06:59
@trollworkout are other OptiFine versions also affected (1.8.x, 1.9.x, ...)?

**Comment by Batman5300** [comment] 2017-07-05 07:24
@sp614x Other versions are not affected, its only 1.7.x. Also, I have the latest version of Nvidia GTX 1050 driver, and for me updating or downgrading my drivers did nothing, I still get shiny potions.

**Comment by sp614x** [comment] 2017-07-05 08:28
@Batman5300 reset all settings in the Nvidia control panel to "Default/Application controlled"?

**Comment by Batman5300** [comment] 2017-07-05 17:14
@sp614x, I have reset all my settings in the Nvidia control panel in Default/Application controlled, but I still get shiny potions. If you can fix this bug in later versions, I know they have different code systems I acknowledge that, you should be able to fix it in 1.7.x.

**Comment by sp614x** [comment] 2017-07-05 20:38
Managed to reproduce it on Nvidia:

![image](https://user-images.githubusercontent.com/16635441/27883923-a4b4311c-61d2-11e7-857f-d469da34fa8b.png)

**Comment by trollworkout** [comment] 2017-07-05 20:57
oh i just noticed I'm ALSO on the Windows 10 64 bit version  too many coincidences to be coincidences. Is deff something to do with Windows 10 or Nvidia card

**Comment by Batman5300** [comment] 2017-07-05 21:23
@sp614x If you are able to produce it on Nvidia, you should be able to know to not produce it,

@trollworkout I don't believe its about our PC because I experienced this in Windows 7 as well before I upgraded my computer last year,

**Comment by sp614x** [comment] 2017-07-05 22:02
When rendering multi-layer items (potions, leather armor, spawn eggs) MC 1.7.x uses a dummy pre-render pass with unusual transparency options (everything disabled). The dummy pass is not present in 1.6.x and in 1.8.x. It has no visual effect and when it is removed the Fast Render works corectly (almost). Looks like some test code made it to production and nobody noticed.

**Comment by sp614x** [comment] 2017-07-05 23:06
Managed to fix the potions with a little hack, the glint effect is still a little bit brighter when Fast Render is enabled.

Fast Render OFF:
![image](https://user-images.githubusercontent.com/16635441/27888207-2404d48c-61e5-11e7-8316-84ab40c0c948.png)

Fast Render ON:
![image](https://user-images.githubusercontent.com/16635441/27888220-345f63ec-61e5-11e7-9314-b35cb0462c01.png)

The problem seems to be NVidia specific and most probably only in recent drivers as Fast Render was working correctly on NVidia when 1.7.10 was released in 2014. 

The potion rendering in 1.7.x is quite complicated and different than 1.6.x and 1.8.x which use a simpler method. This explains why only 1.7.x is affected.

**Comment by trollworkout** [comment] 2017-07-05 23:22
@sp614x  That's great news! I actually like the slightly brighter  Fast Render ON version better 😆 1.7.10 is pretty broken when it comes to rendering . There are many issues that were fixed in newer versions of MC

**Comment by sp614x** [comment] 2017-07-05 23:42
Updated preview E3 for 1.7.10 and F3 for 1.7.2 
- fixed potion glint with Fast Render on NVidia

**Closed by sp614x** 2017-07-05 23:42 UTC

**Comment by GodlessNoob** [comment] 2020-12-07 05:21
Well its not a optifine bug it's a coding bug the mod was not properly coded with optifine
Because of the fast render or the cards could be misbehaving with the mod when I have seen the code there were little problem the code was used ASM4 and ASM5 the code could have be misplaced or bug. Let me know if I was wrong or correct :)
