### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by NooblyNoob** [sp614x/optifine#6869] opened 2022-06-29 21:16 UTC
## Description of Issue
crashes after joining a world or server

## Steps to Reproduce
1. go in to a world or server

## OptiFine Version
1.19 pre

## Installation Method
standalone installer

## Log Files/Crash Reports
The game crashed whilst accessing legacyrandomsource from multiple threads
Error: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
Exit Code: -1

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
- no

**Comment by UnknownTheLad** [comment] 2022-06-29 21:22
Duplicate of #6858

**Closed** 2022-06-29 21:30 UTC
