### ISSUE TITLE
[Bug] Mekanism incompatibility

### ISSUE THREAD

**Issue by peterbro1** [sp614x/optifine#5277] opened 2021-01-31 23:07 UTC
## Description of Issue
Mekanism and Optifine at their latest versions (1/13/2021) are incompatible. I asked for support from mekanism, but they threw it into your hands. (https://github.com/mekanism/Mekanism/issues/6925)

## Steps to Reproduce
1. Install mekanism
2. Install optifine
3. Join server
4. 
## OptiFine Version
Self-explanatory. 1.16.4 (latest) HD_U_G6

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?
mods folder

## Fabric/Forge Version
 35.1.37

## Other Installed Mods
*Every* single mod you have installed, besides OptiFine. 

https://www.curseforge.com/minecraft/modpacks/dog-dog-dog-pack/relations/dependencies

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://gist.github.com/peterbro1/c11b9ec29490cb1b248822a63d3d187a

## Prior Testing
This is a known issue with mekanism and optifine. The latest version of mekanism and the latest version of optifine installed together crashes client on world load.

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.
https://github.com/mekanism/Mekanism/issues/6925

**Comment by ZenIsBestWolf** [comment] 2021-02-01 00:19
Duplicate of #5242 (same issue). Will be fixed in G7.

**Closed by ZenIsBestWolf** 2021-02-01 00:19 UTC
