### ISSUE TITLE
[Category] Short description

### ISSUE THREAD

**Issue by Doughcrafter** [sp614x/optifine#6014] opened 2021-07-11 20:56 UTC
## Description of Issue
I installed the 1.17 Pre22-Pre26 of Optifine on my M1 Macbook Air and optifine works fine alone but whenever I decide to activate shaders my game crashes and I get exit code 0.

## Steps to Reproduce
1. Install Optifine 1.17
2. Go and add a shader pack to your shaders folder. 
3.  And it should end up crashing once you apply the shader.

## OptiFine Version
Optifine 1.17 Pre22-26

## Installation Method
I installed optifine the normal way by double-clicking it and installing it as a Minecraft profile.

## Prior Testing
This has only happened with optifine installed.

**Comment by mrktospl** [comment] 2021-07-11 20:57
duplicate of #5900 
shaders don;t work on macs on 1.17 yet

**Comment by KaiAF** [comment] 2021-07-14 02:15
Already addressed here: #5900

**Closed by KaiAF** 2021-07-14 02:15 UTC
