### ISSUE TITLE
JEI Missing Textures Cause Client Crashes

### ISSUE THREAD

**Issue by SpeedSlider** [sp614x/optifine#462] opened 2017-02-01 19:17 UTC
I am currently using Allthemods2 (ATM2) Version 0.41 for Minecraft 1.11.2 and there are several mods missing textures. I have crash logs for JEI searches for pages with Advanced Generator and Simply Conveyors. I will try to provide a list of all the mods missing textures that may conflict. I can play the game/mudpack with Optifine installed I just can't use JIE without a crash on the pages with the classic Minecraft missing texture block. I can confirm that once I removed the latest version of Optifine that I could use JIE which is how I identified the issue.

Mods missing JEI Textures
-Advance Generators
-ArmorPlus (Note: reported issue on GitHub and they don't care)
-Embers
-Gendustry
-Modular Routers
-Simply Conveyors
-TechReborn

[crash-2017-01-28_16.36.24-client.txt](https://github.com/sp614x/optifine/files/745820/crash-2017-01-28_16.36.24-client.txt)
[crash-2017-01-28_16.40.34-client.txt](https://github.com/sp614x/optifine/files/745819/crash-2017-01-28_16.40.34-client.txt)
[crash-2017-01-28_16.44.03-client.txt](https://github.com/sp614x/optifine/files/745822/crash-2017-01-28_16.44.03-client.txt)
[crash-2017-01-30_12.00.54-client.txt](https://github.com/sp614x/optifine/files/745821/crash-2017-01-30_12.00.54-client.txt)

**Comment by sp614x** [comment] 2017-02-01 20:53
Duplicate of #438

**Closed by sp614x** 2017-02-01 20:53 UTC

**Comment by sp614x** [comment] 2017-02-01 20:54
Latest B7 for 1.11.2 has a bugfix for the problem.
