### ISSUE TITLE
Game freezes every day [1.19, 1.20]

### ISSUE THREAD

**Issue by vinnyg0621** [sp614x/optifine#7478] opened 2023-07-11 23:04 UTC
## Description of Issue
when I was playing, the game all of a sudden just froze. the screen was black for a split second, then the game was frozen but I could still press buttons in the game.

## Steps to Reproduce
1. the game will freeze
2. the screen will turn black for half a second
3. you can still press buttons and pause and unpause the game even when it looks frozen

## OptiFine Version
every version starting with MC 1.19.2

## Installation Method
I used the vanilla game without forge. it still did it even without it

## Log Files/Crash Reports
https://gist.github.com/vinnyg0621/7dd59f91807498259d82f5b4cc5a5911

## Prior Testing
<!-- If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
**no**

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
**yes**
- Does this happen without any mods at all?
   **- Only Forge/Fabric by itself.**
- Does this happen in OptiFine standalone?
**yes**
- Does this happen in Vanilla without OptiFine?
**no**

## Additional Information
I had just this mod installed in 1.20 with no other mods and modloader. it had this issue too

**Comment by Jiingy** [comment] 2023-07-16 21:34
Can you provide more information on this issue? The steps to reproduce just reiterate your title and description. A video would be very helpful showing all your settings and an example of this happening!

**Comment by Jiingy** [comment] 2023-07-29 04:53
Closing as this issue is far too vague, and has no updates since requested.

**Closed by Jiingy** 2023-07-29 04:53 UTC
Labels: details needed
