### ISSUE TITLE
[Crash] Parrots makes the game crash

### ISSUE THREAD

**Issue by roro1506HD** [sp614x/optifine#4319] opened 2020-07-10 14:25 UTC
## Description of Issue
Parrots makes the game crash, I don't know if an action is required in order to make it happen but it looks like it has something to do with shoulders

## Steps to Reproduce
1. Spawn Parrots
2. Walk among them

## OptiFine Version
OptiFine 1.16.1_HD_U_G2_pre2

## Installation Method
Standalone Installer

## Log Files/Crash Reports
[crash-2020-07-10_16.19.17-client.txt](https://github.com/sp614x/optifine/files/4903648/crash-2020-07-10_16.19.17-client.txt)

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/16260475/87165059-e5552900-c2c9-11ea-95d3-e40d6eceb3d8.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No it doesn't

**Comment by sp614x** [comment] 2020-07-10 15:52
Duplicate of #4214

**Closed by sp614x** 2020-07-10 15:52 UTC
