### ISSUE TITLE
1.15.2 Optifine G1 pre 2 Fire not animating

### ISSUE THREAD

**Issue by Hellster90** [sp614x/optifine#3330] opened 2020-02-15 05:01 UTC
If i look at burning iron golems in my iron farm, the flames will be still and not animate
![2020-02-15_13 40 10](https://user-images.githubusercontent.com/61074300/74582164-188bd880-5008-11ea-965c-fa09493c2388.png)
The flame will just stay as in the picture, but if you move to a different viewing angle it will start animating

**Comment by TheRSC** [comment] 2020-02-15 05:52
Try setting Smart Animations to OFF. It’s located under Video Settings -> Performance

**Comment by Hellster90** [comment] 2020-02-15 05:56
Yep that worked, thanks :)

**Comment by sp614x** [comment] 2020-02-18 09:45
Duplicate of #3296.

**Closed by sp614x** 2020-02-18 09:45 UTC
Labels: 1.15, animation
