### ISSUE TITLE
OpenGL Error: 1281 (Invalid value) when fabulous graphics are on.

### ISSUE THREAD

**Issue by Sk3l3tr0n2** [sp614x/optifine#4474] opened 2020-07-27 15:47 UTC
When I turn on fabulous graphics, my minecraft chat is spammed with "OpenGL Error: 1281 (Invalid value)

The optifine version is Optifine 1.16.1 pre10 and I installed it the regular way, downloading it from the site, opening it, then clicking install, and I have no other mods installed when it happens.

**Comment by Nickzz-exe** [comment] 2020-08-08 12:17
Same here, do u have a fix?

**Comment by sp614x** [comment] 2020-08-25 15:17
Duplicate of #4692

**Closed by sp614x** 2020-08-25 15:17 UTC
Labels: 1.16, bug, fabulous
