### ISSUE TITLE
Emissive Textures

### ISSUE THREAD

**Issue by SkaliberWasTaken** [sp614x/optifine#3746] opened 2020-04-15 21:05 UTC
Haven't received any sort of updates about Emissive textures, and the bug has now been reported by myself, and a number of others. Will we even see Emissive textures return in the preview versions?? It seems as though we've now had 4 individual preview versions with no mention of, or fix for Emissive.

Would be nice to at least know that the bug reports have been recognised, and people are at least aware that this module is still not working.

Thanks

**Comment by realjackasterisk** [comment] 2020-04-24 23:19
Duplicate of #3500.

**Closed by realjackasterisk** 2020-04-24 23:19 UTC
