### ISSUE TITLE
[Bug] Optifine crashes with new launcher when using Java 15.0.2.7 (AdoptOpenJDK)

### ISSUE THREAD

**Issue by CloudeLecaw** [sp614x/optifine#5428] opened 2021-03-09 10:12 UTC
Well the threas sais it.. with vanilla it runs but since the new launcher is there Optifine crashes when Java OpenJDK 15.0.2.7 is used

I hope optfine can fix this issue, it was working fine before too... (im using J15 since a long time now...)
Vanilla clients works with the Java 15.0.2.7

Currently it just help to disable the optional java and take the java8 that is devlivert with minecraft.

I hope this can be fixed soon :)

**Comment by sp614x** [comment] 2021-03-09 10:42
Are other modded profiles working with new launcher and custom java (Forge, Fabric)?

**Comment by cricri211** [comment] 2021-03-09 12:06
It seems it's not optifine directly (maybe I'm wrong but anyway) :

When I use java 15.0.2 `C:\Program Files\Java\jdk-15.0.2\bin\javaw.exe` (build 15.0.2+7-27) :
• _Vanilla 1.16.5 works._
• Optifine version doesn't work (I tested 1.16.5_G6, 1.16.5_G7, 1.16.5_G8_pre2)
• fabric-loader-0.11.1-1.16.5 doesn't start (even with or without mods)

With the given jre from minecraft launcher `C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64\bin` :
• Everything works.

With Java 8 `C:\Program Files\Java\jre1.8.0_281\bin\javaw.exe` :
• Vanilla 1.16.5 works.
• Optifine version doesn't work (I tested 1.16.5_G6, 1.16.5_G7, 1.16.5_G8_pre2)
• fabric-loader-0.11.1-1.16.5 doesn't start (even with or without mods)


Maybe it's the launcher that crashes when we start a modded version with another java executable.

**Comment by Blueeyestar** [comment] 2021-03-09 12:09
With the latest launcher from Mojang and Java Version 8 Update 281, the launcher also crashes when you try to start Optifine. Without Optifine, it starts up smoothly

**Comment by CloudeLecaw** [comment] 2021-03-09 12:09
forge-1.16.5-36.0.46-installer - works with the Java 15.0.2 and the new launcher
fabric-installer-0.7.1 - choosen 1.16.5 profil - the launcher freezes
Optifine version doesn't work (I tested 1.16.5_G6, 1.16.5_G7, 1.16.5_G8_pre3) the launcher crashed (it closes directly without any error)

**Comment by CloudeLecaw** [comment] 2021-03-09 13:23
I reported the issue on Mohjang bugtracker too

https://bugs.mojang.com/browse/MCL-17230

It was working all fine before the launcher updated, So im sure they can fix this issue too...maybe....

**Comment by kesu1** [comment] 2021-03-10 19:16
The issue is fixed for me with the latest beta launcher (ver.2311)

**Comment by sp614x** [comment] 2021-03-10 20:01
The current launcher 2.2.2161 crashes if there is no download section for the libraries in the version json.
Adding a download section for one library with valid size and sha1 fixes the problem.
This is already fixed in the beta launcher 2.2.2311.

**Closed by sp614x** 2021-03-10 20:01 UTC
Labels: crash, details needed, launcher

**Comment by CloudeLecaw** [comment] 2021-03-10 20:27
Why you Close this???
This is Optifine bugtragger and Optifine has nio new version!

**Comment by HiItsDevin** [comment] 2021-03-10 20:38
> Why you Close this???
> This is Optifine bugtragger and Optifine has nio new version!
> You closes this Optifine ticket because there is a farbic fix?.... reopen it!
> ![Snag_ef3dba](https://user-images.githubusercontent.com/12080017/110693451-bd66ee00-81e7-11eb-9c31-505d6eacb072.png)
> You may see there is no new version yet
> 
> Fabric has it own bugtracker and good for them that they fixed it

sp614 **clearly** said that the new launcher fixes it.

> The bug is fixed in the **beta launcher 2.2.2311**.

**Comment by sp614x** [comment] 2021-03-10 20:40
This is closed because it is a Mojang launcher bug, not an OptiFine bug.
Mojang has fixed the bug in the beta launcher.
