### ISSUE TITLE
Emissive Textures are not working.

### ISSUE THREAD

**Issue by 19seth99** [sp614x/optifine#3929] opened 2020-05-12 22:37 UTC
## Description of Issue
I have a resource pack that supports emissive textures but they wont work.

## Steps to Reproduce
Just turned them on and noticed it wasn't working.

## OptiFine Version
Optifine 1.15.2 pre16

## Installation Method
Standalone installer

**Comment by sp614x** [comment] 2020-05-29 12:18
Duplicate of #3437.

**Closed by sp614x** 2020-05-29 12:18 UTC
Labels: 1.15, emissive
