### ISSUE TITLE
[1.15.2 pre30 CTD] Crashes on World Load

### ISSUE THREAD

**Issue by KevUndead** [sp614x/optifine#4143] opened 2020-06-21 21:59 UTC
## Description of Issue
Minecraft loads to menu perfectly fine. As soon as a world is Loaded regardless of being created with this version or not, game crashes to desktop with "The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error".

Tested on pre29 with no issues with exact same world and with completely different, newly generated worlds, and re-tested on pre30.

## Steps to Reproduce
1. Load Minecraft on OptiFine pre30.
2. Generate/load any world.

## OptiFine Version
OptiFine 1.15.2_HD_U_G1_pre30

## Installation Method
Installed with the included standalone OptiFine installer from optifine.net.

## Log Files/Crash Reports
Crash-Client.txt file -> https://pastebin.com/HPDRsM7F
Latest.log file -> https://pastebin.com/EjCp7mpz

## F3 Debug Screenshot
Not possible.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine? -> **No.**

## Additional Information
In the crash logs I notice "Class not present" is frequent. At first I thought my files were missing so I deleted and redownloaded Minecraft's files, still crashed on preview 30. Perhaps sp614x forgot some files? Idk.

ALSO Probably Very Important: Currently running on Manjaro Linux with kernel 5.7.

**Comment by KevUndead** [comment] 2020-06-21 22:00
Literally just as I post this apparently there's a bugfix for crashes, I'll update here if it's fixed.

**Comment by sp614x** [comment] 2020-06-21 22:03
Fixed with a ninja-update, please download pre30 again.
Duplicate of #4141.

**Closed by sp614x** 2020-06-21 22:03 UTC
Labels: 1.15, crash
