### ISSUE TITLE
OptiFine with Fabric

### ISSUE THREAD

**Issue by QingKe233** [sp614x/optifine#4609] opened 2020-08-14 12:30 UTC
I want to get a 1.16.2OptiFine with Fabric directly.Not through optifabric.Because he has stopped updating.

**Comment by schrodingerspsycho** [comment] 2020-08-17 09:57
#4561

**Comment by rbits0** [comment] 2020-08-25 04:33
This will work for now https://github.com/Andrews54757/OptiFabric-updated

**Comment by sp614x** [comment] 2020-08-26 16:22
More active forks of OptiFabric:
- https://github.com/Chocohead/OptiFabric
- https://github.com/CDAGaming/OptiFabric.

**Comment by sp614x** [comment] 2020-08-27 06:47
Duplicate of #4561

**Closed by sp614x** 2020-08-27 06:47 UTC
Labels: fabric
