### ISSUE TITLE
[1.15.2 pre16] 3D item's texture bug

### ISSUE THREAD

**Issue by nicolas8841** [sp614x/optifine#3936] opened 2020-05-13 19:08 UTC
## Description of Issue
I trying to create custom 3D models for weapons, assigned to a named item, but it seems not working. The 3D model appeared in the inventory screen but not in the player's hand : there's still the classic texture. All was working in 1.14 and when I applied exactly the same json code on a vanilla model (on a stick).

## OptiFine Version
preview_OptiFine_1.15.2_HD_U_G1_pre16

## Installation Method
I have used the included standalone installer.

## Additional Information
[![Image](https://i.goopics.net/7LbqN.png)](https://goopics.net/i/7LbqN)
https://i.goopics.net/7LbqN.png
[![Image](https://i.goopics.net/5Llqg.png)](https://goopics.net/i/5Llqg)
https://i.goopics.net/5Llqg.png
[![Image](https://i.goopics.net/1DlWw.png)](https://goopics.net/i/1DlWw)
https://i.goopics.net/1DlWw.png
[![Image](https://i.goopics.net/mdAvm.png)](https://goopics.net/i/mdAvm)
https://i.goopics.net/mdAvm.png

**Comment by sp614x** [comment] 2020-05-29 09:53
Duplicate of #3420.

**Closed by sp614x** 2020-05-29 09:53 UTC
Labels: 1.15, CIT
