### ISSUE TITLE
Issue In ItemInHandRendererMixin And More.

### ISSUE THREAD

**Issue by Dyumar** [sp614x/optifine#7067] opened 2022-08-14 16:06 UTC
## Description of Issue
When starting up minecraft 1.18.2, it crashes immediatly.

## Steps to Reproduce
I see the console, but i cant find the issue.

## OptiFine Version
HD U H7

## Installation Method
In the official Page

## Fabric/Forge Version
40.1.0

## Other Installed Mods
https://pastebin.com/qWv2aDMT

## Log Files/Crash Reports
https://pastebin.com/BXThFWpR

## F3 Debug Screenshot
Impossible to take due to the nature of the crash.

## Prior Testing
I dont see there the issue in the mods.

**Comment by vinc3nz** [comment] 2022-08-19 06:22
Try to remove the mod difficultraids. It seams to be a problem with this mod, not with optifine. Try to remove the mods next time to figure out if this issue is caused by optifine or by another mod.

**Comment by sp614x** [comment] 2022-08-23 10:08
Mixin crash, can't be fixed by OptiFine.

**Closed by sp614x** 2022-08-23 10:08 UTC
