### ISSUE TITLE
[Bug] Optifine 1.16.1 G2 pre2 - Parrot dies leads to crash

### ISSUE THREAD

**Issue by trongtanvu** [sp614x/optifine#4286] opened 2020-07-07 04:51 UTC
I was trying to keep my parrots away from a certain spot in my world and when I killed a parrot, the game crashed, giving me an unexpected error. At first, I thought there was a problem in my world, but it turns out that my world loads fine. I moved on forward, thinking it was just one time and when I killed another parrot, the game crashed again with the same error. I tested other mobs to see if it leads to the problem, but it was only occurring to the parrot. I tested on vanilla Minecraft to see if it still has the same problem, but it did not. The version the error occurred on is Optifine 1.16.1 G2 pre2.

Video: https://drive.google.com/file/d/1Zw7VK9R0E62rmh1tcz2y_k91rFWR7XBO/view?usp=sharing
[crash-2020-07-06_21.45.16-client.txt](https://github.com/sp614x/optifine/files/4882522/crash-2020-07-06_21.45.16-client.txt)

**Comment by CreatorsWorld** [comment] 2020-07-07 10:27
Can also confirm personally.

Was just about to report the same issue.

**Comment by Gavins38** [comment] 2020-07-07 10:36
i have same issue to lol but it was random i killed like 10 parrots and then i killed 1 more and i crashed dont ask why i was killing parrots.

**Comment by MagneticChief54** [comment] 2020-07-08 02:11
I just wrote out a bug report on this without seeing this first, it also happens when you feed them cookies

**Comment by sp614x** [comment] 2020-07-08 14:37
Duplicate of #4214

**Closed by sp614x** 2020-07-08 14:37 UTC
