### ISSUE TITLE
[1.15.2 Optifine] CIT Armor Issues (Really Important For Me)

### ISSUE THREAD

**Issue by Behnja** [sp614x/optifine#3935] opened 2020-05-13 17:14 UTC
## Description
The issue is that, well, you know that feature in which you can have custom items in the game by just renaming it? That's all thanks to the cit folder. Well, it works completely fine with swords, axes, etc, except armor. The armor item gets the custom texture I assigned it, but when you put on the armor it doesn't show as the custom model I assigned it. I know I don't have the notepad code wrong because it works completely fine in the 1.14.4 version of Optifine.

## Steps to Reproduce
1. Just grab a resourcepack that has custom armor textures. Grab the names of the custom items, and go to a Minecraft world. Get those items and rename them in an anvil, then put them on your character, and you'll see that the custom textures don't load up in the armor.

## OptiFine Version
1.15.2

## Installation Method
I just went into the official Optifine website, downloaded it, runned the .jar file, the little panel-like loaded up and I clicked install, and done.

## Fabric/Forge Version
**If OptiFine is installed as standalone, you can remove this section.**

## Log Files/Crash Reports
I have no crash reports.

## F3 Debug Screenshot
![2020-05-13_10 57 07](https://user-images.githubusercontent.com/65302993/81843426-cf65fa80-950a-11ea-8e3f-0e62f72e9cf8.png)

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
- Does this happen in Vanilla without OptiFine?
No, since custom textures requires Optifine.

Here are some screenshots so you better understand the problem.

![1](https://user-images.githubusercontent.com/65302993/81843391-c6752900-950a-11ea-9817-b0ba39cb324e.png)
![2](https://user-images.githubusercontent.com/65302993/81843394-c7a65600-950a-11ea-8e65-17ec9ddd11b8.png)

I'd really appreciate if you furder look into the bug, thank you!

**Comment by blek-id** [comment] 2020-05-16 08:47
#3588 it's been acknowledged

**Comment by VoxPopuliZombiemold** [comment] 2020-05-16 17:54
#3602 #3588 #3872 #3654 #3900

**Comment by VoxPopuliZombiemold** [comment] 2020-05-16 18:01
#3950

**Comment by sp614x** [comment] 2020-05-19 15:41
Duplicate of #3588.

**Closed by sp614x** 2020-05-19 15:41 UTC
Labels: 1.15, CIT, duplicate
